/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/

module

public import Mathlib.NumberTheory.NumberField.InfinitePlace.Embeddings
public import Mathlib.NumberTheory.Ostrowski
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

@[expose] public section

/-!
# The field generated by a real algebraic number, and its defining place

For a real algebraic `δ`, the intermediate field `ℚ⟮δ⟯ ⊆ ℝ` is a number field, and the
inclusion `ℚ⟮δ⟯ ↪ ℝ` induces one distinguished archimedean absolute value on it — the one
that measures the honest size of a real algebraic number.  Both facts are one line each, but
they are needed wherever a Diophantine theorem with algebraic coefficients is instantiated:
the coefficient field is `ℚ(δ)` and the place at which the approximation is small is this one.

* `NumberField.numberField_adjoin_of_isAlgebraic` — `NumberField ℚ⟮δ⟯` (not an instance: it
  depends on the non-instance hypothesis `IsAlgebraic ℚ δ`).
* `NumberField.realEmbeddingPlace δ` — the absolute value induced by `ℚ⟮δ⟯ ↪ ℝ`, with
  `realEmbeddingPlace_apply` (it is `|·|` of the underlying real) and
  `realEmbeddingPlace_ratCast` (it restricts to the archimedean absolute value of `ℚ`, in the
  `Rat.AbsoluteValue.real` normalization of `Mathlib/NumberTheory/Ostrowski.lean`).

The last lemma is the shape a Subspace-type theorem with algebraic coefficients asks for: the
distinguished place of `ℚ` together with a chosen extension of it to the coefficient field.
-/

namespace NumberField

open IntermediateField

/-- `ℚ⟮δ⟯` is a number field, for every real algebraic `δ`: `CharZero` is inherited from `ℝ`
and finite dimensionality is `IntermediateField.adjoin.finiteDimensional`. -/
theorem numberField_adjoin_of_isAlgebraic {δ : ℝ} (hδ : IsAlgebraic ℚ δ) :
    NumberField ℚ⟮δ⟯ :=
  have : FiniteDimensional ℚ ℚ⟮δ⟯ := adjoin.finiteDimensional hδ.isIntegral
  ⟨⟩

/-- The distinguished archimedean absolute value of `ℚ⟮δ⟯`: the one induced by the defining
embedding `ℚ⟮δ⟯ ↪ ℝ`.  Among the archimedean places of `ℚ(δ)` this is the one that sees `δ`
itself rather than a conjugate. -/
noncomputable def realEmbeddingPlace (δ : ℝ) : AbsoluteValue ℚ⟮δ⟯ ℝ :=
  place (algebraMap ℚ⟮δ⟯ ℝ)

/-- The distinguished place computes the honest real absolute value. -/
theorem realEmbeddingPlace_apply (δ : ℝ) (x : ℚ⟮δ⟯) :
    realEmbeddingPlace δ x = |(x : ℝ)| := by
  rw [realEmbeddingPlace, place_apply, Real.norm_eq_abs]
  rfl

/-- The distinguished place extends the archimedean absolute value of `ℚ` — the compatibility
a Subspace-type theorem with algebraic coefficients requires of the chosen extension. -/
theorem realEmbeddingPlace_ratCast (δ : ℝ) (q : ℚ) :
    realEmbeddingPlace δ ((q : ℚ⟮δ⟯)) = Rat.AbsoluteValue.real q := by
  rw [realEmbeddingPlace_apply, Rat.AbsoluteValue.real_eq_abs, SubfieldClass.coe_ratCast]
  norm_num

end NumberField
