/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.Algebra.MvPolynomial.Equiv
import Mathlib.FieldTheory.RatFunc.Basic
import Mathlib.FieldTheory.RatFunc.AsPolynomial
import Mathlib.RingTheory.Ideal.Quotient.Operations
import ForMathlib.LinearAlgebra.FiltrationGrowth
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# [AF22] §2.2.1: bidegree-bounded pieces of a relation ideal and their dimensions

The first half of the dimension bookkeeping behind [AF22]'s proof of the lifting theorem
(plan-formalize-AF17, **WP7**).  Fix a field `K` (their `ℚ̄`), a finite index set `σ` (their
`m × m` matrix of indeterminates `Y = (y_{i,j})`) and an ideal

  `I ⊆ K(z)[Y] = MvPolynomial σ (RatFunc K)`,

thought of as the ideal of *functional relations* — see `CITED/AdamczewskiFaverjonRelationIdeal`
for the construction of the relation ideal itself, `𝓘`.  Nothing below uses anything about `I`
beyond `I ≠ ⊤`, which is [AF22]'s observation that «`𝓘(δ₁)` does not contain any non-zero
elements of `ℚ̄`».

## The objects

* `AF.bidegPiece K σ δ₁ δ₂` — the `K`-subspace `K[Y,z]_{δ₁,δ₂}` spanned by the monomials
  `zᵃ Yᵏ` with `a ≤ δ₂` and `kᵢ ≤ δ₁` for every `i`;
* `AF.relPiece I δ₁ δ₂` — `𝓘(δ₁,δ₂) = 𝓘 ∩ K[Y,z]_{δ₁,δ₂}`;
* `AF.relCompl I δ₁ δ₂` — a chosen complement `𝓘^⊥(δ₁,δ₂)` of `𝓘(δ₁,δ₂)` inside
  `K[Y,z]_{δ₁,δ₂}`, and `AF.relDim I δ₁ δ₂ = d(δ₁,δ₂)` its dimension.

## The two lemmas

* **`AF.lemma_2_2`** — `d(δ₁,δ₂) ∼ c₁(δ₁)·δ₂` as `δ₂ → ∞`, with `c₁(δ₁) ≥ 1` independent of
  `δ₂`; and the sharper `AF.exists_relDim_eq`, which says that `d(δ₁,·)` is *exactly* an
  arithmetic progression from some point on.  The sharper form is what a consumer wants: [AF22]
  use Lemma 2.2 twice, once as a lower bound `d ≥ (c₁/2)δ₂` and once as an upper bound
  `d ≤ 2c₁·p`, and both drop out of the progression.
* **`AF.lemma_2_3`** — `d(2δ₁,δ₂) ≤ 2^{m²}·d(δ₁,δ₂)`, by splitting each exponent `k ≤ 2δ₁` as
  `δ₁·ε + k'` with `ε ∈ {0,1}^σ` and `k' ≤ δ₁`.  This is the only place where `I` is used as an
  *ideal* rather than as a subspace.

## Proof note — Lemma 2.2 is not proved the way [AF22] prove it

[AF22]'s Appendix A.1 clears denominators in a basis of the annihilator of `𝓘(δ₁)`, normalises
it so that some `b_{i,jᵢ}(0) ≠ 0`, and then counts linearly independent linear forms in the dual
of `K[Y,z]`, proving separately that the increments are `≥ 1` and non-increasing.  The proof here
works with the subspaces themselves: `d(δ₁,δ₂)` is the dimension of the image of
`K[Y,z]_{δ₁,δ₂}` in `K(z)[Y]/𝓘`, the images form a filtration generated by iterating
multiplication by `z` on the piece of `z`-degree `0`, and the general growth lemma
`Submodule.IsIteratedFiltration.exists_finrank_eq` applies.  No basis, no normalisation, and no
dual space is needed, and the conclusion is *exact* linearity from some point on rather than an
asymptotic.

## References

* [AF22] B. Adamczewski, C. Faverjon. *A new proof of Nishioka's theorem in Mahler's method.*
  arXiv:2210.14528 (2022).  §2.2.1 (Lemmas 2.2, 2.3), Appendix A.1.
* [AF17f] `plans/plan-formalize-AF17.html`: WP7, milestone M4 (Stage 2).
-/

open Filter Module MvPolynomial
open scoped Topology Polynomial

namespace AF

variable {K : Type*} [Field K] {σ : Type*} [Fintype σ] [DecidableEq σ]

/-! ## The bidegree-bounded pieces `K[Y,z]_{δ₁,δ₂}` -/

/-- The generating monomials `zᵃ Yᵏ` of `K[Y,z]_{δ₁,δ₂}`: degree at most `δ₁` in each `y_{i,j}`
and at most `δ₂` in `z`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def bidegGens (K : Type*) [Field K] (σ : Type*) (δ₁ δ₂ : ℕ) :
    Set (MvPolynomial σ (RatFunc K)) :=
  (fun p : (σ →₀ ℕ) × ℕ => monomial p.1 ((RatFunc.X : RatFunc K) ^ p.2)) ''
    {p | (∀ i, p.1 i ≤ δ₁) ∧ p.2 ≤ δ₂}

/-- **`K[Y,z]_{δ₁,δ₂}`** ([AF22] §2.2.1): the `K`-subspace of `K(z)[Y]` of polynomials of degree
at most `δ₁` in each indeterminate `y_{i,j}` and at most `δ₂` in `z`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def bidegPiece (K : Type*) [Field K] (σ : Type*) (δ₁ δ₂ : ℕ) :
    Submodule K (MvPolynomial σ (RatFunc K)) :=
  Submodule.span K (bidegGens K σ δ₁ δ₂)

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem monomial_mem_bidegPiece {δ₁ δ₂ : ℕ} {k : σ →₀ ℕ} {a : ℕ} (hk : ∀ i, k i ≤ δ₁)
    (ha : a ≤ δ₂) : monomial k ((RatFunc.X : RatFunc K) ^ a) ∈ bidegPiece K σ δ₁ δ₂ :=
  Submodule.subset_span ⟨(k, a), ⟨hk, ha⟩, rfl⟩

omit [DecidableEq σ] in
/-- The exponent vectors bounded by `δ₁` form a finite set. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem finite_boundedExponents (δ₁ : ℕ) : {k : σ →₀ ℕ | ∀ i, k i ≤ δ₁}.Finite := by
  classical
  have hfin : Set.Finite (Set.range fun f : σ → Fin (δ₁ + 1) =>
      (Finsupp.equivFunOnFinite.symm fun i => ((f i : ℕ)) : σ →₀ ℕ)) := Set.finite_range _
  refine hfin.subset fun k hk => ⟨fun i => ⟨k i, Nat.lt_succ_of_le (hk i)⟩, ?_⟩
  ext i
  simp

omit [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem finite_bidegGens (δ₁ δ₂ : ℕ) : (bidegGens K σ δ₁ δ₂).Finite := by
  refine Set.Finite.image _ ?_
  exact ((finite_boundedExponents δ₁).prod (Set.finite_Iic δ₂)).subset fun p hp =>
    ⟨hp.1, Set.mem_Iic.mpr hp.2⟩

instance instFiniteDimensionalBidegPiece (δ₁ δ₂ : ℕ) :
    FiniteDimensional K (bidegPiece K σ δ₁ δ₂) :=
  FiniteDimensional.span_of_finite K (finite_bidegGens δ₁ δ₂)

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem bidegPiece_mono {δ₁ δ₂ δ₂' : ℕ} (h : δ₂ ≤ δ₂') :
    bidegPiece K σ δ₁ δ₂ ≤ bidegPiece K σ δ₁ δ₂' :=
  Submodule.span_mono (Set.image_mono fun _ hp => ⟨hp.1, hp.2.trans h⟩)

/-! ## Multiplication by `z` -/

/-- Multiplication by `z`, as a `K`-linear endomorphism of `K(z)[Y]`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def mulZ (K : Type*) [Field K] (σ : Type*) :
    MvPolynomial σ (RatFunc K) →ₗ[K] MvPolynomial σ (RatFunc K) :=
  LinearMap.mulLeft K (C (RatFunc.X : RatFunc K))

@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem mulLeft_pow_apply {A : Type*} [CommRing A] [Algebra K A] (a : A) (n : ℕ) (x : A) :
    ((LinearMap.mulLeft K a : Module.End K A) ^ n) x = a ^ n * x := by
  induction n with
  | zero => simp
  | succ m ih =>
      rw [Module.End.iterate_succ', LinearMap.comp_apply, ih, LinearMap.mulLeft_apply]
      ring

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem mulZ_pow_apply (n : ℕ) (x : MvPolynomial σ (RatFunc K)) :
    ((mulZ K σ : Module.End K (MvPolynomial σ (RatFunc K))) ^ n) x =
      C ((RatFunc.X : RatFunc K) ^ n) * x := by
  rw [mulZ, mulLeft_pow_apply, map_pow]

omit [Fintype σ] [DecidableEq σ] in
/-- The step relation: the piece of `z`-degree `≤ N+1` is the piece of `z`-degree `≤ N` together
with `z^{N+1}` times the piece of `z`-degree `0`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem bidegPiece_succ (δ₁ N : ℕ) :
    bidegPiece K σ δ₁ (N + 1) =
      bidegPiece K σ δ₁ N ⊔ (bidegPiece K σ δ₁ 0).map
        ((mulZ K σ : Module.End K (MvPolynomial σ (RatFunc K))) ^ (N + 1)) := by
  apply le_antisymm
  · refine Submodule.span_le.mpr ?_
    rintro _ ⟨⟨k, a⟩, ⟨hk, ha⟩, rfl⟩
    rcases Nat.lt_succ_iff_lt_or_eq.mp (Nat.lt_succ_of_le ha) with hlt | rfl
    · exact Submodule.mem_sup_left (monomial_mem_bidegPiece hk (Nat.lt_succ_iff.mp hlt))
    · refine Submodule.mem_sup_right ⟨monomial k ((RatFunc.X : RatFunc K) ^ 0),
        monomial_mem_bidegPiece hk le_rfl, ?_⟩
      rw [mulZ_pow_apply, C_mul_monomial, pow_zero, mul_one]
  · refine sup_le (bidegPiece_mono (Nat.le_succ N)) ?_
    rw [Submodule.map_le_iff_le_comap]
    refine Submodule.span_le.mpr ?_
    rintro _ ⟨⟨k, a⟩, ⟨hk, ha⟩, rfl⟩
    simp only [SetLike.mem_coe, Submodule.mem_comap]
    obtain rfl : a = 0 := Nat.le_zero.mp ha
    rw [mulZ_pow_apply, C_mul_monomial, pow_zero, mul_one]
    exact monomial_mem_bidegPiece hk le_rfl

omit [Fintype σ] [DecidableEq σ] in
/-- Multiplication by `z` raises the `z`-degree by exactly one. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem map_mulZ_bidegPiece_le (δ₁ N : ℕ) :
    (bidegPiece K σ δ₁ N).map (mulZ K σ) ≤ bidegPiece K σ δ₁ (N + 1) := by
  rw [Submodule.map_le_iff_le_comap]
  refine Submodule.span_le.mpr ?_
  rintro _ ⟨⟨k, a⟩, ⟨hk, ha⟩, rfl⟩
  simp only [SetLike.mem_coe, Submodule.mem_comap, mulZ, LinearMap.mulLeft_apply,
    C_mul_monomial]
  rw [← pow_succ']
  exact monomial_mem_bidegPiece hk (Nat.succ_le_succ ha)

/-! ## The quotient by the ideal, and the filtration it carries -/

section Ideal

variable (I : Ideal (MvPolynomial σ (RatFunc K)))

/-- The quotient map `K(z)[Y] → K(z)[Y]/𝓘`, as a `K`-linear map. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def relQuot : MvPolynomial σ (RatFunc K) →ₗ[K] (MvPolynomial σ (RatFunc K) ⧸ I) :=
  (Ideal.Quotient.mkₐ K I).toLinearMap

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relQuot_apply (x : MvPolynomial σ (RatFunc K)) :
    relQuot I x = Ideal.Quotient.mk I x := rfl

/-- Multiplication by `z` on the quotient. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def mulZQuot : (MvPolynomial σ (RatFunc K) ⧸ I) →ₗ[K] (MvPolynomial σ (RatFunc K) ⧸ I) :=
  LinearMap.mulLeft K (Ideal.Quotient.mk I (C (RatFunc.X : RatFunc K)))

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relQuot_comp_mulZ_pow (n : ℕ) (x : MvPolynomial σ (RatFunc K)) :
    relQuot I (((mulZ K σ : Module.End K (MvPolynomial σ (RatFunc K))) ^ n) x) =
      ((mulZQuot I : Module.End K (MvPolynomial σ (RatFunc K) ⧸ I)) ^ n) (relQuot I x) := by
  simp only [mulZ_pow_apply, mulZQuot, mulLeft_pow_apply, relQuot_apply, map_mul, map_pow]

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relQuot_comp_mulZ_pow' (n : ℕ) :
    (relQuot I).comp ((mulZ K σ : Module.End K (MvPolynomial σ (RatFunc K))) ^ n) =
      ((mulZQuot I : Module.End K (MvPolynomial σ (RatFunc K) ⧸ I)) ^ n).comp (relQuot I) :=
  LinearMap.ext (relQuot_comp_mulZ_pow I n)

omit [Fintype σ] [DecidableEq σ] in
/-- `z` is invertible in `K(z)`, hence multiplication by it is injective on any quotient — no
properness of `I` needed: over the zero ring every map is injective. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem injective_mulZQuot : Function.Injective (mulZQuot I) := by
  have hunit : IsUnit (Ideal.Quotient.mk I (C (RatFunc.X : RatFunc K))) := by
    refine IsUnit.map _ (?_ : IsUnit (C (RatFunc.X : RatFunc K)))
    exact (isUnit_iff_exists_inv.mpr ⟨C (RatFunc.X : RatFunc K)⁻¹, by
      rw [← map_mul, mul_inv_cancel₀ RatFunc.X_ne_zero, map_one]⟩)
  exact hunit.mul_right_injective

/-- The image of `K[Y,z]_{δ₁,δ₂}` in the quotient `K(z)[Y]/𝓘`.  Its dimension is `d(δ₁,δ₂)`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def relImage (δ₁ δ₂ : ℕ) : Submodule K (MvPolynomial σ (RatFunc K) ⧸ I) :=
  (bidegPiece K σ δ₁ δ₂).map (relQuot I)

instance instFiniteDimensionalRelImage (δ₁ δ₂ : ℕ) : FiniteDimensional K (relImage I δ₁ δ₂) := by
  rw [relImage, bidegPiece, Submodule.map_span]
  exact FiniteDimensional.span_of_finite K ((finite_bidegGens δ₁ δ₂).image _)

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relImage_succ (δ₁ N : ℕ) :
    relImage I δ₁ (N + 1) = relImage I δ₁ N ⊔ (relImage I δ₁ 0).map
      ((mulZQuot I : Module.End K (MvPolynomial σ (RatFunc K) ⧸ I)) ^ (N + 1)) := by
  rw [relImage, relImage, relImage, bidegPiece_succ, Submodule.map_sup, ← Submodule.map_comp,
    relQuot_comp_mulZ_pow', Submodule.map_comp]

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem map_mulZQuot_relImage_le (δ₁ N : ℕ) :
    (relImage I δ₁ N).map (mulZQuot I) ≤ relImage I δ₁ (N + 1) := by
  rw [relImage, relImage, ← Submodule.map_comp]
  have h1 : (mulZQuot I).comp (relQuot I) = (relQuot I).comp (mulZ K σ) := by
    have h2 := relQuot_comp_mulZ_pow' I 1
    rw [pow_one, pow_one] at h2
    exact h2.symm
  rw [h1, Submodule.map_comp]
  exact Submodule.map_mono (map_mulZ_bidegPiece_le δ₁ N)

omit [DecidableEq σ] in
/-- The images `relImage I δ₁ ·` form an iterated filtration in the sense of
`Submodule.IsIteratedFiltration`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem isIteratedFiltration_relImage (δ₁ : ℕ) :
    Submodule.IsIteratedFiltration (mulZQuot I) (relImage I δ₁ 0) (fun N => relImage I δ₁ N) where
  injective := injective_mulZQuot I
  finiteDimensional_zero := instFiniteDimensionalRelImage I δ₁ 0
  finiteDimensional_gen := instFiniteDimensionalRelImage I δ₁ 0
  step := relImage_succ I δ₁
  map_le := map_mulZQuot_relImage_le I δ₁

end Ideal

/-! ## The dimensions are unbounded -/

section Unbounded

variable (I : Ideal (MvPolynomial σ (RatFunc K)))

/-- `K(z)` embeds into the quotient by a proper ideal: a nonzero rational function is a unit of
`K(z)[Y]`, so it survives modulo `𝓘`.  This is [AF22]'s remark that «`𝓘(δ₁)` does not contain any
non-zero element of `ℚ̄`», in the form actually used. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def ratFuncToQuot : RatFunc K →ₗ[K] (MvPolynomial σ (RatFunc K) ⧸ I) :=
  (relQuot I).comp
    (IsScalarTower.toAlgHom K (RatFunc K) (MvPolynomial σ (RatFunc K))).toLinearMap

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem ratFuncToQuot_apply (c : RatFunc K) :
    ratFuncToQuot I c = Ideal.Quotient.mk I (C c) := rfl

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem injective_ratFuncToQuot (hI : I ≠ ⊤) : Function.Injective (ratFuncToQuot I) := by
  refine (injective_iff_map_eq_zero (ratFuncToQuot I)).mpr fun c hc => ?_
  by_contra hne
  rw [ratFuncToQuot_apply, Ideal.Quotient.eq_zero_iff_mem] at hc
  refine hI (Ideal.eq_top_of_isUnit_mem I hc ?_)
  exact isUnit_iff_exists_inv.mpr ⟨C c⁻¹, by rw [← map_mul, mul_inv_cancel₀ hne, map_one]⟩

/-- The powers of `z` are linearly independent over `K` — `z` is transcendental. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem linearIndependent_pow_ratFuncX (N : ℕ) :
    LinearIndependent K fun j : Fin (N + 1) => (RatFunc.X : RatFunc K) ^ (j : ℕ) := by
  classical
  rw [linearIndependent_iff']
  intro s g hsum i hi
  have hP : (∑ j ∈ s, Polynomial.C (g j) * Polynomial.X ^ (j : ℕ) : K[X]) = 0 := by
    by_contra hne
    refine RatFunc.transcendental_X (K := K) ⟨_, hne, ?_⟩
    rw [map_sum, ← hsum]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [map_mul, map_pow, Polynomial.aeval_C, Polynomial.aeval_X, Algebra.smul_def]
  have hco := congrArg (fun q : K[X] => q.coeff (i : ℕ)) hP
  simpa [Polynomial.finsetSum_coeff, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
    Fin.val_inj, Finset.sum_ite_eq, hi] using hco

omit [Fintype σ] [DecidableEq σ] in
/-- The powers of `z` stay linearly independent in the quotient by a proper ideal. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem linearIndependent_relQuot_zpow (hI : I ≠ ⊤) (N : ℕ) :
    LinearIndependent K fun j : Fin (N + 1) =>
      relQuot I (C ((RatFunc.X : RatFunc K) ^ (j : ℕ))) :=
  (linearIndependent_pow_ratFuncX (K := K) N).map' (ratFuncToQuot I)
    (LinearMap.ker_eq_bot.mpr (injective_ratFuncToQuot I hI))

omit [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem le_finrank_relImage (hI : I ≠ ⊤) (δ₁ N : ℕ) :
    N + 1 ≤ finrank K (relImage I δ₁ N) := by
  classical
  have hmem : ∀ j : Fin (N + 1),
      relQuot I (C ((RatFunc.X : RatFunc K) ^ (j : ℕ))) ∈ relImage I δ₁ N := by
    intro j
    refine ⟨C ((RatFunc.X : RatFunc K) ^ (j : ℕ)), ?_, rfl⟩
    have : (C ((RatFunc.X : RatFunc K) ^ (j : ℕ)) : MvPolynomial σ (RatFunc K)) =
        monomial (0 : σ →₀ ℕ) ((RatFunc.X : RatFunc K) ^ (j : ℕ)) := rfl
    rw [this]
    exact monomial_mem_bidegPiece (fun i => by simp) (Nat.lt_succ_iff.mp j.isLt)
  have hli : LinearIndependent K fun j : Fin (N + 1) =>
      (⟨relQuot I (C ((RatFunc.X : RatFunc K) ^ (j : ℕ))), hmem j⟩ : relImage I δ₁ N) :=
    LinearIndependent.of_comp (relImage I δ₁ N).subtype (linearIndependent_relQuot_zpow I hI N)
  simpa using hli.fintype_card_le_finrank

end Unbounded

/-! ## `𝓘(δ₁,δ₂)`, its complement `𝓘^⊥(δ₁,δ₂)`, and `d(δ₁,δ₂)` -/

section Complement

variable (I : Ideal (MvPolynomial σ (RatFunc K)))

/-- **`𝓘(δ₁,δ₂)`** ([AF22] §2.2.1): the part of the ideal of bidegree at most `(δ₁,δ₂)`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def relPiece (δ₁ δ₂ : ℕ) : Submodule K (MvPolynomial σ (RatFunc K)) :=
  I.restrictScalars K ⊓ bidegPiece K σ δ₁ δ₂

/-- `𝓘(δ₁,δ₂)` read inside the piece `K[Y,z]_{δ₁,δ₂}`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def relPieceSub (δ₁ δ₂ : ℕ) : Submodule K ↥(bidegPiece K σ δ₁ δ₂) :=
  Submodule.comap (bidegPiece K σ δ₁ δ₂).subtype (I.restrictScalars K)

/-- A chosen complement of `𝓘(δ₁,δ₂)` inside the piece. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def relComplSub (δ₁ δ₂ : ℕ) : Submodule K ↥(bidegPiece K σ δ₁ δ₂) :=
  Classical.choose (Submodule.exists_isCompl (relPieceSub I δ₁ δ₂))

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem isCompl_relComplSub (δ₁ δ₂ : ℕ) :
    IsCompl (relPieceSub I δ₁ δ₂) (relComplSub I δ₁ δ₂) :=
  Classical.choose_spec (Submodule.exists_isCompl (relPieceSub I δ₁ δ₂))

/-- **`𝓘^⊥(δ₁,δ₂)`** ([AF22] §2.2.1): a chosen complement of `𝓘(δ₁,δ₂)` in `K[Y,z]_{δ₁,δ₂}`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def relCompl (δ₁ δ₂ : ℕ) : Submodule K (MvPolynomial σ (RatFunc K)) :=
  (relComplSub I δ₁ δ₂).map (bidegPiece K σ δ₁ δ₂).subtype

/-- **`d(δ₁,δ₂)`** ([AF22] §2.2.1): the dimension of `𝓘^⊥(δ₁,δ₂)` over `K`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def relDim (δ₁ δ₂ : ℕ) : ℕ := finrank K ↥(relCompl I δ₁ δ₂)

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relCompl_le_bidegPiece (δ₁ δ₂ : ℕ) : relCompl I δ₁ δ₂ ≤ bidegPiece K σ δ₁ δ₂ :=
  Submodule.map_subtype_le _ _

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem map_relPieceSub (δ₁ δ₂ : ℕ) :
    (relPieceSub I δ₁ δ₂).map (bidegPiece K σ δ₁ δ₂).subtype = relPiece I δ₁ δ₂ := by
  rw [relPieceSub, relPiece, Submodule.map_comap_subtype, inf_comm]

omit [Fintype σ] [DecidableEq σ] in
/-- `𝓘^⊥(δ₁,δ₂)` really is a complement of `𝓘(δ₁,δ₂)` inside `K[Y,z]_{δ₁,δ₂}`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relPiece_sup_relCompl (δ₁ δ₂ : ℕ) :
    relPiece I δ₁ δ₂ ⊔ relCompl I δ₁ δ₂ = bidegPiece K σ δ₁ δ₂ := by
  rw [← map_relPieceSub, relCompl, ← Submodule.map_sup, (isCompl_relComplSub I δ₁ δ₂).sup_eq_top,
    Submodule.map_subtype_top]

omit [Fintype σ] [DecidableEq σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relPiece_inf_relCompl (δ₁ δ₂ : ℕ) : relPiece I δ₁ δ₂ ⊓ relCompl I δ₁ δ₂ = ⊥ := by
  rw [← map_relPieceSub, relCompl,
    ← Submodule.map_inf _ (Submodule.injective_subtype (bidegPiece K σ δ₁ δ₂)),
    (isCompl_relComplSub I δ₁ δ₂).inf_eq_bot, Submodule.map_bot]

omit [DecidableEq σ] in
/-- The dimension of the complement is the dimension of the image in the quotient — the form in
which `d(δ₁,δ₂)` is actually computed. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relDim_eq_finrank_relImage (δ₁ δ₂ : ℕ) :
    relDim I δ₁ δ₂ = finrank K ↥(relImage I δ₁ δ₂) := by
  classical
  -- the complement side
  have h1 : finrank K ↥(relPieceSub I δ₁ δ₂) + finrank K ↥(relComplSub I δ₁ δ₂) =
      finrank K ↥(bidegPiece K σ δ₁ δ₂) :=
    Submodule.finrank_add_eq_of_isCompl (isCompl_relComplSub I δ₁ δ₂)
  -- the image side, by rank-nullity for the restriction of the quotient map
  have h2 : finrank K ↥(relImage I δ₁ δ₂) + finrank K ↥(relPieceSub I δ₁ δ₂) =
      finrank K ↥(bidegPiece K σ δ₁ δ₂) := by
    have hrk := LinearMap.finrank_range_add_finrank_ker
      ((relQuot I).comp (bidegPiece K σ δ₁ δ₂).subtype)
    rw [LinearMap.range_comp, Submodule.range_subtype, LinearMap.ker_comp] at hrk
    have hker : LinearMap.ker (relQuot I) = I.restrictScalars K := by
      ext x
      simp [relQuot_apply, Ideal.Quotient.eq_zero_iff_mem]
    rw [hker] at hrk
    exact hrk
  have h3 : relDim I δ₁ δ₂ = finrank K ↥(relComplSub I δ₁ δ₂) :=
    (Submodule.equivMapOfInjective _
      (Submodule.injective_subtype (bidegPiece K σ δ₁ δ₂)) _).finrank_eq.symm
  omega

end Complement

/-! ## [AF22] Lemma 2.2 -/

section Lemma22

variable (I : Ideal (MvPolynomial σ (RatFunc K)))

omit [DecidableEq σ] in
/-- **[AF22] Lemma 2.2, sharp form.**  For every `δ₁` there are `c ≥ 1` and `N₀` such that
`d(δ₁,δ₂)` is *exactly* `d(δ₁,N₀) + c·(δ₂ - N₀)` for all `δ₂ ≥ N₀`.  In particular `c` does not
depend on `δ₂`. -/
@[category research solved, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_relDim_eq (hI : I ≠ ⊤) (δ₁ : ℕ) :
    ∃ c N₀ : ℕ, 1 ≤ c ∧ ∀ δ₂, N₀ ≤ δ₂ → relDim I δ₁ δ₂ = relDim I δ₁ N₀ + c * (δ₂ - N₀) := by
  obtain ⟨c, N₀, hc, hlin⟩ := (isIteratedFiltration_relImage I δ₁).exists_finrank_eq
    (fun B => ⟨B, le_trans (Nat.le_succ B) (le_finrank_relImage I hI δ₁ B)⟩)
  refine ⟨c, N₀, hc, fun δ₂ hδ₂ => ?_⟩
  rw [relDim_eq_finrank_relImage, relDim_eq_finrank_relImage]
  exact hlin δ₂ hδ₂

omit [DecidableEq σ] in
/-- **[AF22] Lemma 2.2.**  *«There exists a positive integer `c₁(δ₁)`, that does not depend on
`δ₂`, such that `d(δ₁,δ₂) ∼ c₁(δ₁)δ₂` as `δ₂` tends to infinity.»* -/
@[category research solved, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem lemma_2_2 (hI : I ≠ ⊤) (δ₁ : ℕ) :
    ∃ c : ℕ, 1 ≤ c ∧
      Tendsto (fun δ₂ : ℕ => (relDim I δ₁ δ₂ : ℝ) / δ₂) atTop (𝓝 (c : ℝ)) := by
  obtain ⟨c, hc, htend⟩ := (isIteratedFiltration_relImage I δ₁).exists_tendsto_finrank_div
    (fun B => ⟨B, le_trans (Nat.le_succ B) (le_finrank_relImage I hI δ₁ B)⟩)
  refine ⟨c, hc, ?_⟩
  refine htend.congr fun δ₂ => ?_
  rw [relDim_eq_finrank_relImage]

end Lemma22

/-! ## [AF22] Lemma 2.3 -/

section Lemma23

variable (I : Ideal (MvPolynomial σ (RatFunc K)))

/-- The `0/1` exponent vector supported on `s` — the exponent of one of the `2^{m²}` monomials
`e_ℓ(Y)` of degree at most `1` in each `y_{i,j}`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def indicatorExp (s : Finset σ) : σ →₀ ℕ := ∑ i ∈ s, Finsupp.single i 1

omit [Fintype σ] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem indicatorExp_apply (s : Finset σ) (i : σ) :
    indicatorExp s i = if i ∈ s then 1 else 0 := by
  classical
  rw [indicatorExp, Finsupp.finsetSum_apply]
  simp [Finsupp.single_apply]

/-- **The bidegree splitting.**  An exponent bounded by `2δ₁` is `δ₁·ε + k'` with `ε` a `0/1`
vector and `k'` bounded by `δ₁`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_indicator_split {δ₁ : ℕ} {k : σ →₀ ℕ} (hk : ∀ i, k i ≤ 2 * δ₁) :
    ∃ (s : Finset σ) (k' : σ →₀ ℕ), (∀ i, k' i ≤ δ₁) ∧ δ₁ • indicatorExp s + k' = k := by
  classical
  refine ⟨Finset.univ.filter (fun i => δ₁ < k i),
    Finsupp.mapRange (fun a => if a ≤ δ₁ then a else a - δ₁) (by simp) k, fun i => ?_, ?_⟩
  · have hki := hk i
    rw [Finsupp.mapRange_apply]
    by_cases hle : k i ≤ δ₁
    · rw [ite_eq_left hle]; omega
    · rw [ite_eq_right hle]; omega
  · ext i
    have hki := hk i
    simp only [Finsupp.add_apply, Finsupp.smul_apply, Finsupp.mapRange_apply, indicatorExp_apply,
      smul_eq_mul, Finset.mem_filter, Finset.mem_univ, true_and]
    by_cases hle : k i ≤ δ₁
    · rw [ite_eq_left hle, ite_eq_right (by omega : ¬ δ₁ < k i)]
      omega
    · rw [ite_eq_right hle, ite_eq_left (by omega : δ₁ < k i)]
      omega

open Finset in
/-- **[AF22] Lemma 2.3.**  `dim 𝓘^⊥(2δ₁,δ₂) ≤ 2^{m²} dim 𝓘^⊥(δ₁,δ₂)`.

Every monomial of bidegree `(2δ₁,δ₂)` is `Yᵟ¹ᵋ` times one of bidegree `(δ₁,δ₂)`, so the image of
`K[Y,z]_{2δ₁,δ₂}` in the quotient is covered by the `2^{m²}` translates of the image of
`K[Y,z]_{δ₁,δ₂}`.  This is the only step that uses that `𝓘` is an *ideal*. -/
@[category research solved, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem lemma_2_3 (δ₁ δ₂ : ℕ) :
    relDim I (2 * δ₁) δ₂ ≤ 2 ^ Fintype.card σ * relDim I δ₁ δ₂ := by
  classical
  rw [relDim_eq_finrank_relImage, relDim_eq_finrank_relImage]
  -- the covering map: `2^{m²}` copies of the small image, translated by the `Yᵟ¹ᵋ`
  set F : (Finset σ → relImage I δ₁ δ₂) →ₗ[K] (MvPolynomial σ (RatFunc K) ⧸ I) :=
    ∑ s : Finset σ,
      (LinearMap.mulLeft K (Ideal.Quotient.mk I (monomial (δ₁ • indicatorExp s) 1))).comp
        ((relImage I δ₁ δ₂).subtype.comp (LinearMap.proj s)) with hF
  have hFapply : ∀ (s : Finset σ) (v : relImage I δ₁ δ₂),
      F (Pi.single s v : Finset σ → relImage I δ₁ δ₂) =
        Ideal.Quotient.mk I (monomial (δ₁ • indicatorExp s) 1) * (v : MvPolynomial σ (RatFunc K) ⧸ I) := by
    intro s v
    rw [hF]
    simp only [LinearMap.coe_sum, Finset.sum_apply, LinearMap.comp_apply, LinearMap.proj_apply,
      LinearMap.mulLeft_apply, Submodule.subtype_apply]
    rw [Finset.sum_eq_single s]
    · rw [Pi.single_eq_same]
    · intro b _ hb
      rw [Pi.single_eq_of_ne hb]
      simp
    · intro hb
      exact absurd (Finset.mem_univ s) hb
  -- the big image is contained in the range
  have hle : relImage I (2 * δ₁) δ₂ ≤ LinearMap.range F := by
    rw [relImage, bidegPiece, Submodule.map_span, Submodule.span_le]
    rintro _ ⟨_, ⟨⟨k, a⟩, ⟨hk, ha⟩, rfl⟩, rfl⟩
    obtain ⟨s, k', hk', hsplit⟩ := exists_indicator_split hk
    have hmem : relQuot I (monomial k' ((RatFunc.X : RatFunc K) ^ a)) ∈ relImage I δ₁ δ₂ :=
      ⟨_, monomial_mem_bidegPiece hk' ha, rfl⟩
    refine ⟨(Pi.single s ⟨_, hmem⟩ : Finset σ → relImage I δ₁ δ₂), ?_⟩
    rw [hFapply]
    simp only [relQuot_apply]
    rw [← map_mul, monomial_mul_monomial, one_mul, hsplit]
  calc finrank K (relImage I (2 * δ₁) δ₂)
      ≤ finrank K (LinearMap.range F) := Submodule.finrank_mono hle
    _ ≤ finrank K (Finset σ → relImage I δ₁ δ₂) := LinearMap.finrank_range_le F
    _ = 2 ^ Fintype.card σ * finrank K (relImage I δ₁ δ₂) := by
        rw [Module.finrank_pi_fintype, Finset.sum_const, Finset.card_univ, Fintype.card_finset,
          smul_eq_mul]

end Lemma23

end AF
