/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.RingTheory.PowerSeries.Basic
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Algebra.Polynomial.Roots
import Mathlib.Analysis.Normed.Field.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# [AF17] §4: the three tools (plan-formalize-AF17, WP3)

The auxiliary results of [AF17] §4 — *«nous aurons besoin de trois résultats auxiliaires»* — on
which both of that paper's proofs of Thm 1.7(i), and hence Cor 1.8 (the corpus's
`AF.transcendental_or_rat_of_automatic`, a cited axiom until WP5 made it a theorem), rest:

* **Lemme 4.3**, the descent of a linear relation from `ℚ̄[z]` to `k[z]` (`lemme_4_3`,
  `lemme_4_3_eval`);
* **Lemme 4.2**, the doubling that turns any point into a *regular* point of an enlarged system
  (`lemme_4_2`);
* **Lemme 4.1**, the embedding that clears poles of the system matrix — which for the systems of
  this corpus is vacuous (`lemme_4_1_of_polynomial`).

## Two settings, on purpose

The descent is a statement about **coefficients**: it says that a relation whose *functions* have
coefficients in `k` may be taken to have *polynomial coefficients* in `k` as well.  It is
therefore stated for `PowerSeries k` — the object "power series with coefficients in `k`" — and
proved by applying a `k`-linear functional `π : L → k` to every coefficient.  Where [AF17] take a
primitive element `φ` of the finite extension generated by the `wᵢ` and expand in the `k`-basis
`1, φ, …, φ^{h-1}`, the argument here uses one coordinate functional of an arbitrary `k`-basis of
`L`; the mathematics is identical and neither finiteness nor separability of `L/k` is used.

Lemmes 4.1 and 4.2 are statements about **systems**: `IsMahlerSolution q A F S` says that
functions `F i : 𝕜 → 𝕜` satisfy `F(z) = A(z)F(z^q)` on a set `S`, and `IsRegularPoint q A α` says
no `α^{q^l}` kills `det A`.  Both are stated for a matrix `A` with entries in `k[z]`; see the
scope notes.

## Scope, and three findings

* **Polynomial systems only** (risk R6 of [AF17f], discharged).  [AF17] work with
  `A ∈ GLₙ(ℚ̄(z))` and pay for it with Lemme 4.1, whose proof multiplies by an infinite product
  and differentiates the system.  They also record that this is unnecessary for automatic
  series, whose matrix can be taken polynomial — which is exactly what `RB.mahlerMatrix` is.  So
  the whole `System` section is written over `k[z]`, `IsRegularPoint` reads off `det A` alone,
  and Lemme 4.1 reduces to the identity embedding.  The general Lemme 4.1 is **not** formalized.
* **§5 needs only the descent.**  Reading [AF17] §5: Thm 1.10's proof uses Thm 1.4 plus
  «l'argument de descente déjà utilisé dans la démonstration du lemme 4.3»; Thm 1.9's proof uses
  Thm 1.4; Thm 1.7's proof uses Thms 1.9 and 1.10 and linear algebra.  Lemmes 4.1 and 4.2 are
  used **nowhere** in §5 — they belong to §4's *first* proof of Thm 1.7(i).
* **… and that first proof is the cheaper route to Cor 1.8.**  §4 derives Thm 1.7(i) from
  Lemmes 4.1–4.3 and a lifting theorem applied to a *linear* form — which is the Stage-1 axiom
  fixed by [AF17f] gate G1 ([AF22] Thm 2.1 = [AF17] Thm 1.4 at degree 1).  Since Cor 1.8 is
  Thm 1.7(i) for the pair `(f, 1)`, the route
  `WP1 → Lemme 4.1 → Lemme 4.2 → axiom → Lemme 4.3 → Thm 1.7(i) → Cor 1.8`
  reaches the corollary **without** Thm 1.10, whose proof is the one genuinely analytic argument
  in §5 (Laurent truncation, operator-norm estimates, the integers `N₀`, `N₁`).  Nothing below
  assembles Thm 1.7(i); that route is executed in `CITED/AdamczewskiFaverjonProof.lean` (WP4),
  which confirms the finding.

## Not built here

* The **analytic-to-formal bridge**.  Lemme 4.3 is consumed in [AF17] for relations between
  *analytic* functions; turning `Σᵢ wᵢ(z)fᵢ(z) = 0 on a disc` into the power-series identity this
  file takes as hypothesis is the uniqueness of Taylor coefficients.  Built in
  `CITED/AdamczewskiFaverjonProof.lean` (`AF.relation_formal_of_functional`), where the functions
  are, not here.
* The **`ℤ[z] → ℚ[z]` step**.  `RB.mahlerMatrix` has entries in `ℤ[z]`; the `k` of [AF17] is a
  number field.  Mapping the corpus's matrix into `ℚ[z]` is a one-line `Polynomial.map` that
  belongs to the assembly, not here.
* Thms 1.7, 1.9, 1.10 and Cor 1.8 themselves.  Thm 1.7(i) and Cor 1.8 are built in
  `CITED/AdamczewskiFaverjonProof.lean` (WP4) out of the lemmas below; Thms 1.9, 1.10 and
  Thm 1.7(ii) are off that route and are built nowhere.

## Contents

* `AF.polyMap`, `AF.psMap`, **`AF.psMap_coe_mul`**, `AF.eval_polyMap` — a `k`-linear functional
  applied to coefficients, and the two places the hypotheses `hᵢ ∈ k[[z]]`, `α ∈ k` enter.
* `AF.descent_relation`, **`AF.lemme_4_3`**, **`AF.lemme_4_3_eval`** — the descent, in AF's form
  and in the prescribed-`k`-rational-value form that Thm 1.10 consumes.
* `AF.IsMahlerSolution`, `AF.IsRegularPoint` — the system and its regular points.
* **`AF.lemme_4_1_of_polynomial`** — Lemme 4.1 for polynomial systems: the identity embedding.
* `AF.compPow`, `AF.dblMat`, **`AF.isMahlerSolution_dblMat`**, `AF.swapBlocks`,
  **`AF.det_dblMat`** — one doubling: the block matrix `[[A−I, A(z^q)], [I, 0]]`, the transported
  solution, and `det B₁ = ε·det A(z^q)` with `ε² = 1`.
* `AF.dblIdx`, `AF.dblIterMat`, `AF.dblIterSol`, `AF.dblEmb`, `AF.isMahlerSolution_dblIterMat`,
  **`AF.det_dblIterMat`** — the iteration, and `det B_j = ε·(det A)(z^{q^j})`.
* **`AF.exists_regular_shift`**, **`AF.lemme_4_2`** — only finitely many Mahler iterates can be
  singular, hence regularity after finitely many doublings.
* `AF.injective_pow_pow_of_norm_lt_one` — `0 < |α| < 1` gives `lemme_4_2` its injectivity
  hypothesis.

## References

* [AF17] B. Adamczewski, C. Faverjon. *Méthode de Mahler: relations linéaires, transcendance et
  applications aux nombres automatiques.* Proc. London Math. Soc. **115** (2017), 55–90
  (arXiv:1508.07158v2; §4 = pp. 16–22 of that version, whose numbering is used throughout).
* [AF22] B. Adamczewski, C. Faverjon. *A new proof of Nishioka's theorem in Mahler's method.*
  arXiv:2210.14528 (2022).  (Thm 2.1 = the Stage-1 axiom these tools would be combined with.)
* [BBC15] J. Bell, Y. Bugeaud, M. Coons. Proc. LMS **110** (2015), 1157–1206.  (The construction
  [AF17] adapt in Lemme 4.1.)
* [AF17f] `plans/plan-formalize-AF17.html` (2026-08-03): WP3, risk R6, gate G1.
-/

namespace AF

open Polynomial

/-! ## Lemme 4.3: descent of a relation to the base field -/

section Descent

variable {k L : Type*} [Field k] [Field L] [Algebra k L]

/-- A `k`-linear functional on `L`, applied to the coefficients of a polynomial over `L`. -/
@[category API, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
noncomputable def polyMapFun (π : L →ₗ[k] k) (p : Polynomial L) : Polynomial k :=
  ∑ n ∈ p.support, monomial n (π (p.coeff n))

@[category API, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
lemma coeff_polyMapFun (π : L →ₗ[k] k) (p : Polynomial L) (n : ℕ) :
    (polyMapFun π p).coeff n = π (p.coeff n) := by
  classical
  simp only [polyMapFun, finsetSum_coeff, coeff_monomial]
  by_cases h : n ∈ p.support
  · rw [Finset.sum_eq_single n (fun m _ hm => by simp [hm]) (fun hn => absurd h hn)]
    simp
  · rw [Polynomial.notMem_support_iff.mp h, map_zero]
    exact Finset.sum_eq_zero fun m hm => by simp [show ¬ m = n from fun hh => h (hh ▸ hm)]

/-- The coefficientwise action of `π` on `L[z]`, as a `k`-linear map. -/
@[category API, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
noncomputable def polyMap (π : L →ₗ[k] k) : Polynomial L →ₗ[k] Polynomial k where
  toFun := polyMapFun π
  map_add' p q := by ext n; simp [coeff_polyMapFun]
  map_smul' c p := by ext n; simp [coeff_polyMapFun]

@[category API, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
lemma coeff_polyMap (π : L →ₗ[k] k) (p : Polynomial L) (n : ℕ) :
    (polyMap π p).coeff n = π (p.coeff n) := coeff_polyMapFun π p n

/-- The same functional applied to the coefficients of a power series over `L`. -/
@[category API, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
noncomputable def psMap (π : L →ₗ[k] k) : PowerSeries L →ₗ[k] PowerSeries k where
  toFun F := PowerSeries.mk fun n => π (PowerSeries.coeff n F)
  map_add' F G := by ext n; simp
  map_smul' c F := by ext n; simp

@[category API, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
lemma coeff_psMap (π : L →ₗ[k] k) (F : PowerSeries L) (n : ℕ) :
    PowerSeries.coeff n (psMap π F) = π (PowerSeries.coeff n F) := by
  simp [psMap]

/-- **The mechanism of the descent**: a `k`-linear functional applied coefficientwise passes
through a product `w(z)·h(z)` in which the *second* factor has its coefficients in `k`.

This is the one computation behind [AF17] Lemme 4.3 and behind the descent step reused in the
proof of Thm 1.10 («l'argument de descente déjà utilisé dans la démonstration du lemme 4.3»). -/
@[category research solved, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
lemma psMap_coe_mul (π : L →ₗ[k] k) (p : Polynomial L) (F : PowerSeries k) :
    psMap π ((p : PowerSeries L) * F.map (algebraMap k L))
      = ((polyMap π p : Polynomial k) : PowerSeries k) * F := by
  ext n
  rw [coeff_psMap, PowerSeries.coeff_mul, PowerSeries.coeff_mul, map_sum]
  refine Finset.sum_congr rfl fun x _ => ?_
  rw [Polynomial.coeff_coe, PowerSeries.coeff_map, Polynomial.coeff_coe, coeff_polyMap,
    mul_comm, ← Algebra.smul_def, map_smul, smul_eq_mul, mul_comm]

/-- Evaluation at a point of the *base* field commutes with the coefficientwise action of `π`. -/
@[category research solved, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
lemma eval_polyMap (π : L →ₗ[k] k) (p : Polynomial L) (α : k) :
    (polyMap π p).eval α = π (p.eval (algebraMap k L α)) := by
  have hdeg : (polyMap π p).natDegree ≤ p.natDegree :=
    natDegree_le_iff_coeff_eq_zero.mpr fun m hm => by
      rw [coeff_polyMap, coeff_eq_zero_of_natDegree_lt hm, map_zero]
  rw [eval_eq_sum_range' (Nat.lt_succ_of_le hdeg), eval_eq_sum_range' (Nat.lt_succ_self _),
    map_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [coeff_polyMap, ← map_pow, mul_comm (p.coeff i), ← Algebra.smul_def, map_smul, smul_eq_mul,
    mul_comm]

variable {ι : Type*} [Fintype ι]

/-- **The descent, in the form the proofs use**: applying a `k`-linear functional coefficientwise
to a relation `Σᵢ wᵢ(z)hᵢ(z) = 0` whose `hᵢ` have coefficients in `k` produces a relation with
coefficients in `k`. -/
@[category research solved, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
theorem descent_relation (π : L →ₗ[k] k) (h : ι → PowerSeries k) (w : ι → Polynomial L)
    (hrel : ∑ i, (w i : PowerSeries L) * (h i).map (algebraMap k L) = 0) :
    ∑ i, ((polyMap π (w i) : Polynomial k) : PowerSeries k) * h i = 0 :=
  calc ∑ i, ((polyMap π (w i) : Polynomial k) : PowerSeries k) * h i
      = ∑ i, psMap π ((w i : PowerSeries L) * (h i).map (algebraMap k L)) :=
        Finset.sum_congr rfl fun i _ => (psMap_coe_mul π (w i) (h i)).symm
    _ = psMap π (∑ i, (w i : PowerSeries L) * (h i).map (algebraMap k L)) := (map_sum _ _ _).symm
    _ = 0 := by rw [hrel, map_zero]

/-- **[AF17] Lemme 4.3** — *le lemme de descente*.  Let `h₁,…,hₙ` be power series with
coefficients in a field `k`, let `α ∈ k`, and let `w₁,…,wₙ ∈ L[z]` (`L ⊇ k`, in [AF17]
`L = ℚ̄`) satisfy

  `w₁(z)h₁(z) + ⋯ + wₙ(z)hₙ(z) = 0`,  `wᵢ(α) = 0` for `i ∈ I`,  `w_{i₀}(α) ≠ 0`.

Then the same holds with coefficients in `k`: there are `w'ᵢ ∈ k[z]` with `Σ w'ᵢhᵢ = 0`,
`w'ᵢ(α) = 0` on `I`, and `w'_{i₀}(α) ≠ 0` — in particular not all `w'ᵢ` vanish.

[AF17] argue with a primitive element for the finite extension generated by the coefficients of
the `wᵢ` and expand in the basis `1, φ, …, φ^{h-1}`; the proof here picks instead a single
`k`-linear functional `π : L → k` with `π(w_{i₀}(α)) ≠ 0` (a coordinate functional for *any*
`k`-basis of `L`) and applies it to the coefficients.  That is the same argument with the
bookkeeping removed, and it needs neither finiteness nor separability of `L/k`.

Note where the hypotheses enter: `π` is only `k`-linear, so it may be pulled through a product
`wᵢ(z)hᵢ(z)` exactly because the `hᵢ` have coefficients in `k` (`psMap_coe_mul`), and through an
evaluation exactly because `α ∈ k` (`eval_polyMap`). -/
@[category research solved, AMS 11 12, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem lemme_4_3 (h : ι → PowerSeries k) (α : k) (w : ι → Polynomial L)
    (hrel : ∑ i, (w i : PowerSeries L) * (h i).map (algebraMap k L) = 0)
    (I : Set ι) (hI : ∀ i ∈ I, (w i).eval (algebraMap k L α) = 0)
    {i₀ : ι} (hi₀ : (w i₀).eval (algebraMap k L α) ≠ 0) :
    ∃ w' : ι → Polynomial k,
      (∑ i, ((w' i : Polynomial k) : PowerSeries k) * h i = 0) ∧
        (∀ i ∈ I, (w' i).eval α = 0) ∧ (w' i₀).eval α ≠ 0 := by
  obtain ⟨π, hπ⟩ := Module.Projective.exists_dual_ne_zero k hi₀
  refine ⟨fun i => polyMap π (w i), descent_relation π h w hrel, fun i hi => ?_, ?_⟩
  · rw [eval_polyMap, hI i hi, map_zero]
  · rwa [eval_polyMap]

/-- **The descent with a prescribed `k`-rational evaluation** — the form consumed by the proof of
[AF17] Thm 1.10, where the lifted matrix `C(z)` over `ℚ̄[z]` has to be replaced by one over `k[z]`
*with the same value* `C(α) = A_d` (a matrix over `k`).

Here the functional is a `k`-linear retraction `π : L → k` of `k ↪ L`, which exists for every
field extension; `π` then fixes the prescribed values `vᵢ ∈ k`. -/
@[category research solved, AMS 11 12, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem lemme_4_3_eval (h : ι → PowerSeries k) (α : k) (v : ι → k) (w : ι → Polynomial L)
    (hrel : ∑ i, (w i : PowerSeries L) * (h i).map (algebraMap k L) = 0)
    (heval : ∀ i, (w i).eval (algebraMap k L α) = algebraMap k L (v i)) :
    ∃ w' : ι → Polynomial k,
      (∑ i, ((w' i : Polynomial k) : PowerSeries k) * h i = 0) ∧ ∀ i, (w' i).eval α = v i := by
  obtain ⟨π, hπ⟩ := (Algebra.linearMap k L).exists_leftInverse_of_injective
    (LinearMap.ker_eq_bot.mpr (algebraMap k L).injective)
  refine ⟨fun i => polyMap π (w i), descent_relation π h w hrel, fun i => ?_⟩
  rw [eval_polyMap, heval i]
  exact congrFun (congrArg (fun f : k →ₗ[k] k => (f : k → k)) hπ) (v i)

end Descent

/-! ## The setting for Lemmes 4.1 and 4.2: polynomial Mahler systems -/

section System

variable {k 𝕜 : Type*} [Field k] [Field 𝕜] [Algebra k 𝕜]
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **A solution of the `q`-Mahler system** `F(z) = A(z)F(z^q)` on a set `S` ([AF17] (1.2)):
the functions `F i : 𝕜 → 𝕜` satisfy the system at every point of `S`, the matrix `A` having
polynomial entries over the base field `k`. -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
def IsMahlerSolution (q : ℕ) (A : Matrix ι ι (Polynomial k)) (F : ι → 𝕜 → 𝕜) (S : Set 𝕜) : Prop :=
  ∀ z ∈ S, ∀ i, F i z = ∑ j, aeval z (A i j) * F j (z ^ q)

/-- **A regular point of a polynomial system** ([AF17] §1): `α` is *singular* when some `α^{q^l}`
is a pole of a coefficient of `A(z)` or of `A(z)⁻¹`.  For a matrix with *polynomial* entries the
first alternative is empty and the second says `det A(α^{q^l}) = 0`, so regularity reads: -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
def IsRegularPoint (q : ℕ) (A : Matrix ι ι (Polynomial k)) (α : 𝕜) : Prop :=
  ∀ l : ℕ, aeval (α ^ q ^ l) A.det ≠ 0

/-! ### Lemme 4.1, and why it costs nothing here -/

omit [DecidableEq ι] in
/-- **[AF17] Lemme 4.1 for a polynomial system** — vacuous, and that is the point.

Lemme 4.1 embeds a system whose matrix `A(z)` has *rational-function* entries into a bigger one
whose matrix has no pole at any `α^{q^l}`, at the price of `gᵢ(α) = λᵢfᵢ(α)` with `λᵢ ∈ k∖{0}`;
its proof multiplies by an infinite product `∏_{j≥0} β(z^{q^j})` and differentiates the system
`s` times.  None of that is needed for the systems this corpus meets, and [AF17] say so:

> «Notons que cette astuce s'avère inutile dans le cas des séries automatiques (ou même
> régulières) puisque l'on peut alors se ramener à un système mahlérien dont la matrice est à
> coefficients polynômes.»

Every system in this file — and in particular every `RB.mahlerMatrix`, whose entries lie in
`ℤ[z]` by construction — is polynomial, so the embedding may be taken to be the identity, with
`λᵢ = 1`.  This is `plans/plan-formalize-AF17.html` risk R6, discharged: the general Lemme 4.1
is **not** formalized here and is not on the route to Cor 1.8. -/
@[category research solved, AMS 11 12 39, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem lemme_4_1_of_polynomial (q : ℕ) (A : Matrix ι ι (Polynomial k)) (F : ι → 𝕜 → 𝕜)
    (S : Set 𝕜) (hF : IsMahlerSolution q A F S) (α : 𝕜) :
    ∃ (B : Matrix ι ι (Polynomial k)) (G : ι → 𝕜 → 𝕜) (lam : ι → k),
      IsMahlerSolution q B G S ∧ (∀ i, lam i ≠ 0) ∧
        ∀ i, G i α = algebraMap k 𝕜 (lam i) * F i α :=
  ⟨A, F, 1, hF, fun _ => one_ne_zero, fun _ => by simp⟩

/-! ### Lemme 4.2: the doubling construction -/

/-- `A(z^q)`, entrywise. -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
noncomputable def compPow (q : ℕ) (A : Matrix ι ι (Polynomial k)) : Matrix ι ι (Polynomial k) :=
  A.map fun p => p.comp (X ^ q)

omit [Fintype ι] [DecidableEq ι] in
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
lemma aeval_compPow (q : ℕ) (A : Matrix ι ι (Polynomial k)) (z : 𝕜) (i j : ι) :
    aeval z (compPow q A i j) = aeval (z ^ q) (A i j) := by
  simp [compPow, Matrix.map_apply, Polynomial.aeval_comp]

@[category research solved, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
lemma det_compPow (q : ℕ) (A : Matrix ι ι (Polynomial k)) :
    (compPow q A).det = A.det.comp (X ^ q) := by
  rw [Polynomial.comp_eq_aeval, AlgHom.map_det]
  rfl

/-- **The doubled matrix** ([AF17] (4.5)): `B₁(z) = [[A(z) − I, A(z^q)], [I, 0]]`, the system
satisfied by the `2n` functions `f₁(z),…,fₙ(z), f₁(z^q),…,fₙ(z^q)`. -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
noncomputable def dblMat (q : ℕ) (A : Matrix ι ι (Polynomial k)) :
    Matrix (ι ⊕ ι) (ι ⊕ ι) (Polynomial k) :=
  Matrix.fromBlocks (A - 1) (compPow q A) 1 0

/-- **The doubling transports solutions** ([AF17] (4.5)): if `F` solves `F(z) = A(z)F(z^q)` on a
set `S` stable under `z ↦ z^q`, then `(F(z), F(z^q))` solves the doubled system.

The computation is pure algebra: the `(A − I)`-block cancels the copy of `F(z^q)` that the
identity block reintroduces, and the `A(z^q)`-block is the original system read at `z^q`. -/
@[category research solved, AMS 11 12 39, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem isMahlerSolution_dblMat {q : ℕ} {A : Matrix ι ι (Polynomial k)} {F : ι → 𝕜 → 𝕜}
    {S : Set 𝕜} (hS : ∀ z ∈ S, z ^ q ∈ S) (hF : IsMahlerSolution q A F S) :
    IsMahlerSolution q (dblMat q A) (Sum.elim F fun i z => F i (z ^ q)) S := by
  classical
  intro z hz i
  have key : ∀ (G : ι → 𝕜) (i : ι),
      ∑ j : ι, aeval z ((1 : Matrix ι ι (Polynomial k)) i j) * G j = G i := by
    intro G i
    simp [Matrix.one_apply, apply_ite (aeval z)]
  rw [Fintype.sum_sum_type]
  cases i with
  | inl i =>
    have h1 := hF z hz i
    have h2 := hF (z ^ q) (hS z hz) i
    have s1 : ∑ j : ι, aeval z (dblMat q A (Sum.inl i) (Sum.inl j)) *
        (Sum.elim F fun i z => F i (z ^ q)) (Sum.inl j) (z ^ q) = F i z - F i (z ^ q) := by
      have e : ∀ j : ι, aeval z (dblMat q A (Sum.inl i) (Sum.inl j)) *
          (Sum.elim F fun i z => F i (z ^ q)) (Sum.inl j) (z ^ q)
          = aeval z (A i j) * F j (z ^ q)
            - aeval z ((1 : Matrix ι ι (Polynomial k)) i j) * F j (z ^ q) := fun j => by
        simp only [dblMat, Matrix.fromBlocks_apply₁₁, Matrix.sub_apply, map_sub, Sum.elim_inl,
          sub_mul]
      rw [Finset.sum_congr rfl fun j _ => e j, Finset.sum_sub_distrib, key, ← h1]
    have s2 : ∑ j : ι, aeval z (dblMat q A (Sum.inl i) (Sum.inr j)) *
        (Sum.elim F fun i z => F i (z ^ q)) (Sum.inr j) (z ^ q) = F i (z ^ q) := by
      have e : ∀ j : ι, aeval z (dblMat q A (Sum.inl i) (Sum.inr j)) *
          (Sum.elim F fun i z => F i (z ^ q)) (Sum.inr j) (z ^ q)
          = aeval (z ^ q) (A i j) * F j ((z ^ q) ^ q) := fun j => by
        simp only [dblMat, Matrix.fromBlocks_apply₁₂, Sum.elim_inr, aeval_compPow]
      rw [Finset.sum_congr rfl fun j _ => e j, ← h2]
    rw [s1, s2, Sum.elim_inl]
    ring
  | inr i =>
    have s1 : ∑ j : ι, aeval z (dblMat q A (Sum.inr i) (Sum.inl j)) *
        (Sum.elim F fun i z => F i (z ^ q)) (Sum.inl j) (z ^ q) = F i (z ^ q) := by
      have e : ∀ j : ι, aeval z (dblMat q A (Sum.inr i) (Sum.inl j)) *
          (Sum.elim F fun i z => F i (z ^ q)) (Sum.inl j) (z ^ q)
          = aeval z ((1 : Matrix ι ι (Polynomial k)) i j) * F j (z ^ q) := fun j => by
        simp only [dblMat, Matrix.fromBlocks_apply₂₁, Sum.elim_inl]
      rw [Finset.sum_congr rfl fun j _ => e j, key]
    have s2 : ∑ j : ι, aeval z (dblMat q A (Sum.inr i) (Sum.inr j)) *
        (Sum.elim F fun i z => F i (z ^ q)) (Sum.inr j) (z ^ q) = 0 := by
      simp [dblMat]
    rw [s1, s2, Sum.elim_inr]
    ring

/-- The block swap `[[0, I], [I, 0]]`, an involution — the only place a sign could enter. -/
@[category API, AMS 11 12 15, ref "AF17", group "af_mahler_alternative"]
noncomputable def swapBlocks : Matrix (ι ⊕ ι) (ι ⊕ ι) (Polynomial k) := Matrix.fromBlocks 0 1 1 0

@[category API, AMS 11 12 15, ref "AF17", group "af_mahler_alternative"]
lemma swapBlocks_mul_self :
    (swapBlocks : Matrix (ι ⊕ ι) (ι ⊕ ι) (Polynomial k)) * swapBlocks = 1 := by
  simp [swapBlocks, Matrix.fromBlocks_multiply]

/-- **The determinant of the doubled system** ([AF17] p. 19: «on a `det B₁(z) = det A(z^q)`»):
`det B₁ = ε · det A(z^q)` with `ε² = 1`.

The unit `ε` is the determinant of the block swap; carrying it as an involution rather than
computing its sign `(−1)^n` is enough for every use, since only the *vanishing* of the
determinant matters. -/
@[category research solved, AMS 11 12 15, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem det_dblMat (q : ℕ) (A : Matrix ι ι (Polynomial k)) :
    ∃ ε : Polynomial k, ε * ε = 1 ∧ (dblMat q A).det = ε * (compPow q A).det := by
  refine ⟨(swapBlocks : Matrix (ι ⊕ ι) (ι ⊕ ι) (Polynomial k)).det, ?_, ?_⟩
  · rw [← Matrix.det_mul, swapBlocks_mul_self, Matrix.det_one]
  · have hfac : dblMat q A = Matrix.fromBlocks 1 (A - 1) 0 1 *
        (swapBlocks * Matrix.fromBlocks 1 0 0 (compPow q A)) := by
      simp [dblMat, swapBlocks, Matrix.fromBlocks_multiply]
    rw [hfac, Matrix.det_mul, Matrix.det_mul, Matrix.det_fromBlocks_zero₂₁,
      Matrix.det_fromBlocks_zero₂₁]
    simp

/-! ### Iterating the doubling -/

/-- The index type after `j` doublings: `2ʲ` copies of `ι`. -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
def dblIdx (ι : Type*) : ℕ → Type _
  | 0 => ι
  | j + 1 => dblIdx ι j ⊕ dblIdx ι j

instance dblIdx.instFintype (ι : Type*) [Fintype ι] : (j : ℕ) → Fintype (dblIdx ι j)
  | 0 => ‹Fintype ι›
  | j + 1 =>
    letI := dblIdx.instFintype ι j
    inferInstanceAs (Fintype (dblIdx ι j ⊕ dblIdx ι j))

instance dblIdx.instDecidableEq (ι : Type*) [DecidableEq ι] : (j : ℕ) → DecidableEq (dblIdx ι j)
  | 0 => ‹DecidableEq ι›
  | j + 1 =>
    letI := dblIdx.instDecidableEq ι j
    inferInstanceAs (DecidableEq (dblIdx ι j ⊕ dblIdx ι j))

/-- `B_j(z)`, the matrix after `j` doublings ([AF17] p. 20, the recursion defining `B_{n₀}`). -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
noncomputable def dblIterMat (q : ℕ) (A : Matrix ι ι (Polynomial k)) :
    (j : ℕ) → Matrix (dblIdx ι j) (dblIdx ι j) (Polynomial k)
  | 0 => A
  | j + 1 => dblMat q (dblIterMat q A j)

/-- The solution vector of `B_j`: the tuple of the `f_i(z^{q^a})`, with repetitions. -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
def dblIterSol (q : ℕ) (F : ι → 𝕜 → 𝕜) : (j : ℕ) → dblIdx ι j → 𝕜 → 𝕜
  | 0 => F
  | j + 1 => Sum.elim (dblIterSol q F j) fun i z => dblIterSol q F j i (z ^ q)

/-- The canonical inclusion of the original index set into the doubled one. -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
def dblEmb (ι : Type*) : (j : ℕ) → ι → dblIdx ι j
  | 0 => id
  | j + 1 => fun i => Sum.inl (dblEmb ι j i)

omit [Fintype ι] [DecidableEq ι] in
@[category research solved, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
lemma dblIterSol_dblEmb (q : ℕ) (F : ι → 𝕜 → 𝕜) :
    ∀ (j : ℕ) (i : ι), dblIterSol q F j (dblEmb ι j i) = F i
  | 0, _ => rfl
  | j + 1, i => dblIterSol_dblEmb q F j i

@[category research solved, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
theorem isMahlerSolution_dblIterMat {q : ℕ} {A : Matrix ι ι (Polynomial k)} {F : ι → 𝕜 → 𝕜}
    {S : Set 𝕜} (hS : ∀ z ∈ S, z ^ q ∈ S) (hF : IsMahlerSolution q A F S) :
    ∀ j, IsMahlerSolution q (dblIterMat q A j) (dblIterSol q F j) S
  | 0 => hF
  | j + 1 => isMahlerSolution_dblMat hS (isMahlerSolution_dblIterMat hS hF j)

/-- **`det B_j = ε · (det A)(z^{q^j})`, `ε² = 1`** ([AF17] p. 20: «On obtient donc que
`det B_{n₀}(z) = det B₀(z^{q^{n₀}})`»).  The `j`-fold doubling shifts the determinant by `j`
Mahler steps and nothing else. -/
@[category research solved, AMS 11 12 15, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem det_dblIterMat (q : ℕ) (A : Matrix ι ι (Polynomial k)) :
    ∀ j : ℕ, ∃ ε : Polynomial k, ε * ε = 1 ∧
      (dblIterMat q A j).det = ε * A.det.comp (X ^ q ^ j)
  | 0 => ⟨1, one_mul 1, by simp only [dblIterMat, pow_zero, pow_one, comp_X, one_mul]; rfl⟩
  | j + 1 => by
    obtain ⟨ε, hε, h⟩ := det_dblIterMat q A j
    obtain ⟨δ, hδ, hd⟩ := det_dblMat q (dblIterMat q A j)
    have hstep : (dblIterMat q A (j + 1)).det = (dblMat q (dblIterMat q A j)).det := rfl
    refine ⟨δ * ε.comp (X ^ q), ?_, ?_⟩
    · calc δ * ε.comp (X ^ q) * (δ * ε.comp (X ^ q))
          = (δ * δ) * (ε * ε).comp (X ^ q) := by rw [mul_comp]; ring
        _ = 1 := by rw [hδ, hε, one_comp, mul_one]
    · rw [hstep, hd, det_compPow, h, mul_comp, comp_assoc, pow_comp, X_comp, ← pow_mul,
        ← pow_succ']
      ring

/-! ### Only finitely many Mahler iterates can be singular -/

/-- All but finitely many of the points `α^{q^l}` avoid the zeros of `det A` — the choice of the
integer `n₀` in [AF17] p. 19 («Comme les racines de `det B₁` sont en nombre fini, il existe un
entier `n₀` tel que …»).

The hypotheses are the two that make the argument work: `det A ≠ 0`, i.e. the system is
invertible ([AF17] take `A ∈ GLₙ(k(z))`), and the injectivity of `l ↦ α^{q^l}`, which for
`0 < |α| < 1` and `q ≥ 2` holds because the moduli decrease strictly. -/
@[category research solved, AMS 11 12 39, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem exists_regular_shift {q : ℕ} {A : Matrix ι ι (Polynomial k)} (hdet : A.det ≠ 0) {α : 𝕜}
    (hinj : Function.Injective fun l : ℕ => α ^ q ^ l) :
    ∃ n₀ : ℕ, ∀ l, n₀ ≤ l → aeval (α ^ q ^ l) A.det ≠ 0 := by
  have hmap : A.det.map (algebraMap k 𝕜) ≠ 0 :=
    fun h => hdet (Polynomial.map_eq_zero_iff (algebraMap k 𝕜).injective |>.mp h)
  have hfin : {l : ℕ | aeval (α ^ q ^ l) A.det = 0}.Finite := by
    refine Set.Finite.ofFinset ((Polynomial.finite_setOfPred_isRoot hmap).toFinset.preimage
      (fun l : ℕ => α ^ q ^ l) hinj.injOn) fun l => ?_
    simp [Polynomial.IsRoot, Polynomial.eval_map, ← Polynomial.aeval_def]
  obtain ⟨n₀, hn₀⟩ := hfin.bddAbove
  exact ⟨n₀ + 1, fun l hl h => by have := hn₀ (Set.mem_ofPred.mpr h); omega⟩

/-- **[AF17] Lemme 4.2** — *le dédoublement*.  A point `α` that is not a pole of the system
(automatic here: the matrix is polynomial, `lemme_4_1_of_polynomial`) becomes a **regular** point
after finitely many doublings, the original functions surviving unchanged inside the enlarged
solution vector.

This is the elementary route to regularity: enlarging the system rather than desingularizing the
matrix ([AF17] Thm 1.10).  It costs nothing but bookkeeping — the determinant of `B_j` is that of
`A` read `j` Mahler steps later (`det_dblIterMat`), and only finitely many steps can be singular
(`exists_regular_shift`). -/
@[category research solved, AMS 11 12 39, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem lemme_4_2 {q : ℕ} {A : Matrix ι ι (Polynomial k)} {F : ι → 𝕜 → 𝕜} {S : Set 𝕜} {α : 𝕜}
    (hS : ∀ z ∈ S, z ^ q ∈ S) (hF : IsMahlerSolution q A F S) (hdet : A.det ≠ 0)
    (hinj : Function.Injective fun l : ℕ => α ^ q ^ l) :
    ∃ j : ℕ, IsMahlerSolution q (dblIterMat q A j) (dblIterSol q F j) S ∧
      IsRegularPoint q (dblIterMat q A j) α ∧
      ∀ i, dblIterSol q F j (dblEmb ι j i) = F i := by
  obtain ⟨n₀, hn₀⟩ := exists_regular_shift (q := q) hdet hinj
  refine ⟨n₀, isMahlerSolution_dblIterMat hS hF n₀, fun l => ?_, dblIterSol_dblEmb q F n₀⟩
  obtain ⟨ε, hε, h⟩ := det_dblIterMat q A n₀
  rw [h, map_mul]
  refine mul_ne_zero (fun h0 => ?_) ?_
  · have h1 := congrArg (aeval (α ^ q ^ l) : Polynomial k → 𝕜) hε
    rw [map_mul, h0, mul_zero, map_one] at h1
    exact one_ne_zero h1.symm
  · rw [Polynomial.aeval_comp, map_pow, aeval_X, ← pow_mul, ← pow_add]
    exact hn₀ (l + n₀) (Nat.le_add_left _ _)

end System

/-! ### The standing hypothesis `0 < |α| < 1` discharges the injectivity -/

/-- In a normed field, the Mahler iterates `α, α^q, α^{q²}, …` of a point of the punctured open
unit disc are pairwise distinct — their norms `‖α‖^{q^l}` decrease strictly.

This is [AF17]'s standing hypothesis `0 < |α| < 1` in the form `lemme_4_2` consumes. -/
@[category research solved, AMS 11 12 39, ref "AF17" "AF17f", group "af_mahler_alternative"]
theorem injective_pow_pow_of_norm_lt_one {𝕜 : Type*} [NormedField 𝕜] {α : 𝕜} (h0 : α ≠ 0)
    (h1 : ‖α‖ < 1) {q : ℕ} (hq : 2 ≤ q) : Function.Injective fun l : ℕ => α ^ q ^ l := by
  have hstrict : StrictAnti fun n : ℕ => ‖α‖ ^ n := fun m n hmn =>
    pow_lt_pow_right_of_lt_one₀ (norm_pos_iff.mpr h0) h1 hmn
  intro a b hab
  refine Nat.pow_right_injective hq (hstrict.injective ?_)
  simpa only [← norm_pow] using congrArg norm hab

end AF
