/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import CITED.AdamczewskiFaverjonDescent
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# [AF22] §2.4: the specialization at `α`

plan-formalize-AF17's **WP18**, gap (5) of Stage 2.

`AF.exists_lift`, the last step of §2.4, takes one analytic hypothesis: the *specialization*

  `hspec : ∑_{j<δ} p_{ij}(α)·xα^j = e·τ_i`,

and `AF.hspec_of_evalHom` (rev. 14) records what supplies it — a ring homomorphism
`ev : R →+* K`, «evaluate at `α`», on a subring of the abstract ambient field.  rev. 21 pinned
this as gap (5) and rev. 23 took the decision: **fold `ev` into `AF.lemma_2_8`, do not make it a
third axiom.**  This file makes that decision concrete, and it turns out to cost less than the
decision assumed.

## The specialization at `α` is the branch at `ξ`, seen through the twist

[AF22] Lemma 2.8 says the coordinates of `φ(z)` are analytic near `α^{q^{k₀}} = ξ`.  §2.4 does not
evaluate `φ` at `ξ`; it evaluates the **twisted** functions `φ(z^{q^{k₀}})` at `α` — and those are
the same numbers.  So the object gap (5) needs is not a new kind of thing: it is
`AF.IsAnalyticBranch` **again**, for the twisted matrix `s(φ)` at the point `φ(α)`, with `Ψ' z =
Ψ(z^{q^{k₀}})` and — because `Ψ'(φ α) = Ψ(ξ)` — with **the same `Φ₀`**.  Folding gap (5) into the
axiom therefore costs one more clause *of a shape the axiom already has*, and no new interface.

## Three things that were not obvious

* **A germ along `𝓟 U` has a value.**  WP12(b) chose the free filter `l = 𝓟 U` so that a germ *is*
  a function on `U`; the consequence used here is that evaluation at any `ξ ∈ U` is a ring
  homomorphism `AF.germEvalAt`.  Composed with the realization it gives `AF.branchEval`, and that
  is the `ev` §2.4 asks for.

* **`ev` cannot be `K`-valued, and does not need to be.**  A realization by *functions* lands in
  `ℂ`; there is no homomorphism to `K` in sight.  Since `φ : K →+* ℂ` is injective, an identity in
  `K` may be checked in `ℂ`, so `AF.hspec_of_evalHomC` — the same statement with a `ℂ`-valued `ev`
  — is what an analytic realization can actually discharge.  The `K`-valued interface of rev. 14 is
  the wrong primitive, in the same way `→* circle` was in the solenoid program.

* **`ev` lands in `φ(K)` on the subring that matters, and that is `Φ₀`'s doing.**  On
  `AF.branchRing` — the subring generated by `K[z]` and the entries — `AF.branchEval` takes the
  generators to `φ(w.eval α)` and to `φ(Φ₀ i j)`, so `AF.branchEval_mem_range` puts the whole
  subring into `φ.range`.  Consequently every number §2.4 reads off is *automatically* algebraic,
  and the axiom needs no clause saying so.

## The primitive element can be chosen inside the subring

The remaining hypothesis of `AF.hspec_of_evalHom` is `hevx`: the primitive element `ϕ` of (2.36)
must lie in the domain of `ev`.  `AF.exists_polynomial_decomposition` produces *some* `ϕ`, with no
control over where it sits, and there is nothing in the branch interface that would evaluate an
arbitrary element of `Ω`.

It is not needed.  The entries are algebraic over `K(z)`, so the field they generate is already
`K(z)[entries]`; a primitive element is therefore a `K(z)`-polynomial in them, and clearing one
denominator puts `e(z)·ϕ` inside `AF.branchRing` — where it is still primitive, `e(z)` being a
unit of `K(z)`.  `AF.exists_polynomial_decomposition_mem` is that refinement, and with it `hevx`
costs nothing and `xα ∈ K` is free.

## Contents

* `AF.germEvalAt` — a germ along a principal filter has a value at each point of the set;
* `AF.branchRing`, `AF.branchEval` — the subring §2.4 evaluates on, and the evaluation;
* `AF.branchEval_mem_range` — its values are algebraic;
* **`AF.hspec_of_evalHomC`** — `hspec` from a `ℂ`-valued evaluation;
* `AF.natDegree_minpoly_algebraMap_mul`, `AF.exists_primitive_decomposition_adjoin`,
  `AF.exists_denominator_mem`, **`AF.exists_polynomial_decomposition_mem`** — the primitive
  element inside the subring;
* **`AF.exists_hspec_of_branch`** — `hspec` from an analytic branch at `φ α`, with the
  decomposition produced inside its subring: gap (5) discharged, modulo the one numerical
  identity that is §2.4's own arithmetic.

## Superseded by the free-module route

`AF.exists_hspec_of_branch` is **not** what the assembly uses.  Its denominator `d` comes from the
decomposition of the *twisted* matrix, hence depends on `k₀`, and the specialization needs
`d(α) ≠ 0` — which [AF22] obtain from «for `k₀ ≫ 1`» only because *their* `d` is read off the
untwisted matrix and is therefore fixed before `k₀`.  There is no second «for `k₀ ≫ 1`» to spend
here, so that step is unprovable in this order of quantifiers.

`CITED/AdamczewskiFaverjonFreeSplit.lean` removes the difficulty rather than working around it:
`K[z]` is a principal ideal domain, so the coefficients of the relation generate a *free*
`K[z]`-module whose basis has polynomial coordinates — no denominator, no condition on `α`.
`AF.exists_hspec_free_of_branch` is the statement below in that shape, and everything in this file
above it is used unchanged by it.

## References

* [AF22] B. Adamczewski, C. Faverjon. *A new proof of Nishioka's theorem in Mahler's method.*
  arXiv:2210.14528 (2022), §2.4 ((2.36), (2.37)), §2.2.3 (Lemma 2.8).
* [AF17f] `plans/plan-formalize-AF17.html`: WP18, gap (5) of Stage 2, milestone M4.
-/

open Filter Topology

open scoped Polynomial IntermediateField

namespace AF

/-! ## A germ along a principal filter has a value -/

section GermEval

variable {U : Set ℂ} {ξ : ℂ}

/-- **Evaluation of a germ at a point of the set.**  Along the *principal* filter `𝓟 U` two
functions have the same germ exactly when they agree on all of `U` — this is why WP12(b) chose a
free filter — so evaluation at any `ξ ∈ U` is well defined, and it is a ring homomorphism. -/
@[category API, AMS 13 30, ref "AF22", group "af_mahler_alternative"]
def germEvalAt (hξ : ξ ∈ U) : Germ (𝓟 U) ℂ →+* ℂ where
  toFun g := Germ.liftOn g (fun f => f ξ) fun _ _ h => (Filter.eventuallyEq_principal.1 h) hξ
  map_one' := rfl
  map_mul' := by rintro ⟨f⟩ ⟨g⟩; rfl
  map_zero' := rfl
  map_add' := by rintro ⟨f⟩ ⟨g⟩; rfl

@[category API, AMS 13 30, ref "AF22", group "af_mahler_alternative"]
theorem germEvalAt_coe (hξ : ξ ∈ U) (f : ℂ → ℂ) :
    germEvalAt hξ ((f : ℂ → ℂ) : Germ (𝓟 U) ℂ) = f ξ := rfl

end GermEval

/-! ## The subring §2.4 evaluates on, and the evaluation -/

section BranchEval

variable {K Ω : Type*} [Field K] [Field Ω] [Algebra (RatFunc K) Ω]
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **The subring [AF22] §2.4 lives in**: generated by the polynomials in `z` and by the entries of
the relation matrix.  Every element of §2.4's coefficient row lies in it once the denominator is
cleared, and — this is the point — so does the primitive element, by
`AF.exists_polynomial_decomposition_mem`. -/
@[category API, AMS 11 12 13, ref "AF22", group "af_mahler_alternative"]
def branchRing (K : Type*) [Field K] {Ω : Type*} [Field Ω] [Algebra (RatFunc K) Ω] {ι : Type*}
    (Φ' : Matrix ι ι Ω) : Subring Ω :=
  Subring.closure (Set.range (toAmbient K Ω) ∪ Set.range fun p : ι × ι => Φ' p.1 p.2)

variable {φ : K →+* ℂ} {Φ' : Matrix ι ι Ω} {ζ : ℂ} {V : Set ℂ} {R : Subring Ω}
  {real : R →+* Germ (𝓟 V) ℂ} {Ψ : ℂ → Matrix ι ι ℂ} {Φ₁ : Matrix ι ι K}

omit [Fintype ι] [DecidableEq ι] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem toAmbient_mem_branchRing (w : K[X]) : toAmbient K Ω w ∈ branchRing K Φ' :=
  Subring.subset_closure (Or.inl ⟨w, rfl⟩)

omit [Fintype ι] [DecidableEq ι] in
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem mat_mem_branchRing (i j : ι) : Φ' i j ∈ branchRing K Φ' :=
  Subring.subset_closure (Or.inr ⟨(i, j), rfl⟩)

omit [Fintype ι] [DecidableEq ι] in
/-- The realization subring of a branch contains `AF.branchRing`: both generating families are
already in it, by `poly_mem` and `mat_mem`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem branchRing_le (hbr : IsBranchRealization φ (𝓟 V) Φ' R real Ψ) :
    branchRing K Φ' ≤ R :=
  Subring.closure_le.2 <| Set.union_subset (by rintro _ ⟨w, rfl⟩; exact hbr.poly_mem w)
    (by rintro _ ⟨p, rfl⟩; exact hbr.mat_mem p.1 p.2)

/-- **The evaluation homomorphism of [AF22] §2.4.**  The realization sends an element of the
ambient field to a germ of complex functions; evaluating that germ at the point gives the number
§2.4 wants.  This is the `ev` of `AF.hspec_of_evalHom`, with values in `ℂ` rather than in `K` —
see `AF.hspec_of_evalHomC`. -/
@[category research solved, AMS 11 12 13 30, ref "AF22", group "af_mahler_alternative"]
noncomputable def branchEval (hb : IsAnalyticBranch φ Φ' ζ V R real Ψ Φ₁) : R →+* ℂ :=
  (germEvalAt hb.mem_dom).comp real

@[category API, AMS 11 13 30, ref "AF22", group "af_mahler_alternative"]
theorem branchEval_poly (hb : IsAnalyticBranch φ Φ' ζ V R real Ψ Φ₁) (w : K[X]) :
    branchEval hb ⟨toAmbient K Ω w, hb.isBranch.poly_mem w⟩ = (w.map φ).eval ζ := by
  rw [branchEval, RingHom.comp_apply, hb.isBranch.real_poly, germEvalAt_coe]

/-- **On the relation matrix the evaluation returns `Φ₀`** — this is Lemma 2.8(c) doing its second
job, and the reason no clause about algebraicity has to be added to the axiom. -/
@[category research solved, AMS 11 13 30, ref "AF22", group "af_mahler_alternative"]
theorem branchEval_mat (hb : IsAnalyticBranch φ Φ' ζ V R real Ψ Φ₁) (i j : ι) :
    branchEval hb ⟨Φ' i j, hb.isBranch.mat_mem i j⟩ = φ (Φ₁ i j) := by
  rw [branchEval, RingHom.comp_apply, hb.isBranch.real_mat, germEvalAt_coe, ← hb.map_value,
    Matrix.map_apply]

/-- **Every number §2.4 reads off is algebraic.**  On `AF.branchRing` the evaluation takes the two
generating families into `φ(K)` — polynomials because the point is `φ(β)` for an algebraic `β`, the
matrix entries because of `Φ₁` — so it takes the whole subring there. -/
@[category research solved, AMS 11 12 13 30, ref "AF22", group "af_mahler_alternative"]
theorem branchEval_mem_range (hb : IsAnalyticBranch φ Φ' ζ V R real Ψ Φ₁) {β : K} (hζ : ζ = φ β)
    {y : Ω} (hy : y ∈ branchRing K Φ') :
    branchEval hb ⟨y, branchRing_le hb.isBranch hy⟩ ∈ φ.range := by
  induction hy using Subring.closure_induction with
  | mem x hx =>
      rcases hx with ⟨w, rfl⟩ | ⟨p, rfl⟩
      · rw [branchEval_poly, hζ, Polynomial.eval_map, Polynomial.eval₂_hom]
        exact ⟨w.eval β, rfl⟩
      · exact ⟨Φ₁ p.1 p.2, (branchEval_mat hb p.1 p.2).symm⟩
  | one => exact ⟨1, by rw [map_one]; exact (map_one _).symm⟩
  | zero => exact ⟨0, by rw [map_zero]; exact (map_zero _).symm⟩
  | add x y hx hy ihx ihy =>
      have h : (⟨x + y, branchRing_le hb.isBranch (Subring.add_mem _ hx hy)⟩ : R)
          = ⟨x, branchRing_le hb.isBranch hx⟩ + ⟨y, branchRing_le hb.isBranch hy⟩ := rfl
      rw [h, map_add]
      exact Subring.add_mem _ ihx ihy
  | neg x hx ihx =>
      have h : (⟨-x, branchRing_le hb.isBranch (Subring.neg_mem _ hx)⟩ : R)
          = -⟨x, branchRing_le hb.isBranch hx⟩ := rfl
      rw [h, map_neg]
      exact Subring.neg_mem _ ihx
  | mul x y hx hy ihx ihy =>
      have h : (⟨x * y, branchRing_le hb.isBranch (Subring.mul_mem _ hx hy)⟩ : R)
          = ⟨x, branchRing_le hb.isBranch hx⟩ * ⟨y, branchRing_le hb.isBranch hy⟩ := rfl
      rw [h, map_mul]
      exact Subring.mul_mem _ ihx ihy

end BranchEval

/-! ## `hspec` from a `ℂ`-valued evaluation -/

section HspecC

variable {K Ω : Type*} [Field K] [Field Ω] [Algebra (RatFunc K) Ω] {ι : Type*}

/-- **[AF22] §2.4's specialization, discharged by a `ℂ`-valued evaluation.**

`AF.hspec_of_evalHom` asks for `ev : R →+* K`.  A realization of the ambient field by *functions*
cannot give that — its values are complex numbers — but it does not have to: `φ : K →+* ℂ` is
injective, so an identity in `K` may be checked in `ℂ`.

Two departures from rev. 14's shape, both weakenings:

* the evaluation is `ℂ`-valued, and the three defining properties are read through `φ`;
* the coefficient row `c i` need not lie in `R` — only the **cleared** element
  `y i = d(z)·c i` does, which is what `AF.branchRing` actually contains.  Nothing in §2.4 uses
  `ev(c i)` separately from `ev(d)·ev(c i)`. -/
@[category research solved, AMS 11 12 13, ref "AF22", group "af_mahler_alternative"]
theorem hspec_of_evalHomC {R : Subring Ω} (ev : R →+* ℂ) {φ : K →+* ℂ}
    {α xα : K} {x : Ω} (hxR : x ∈ R) (hevx : ev ⟨x, hxR⟩ = φ xα)
    (hpolyR : ∀ w : K[X], toAmbient K Ω w ∈ R)
    (hevpoly : ∀ w : K[X], ev ⟨toAmbient K Ω w, hpolyR w⟩ = φ (w.eval α))
    {δ : ℕ} {p : ι → ℕ → K[X]} {y : ι → Ω} (hyR : ∀ i, y i ∈ R) {v : ι → K}
    (hevy : ∀ i, ev ⟨y i, hyR i⟩ = φ (v i))
    (hdec : ∀ i, y i = ∑ j ∈ Finset.range δ, toAmbient K Ω (p i j) * x ^ j) (i : ι) :
    ∑ j ∈ Finset.range δ, (p i j).eval α * xα ^ j = v i := by
  have hu : (⟨y i, hyR i⟩ : R)
      = ∑ j ∈ Finset.range δ, (⟨toAmbient K Ω (p i j), hpolyR _⟩ : R) * ⟨x, hxR⟩ ^ j := by
    apply Subtype.ext
    push_cast
    exact hdec i
  have h := congrArg ev hu
  simp only [map_sum, map_mul, map_pow, hevpoly, hevx, hevy] at h
  refine φ.injective ?_
  rw [h, map_sum]
  exact Finset.sum_congr rfl fun j _ => by rw [map_mul, map_pow]

end HspecC

/-! ## The primitive element, inside the subring -/

section PrimitiveMem

/-- **Scaling a primitive element by a non-zero scalar of the base field changes nothing.**  The
two generate the same simple extension, so their minimal polynomials have the same degree — which
is what lets `AF.exists_polynomial_decomposition_mem` clear a denominator without disturbing the
`δ` of (2.36). -/
@[category API, AMS 12, ref "AF22", group "af_mahler_alternative"]
theorem natDegree_minpoly_algebraMap_mul {F Ω : Type*} [Field F] [Field Ω] [Algebra F Ω] {a : F}
    (ha : a ≠ 0) {y : Ω} (hy : IsIntegral F y) :
    (minpoly F (algebraMap F Ω a * y)).natDegree = (minpoly F y).natDegree := by
  have hint : IsIntegral F (algebraMap F Ω a * y) := (isIntegral_algebraMap).mul hy
  have hEq : F⟮algebraMap F Ω a * y⟯ = F⟮y⟯ := by
    refine le_antisymm ?_ ?_
    · rw [IntermediateField.adjoin_simple_le_iff]
      exact mul_mem (IntermediateField.algebraMap_mem _ a) (IntermediateField.mem_adjoin_simple_self F y)
    · rw [IntermediateField.adjoin_simple_le_iff]
      have hmem : algebraMap F Ω a⁻¹ * (algebraMap F Ω a * y) ∈ F⟮algebraMap F Ω a * y⟯ :=
        mul_mem (IntermediateField.algebraMap_mem _ _)
          (IntermediateField.mem_adjoin_simple_self F _)
      have heq : algebraMap F Ω a⁻¹ * (algebraMap F Ω a * y) = y := by
        rw [← mul_assoc, ← map_mul, inv_mul_cancel₀ ha, map_one, one_mul]
      rw [heq] at hmem
      exact hmem
  rw [← IntermediateField.adjoin.finrank hint, ← IntermediateField.adjoin.finrank hy, hEq]

variable {F Ω : Type*} [Field F] [CharZero F] [Field Ω] [Algebra F Ω]

/-- **`AF.exists_primitive_decomposition` with the primitive element located.**  The proof is the
same power basis; what is added is the one clause the decomposition does not record and gap (5)
needs — that `ϕ` lies in the field the family generates, and so is a polynomial in the family. -/
@[category research solved, AMS 11 12, ref "AF22", group "af_mahler_alternative"]
theorem exists_primitive_decomposition_adjoin {ι : Type*} [Finite ι] (x : ι → Ω)
    (hint : ∀ s, IsIntegral F (x s)) :
    ∃ (ϕ : Ω) (δ : ℕ) (c : ι → ℕ → F), ϕ ∈ IntermediateField.adjoin F (Set.range x) ∧
      IsIntegral F ϕ ∧ (minpoly F ϕ).natDegree = δ ∧
      ∀ s, x s = ∑ j ∈ Finset.range δ, algebraMap F Ω (c s j) * ϕ ^ j := by
  classical
  have : Finite (Set.range x) := (Set.finite_range x).to_subtype
  set L : IntermediateField F Ω := IntermediateField.adjoin F (Set.range x) with hL
  have : FiniteDimensional F L :=
    IntermediateField.finiteDimensional_adjoin (fun y hy => by
      obtain ⟨s, rfl⟩ := hy
      exact hint s)
  set pb := Field.powerBasisOfFiniteOfSeparable F L with hpb
  have hgen : (algebraMap L Ω) pb.gen = (pb.gen : Ω) := rfl
  have hmin : minpoly F ((pb.gen : Ω)) = minpoly F pb.gen := by
    rw [← hgen]
    exact minpoly.algebraMap_eq (algebraMap L Ω).injective pb.gen
  have hdeg : (minpoly F ((pb.gen : Ω))).natDegree = pb.dim := by
    rw [hmin]
    exact pb.natDegree_minpoly
  have hmemL : ∀ s, x s ∈ L := fun s =>
    IntermediateField.subset_adjoin F (Set.range x) ⟨s, rfl⟩
  refine ⟨(pb.gen : Ω), pb.dim, fun s j => if hj : j < pb.dim then
      pb.basis.repr ⟨x s, hmemL s⟩ ⟨j, hj⟩ else 0, pb.gen.2, ?_, hdeg, fun s => ?_⟩
  · exact (IsIntegral.of_finite F pb.gen).map L.val
  · have hrepr : (⟨x s, hmemL s⟩ : L) = ∑ j : Fin pb.dim,
        pb.basis.repr ⟨x s, hmemL s⟩ j • pb.gen ^ (j : ℕ) := by
      conv_lhs => rw [← pb.basis.sum_repr ⟨x s, hmemL s⟩]
      exact Finset.sum_congr rfl fun j _ => by rw [pb.basis_eq_pow]
    have hΩ : x s = ∑ j : Fin pb.dim,
        algebraMap F Ω (pb.basis.repr ⟨x s, hmemL s⟩ j) * (pb.gen : Ω) ^ (j : ℕ) := by
      have h := congrArg L.val hrepr
      rw [map_sum] at h
      simpa [Algebra.smul_def] using h
    rw [hΩ, ← Fin.sum_univ_eq_sum_range]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp

end PrimitiveMem

section Denominator

variable {K : Type*} [Field K] {Ω : Type*} [Field Ω] [Algebra (RatFunc K) Ω]

/-- **Clearing one denominator lands in the subring.**  An element of the `K(z)`-algebra generated
by a set `S` is a `K(z)`-combination of finitely many monomials in `S`; a common denominator of
those coefficients moves it into any subring that contains `K[z]` and `S`. -/
@[category research solved, AMS 11 12 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_denominator_mem {S : Set Ω} {T : Subring Ω}
    (hpoly : ∀ w : K[X], toAmbient K Ω w ∈ T) (hS : S ⊆ (T : Set Ω)) {y : Ω}
    (hy : y ∈ Algebra.adjoin (RatFunc K) S) :
    ∃ e : K[X], e ≠ 0 ∧ toAmbient K Ω e * y ∈ T := by
  classical
  have hmon : (Submonoid.closure S : Set Ω) ⊆ (T : Set Ω) :=
    Submonoid.closure_le.2 hS
  have hspan : y ∈ Submodule.span (RatFunc K) ((Submonoid.closure S : Submonoid Ω) : Set Ω) := by
    rw [← Algebra.adjoin_eq_span]
    exact hy
  obtain ⟨n, f, g, hfg⟩ := Submodule.mem_span_set'.1 hspan
  obtain ⟨d, hd0, p, hp⟩ := exists_commonDenominator f
  refine ⟨d, hd0, ?_⟩
  have hsum : toAmbient K Ω d * y = ∑ i, toAmbient K Ω (p i) * (g i : Ω) := by
    rw [← hfg, Finset.mul_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Algebra.smul_def, ← mul_assoc, toAmbient_apply, toAmbient_apply, ← map_mul, hp i]
  rw [hsum]
  exact Subring.sum_mem _ fun i _ => Subring.mul_mem _ (hpoly _) (hmon (g i).2)

end Denominator

section DecompositionMem

variable {K : Type*} [Field K] [CharZero K] {Ω : Type*} [Field Ω] [Algebra (RatFunc K) Ω]

/-- **[AF22] (2.36) with the primitive element inside the subring.**

This is the refinement gap (5) needs.  `AF.exists_polynomial_decomposition` produces *some*
primitive element, and there is nothing in the branch interface that evaluates an arbitrary element
of `Ω`; `AF.hspec_of_evalHom`'s hypothesis `hevx` would then be a genuine extra demand on the
axiom.

It is not.  The `x s` are algebraic over `K(z)`, so the field they generate *is* the `K(z)`-algebra
they generate, hence the primitive element is a `K(z)`-polynomial in them
(`AF.exists_primitive_decomposition_adjoin`), and one denominator moves it into the subring
(`AF.exists_denominator_mem`).  Scaling by that denominator leaves it primitive
(`AF.natDegree_minpoly_algebraMap_mul`), so `δ` is unchanged.

The consequence is that `xα = ev(ϕ)` is *automatically* a value of `φ`, by
`AF.branchEval_mem_range` — so gap (5) costs the axiom nothing beyond a branch at `φ α`. -/
@[category research solved, AMS 11 12 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_polynomial_decomposition_mem {ι : Type*} [Fintype ι] (x : ι → Ω)
    (hint : ∀ s, IsIntegral (RatFunc K) (x s)) {T : Subring Ω}
    (hpoly : ∀ w : K[X], toAmbient K Ω w ∈ T) (hxT : ∀ s, x s ∈ T) :
    ∃ (ϕ : Ω) (δ : ℕ) (d : K[X]) (p : ι → ℕ → K[X]),
      ϕ ∈ T ∧ IsIntegral (RatFunc K) ϕ ∧ (minpoly (RatFunc K) ϕ).natDegree = δ ∧ d ≠ 0 ∧
      ∀ s, toAmbient K Ω d * x s = ∑ j ∈ Finset.range δ, toAmbient K Ω (p s j) * ϕ ^ j := by
  classical
  obtain ⟨ϕ₀, δ, c, hmem, hϕ₀, hδ, hx⟩ := exists_primitive_decomposition_adjoin x hint
  -- the primitive element is a polynomial in the family, hence lies in `T` after scaling
  have hadj : ϕ₀ ∈ Algebra.adjoin (RatFunc K) (Set.range x) := by
    have halg : ∀ y ∈ Set.range x, IsAlgebraic (RatFunc K) y := by
      rintro _ ⟨s, rfl⟩
      exact (hint s).isAlgebraic
    rw [← IntermediateField.adjoin_toSubalgebra_of_isAlgebraic halg]
    exact hmem
  obtain ⟨e, he0, heT⟩ := exists_denominator_mem hpoly (by rintro _ ⟨s, rfl⟩; exact hxT s) hadj
  set a : RatFunc K := algebraMap K[X] (RatFunc K) e with ha
  have ha0 : a ≠ 0 := by
    rw [ha]
    exact fun h => he0 ((IsFractionRing.injective K[X] (RatFunc K)) (by simpa using h))
  set ϕ : Ω := algebraMap (RatFunc K) Ω a * ϕ₀ with hϕdef
  have hϕT : ϕ ∈ T := by rw [hϕdef, ← toAmbient_apply]; exact heT
  have hϕint : IsIntegral (RatFunc K) ϕ := (isIntegral_algebraMap).mul hϕ₀
  have hϕδ : (minpoly (RatFunc K) ϕ).natDegree = δ := by
    rw [hϕdef, natDegree_minpoly_algebraMap_mul ha0 hϕ₀, hδ]
  -- rewrite the decomposition in powers of `ϕ`, then clear the new denominators
  have hx' : ∀ s, x s = ∑ j ∈ Finset.range δ,
      algebraMap (RatFunc K) Ω (c s j / a ^ j) * ϕ ^ j := by
    intro s
    rw [hx s]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [hϕdef, mul_pow, ← mul_assoc, ← map_pow (algebraMap (RatFunc K) Ω) a j, ← map_mul,
      div_mul_cancel₀ _ (pow_ne_zero j ha0)]
  obtain ⟨d, hd0, p, hp⟩ :=
    exists_commonDenominator (fun s : ι × Fin δ => c s.1 (s.2 : ℕ) / a ^ (s.2 : ℕ))
  refine ⟨ϕ, δ, d, fun s j => if hj : j < δ then p (s, ⟨j, hj⟩) else 0, hϕT, hϕint, hϕδ, hd0,
    fun s => ?_⟩
  rw [hx' s, Finset.mul_sum]
  refine Finset.sum_congr rfl fun j hj => ?_
  rw [Finset.mem_range] at hj
  show _ = toAmbient K Ω (if h : j < δ then p (s, ⟨j, h⟩) else 0) * ϕ ^ j
  rw [dite_eq_left hj, toAmbient_apply, toAmbient_apply, ← mul_assoc, ← map_mul, hp (s, ⟨j, hj⟩)]

end DecompositionMem

/-! ## Gap (5): `hspec` from a branch at `α` -/

section HspecOfBranch

variable {K Ω : Type*} [Field K] [CharZero K] [Field Ω] [Algebra (RatFunc K) Ω]
variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable {φ : K →+* ℂ} {Φ' : Matrix ι ι Ω} {α : K} {V : Set ℂ} {R : Subring Ω}
  {real : R →+* Germ (𝓟 V) ℂ} {Ψ : ℂ → Matrix ι ι ℂ} {Φ₁ : Matrix ι ι K}

/-- **Gap (5) of Stage 2, discharged.**

An analytic branch at the point `φ(α)` — for the *twisted* relation matrix, which by [AF22]
Lemma 2.8 is the same analytic datum as the branch at `ξ = φ(α)^{q^{k₀}}` — delivers everything
[AF22] (2.36) and `AF.exists_lift` ask for:

* the decomposition itself, with the primitive element `x` **inside** the branch's subring, so
  that the branch can evaluate it (`AF.exists_polynomial_decomposition_mem`);
* its value `xα`, which is *automatically* an algebraic number (`AF.branchEval_mem_range`) — so
  the final linear form has coefficients in `K[z]` and no clause about this has to be added to
  `AF.lemma_2_8`;
* and the specialization `hspec` for whatever value the branch assigns to `d(z)·c_i`.

That last value is the only thing left, and it is not analytic: it is [AF22]'s computation
`Θ_{k₀}(ξ) = A_{k₀}(α)`, i.e. pure arithmetic with the numbers `Φ₀` and `A_{k₀}(α)`, and belongs
to the final assembly.  Nothing else in §2.4 needs the ambient field to be a field of functions. -/
@[category research solved, AMS 11 12 13 30, ref "AF22", group "af_mahler_alternative"]
theorem exists_hspec_of_branch (hb : IsAnalyticBranch φ Φ' (φ α) V R real Ψ Φ₁) {c : ι → Ω}
    (hint : ∀ i, IsIntegral (RatFunc K) (c i)) (hcT : ∀ i, c i ∈ branchRing K Φ') :
    ∃ (x : Ω) (hxT : x ∈ branchRing K Φ') (δ : ℕ) (d : K[X]) (p : ι → ℕ → K[X]) (xα : K),
      IsIntegral (RatFunc K) x ∧ (minpoly (RatFunc K) x).natDegree = δ ∧ d ≠ 0 ∧
      branchEval hb ⟨x, branchRing_le hb.isBranch hxT⟩ = φ xα ∧
      (∀ i, toAmbient K Ω d * c i
        = ∑ j ∈ Finset.range δ, toAmbient K Ω (p i j) * x ^ j) ∧
      ∀ (i : ι) (w : K),
        branchEval hb ⟨toAmbient K Ω d * c i, branchRing_le hb.isBranch
            (Subring.mul_mem _ (toAmbient_mem_branchRing _) (hcT i))⟩ = φ w →
          ∑ j ∈ Finset.range δ, (p i j).eval α * xα ^ j = w := by
  classical
  obtain ⟨x, δ, d, p, hxT, hxint, hxδ, hd0, hdec⟩ :=
    exists_polynomial_decomposition_mem (T := branchRing K Φ') c hint
      (fun w => toAmbient_mem_branchRing w) hcT
  obtain ⟨xα, hxα⟩ := branchEval_mem_range hb (β := α) rfl hxT
  have hevpoly : ∀ w : K[X],
      branchEval hb ⟨toAmbient K Ω w, hb.isBranch.poly_mem w⟩ = φ (w.eval α) := by
    intro w
    rw [branchEval_poly, Polynomial.eval_map, Polynomial.eval₂_hom]
  refine ⟨x, hxT, δ, d, p, xα, hxint, hxδ, hd0, hxα.symm, hdec, fun i w hw => ?_⟩
  exact hspec_of_evalHomC (branchEval hb) (branchRing_le hb.isBranch hxT) hxα.symm
    hb.isBranch.poly_mem hevpoly (p := fun _ => p i)
    (y := fun _ : ι => toAmbient K Ω d * c i)
    (fun _ => branchRing_le hb.isBranch
      (Subring.mul_mem _ (toAmbient_mem_branchRing _) (hcT i)))
    (v := fun _ => w) (fun _ => hw) (fun _ => hdec i) i

end HspecOfBranch

end AF
