/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import CITED.AdamczewskiFaverjonReverseTransport
import CITED.AdamczewskiFaverjonRegular
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# The descent to a number field

plan-formalize-AF17's **WP17**, finding **F1** of gap (6) of Stage 2.

WP15 recorded the obstruction: [AF22] Lemma 2.11 as assembled in
`CITED/AdamczewskiFaverjonKeyLemma` needs **two incompatible instances on one field**.

* `AF.lemma_2_8`, the branch-existence axiom, needs `[IsAlgClosed K]` — its `Φ₀` is a matrix of
  values of algebraic functions at an algebraic point.
* `AF.key_lemma_of_auxiliary` needs `[NumberField K]` — Step (LB) is Liouville's inequality, and
  the height layer is `Mathlib.NumberTheory.Height`, whose `Height.AdmissibleAbsValues` asks for a
  **finite** multiset of archimedean absolute values.  `ℚ̄` has infinitely many; the class cannot
  hold for it, so this is not an accident of packaging.

No field is both.  [AF22] never meet this because their heights are absolute.  This file supplies
the missing move: the arithmetic runs over a number subfield `L`, the branch over the big field
`K`, and the two meet in `ℂ`.

## Why this is the right cut, and where the constants live

The temptation is to descend *late* — to give each auxiliary polynomial `P` its own number field.
That is fatal, and the reason is worth recording: `Height.logHeight₁` is the **relative** height,
`[F:ℚ]` times the absolute one, so a field that grows with `δ₁` makes Step (LB)'s constant

  `c₃ = m²b₁γ + b₂·h(α)`

grow with `δ₁` too, and `AF.key_lemma_contradiction` — whose whole content is that `c₂` and `c₃`
do *not* depend on `δ₁` — collapses.  The descent must therefore be made **once**, before `δ₁` is
introduced, and that is exactly possible: `k₀`, the branch, and hence `Φ₀` and
`M = A_{k₀}(α)Ψ(ξ)⁻¹` are all chosen before Step (AF) begins.

What is *not* needed is uniform control of the height of `P` itself: `AF.key_lemma_of_auxiliary`
absorbs `∑_ν h(P_ν)` into the `δ₁`-dependent constant `C` of `AF.key_lemma_contradiction`.  Only
`A` and `α` need heights that are fixed, and they are given data.

## What has to travel, and what does not

`AF.key_lemma` has twenty-odd hypotheses, and all but two of them are statements about complex
numbers — `fs`, `Ψ`, `S`, the radii — or about the data read through `φ`.  Those are indifferent
to which field `α`, `A`, `τ`, `f`, `M` are taken from, because `φ_L = φ_K ∘ (algebraMap L K)`
makes `φ_L(x)` and `φ_K(algebraMap x)` the same complex number.  **Exactly two** hypotheses couple
the field to the ambient field `Ω` of [AF22] §2.2, and this file descends both:

* `AF.isRelationMatrix_descend` — `Φalg` kills the relation ideal over `L` because it kills the
  one over `K` and the first maps into the second;
* `AF.isAnalyticBranch_descend` — the branch realization is a homomorphism out of a subring of
  `Ω`, and `Ω` is a `K(z)`-algebra, hence an `L(z)`-algebra; the polynomial clause `poly_mem`
  restricts because `L[z] → Ω` factors through `K[z] → Ω`.

The conclusion of `AF.key_lemma` — an identity of complex functions near `ξ` — is field-free, so
it comes back over `K` for free, which is what lets WP16's reverse transport consume it.

## The one thing the plan's sketch missed

«`L := K(entries of M)`» is not enough: `AF.key_lemma` also takes the Mahler solutions
`f : ι → PowerSeries L`, and a power series has **infinitely many** coefficients.  They are not
free: comparing coefficients in `f = A(z)·f(z^q)` gives

  `[z^n] f_i = ∑_j ∑_{a+qb=n} A_{ij}[a]·[z^b] f_j`,   and `b ≤ n/q < n` for `n ≥ 1`,

so `AF.coeff_mem_of_isFormalMahlerSolution`: **every** coefficient lies in the subring generated by
the coefficients of `A` and the constant terms `f_i(0)`.  That is a finite set, so the number field
exists after all — but it has to contain `f(0)`, which the sketch does not mention.

## Contents

* `AF.germMapRingHom`, `AF.ratFuncMap` — the two functorialities Mathlib does not package;
* `AF.germEval_map`, `AF.relationIdeal_map_mem` — the relation ideal over `L` maps into the one
  over `K`;
* `AF.isRelationMatrix_descend`, `AF.isBranchRealization_descend`, `AF.isAnalyticBranch_descend`;
* **`AF.key_lemma_descent`** — [AF22] Lemma 2.11 with the arithmetic over a number field and the
  branch over an algebraically closed field;
* `AF.coeff_mem_of_isFormalMahlerSolution` — the Mahler solutions are defined over a finitely
  generated field;
* `AF.numberField_adjoin_finset` — and a finite set of algebraic numbers generates a number field.

## References

* [AF22] B. Adamczewski, C. Faverjon. *A new proof of Nishioka's theorem in Mahler's method.*
  arXiv:2210.14528 (2022), §2.3 (Lemma 2.11), Appendix A.2.
* [AF17f] `plans/plan-formalize-AF17.html`: WP17, finding F1 of gap (6), milestone M4.
-/

open Filter MvPolynomial Metric Topology

open scoped Polynomial nonZeroDivisors

namespace AF

/-! ## Germs, functorially -/

section GermMap

variable {α : Type*} {R S : Type*} [Semiring R] [Semiring S]

/-- **A ring homomorphism acts on germs.**  Mathlib has `Filter.Germ.map` for bare functions and
`Filter.Germ.coeRingHom` for the coercion, but not the two combined; the relation ideal is a
kernel in the germ ring, so transporting it needs this. -/
@[category API, AMS 13, ref "AF22", group "af_mahler_alternative"]
def germMapRingHom (l : Filter α) (f : R →+* S) : Germ l R →+* Germ l S where
  toFun := Germ.map f
  map_one' := by
    show Germ.map f ((1 : α → R) : Germ l R) = 1
    rw [Germ.map_coe]
    exact congrArg _ (funext fun _ => map_one f)
  map_mul' x y := by
    induction x using Germ.inductionOn with
    | _ g =>
      induction y using Germ.inductionOn with
      | _ h =>
        show Germ.map f ((fun n => g n * h n : α → R) : Germ l R) = _
        rw [Germ.map_coe, Germ.map_coe, Germ.map_coe, ← Germ.coe_mul]
        exact congrArg _ (funext fun n => map_mul f (g n) (h n))
  map_zero' := by
    show Germ.map f ((0 : α → R) : Germ l R) = 0
    rw [Germ.map_coe]
    exact congrArg _ (funext fun _ => map_zero f)
  map_add' x y := by
    induction x using Germ.inductionOn with
    | _ g =>
      induction y using Germ.inductionOn with
      | _ h =>
        show Germ.map f ((fun n => g n + h n : α → R) : Germ l R) = _
        rw [Germ.map_coe, Germ.map_coe, Germ.map_coe, ← Germ.coe_add]
        exact congrArg _ (funext fun n => map_add f (g n) (h n))

@[category API, AMS 13, ref "AF22", group "af_mahler_alternative"]
theorem germMapRingHom_coe (l : Filter α) (f : R →+* S) (g : α → R) :
    germMapRingHom l f (g : Germ l R) = ((fun n => f (g n) : α → S) : Germ l S) := rfl

end GermMap

/-! ## The field of rational functions, functorially -/

section RatFuncMap

variable (L K : Type*) [Field L] [Field K] [Algebra L K]

omit [Algebra L K] in
@[category API, AMS 12 13, ref "AF22", group "af_mahler_alternative"]
theorem polyMap_le_comap_nonZeroDivisors {e : L →+* K} (he : Function.Injective e) :
    (L[X])⁰ ≤ (K[X])⁰.comap (Polynomial.mapRingHom e) := by
  intro p hp
  rw [Submonoid.mem_comap, mem_nonZeroDivisors_iff_ne_zero]
  rw [mem_nonZeroDivisors_iff_ne_zero] at hp
  simpa using (Polynomial.map_ne_zero_iff he).2 hp

/-- **`L(z) → K(z)`**, induced by `L → K`.  Mathlib's `RatFunc.mapRingHom` with its
non-zero-divisor side condition discharged. -/
@[category API, AMS 12 13, ref "AF22", group "af_mahler_alternative"]
noncomputable def ratFuncMap : RatFunc L →+* RatFunc K :=
  RatFunc.mapRingHom (Polynomial.mapRingHom (algebraMap L K))
    (polyMap_le_comap_nonZeroDivisors L K (algebraMap L K).injective)

variable {L K}

@[category API, AMS 12 13, ref "AF22", group "af_mahler_alternative"]
theorem ratFuncMap_algebraMap (p : L[X]) :
    ratFuncMap L K (algebraMap L[X] (RatFunc L) p)
      = algebraMap K[X] (RatFunc K) (p.map (algebraMap L K)) := by
  have h := RatFunc.map_apply_div (Polynomial.mapRingHom (algebraMap L K))
    (polyMap_le_comap_nonZeroDivisors L K (algebraMap L K).injective) p 1
  simpa [ratFuncMap, RatFunc.coe_mapRingHom_eq_coe_map] using h

end RatFuncMap

/-! ## The relation ideal, base changed -/

section RelationIdealMap

variable {L K : Type*} [Field L] [Field K] [Algebra L K]

/-- Evaluation of polynomials along points commutes with a change of base field. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem germMap_germPolyEval (pt : ℕ → L) (p : L[X]) :
    germMapRingHom atTop (algebraMap L K) (germPolyEval pt p)
      = germPolyEval (fun n => algebraMap L K (pt n)) (p.map (algebraMap L K)) := by
  rw [germPolyEval_apply, germMapRingHom_coe, germPolyEval_apply]
  exact congrArg _ (funext fun n => by
    rw [Polynomial.eval_map, Polynomial.eval₂_hom])

/-- …and so does evaluation of rational functions, both being ring homomorphisms out of the
localization of `L[z]` that agree on `L[z]`. -/
@[category API, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem germMap_comp_germRatFuncEval {pt : ℕ → L} (hpt : Function.Injective pt)
    (hptK : Function.Injective fun n => algebraMap L K (pt n)) :
    (germMapRingHom atTop (algebraMap L K)).comp (germRatFuncEval hpt)
      = (germRatFuncEval hptK).comp (ratFuncMap L K) := by
  refine IsLocalization.ringHom_ext (L[X])⁰ (RingHom.ext fun p => ?_)
  rw [RingHom.comp_apply, RingHom.comp_apply, RingHom.comp_apply, RingHom.comp_apply,
    germRatFuncEval_algebraMap, ratFuncMap_algebraMap, germRatFuncEval_algebraMap,
    germMap_germPolyEval]

/-- **The relation ideal is functorial.**  A polynomial over `L(z)` that vanishes at the points
still vanishes at their images in `K`. -/
@[category research solved, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem germMap_germEval {σ : Type*} {pt : ℕ → L} (hpt : Function.Injective pt)
    (hptK : Function.Injective fun n => algebraMap L K (pt n)) (Yval : ℕ → σ → L)
    (P : MvPolynomial σ (RatFunc L)) :
    germMapRingHom atTop (algebraMap L K) (germEval hpt Yval P)
      = germEval hptK (fun n s => algebraMap L K (Yval n s))
        (MvPolynomial.map (ratFuncMap L K) P) := by
  have hhom : (germMapRingHom atTop (algebraMap L K)).comp (germEval hpt Yval)
      = (germEval hptK fun n s => algebraMap L K (Yval n s)).comp
        (MvPolynomial.map (ratFuncMap L K)) := by
    refine MvPolynomial.ringHom_ext (fun a => ?_) (fun s => ?_)
    · rw [RingHom.comp_apply, RingHom.comp_apply, MvPolynomial.map_C, germEval, germEval,
        eval₂Hom_C, eval₂Hom_C]
      exact DFunLike.congr_fun (germMap_comp_germRatFuncEval hpt hptK) a
    · rw [RingHom.comp_apply, RingHom.comp_apply, MvPolynomial.map_X, germEval, germEval,
        eval₂Hom_X', eval₂Hom_X', germMapRingHom_coe]
  exact DFunLike.congr_fun hhom P

@[category research solved, AMS 11 13, ref "AF22", group "af_mahler_alternative"]
theorem relationIdeal_map_mem {σ : Type*} {pt : ℕ → L} (hpt : Function.Injective pt)
    (hptK : Function.Injective fun n => algebraMap L K (pt n)) (Yval : ℕ → σ → L)
    {P : MvPolynomial σ (RatFunc L)} (hP : P ∈ relationIdeal hpt Yval) :
    MvPolynomial.map (ratFuncMap L K) P ∈
      relationIdeal hptK fun n s => algebraMap L K (Yval n s) := by
  rw [relationIdeal, RingHom.mem_ker] at hP ⊢
  rw [← germMap_germEval hpt hptK Yval P, hP, map_zero]

end RelationIdealMap

/-! ## The ambient field over the subfield -/

section AmbientDescend

variable {L K Ω : Type*} [Field L] [Field K] [Algebra L K] [Field Ω]
variable [Algebra (RatFunc K) Ω] [Algebra (RatFunc L) Ω]

/-- **The compatibility of the two `RatFunc`-algebra structures on the ambient field.**  `Ω` is a
`K(z)`-algebra by [AF22] §2.2; it becomes an `L(z)`-algebra through `AF.ratFuncMap`, and this is
the one equation everything in this section needs.  It is not an instance because it would make
instance search loop; the assembly supplies it by `letI`. -/
@[category API, AMS 12 13, ref "AF22", group "af_mahler_alternative"]
def IsRatFuncTower (L K Ω : Type*) [Field L] [Field K] [Algebra L K] [Field Ω]
    [Algebra (RatFunc K) Ω] [Algebra (RatFunc L) Ω] : Prop :=
  (algebraMap (RatFunc L) Ω) = (algebraMap (RatFunc K) Ω).comp (ratFuncMap L K)

/-- Reading a polynomial over the subfield in the ambient field is reading its image. -/
@[category API, AMS 12 13, ref "AF22", group "af_mahler_alternative"]
theorem toAmbient_descend (htow : IsRatFuncTower L K Ω) (p : L[X]) :
    toAmbient L Ω p = toAmbient K Ω (p.map (algebraMap L K)) := by
  rw [toAmbient_apply, toAmbient_apply, htow, RingHom.comp_apply, ratFuncMap_algebraMap]

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **[AF22] Definition 2.6 descends.**  A relation matrix over the big field is one over the
subfield: every relation over `L(z)` becomes a relation over `K(z)`
(`AF.relationIdeal_map_mem`), and the two `aeval`s agree by `AF.IsRatFuncTower`. -/
@[category research solved, AMS 11 12 13 15, ref "AF22", group "af_mahler_alternative"]
theorem isRelationMatrix_descend (htow : IsRatFuncTower L K Ω) {pt : ℕ → L}
    (hpt : Function.Injective pt) (hptK : Function.Injective fun n => algebraMap L K (pt n))
    (Yval : ℕ → ι × ι → L) {Φalg : Matrix ι ι Ω}
    (h : IsRelationMatrix (relationIdeal hptK fun n s => algebraMap L K (Yval n s)) Φalg) :
    IsRelationMatrix (relationIdeal hpt Yval) Φalg := by
  refine ⟨fun P hP => ?_, h.2⟩
  have h1 := h.1 _ (relationIdeal_map_mem hpt hptK Yval hP)
  rw [← h1, MvPolynomial.aeval_def, MvPolynomial.aeval_def, MvPolynomial.eval₂_map, htow]

variable {φ : K →+* ℂ} {Φalg : Matrix ι ι Ω} {R : Subring Ω} {Ψ : ℂ → Matrix ι ι ℂ}

omit [Fintype ι] [DecidableEq ι] in
/-- **The branch realization restricts to the subfield.**  `AF.IsBranchRealization` says two
things: that `L[z]` lands in the realization subring and is realized by polynomial functions, and
that the relation matrix is realized by `Ψ`.  The second is about `Ω` alone and is untouched; the
first restricts because `L[z] → Ω` factors through `K[z] → Ω`. -/
@[category research solved, AMS 11 12 13 30, ref "AF22", group "af_mahler_alternative"]
theorem isBranchRealization_descend (htow : IsRatFuncTower L K Ω) {l : Filter ℂ}
    {real : R →+* Germ l ℂ} (h : IsBranchRealization φ l Φalg R real Ψ) :
    IsBranchRealization (φ.comp (algebraMap L K)) l Φalg R real Ψ := by
  have hmem : ∀ w : L[X], toAmbient L Ω w ∈ R := fun w => by
    rw [toAmbient_descend htow]; exact h.poly_mem _
  refine ⟨hmem, fun w => ?_, h.mat_mem, h.real_mat⟩
  have hsub : (⟨toAmbient L Ω w, hmem w⟩ : R)
      = ⟨toAmbient K Ω (w.map (algebraMap L K)), h.poly_mem _⟩ :=
    Subtype.ext (toAmbient_descend htow w)
  rw [hsub, h.real_poly, Polynomial.map_map]

/-- **[AF22] Lemma 2.8(b,c) restricts to the subfield** — provided the value `Φ₀` does.  That
proviso is the whole content of the descent: the branch is produced over an algebraically closed
field, and `L` has to be chosen *after* it, large enough to contain the finitely many entries of
`Φ₀`.  Everything else — the domain, the analyticity, the realization — is indifferent. -/
@[category research solved, AMS 11 12 15 30, ref "AF22", group "af_mahler_alternative"]
theorem isAnalyticBranch_descend (htow : IsRatFuncTower L K Ω) {ξ : ℂ} {U : Set ℂ}
    {real : R →+* Germ (𝓟 U) ℂ} {Φ₀ : Matrix ι ι L}
    (h : IsAnalyticBranch φ Φalg ξ U R real Ψ (Φ₀.map (algebraMap L K))) :
    IsAnalyticBranch (φ.comp (algebraMap L K)) Φalg ξ U R real Ψ Φ₀ := by
  refine ⟨h.isOpen_dom, h.mem_dom, h.analytic, isBranchRealization_descend htow h.isBranch, ?_, ?_⟩
  · rw [← h.map_value, Matrix.map_map, RingHom.coe_comp]
  · intro hd
    exact h.det_ne_zero (by rw [det_map_ringHom, hd, map_zero])

end AmbientDescend

/-! ## [AF22] Lemma 2.11, with the arithmetic over a number field -/

section KeyLemmaDescent

variable {L K Ω : Type*} [Field L] [NumberField L] [Field K] [Algebra L K] [Field Ω]
variable [Algebra (RatFunc K) Ω] [Algebra (RatFunc L) Ω]
variable {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]

omit [NumberField L] [Algebra L K] [Nonempty ι] in
/-- Iterating the matrix and evaluating commutes with a change of base field — the identity that
lets the assembly write the relation ideal over `K` in the form `AF.key_lemma_descent` asks for. -/
@[category API, AMS 11 15, ref "AF22", group "af_mahler_alternative"]
theorem algebraMap_iterMatrix_eval (e : L →+* K) (q n : ℕ) (A : Matrix ι ι L[X]) (α : L)
    (i j : ι) :
    e ((iterMatrix q A n i j).eval α) = (iterMatrix q (mapMat e A) n i j).eval (e α) := by
  have h : evalMat (e α) (iterMatrix q (mapMat e A) n) = (evalMat α (iterMatrix q A n)).map e := by
    rw [← mapMat_iterMatrix, evalMat_mapMat]
  have := congrFun (congrFun (congrArg (fun M : Matrix ι ι K => (M : ι → ι → K)) h) i) j
  simpa [evalMat_apply, Matrix.map_apply] using this.symm

/-- **[AF22] Lemma 2.11, descended.**  The arithmetic — Steps (AF), (NV) and Liouville's
inequality — runs over the number field `L`; the branch and the ambient field of §2.2 live over
the big field `K`, which is where `AF.lemma_2_8` puts them.  The two meet only in `ℂ`, through
`φ_L = φ ∘ (algebraMap L K)`, and the conclusion is an identity of complex functions, so it comes
back over `K` for free: this is what WP16's `AF.relation_of_eventually_formVal_eq_zero` consumes.

Exactly two hypotheses had to cross the gap, `hrel` and `hb`, and both are given here in their
`K`-form; the remaining twenty are literally `AF.key_lemma`'s, read through `φ_L`.

The proviso that carries the whole descent is in `hb`: the value `Φ₀` of Lemma 2.8(c) must lie in
`L`.  It is a matrix of algebraic numbers, so `L` can be chosen to contain it
(`AF.numberField_adjoin_finset`) — but only *after* the branch is produced, which is why the
descent is made once, before `δ₁` is introduced, and not inside Step (AF). -/
@[category research solved, AMS 11 12 13 15 30 39, ref "AF22", group "af_mahler_alternative"]
theorem key_lemma_descent (htow : IsRatFuncTower L K Ω) {q k₀ : ℕ} (hq : 2 ≤ q)
    {A : Matrix ι ι L[X]} {α : L} {φ : K →+* ℂ} {φL : L →+* ℂ}
    (hφ : φL = φ.comp (algebraMap L K)) (τ : ι → L) {f : ι → PowerSeries L} {fs : ι → ℂ → ℂ}
    {Φalg : Matrix ι ι Ω} {R : Subring Ω} {U : Set ℂ} {real : R →+* Germ (𝓟 U) ℂ}
    {Ψ : ℂ → Matrix ι ι ℂ} {Φ₀ M : Matrix ι ι L} {ξ : ℂ} {S : Set ℂ} {ρ₁ r s t Cb : ℝ}
    (hpt : Function.Injective fun k : ℕ => α ^ q ^ k)
    (hptK : Function.Injective fun k : ℕ => algebraMap L K (α ^ q ^ k))
    (hrel : IsRelationMatrix (relationIdeal hptK fun (n : ℕ) (w : ι × ι) =>
      algebraMap L K ((iterMatrix q A n w.1 w.2).eval α)) Φalg)
    (hb : IsAnalyticBranch φ Φalg ξ U R real Ψ (Φ₀.map (algebraMap L K)))
    (hball : closedBall ξ ρ₁ ⊆ U) (hρ₁ : 0 < ρ₁) (hsph₁ : ∀ z ∈ closedBall ξ ρ₁, ‖z‖ ≤ t)
    (hreal : ∀ j, IsSumOn r ((f j).map φL) (fs j)) (hr0 : 0 < r)
    (hS : ∀ z ∈ S, z ^ q ∈ S) (hmah : IsMahlerSolution q (mapMat φL A) fs S) (hαS : φL α ∈ S)
    (hL : formVal (fun i => φL (τ i)) fs 1 (φL α) = 0) (hSt : ∀ z : ℂ, ‖z‖ ≤ t → z ∈ S)
    (hξ : ξ = φL α ^ q ^ k₀)
    (ha : M.map φL * Ψ ξ = evalMat (φL α) (iterMatrix q (mapMat φL A) k₀))
    (hs0 : 0 < s) (hsr : s < r) (ht0 : 0 < t) (ht1 : t < 1) (htr : t < r) (hC1 : 1 ≤ Cb)
    (hA : ∀ z : ℂ, ‖z‖ ≤ t → ∀ i j, ‖(mapMat φL A i j).eval z‖ ≤ Cb)
    (h1C : 1 ≤ (Fintype.card ι : ℝ) * Cb) :
    ∀ᶠ z in 𝓝 ξ, formVal (fun i => φL (τ i)) fs (M.map φL * Ψ z) z = 0 := by
  subst hφ
  exact key_lemma hq τ hpt (isRelationMatrix_descend htow hpt hptK _ hrel)
    (isAnalyticBranch_descend htow hb) hball hρ₁ hsph₁ hreal hr0 hS hmah hαS hL hSt hξ ha
    hs0 hsr ht0 ht1 htr hC1 hA h1C

end KeyLemmaDescent

/-! ## The Mahler solutions are defined over a finitely generated field -/

section MahlerCoeff

variable {L : Type*} [Field L] {ι : Type*} [Fintype ι]

/-- **Every coefficient of a formal Mahler solution lies in the ring generated by the system and
the constant terms.**

This is what the plan's sketch «`L := K(entries of M)`» left out.  `AF.key_lemma` takes the
solutions as *power series over the field*, and a power series has infinitely many coefficients,
so a naive descent would need infinitely many generators.  It does not: comparing coefficients in
`f = A(z)·f(z^q)` gives

  `[z^n] f_i = ∑_j ∑_{a+qb=n} A_{ij}[a]·[z^b] f_j`,

and `q ≥ 2` forces `b ≤ n/q < n` for `n ≥ 1`, so a strong induction reduces every coefficient to
the coefficients of `A` and the constant terms `f_i(0)` — finitely many generators after all.

The hypothesis `2 ≤ q` is not cosmetic: at `q = 1` the recursion is `f = A(z)f(z)`, `b = n` is
allowed, and there is nothing to induct on. -/
@[category research solved, AMS 11 13 39, ref "AF22", group "af_mahler_alternative"]
theorem coeff_mem_of_isFormalMahlerSolution {q : ℕ} (hq : 2 ≤ q) {A : Matrix ι ι L[X]}
    {F : ι → PowerSeries L} (hF : IsFormalMahlerSolution q A F) {T : Subring L}
    (hA : ∀ i j n, (A i j).coeff n ∈ T) (h0 : ∀ i, PowerSeries.coeff 0 (F i) ∈ T) (n : ℕ)
    (i : ι) : PowerSeries.coeff n (F i) ∈ T := by
  induction n using Nat.strong_induction_on generalizing i with
  | _ n ih =>
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · exact h0 i
    rw [hF i, map_sum]
    refine Subring.sum_mem _ fun j _ => ?_
    rw [PowerSeries.coeff_mul]
    refine Subring.sum_mem _ fun p hp => ?_
    refine Subring.mul_mem _ ?_ ?_
    · rw [Polynomial.coeff_coe]
      exact hA i j p.1
    · rw [substPowSeries, PowerSeries.coeff_mk]
      split_ifs with hdvd
      · refine ih _ ?_ j
        have hple : p.2 ≤ n := by
          have := Finset.HasAntidiagonal.mem_antidiagonal.mp hp
          omega
        exact lt_of_le_of_lt (Nat.div_le_div_right hple) (Nat.div_lt_self hn (by omega))
      · exact T.zero_mem

end MahlerCoeff

/-! ## Descending the data -/

section DescendData

variable {R S : Type*} [CommRing R] [CommRing S] (e : R →+* S)

/-- A matrix all of whose entries are in the image comes from a matrix over the source. -/
@[category API, AMS 13 15, ref "AF22", group "af_mahler_alternative"]
theorem exists_matrix_map_eq {ι : Type*} {N : Matrix ι ι S} (h : ∀ i j, N i j ∈ Set.range e) :
    ∃ N' : Matrix ι ι R, N'.map e = N := by
  classical
  exact ⟨Matrix.of fun i j => (h i j).choose, by ext i j; exact (h i j).choose_spec⟩

/-- The same for a power series — this is the clause `AF.coeff_mem_of_isFormalMahlerSolution` is
for. -/
@[category API, AMS 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_powerSeries_map_eq {g : PowerSeries S}
    (h : ∀ n, PowerSeries.coeff n g ∈ Set.range e) : ∃ g' : PowerSeries R, g'.map e = g := by
  classical
  refine ⟨PowerSeries.mk fun n => (h n).choose, ?_⟩
  ext n
  rw [PowerSeries.coeff_map, PowerSeries.coeff_mk]
  exact (h n).choose_spec

/-- …and for a polynomial, which is Mathlib's `Polynomial.lifts`. -/
@[category API, AMS 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_polynomial_map_eq {p : S[X]} (h : ∀ n, p.coeff n ∈ Set.range e) :
    ∃ p' : R[X], p'.map e = p :=
  (Polynomial.mem_lifts _).1 ((Polynomial.lifts_iff_coeff_lifts p).2 h)

end DescendData

section DescendMahler

variable {L K : Type*} [Field L] [Field K] {ι : Type*} [Fintype ι]

/-- **The Mahler solutions descend to the subfield generated by the system and the constant
terms.**  `AF.coeff_mem_of_isFormalMahlerSolution` and `AF.exists_powerSeries_map_eq` together:
this is what makes the descent of `AF.key_lemma`'s `f : ι → PowerSeries L` possible at all, and
the only clause of it that is not immediate. -/
@[category research solved, AMS 11 13 39, ref "AF22", group "af_mahler_alternative"]
theorem exists_map_eq_of_isFormalMahlerSolution {q : ℕ} (hq : 2 ≤ q) (e : L →+* K)
    {A : Matrix ι ι K[X]} {F : ι → PowerSeries K} (hF : IsFormalMahlerSolution q A F)
    (hA : ∀ i j n, (A i j).coeff n ∈ Set.range e)
    (h0 : ∀ i, PowerSeries.coeff 0 (F i) ∈ Set.range e) (i : ι) :
    ∃ g : PowerSeries L, g.map e = F i :=
  exists_powerSeries_map_eq e fun n =>
    coeff_mem_of_isFormalMahlerSolution hq hF (T := e.range)
      (fun i j n => by simpa [RingHom.mem_range] using hA i j n)
      (fun i => by simpa [RingHom.mem_range] using h0 i) n i

end DescendMahler

/-! ## A finite set of algebraic numbers generates a number field -/

section NumberFieldAdjoin

variable {K : Type*} [Field K] [CharZero K]

/-- **The number field of the descent.**  `L := ℚ(S)` for a finite set `S` of algebraic numbers is
finite over `ℚ`, hence a number field, and the height layer of Step (LB) is available on it.

In the assembly `S` is `{α} ∪ (coefficients of A) ∪ (τ i) ∪ (entries of Φ₀) ∪ (f_i(0))` — finite
because of `AF.coeff_mem_of_isFormalMahlerSolution`, and chosen after the branch because of
`Φ₀`. -/
@[category research solved, AMS 11 12, ref "AF22", group "af_mahler_alternative"]
theorem numberField_adjoin_finset (S : Finset K) (hS : ∀ x ∈ S, IsIntegral ℚ x) :
    NumberField ↥(IntermediateField.adjoin ℚ (S : Set K)) where
  to_charZero := inferInstance
  to_finiteDimensional := by
    haveI : Finite (S : Set K) := S.finite_toSet.to_subtype
    exact IntermediateField.finiteDimensional_adjoin hS

end NumberFieldAdjoin

end AF
