/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.RingTheory.LaurentSeries
import Mathlib.RingTheory.Localization.Integer
import ForMathlib.FieldTheory.RegularExtension
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# [AF22] §2.4: the primitive element, and the splitting of the lifted relation

The second half of plan-formalize-AF17's **WP8**.  At the end of [AF22]'s proof of Theorem 2.1 the
lifted linear relation `Q(z, f(z)) = 0` has its coefficients not in `ℚ̄[z]` but in
`ℚ̄[z, ϕ(z^{q^{k₀}})]`, where `ϕ` is a primitive element of the finite extension of `ℚ̄(z)`
generated by the coordinates of the relation matrix `φ(z)`.  Three steps turn that into the
polynomial coefficients Theorem 2.1 advertises — the property gate G1 of the plan pinned as the
corpus's actual requirement:

1. **the primitive element**: the coordinates of `φ(z)` are algebraic over `ℚ̄(z)`, so they
   generate a finite extension, which in characteristic zero is separable and therefore simple;
   each coordinate is then a `ℚ̄(z)`-polynomial in `ϕ` of degree `< [ℚ̄(z)(ϕ) : ℚ̄(z)]`
   (`AF.exists_primitive_decomposition`);
2. **the common denominator** `d(z) ∈ ℚ̄[z]` of those finitely many rational coefficients
   (`AF.exists_commonDenominator`), after which the coefficients are genuinely *polynomial* in
   `z` and in `ϕ`;
3. **the splitting**: from `Q(z, f(z)) = 0` with `Q = ∑ⱼ Qⱼ ϕʲ` conclude `Qⱼ(z, f(z)) = 0` for
   every `j` (`AF.linearForm_split`).

## Where the cited input enters, and where it does not

Step 3 is the one that needs [AF22]'s appeal to Lang: `ℚ̄(z)(f(z))` is a **regular** extension of
`ℚ̄(z)`, hence linearly disjoint from `A`, hence the powers of `ϕ` stay independent over
`ℚ̄(z)(f(z))`.  Gate **G5** of the plan split that appeal into three layers and cut at the middle
one.  Concretely:

* the *top* layer — regular ⇒ the powers stay independent ⇒ the relation splits — is **proved**,
  in `ForMathlib/FieldTheory/RegularExtension.lean`, and is what this file consumes;
* the *middle* layer — the regularity of `ℚ̄(z)(f)/ℚ̄(z)` itself, [AF17] Lemme 2.2 — is the
  Stage-2 cited axiom, and is **not** assumed here: every statement below carries it as an
  explicit hypothesis `algebraicClosure (RatFunc K) E = ⊥`.  Writing that hypothesis down as a
  cited axiom is WP8-bis; `AF.IsRegularSolField` is the predicate it will assert.

So this file is `std3` with **no** cited axiom, and the axiom it is waiting for is a hypothesis in
its statements — the arrangement that keeps the corpus's footprint honest.

## A note on the ambient field

[AF22] have one ambient field: the Puiseux series, which contain both `A` and the functions
`fᵢ`.  Here the two are separated — `A` is any algebraically closed extension of `K(z)` (gate G3),
the `fᵢ` live in `LaurentSeries K` — so the statements below fix a single field `Ω` containing
both, and `AlgebraicClosure (LaurentSeries K)` is the intended instance.  The regularity
predicate is stated for the subfield generated by the `fᵢ` *inside that same `Ω`*, which keeps it
purely algebraic (plan risk R13) and avoids transporting it along an embedding; `AF.solField` and
`AF.IsRegularSolField` are therefore parametrized by `Ω`.

## Contents

* **`AF.exists_primitive_decomposition`** — a finite family of elements algebraic over `F`
  (char 0) is a family of `F`-polynomials in one primitive element;
* **`AF.exists_commonDenominator`** — a finite family of rational functions has a common
  denominator;
* **`AF.exists_polynomial_decomposition`** — the two combined: `d(z)·φᵢⱼ(z)` is a polynomial in
  `z` and `ϕ`, which is [AF22]'s (2.36) with the denominators cleared;
* **`AF.linearForm_split`** — [AF22] §2.4's last step, the splitting of the lifted linear form;
* `AF.solField`, `AF.IsRegularSolField` — the solution field `K(z)(f)` and the regularity
  predicate that WP8-bis will assert of it, plus `AF.linearForm_split_solField`, the form in
  which §2.4 consumes it.

## References

* [AF22] B. Adamczewski, C. Faverjon. *A new proof of Nishioka's theorem in Mahler's method.*
  arXiv:2210.14528 (2022), §2.4.
* [AF17] B. Adamczewski, C. Faverjon. *Méthode de Mahler: relations linéaires, transcendance et
  applications aux nombres automatiques.*  Proc. LMS 115 (2017), 55–90; arXiv:1508.07158, Lemme
  2.2 (the regularity of the solution field).
* [Lan02] S. Lang, *Algebra*, 3rd ed., GTM 211, Chap. VIII (regular extensions and linear
  disjointness).
* [AF17f] `plans/plan-formalize-AF17.html`: WP8, WP8-bis, gate G5, milestone M4.
-/

open scoped RatFunc Polynomial nonZeroDivisors
open IntermediateField

namespace AF

/-! ## Step 1: one primitive element for a finite family -/

section Primitive

variable {F Ω : Type*} [Field F] [CharZero F] [Field Ω] [Algebra F Ω]

/-- **[AF22] (2.36), the field-theoretic half.**  *«The coordinates of `φ(z)` being algebraic over
`ℚ̄(z)`, they generate a finite extension of `ℚ̄(z)`.  Choosing a primitive element `ϕ(z)` we
obtain a decomposition `φ(z) = ∑ⱼ φⱼ(z)ϕ(z)ʲ`, where the matrices `φⱼ(z)` have coefficients in
`ℚ̄(z)`.»*

In characteristic zero a finite extension is separable, hence simple, so no hypothesis beyond
algebraicity is needed. -/
@[category research solved, AMS 11 12, ref "AF22" "AF17", group "af_mahler_alternative"]
theorem exists_primitive_decomposition {ι : Type*} [Finite ι] (x : ι → Ω)
    (hint : ∀ s, IsIntegral F (x s)) :
    ∃ (ϕ : Ω) (δ : ℕ) (c : ι → ℕ → F), IsIntegral F ϕ ∧ (minpoly F ϕ).natDegree = δ ∧
      ∀ s, x s = ∑ j ∈ Finset.range δ, algebraMap F Ω (c s j) * ϕ ^ j := by
  classical
  have : Finite (Set.range x) := (Set.finite_range x).to_subtype
  set L : IntermediateField F Ω := IntermediateField.adjoin F (Set.range x) with hL
  have : FiniteDimensional F L :=
    IntermediateField.finiteDimensional_adjoin (fun y hy => by
      obtain ⟨s, rfl⟩ := hy
      exact hint s)
  set pb := Field.powerBasisOfFiniteOfSeparable F L with hpb
  have hgen : (algebraMap L Ω) pb.gen = (pb.gen : Ω) := rfl
  have hmin : minpoly F ((pb.gen : Ω)) = minpoly F pb.gen := by
    rw [← hgen]
    exact minpoly.algebraMap_eq (algebraMap L Ω).injective pb.gen
  have hdeg : (minpoly F ((pb.gen : Ω))).natDegree = pb.dim := by
    rw [hmin]
    exact pb.natDegree_minpoly
  have hmemL : ∀ s, x s ∈ L := fun s =>
    IntermediateField.subset_adjoin F (Set.range x) ⟨s, rfl⟩
  refine ⟨(pb.gen : Ω), pb.dim, fun s j => if hj : j < pb.dim then
      pb.basis.repr ⟨x s, hmemL s⟩ ⟨j, hj⟩ else 0, ?_, hdeg, fun s => ?_⟩
  · exact (IsIntegral.of_finite F pb.gen).map L.val
  · have hrepr : (⟨x s, hmemL s⟩ : L) = ∑ j : Fin pb.dim,
        pb.basis.repr ⟨x s, hmemL s⟩ j • pb.gen ^ (j : ℕ) := by
      conv_lhs => rw [← pb.basis.sum_repr ⟨x s, hmemL s⟩]
      exact Finset.sum_congr rfl fun j _ => by rw [pb.basis_eq_pow]
    have hΩ : x s = ∑ j : Fin pb.dim,
        algebraMap F Ω (pb.basis.repr ⟨x s, hmemL s⟩ j) * (pb.gen : Ω) ^ (j : ℕ) := by
      have h := congrArg L.val hrepr
      rw [map_sum] at h
      simpa [Algebra.smul_def] using h
    rw [hΩ, ← Fin.sum_univ_eq_sum_range]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp

end Primitive

/-! ## Step 2: a common denominator -/

section Denominator

variable {K : Type*} [Field K]

/-- **A common denominator** for a finite family of rational functions — [AF22]'s «let `d(z) ∈
ℚ̄[z]` denote a common denominator of the coordinates of the matrices `φⱼ(z)`».  This is what
makes the coefficients of the lifted relation *polynomial* rather than merely rational. -/
@[category research solved, AMS 11 12 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_commonDenominator {ι : Type*} [Fintype ι] (c : ι → RatFunc K) :
    ∃ d : K[X], d ≠ 0 ∧ ∃ p : ι → K[X], ∀ s,
      algebraMap K[X] (RatFunc K) d * c s = algebraMap K[X] (RatFunc K) (p s) := by
  classical
  obtain ⟨b, hb⟩ := IsLocalization.exist_integer_multiples (K[X])⁰ (Finset.univ : Finset ι) c
  have hb' : ∀ s : ι, ∃ a : K[X], algebraMap K[X] (RatFunc K) a = (b : K[X]) • c s := fun s =>
    RingHom.mem_rangeS.mp (hb s (Finset.mem_univ s))
  choose p hp using hb'
  refine ⟨(b : K[X]), nonZeroDivisors.ne_zero b.2, p, fun s => ?_⟩
  rw [hp s, Algebra.smul_def]

end Denominator

/-! ## Steps 1 + 2 -/

section Combined

variable {K : Type*} [Field K] [CharZero K] {Ω : Type*} [Field Ω] [Algebra (RatFunc K) Ω]

/-- **[AF22] (2.36) with the denominators cleared**: a finite family of elements algebraic over
`K(z)` becomes, after multiplication by one polynomial `d(z) ≠ 0`, a family of polynomials in `z`
and in a single primitive element `ϕ`. -/
@[category research solved, AMS 11 12 13, ref "AF22", group "af_mahler_alternative"]
theorem exists_polynomial_decomposition {ι : Type*} [Fintype ι] (x : ι → Ω)
    (hint : ∀ s, IsIntegral (RatFunc K) (x s)) :
    ∃ (ϕ : Ω) (δ : ℕ) (d : K[X]) (p : ι → ℕ → K[X]),
      IsIntegral (RatFunc K) ϕ ∧ (minpoly (RatFunc K) ϕ).natDegree = δ ∧ d ≠ 0 ∧
      ∀ s, algebraMap (RatFunc K) Ω (algebraMap K[X] (RatFunc K) d) * x s =
        ∑ j ∈ Finset.range δ,
          algebraMap (RatFunc K) Ω (algebraMap K[X] (RatFunc K) (p s j)) * ϕ ^ j := by
  classical
  obtain ⟨ϕ, δ, c, hϕ, hδ, hx⟩ := exists_primitive_decomposition x hint
  obtain ⟨d, hd0, p, hp⟩ := exists_commonDenominator (fun s : ι × Fin δ => c s.1 (s.2 : ℕ))
  refine ⟨ϕ, δ, d, fun s j => if hj : j < δ then p (s, ⟨j, hj⟩) else 0, hϕ, hδ, hd0, fun s => ?_⟩
  rw [hx s, Finset.mul_sum]
  refine Finset.sum_congr rfl fun j hj => ?_
  rw [Finset.mem_range] at hj
  show _ = algebraMap (RatFunc K) Ω (algebraMap K[X] (RatFunc K)
    (if h : j < δ then p (s, ⟨j, h⟩) else 0)) * ϕ ^ j
  rw [dite_eq_left hj, ← mul_assoc, ← map_mul, hp (s, ⟨j, hj⟩)]

end Combined

/-! ## Step 3: the splitting of the lifted relation -/

section Splitting

variable {F Ω : Type*} [Field F] [Field Ω] [Algebra F Ω]

/-- **[AF22] §2.4, last step.**  *«Since `ℚ̄(z)(f(z))` and `A` are linearly disjoint over `ℚ̄(z)`,
the functions `ϕ(z^{q^{k₀}})ʲ`, `0 ≤ j ≤ δ-1`, remain linearly independent over `ℚ̄(z)(f(z))`.
Thus, splitting the linear form `Q` as `Q(z,X) = ∑ⱼ Qⱼ(z,X)ϕ(z^{q^{k₀}})ʲ`, we deduce that
`Qⱼ(z, f(z)) = 0` for all `j`.»*

The hypothesis `hreg` is the regularity of the extension `E/F` — in characteristic zero exactly
Mathlib's `algebraicClosure F E = ⊥` — which is [AF17] Lemme 2.2 and the Stage-2 cited axiom
(WP8-bis).  Everything above it is proved: the independence of the powers of `x` over `E` is
`algebraicClosure.eq_zero_of_sum_pow_eq_zero`, delivered with gate G5. -/
@[category research solved, AMS 11 12, ref "AF22" "AF17" "Lan02", group "af_mahler_alternative"]
theorem linearForm_split (E : IntermediateField F Ω) (hreg : algebraicClosure F E = ⊥)
    {x : Ω} (hx : IsIntegral F x) {ι : Type*} [Fintype ι] {δ : ℕ}
    (hδ : δ ≤ (minpoly F x).natDegree) (w : ι → ℕ → F) (g : ι → E)
    (hrel : ∑ i, (∑ j ∈ Finset.range δ, algebraMap F Ω (w i j) * x ^ j) *
      algebraMap E Ω (g i) = 0) :
    ∀ j ∈ Finset.range δ, ∑ i, algebraMap F E (w i j) * g i = 0 := by
  classical
  -- the coefficients of the splitting, padded by zero up to the degree of `x` over `F`
  set c : Fin (minpoly F x).natDegree → E := fun j =>
    if (j : ℕ) < δ then ∑ i, algebraMap F E (w i (j : ℕ)) * g i else 0 with hc
  -- the same, read in `Ω`
  set G : ℕ → Ω := fun j =>
    if j < δ then (∑ i, algebraMap F Ω (w i j) * algebraMap E Ω (g i)) * x ^ j else 0 with hG
  have hcG : ∀ j : Fin (minpoly F x).natDegree, algebraMap E Ω (c j) * x ^ (j : ℕ) = G (j : ℕ) := by
    intro j
    rw [hc, hG]
    by_cases hj : (j : ℕ) < δ
    · simp only [ite_eq_left hj]
      congr 1
      rw [map_sum]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [map_mul, ← IsScalarTower.algebraMap_apply]
    · simp [ite_eq_right hj]
  have hzero : ∑ j, algebraMap E Ω (c j) * x ^ (j : ℕ) = 0 := by
    calc ∑ j, algebraMap E Ω (c j) * x ^ (j : ℕ)
        = ∑ j ∈ Finset.range (minpoly F x).natDegree, G j := by
          rw [← Fin.sum_univ_eq_sum_range G]
          exact Finset.sum_congr rfl fun j _ => hcG j
      _ = ∑ j ∈ Finset.range δ, G j := by
          refine (Finset.sum_subset (fun j hj => ?_) fun j _ hj => ?_).symm
          · rw [Finset.mem_range] at hj ⊢
            omega
          · rw [Finset.mem_range] at hj
            simp [hG, ite_eq_right hj]
      _ = ∑ j ∈ Finset.range δ, (∑ i, algebraMap F Ω (w i j) * algebraMap E Ω (g i)) * x ^ j := by
          refine Finset.sum_congr rfl fun j hj => ?_
          rw [Finset.mem_range] at hj
          simp [hG, ite_eq_left hj]
      _ = ∑ i, (∑ j ∈ Finset.range δ, algebraMap F Ω (w i j) * x ^ j) * algebraMap E Ω (g i) := by
          simp_rw [Finset.sum_mul]
          rw [Finset.sum_comm]
          exact Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => by ring
      _ = 0 := hrel
  intro j hj
  rw [Finset.mem_range] at hj
  have hjlt : j < (minpoly F x).natDegree := lt_of_lt_of_le hj hδ
  have hzj := algebraicClosure.eq_zero_of_sum_pow_eq_zero hreg hx c hzero ⟨j, hjlt⟩
  rw [hc] at hzj
  simpa [hj] using hzj

end Splitting

/-! ## The solution field, and the shape of the WP8-bis axiom -/

section SolField

variable (K : Type*) [Field K] {Ω : Type*} [Field Ω] [Algebra (RatFunc K) Ω]

/-- **The solution field `K(z)(f₁,…,f_n)`** of a Mahler system, inside an ambient field `Ω`. -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
noncomputable def solField {ι : Type*} (f : ι → Ω) : IntermediateField (RatFunc K) Ω :=
  IntermediateField.adjoin (RatFunc K) (Set.range f)

/-- **[AF17] Lemme 2.2, as a predicate**: `K(z)` is relatively algebraically closed in the
solution field — in characteristic zero, exactly the regularity of `K(z)(f)/K(z)`.

This is *not* asserted here.  It is the Stage-2 cited axiom of `plans/plan-formalize-AF17.html`
(WP8-bis), whose literature proof runs: a member of the relative algebraic closure is algebraic
over `K(z)` and, by the Mahler system, satisfies a linear `q`-Mahler equation ([AF17] Lemme 2.2,
using that a subextension of a finitely generated extension is finitely generated, [Lan02] Chap.
VIII Ex. 4); an algebraic `q`-Mahler function is rational ([Nis96] Thm 5.1.7 = [Ran92] Thm 4.3
with Corollaires 1–2). -/
@[category API, AMS 11 12 39, ref "AF17", group "af_mahler_alternative"]
def IsRegularSolField {ι : Type*} (f : ι → Ω) : Prop :=
  algebraicClosure (RatFunc K) ↥(solField K f) = ⊥

/-- The functions themselves lie in their solution field. -/
@[category API, AMS 11 12, ref "AF17", group "af_mahler_alternative"]
theorem mem_solField {ι : Type*} (f : ι → Ω) (i : ι) : f i ∈ solField K f :=
  IntermediateField.subset_adjoin (RatFunc K) (Set.range f) ⟨i, rfl⟩

/-- **[AF22] §2.4 in the form the proof of Theorem 2.1 consumes**: a linear relation between the
`fᵢ(z)` whose coefficients are polynomials in `z` and in `ϕ` splits into linear relations whose
coefficients are polynomials in `z` alone — one for each power of `ϕ`. -/
@[category research solved, AMS 11 12 39, ref "AF22" "AF17", group "af_mahler_alternative"]
theorem linearForm_split_solField {ι : Type*} [Fintype ι] {f : ι → Ω}
    (hreg : IsRegularSolField K f) {x : Ω} (hx : IsIntegral (RatFunc K) x) {δ : ℕ}
    (hδ : δ ≤ (minpoly (RatFunc K) x).natDegree) (w : ι → ℕ → RatFunc K)
    (hrel : ∑ i, (∑ j ∈ Finset.range δ, algebraMap (RatFunc K) Ω (w i j) * x ^ j) * f i = 0) :
    ∀ j ∈ Finset.range δ, ∑ i, algebraMap (RatFunc K) Ω (w i j) * f i = 0 := by
  have h := linearForm_split (solField K f) hreg hx hδ w
    (fun i => ⟨f i, mem_solField K f i⟩) (by simpa using hrel)
  intro j hj
  have hj' := h j hj
  have hmap := congrArg (algebraMap (↥(solField K f)) Ω) hj'
  rw [map_sum, map_zero] at hmap
  rw [← hmap]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [map_mul, ← IsScalarTower.algebraMap_apply]
  rfl

end SolField

end AF
