/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.Data.Set.Finite.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Automatic sequences — basic notions (Allouche–Shallit)

Jean-Paul Allouche and Jeffrey Outlaw Shallit, *Automatic Sequences: Theory, Applications,
Generalizations*, Cambridge University Press, 2003.

This file records the foundational notions of the theory of automatic sequences, used throughout
the corpus (e.g. by the Adamczewski–Bugeaud transcendence results in `AB/` and the automatic
parity-vector development in `B3/`).

## Notions

* **`k`-kernel** (`kKernel`). The set of subsequences `n ↦ a (kⁱ·n + r)` for `i ≥ 0` and
  `0 ≤ r < kⁱ`.
* **Automatic sequence** (`IsAutomatic`). A sequence `a : ℕ → ℕ` is *`k`-automatic* iff its
  `k`-kernel is finite (Eilenberg's characterization); a sequence is *automatic* iff it is
  `k`-automatic for some `k ≥ 2` — equivalently, generated by a deterministic finite automaton with
  output. The kernel formulation is used so the statement is self-contained (no DFAO machinery).

## Off `ℕ`-valued sequences ([B1E2b] WP11a)

`IsAutomatic` consumes `ℕ → ℕ`, but automaticity is a property of a sequence over *any* finite
alphabet, and several consumers (`RB.E2`, `RB.AlgebraicBase`) carry `ℤ`-valued words.  Encoding
such a word as a `ℕ`-valued one is not innocent: a non-injective encoding can *create*
automaticity out of nothing (`RB.toNat_encoding_trap`), which is why `RB.E2Quadratic` had to
quantify over an arbitrary *faithful* encoding.

`kKernel'`/`IsAutomatic'` state the same notions for `ℕ → α`, `α` arbitrary.  The existing
`ℕ`-valued API is left untouched (several files consume it) and the two agree on the nose
(`kKernel_eq_kKernel'`, `isAutomatic_iff_isAutomatic'` — both `rfl`).  With the general version
the encoding apparatus becomes two lemmas:

* `isAutomatic'_congr_of_injective` — automaticity is invariant under injective relabelling of the
  alphabet (`isAutomatic'_comp_iff` needs only injectivity **on the range**, which is what the
  applications have);
* `isAutomatic'_iff_faithful_encoding` — hence "some faithful `ℕ`-encoding of `w` is automatic" is
  *equivalent* to "`w` is automatic", with no choice of encoding left in the statement.

One half of the congruence is unconditional: `IsAutomatic' a → IsAutomatic' (g ∘ a)` for every `g`
(the kernel of `g ∘ a` is the image of the kernel of `a`).  The injectivity is needed for the
converse only — that asymmetry *is* the encoding trap, and `not_isAutomatic'_of_injective` (an
injective sequence is never automatic) makes it exhibitable in one line.

## Contents
* `kKernel`, `IsAutomatic` — the `k`-kernel and the automatic-sequence predicate.
* `kKernel'`, `IsAutomatic'` — the same over an arbitrary alphabet, with `kKernel_eq_kKernel'`.
* `finite_range_of_isAutomatic'` — an automatic sequence has a finite alphabet, for free.
* `kKernel'_comp`, `isAutomatic'_comp_iff`, `isAutomatic'_congr_of_injective` — relabelling.
* `isAutomatic'_iff_faithful_encoding` — the faithful-encoding form, as a corollary.
* `not_isAutomatic'_of_injective`, `isAutomatic'_const` — the two extreme cases.

## References
* [AS03] Allouche, Jean-Paul, and Jeffrey Outlaw Shallit. *Automatic Sequences: Theory,
  Applications, Generalizations.* Cambridge University Press, 2003.  (Kernel characterization:
  Thm 6.6.2; closure under codings: Thm 6.8.1.)
* [B1E2b] `plans/plan-B1E2b.html` (2026-07-28): WP11a (review item F7d).
-/

namespace AS

/-- The **`k`-kernel** of a sequence `a : ℕ → ℕ`: the set of all subsequences `n ↦ a (kⁱ·n + r)`
for `i ≥ 0` and `0 ≤ r < kⁱ`. By Eilenberg's theorem, `a` is `k`-automatic iff this set is finite. -/
@[category API, AMS 11 68, ref "AS03"]
def kKernel (k : ℕ) (a : ℕ → ℕ) : Set (ℕ → ℕ) :=
  {s | ∃ i r, r < k ^ i ∧ s = fun n => a (k ^ i * n + r)}

/-- A sequence is **automatic** iff it is `k`-automatic for some base `k ≥ 2`, i.e. its `k`-kernel
is finite — equivalently, it is generated by a deterministic finite automaton with output. -/
@[category API, AMS 11 68, ref "AS03"]
def IsAutomatic (a : ℕ → ℕ) : Prop :=
  ∃ k, 2 ≤ k ∧ (kKernel k a).Finite

/-! ## An arbitrary alphabet ([B1E2b] WP11a) -/

/-- The **`k`-kernel** of a sequence `a : ℕ → α` over an arbitrary alphabet: the set of all
subsequences `n ↦ a (kⁱ·n + r)` for `i ≥ 0` and `0 ≤ r < kⁱ`.  At `α = ℕ` this is `kKernel`, on
the nose (`kKernel_eq_kKernel'`). -/
@[category API, AMS 11 68, ref "AS03"]
def kKernel' {α : Type*} (k : ℕ) (a : ℕ → α) : Set (ℕ → α) :=
  {s | ∃ i r, r < k ^ i ∧ s = fun n => a (k ^ i * n + r)}

/-- A sequence `a : ℕ → α` over an arbitrary alphabet is **automatic** iff its `k`-kernel is finite
for some `k ≥ 2`.  No finite-alphabet hypothesis has to be carried alongside: finiteness of the
kernel already forces it (`finite_range_of_isAutomatic'`). -/
@[category API, AMS 11 68, ref "AS03"]
def IsAutomatic' {α : Type*} (a : ℕ → α) : Prop :=
  ∃ k, 2 ≤ k ∧ (kKernel' k a).Finite

/-- The general kernel restricts to the `ℕ`-valued one definitionally. -/
@[category API, AMS 11 68, ref "AS03"]
theorem kKernel_eq_kKernel' (k : ℕ) (a : ℕ → ℕ) : kKernel k a = kKernel' k a := rfl

/-- `IsAutomatic'` restricts to `IsAutomatic` definitionally: the general API is a conservative
extension, and every existing consumer keeps working unchanged. -/
@[category API, AMS 11 68, ref "AS03"]
theorem isAutomatic_iff_isAutomatic' (a : ℕ → ℕ) : IsAutomatic a ↔ IsAutomatic' a := Iff.rfl

/-- **An automatic sequence has a finite alphabet.**  Distinct letters give distinct kernel
members: `a m` is the value at `0` of the decimation `n ↦ a (kⁱ·n + m)`, which lies in the kernel as
soon as `m < kⁱ` — and `m < k^m` for `k ≥ 2`.  So `Set.range a` is the image of the kernel under
evaluation at `0`.

Hence statements like `RB.EAll` need no separate boundedness hypothesis on the word. -/
@[category research solved, AMS 11 68, ref "AS03"]
theorem finite_range_of_isAutomatic' {α : Type*} {a : ℕ → α} (h : IsAutomatic' a) :
    (Set.range a).Finite := by
  obtain ⟨k, hk, hfin⟩ := h
  refine Set.Finite.subset (hfin.image (fun s => s 0)) ?_
  rintro _ ⟨m, rfl⟩
  exact ⟨fun n => a (k ^ m * n + m), ⟨m, m, Nat.lt_pow_self hk, rfl⟩, by simp⟩

/-! ### Relabelling the alphabet -/

/-- Relabelling commutes with decimation: the `k`-kernel of `g ∘ a` is the image of the `k`-kernel
of `a` under `s ↦ g ∘ s`.  In particular `IsAutomatic' a → IsAutomatic' (g ∘ a)` for **every**
`g` — the direction that needs no injectivity. -/
@[category API, AMS 11 68, ref "AS03"]
theorem kKernel'_comp {α β : Type*} (k : ℕ) (a : ℕ → α) (g : α → β) :
    kKernel' k (g ∘ a) = (fun s => g ∘ s) '' kKernel' k a := by
  ext s
  constructor
  · rintro ⟨i, r, hr, rfl⟩
    exact ⟨_, ⟨i, r, hr, rfl⟩, rfl⟩
  · rintro ⟨t, ⟨i, r, hr, rfl⟩, rfl⟩
    exact ⟨i, r, hr, rfl⟩

/-- Every member of the `k`-kernel of `a` takes its values among those of `a`. -/
@[category API, AMS 11 68, ref "AS03"]
theorem range_subset_of_mem_kKernel' {α : Type*} {k : ℕ} {a s : ℕ → α}
    (hs : s ∈ kKernel' k a) : Set.range s ⊆ Set.range a := by
  rintro _ ⟨n, rfl⟩
  obtain ⟨i, r, -, rfl⟩ := hs
  exact ⟨_, rfl⟩

/-- Relabelling by a map injective **on the range of the sequence** preserves kernel finiteness in
both directions.  Injectivity elsewhere is irrelevant, which is what makes this usable for the
`ℤ → ℕ` encodings of a bounded word. -/
@[category API, AMS 11 68, ref "AS03"]
theorem finite_kKernel'_comp_iff {α β : Type*} {k : ℕ} {a : ℕ → α} {g : α → β}
    (hg : Set.InjOn g (Set.range a)) :
    (kKernel' k (g ∘ a)).Finite ↔ (kKernel' k a).Finite := by
  rw [kKernel'_comp]
  refine ⟨fun h => Set.Finite.of_finite_image h ?_, fun h => h.image _⟩
  intro s hs t ht hst
  funext n
  exact hg (range_subset_of_mem_kKernel' hs ⟨n, rfl⟩) (range_subset_of_mem_kKernel' ht ⟨n, rfl⟩)
    (congrFun hst n)

/-- **Automaticity is invariant under relabelling injective on the range.** -/
@[category API, AMS 11 68, ref "AS03"]
theorem isAutomatic'_comp_iff {α β : Type*} {a : ℕ → α} {g : α → β}
    (hg : Set.InjOn g (Set.range a)) : IsAutomatic' (g ∘ a) ↔ IsAutomatic' a :=
  exists_congr fun _ => and_congr_right fun _ => finite_kKernel'_comp_iff hg

/-- **Automaticity is invariant under injective relabelling of the alphabet** ([AS03] Thm 6.8.1
for the free direction; the converse is where injectivity enters).  This is the lemma that
replaces the faithful-encoding apparatus of `RB.E2`. -/
@[category API, AMS 11 68, ref "AS03" "B1E2b"]
theorem isAutomatic'_congr_of_injective {α β : Type*} {a : ℕ → α} {g : α → β}
    (hg : Function.Injective g) : IsAutomatic' (g ∘ a) ↔ IsAutomatic' a :=
  isAutomatic'_comp_iff hg.injOn

/-- **The faithful-encoding form** ([B1E2b] WP11a): if `f : ℕ → ℕ` is a *faithful* encoding of
`w : ℕ → α` — `f m = f n ↔ w m = w n`, i.e. `f` separates exactly the letters `w` separates — then
`f` is automatic **iff** `w` is.

So a statement quantified over an arbitrary faithful encoding (the shape `RB.E2Quadratic` was
forced into, before `IsAutomatic'` existed) says exactly what the encoding-free statement says,
and the choice of encoding carries no information.

The proof factors `w = g ∘ f` through the relabelling `g` sending a letter of `f` to the letter of
`w` it encodes; faithfulness makes `g` well defined on `Set.range f` and injective there. -/
@[category API, AMS 11 68, ref "AS03" "B1E2b"]
theorem isAutomatic'_iff_faithful_encoding {α : Type*} {w : ℕ → α} {f : ℕ → ℕ}
    (hf : ∀ m n, f m = f n ↔ w m = w n) : IsAutomatic f ↔ IsAutomatic' w := by
  classical
  set g : ℕ → α := fun j => if h : ∃ m, f m = j then w h.choose else w 0 with hgdef
  have hgf : g ∘ f = w := by
    funext n
    have h : ∃ m, f m = f n := ⟨n, rfl⟩
    simp only [Function.comp_apply, hgdef, dif_pos h]
    exact (hf h.choose n).mp h.choose_spec
  have hginj : Set.InjOn g (Set.range f) := by
    rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩ h
    have hm : g (f m) = w m := congrFun hgf m
    have hn : g (f n) = w n := congrFun hgf n
    exact (hf m n).mpr (by rw [← hm, ← hn, h])
  have key := isAutomatic'_comp_iff (a := f) (g := g) hginj
  rw [hgf] at key
  exact (isAutomatic_iff_isAutomatic' f).trans key.symm

/-! ### The two extreme cases -/

/-- **An injective sequence is never automatic**: the diagonal decimations `n ↦ a (kⁱ·n)` are
pairwise distinct (compare them at `n = 1`, where they read `a (kⁱ)`), so the `k`-kernel is
infinite for every `k ≥ 2`.

This is the cheap half of the *encoding trap*: composing with a non-injective relabelling can turn
such a sequence into a constant one, and constants are automatic (`isAutomatic'_const`).  So the
injectivity hypothesis of `isAutomatic'_congr_of_injective` cannot be dropped. -/
@[category research solved, AMS 11 68, ref "AS03" "B1E2b"]
theorem not_isAutomatic'_of_injective {α : Type*} {a : ℕ → α} (ha : Function.Injective a) :
    ¬ IsAutomatic' a := by
  rintro ⟨k, hk, hfin⟩
  refine (Set.infinite_of_injective_forall_mem (f := fun i : ℕ => fun n => a (k ^ i * n))
    ?_ ?_) hfin
  · intro i j hij
    have h1 : a (k ^ i) = a (k ^ j) := by simpa using congrFun hij 1
    exact Nat.pow_right_injective hk (ha h1)
  · refine fun i => ⟨i, 0, Nat.pow_pos (by omega), ?_⟩
    funext n
    simp

/-- A constant sequence is automatic over any alphabet: its `k`-kernel is a singleton. -/
@[category API, AMS 11 68, ref "AS03"]
theorem isAutomatic'_const {α : Type*} (v : α) : IsAutomatic' (fun _ : ℕ => v) := by
  refine ⟨2, le_refl 2, Set.Finite.subset (Set.finite_singleton (fun _ : ℕ => v)) ?_⟩
  rintro s ⟨i, r, -, rfl⟩
  rfl

end AS
