/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Set.Card
import Mathlib.SetTheory.Cardinal.NatCard
import Mathlib.Data.Fintype.Pi
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import CITED.AlloucheShallitBasic
import ForMathlib.Combinatorics.SubwordComplexity
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Cobham's bound: automatic sequences have linear subword complexity

**`p_a(m) = O(m)` for every automatic `a`** ([Cob72]; [AS03] Thm 10.3.1) — *proved*, not
axiomatized, and directly from the `k`-kernel (`AS.kKernel`) of `CITED.AlloucheShallitBasic`.

## The proof, and why it stays inside the kernel

The textbook argument runs through a DFAO reading most-significant-digit first, and bounds
`p_a(m) ≤ |Q|²·k·m` by "the window straddles at most two blocks, each fixed by the state after
its prefix".  Getting an MSD automaton out of a finite kernel is Eilenberg's theorem plus a
subset construction — a large formalization we do not need.  The kernel (an LSD notion) carries
the argument by itself once the right invariant is spotted:

* an automatic sequence takes **finitely many values** (`range_finite_of_kernel_finite`):
  `a n = s 0` for the kernel element `s = (t ↦ a(kⁱt + n))` at any `i` with `n < kⁱ`;
* so the **profile** `P q := (s ↦ s q) : K → range a` lives in a *finite type*, and
* with `N = kⁱ ≥ m`, writing `n = N·q + r`, every letter `a(n+u)` of the length-`m` window is
  `s q` or `s (q+1)` for a kernel element `s` determined by `r + u` — hence the whole window is
  a function of the triple `(r, P q, P (q+1))` (`hdet` inside the proof).

Counting triples gives `p_a(m) ≤ N·|F×F|` with `F = K → range a`, and choosing `N` minimal
with `m ≤ N = kⁱ` gives `N ≤ k·m` (`exists_scale`), so `C = k·|F×F|` works.  The constant is
far from optimal (`|F| = V^D` against the DFAO's `|Q|`); only its existence is ever used.

## Reading this correctly

The bound is an **upper** bound, so it can only ever refute automaticity via
*superlinearity* — `not_automatic_of_complexity_superlinear`.  A linear **lower** bound, however
large its constant, is perfectly compatible with automaticity: Thue–Morse is `2`-automatic with
`liminf p(l)/l = 3`, well above e.g. the `1.70951129` of [Dub09] Cor 4.  See [B1E2] §4; do not
let the wording drift.

## Contents

* `AS.complexity` — `p_a(m)`, over `ForMathlib.SubwordComplexity.factor` (whose `factor u k i`
  is the length-`k` factor at `i`; note the argument order).
* `kernel_apply_mem_range`, `range_finite_of_kernel_finite` — automatic ⇒ finitely many values.
* `exists_scale` — the window scale `m ≤ kⁱ ≤ k·m`.
* **`complexity_linear_of_automatic`** — `IsAutomatic a → ∃ C, ∀ m ≥ 1, p_a(m) ≤ C·m`.
* **`not_automatic_of_complexity_superlinear`** — the contrapositive consumers use.

## References

* [Cob72] A. Cobham. *Uniform tag sequences.* Math. Systems Theory **6** (1972), 164–192.
  (The original linear-complexity bound.)
* [AS03] Allouche, Shallit. *Automatic Sequences.* CUP 2003.  (Thm 10.3.1; Thm 6.6.2 =
  Eilenberg's kernel criterion, which we sidestep.)
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J.
  **51** (2009), 243–252.  (Cor 4 — the linear floor that this bound does *not* contradict.)
* [B1E2] `plans/plan-B1E2.html` (rev. 2, 2026-07): WP8(a), §4.
-/

namespace AS

open ForMathlib.SubwordComplexity

/-- The **subword complexity** `p_a(m)` of an infinite sequence: the number of distinct
length-`m` factors occurring at *any* position.

Reuses `ForMathlib.SubwordComplexity.factor` (mind the argument order: `factor a m n` is the
length-`m` factor at position `n`).  This is the infinite-word counterpart of that file's
windowed `subwordComplexity`, and the `ℕ`-valued generalization of `TH.complexity`. -/
@[category API, AMS 11 68, ref "AS03", group "cobham_linear_complexity"]
noncomputable def complexity (a : ℕ → ℕ) (m : ℕ) : ℕ := (Set.range fun n => factor a m n).ncard

/-- Every value of a `k`-kernel element is a value of `a`. -/
@[category API, AMS 11 68, ref "AS03", group "cobham_linear_complexity"]
lemma kernel_apply_mem_range {k : ℕ} {a : ℕ → ℕ} {s : ℕ → ℕ} (hs : s ∈ kKernel k a) (q : ℕ) :
    s q ∈ Set.range a := by
  obtain ⟨i, r, hr, rfl⟩ := hs
  exact ⟨k ^ i * q + r, rfl⟩

/-- An automatic sequence takes **finitely many values**: `a n` is the `0`-th entry of the
kernel element `t ↦ a(kⁱt + n)`, for any `i` with `n < kⁱ`. -/
@[category research solved, AMS 11 68, ref "AS03", group "cobham_linear_complexity"]
lemma range_finite_of_kernel_finite {k : ℕ} {a : ℕ → ℕ} (hk : 2 ≤ k)
    (hK : (kKernel k a).Finite) : (Set.range a).Finite := by
  refine Set.Finite.subset (hK.image (fun s => s 0)) ?_
  rintro v ⟨n, rfl⟩
  exact ⟨fun t => a (k ^ n * t + n), ⟨n, n, Nat.lt_pow_self hk, rfl⟩, by simp⟩

/-- The window scale: some `i` with `m ≤ kⁱ ≤ k·m` (take `i` minimal with `m ≤ kⁱ`). -/
@[category API, AMS 11 68, ref "AS03", group "cobham_linear_complexity"]
lemma exists_scale {k m : ℕ} (hk : 2 ≤ k) (hm : 1 ≤ m) : ∃ i, m ≤ k ^ i ∧ k ^ i ≤ k * m := by
  classical
  have hex : ∃ i, m ≤ k ^ i := ⟨m, le_of_lt (Nat.lt_pow_self hk)⟩
  refine ⟨Nat.find hex, Nat.find_spec hex, ?_⟩
  rcases Nat.eq_zero_or_pos (Nat.find hex) with h0 | hpos
  · rw [h0, pow_zero]
    exact Nat.one_le_iff_ne_zero.mpr (Nat.mul_ne_zero (by omega) (by omega))
  · have hlt : k ^ (Nat.find hex - 1) < m := Nat.not_le.mp (Nat.find_min hex (by omega))
    calc k ^ Nat.find hex = k * k ^ (Nat.find hex - 1) := by rw [← pow_succ']; congr 1; omega
      _ ≤ k * m := Nat.mul_le_mul_left _ (le_of_lt hlt)

/-- **Cobham's bound** ([Cob72]; [AS03] Thm 10.3.1): an automatic sequence has linear subword
complexity, `p_a(m) ≤ C·m` for `m ≥ 1`.

Proved from kernel finiteness alone: with `N = kⁱ ∈ [m, k·m]`, the length-`m` window at
`n = N·q + r` is a function of `(r, P q, P (q+1))`, where the profile `P q = (s ↦ s q)` ranges
over the finite type `K → range a`.  No DFAO, no Eilenberg, no subset construction. -/
@[category research solved, AMS 11 68, ref "Cob72" "AS03", group "cobham_linear_complexity"]
theorem complexity_linear_of_automatic {a : ℕ → ℕ} (h : IsAutomatic a) :
    ∃ C, ∀ m, 1 ≤ m → complexity a m ≤ C * m := by
  classical
  obtain ⟨k, hk, hK⟩ := h
  have hra : (Set.range a).Finite := range_finite_of_kernel_finite hk hK
  haveI : Finite ↥(kKernel k a) := hK
  haveI : Finite ↥(Set.range a) := hra
  refine ⟨k * Nat.card ((↥(kKernel k a) → ↥(Set.range a)) × (↥(kKernel k a) → ↥(Set.range a))),
    fun m hm => ?_⟩
  obtain ⟨i, him, hik⟩ := exists_scale hk hm
  set N := k ^ i with hNdef
  have hNpos : 0 < N := pow_pos (by omega) i
  -- the profile: `q ↦ (s ↦ s q)`, valued in a finite type because `a` has finite range
  set P : ℕ → (↥(kKernel k a) → ↥(Set.range a)) :=
    fun q s => ⟨s.val q, kernel_apply_mem_range s.2 q⟩ with hPdef
  set Φ : ℕ → Fin N × (↥(kKernel k a) → ↥(Set.range a)) × (↥(kKernel k a) → ↥(Set.range a)) :=
    fun n => (⟨n % N, Nat.mod_lt _ hNpos⟩, P (n / N), P (n / N + 1)) with hΦdef
  -- equal profiles ⇒ equal blocks at scale `N`
  have hkey : ∀ q₁ q₂ : ℕ, P q₁ = P q₂ → ∀ j, j < N → a (N * q₁ + j) = a (N * q₂ + j) := by
    intro q₁ q₂ hq j hj
    have hs : (fun t => a (N * t + j)) ∈ kKernel k a := ⟨i, j, hj, rfl⟩
    simpa [hPdef] using congrArg Subtype.val (congrFun hq ⟨_, hs⟩)
  -- the window is a function of `Φ`: it straddles the blocks at `q` and `q+1`
  have hdet : ∀ n₁ n₂, Φ n₁ = Φ n₂ → factor a m n₁ = factor a m n₂ := by
    intro n₁ n₂ he
    have hr : n₁ % N = n₂ % N := by
      simpa [hΦdef, Fin.ext_iff] using congrArg Prod.fst he
    have hq : P (n₁ / N) = P (n₂ / N) := by simpa [hΦdef] using congrArg (fun z => z.2.1) he
    have hq' : P (n₁ / N + 1) = P (n₂ / N + 1) := by
      simpa [hΦdef] using congrArg (fun z => z.2.2) he
    funext u
    simp only [factor]
    have e₁ : N * (n₁ / N) + n₁ % N = n₁ := Nat.div_add_mod n₁ N
    have e₂ : N * (n₂ / N) + n₂ % N = n₂ := Nat.div_add_mod n₂ N
    have m₁ : N * (n₁ / N + 1) = N * (n₁ / N) + N := by ring
    have m₂ : N * (n₂ / N + 1) = N * (n₂ / N) + N := by ring
    have hu : (u : ℕ) < m := u.isLt
    have hrN : n₁ % N < N := Nat.mod_lt _ hNpos
    rcases Nat.lt_or_ge (n₁ % N + u) N with hj | hj
    · -- the letter sits in the block at `q`
      have g₁ : n₁ + (u : ℕ) = N * (n₁ / N) + (n₁ % N + u) := by omega
      have g₂ : n₂ + (u : ℕ) = N * (n₂ / N) + (n₁ % N + u) := by omega
      rw [g₁, g₂]
      exact hkey _ _ hq _ hj
    · -- it has spilled into the block at `q+1`
      have g₁ : n₁ + (u : ℕ) = N * (n₁ / N + 1) + (n₁ % N + u - N) := by omega
      have g₂ : n₂ + (u : ℕ) = N * (n₂ / N + 1) + (n₁ % N + u - N) := by omega
      rw [g₁, g₂]
      exact hkey _ _ hq' _ (by omega)
  -- hence the factors are no more numerous than the triples
  have hinj : complexity a m ≤ (Set.range Φ).ncard := by
    unfold complexity
    refine Set.ncard_le_ncard_of_injOn (fun w => Φ (Function.invFun (fun n => factor a m n) w))
      (fun w _ => Set.mem_range_self _) ?_ (Set.toFinite _)
    intro w₁ h₁ w₂ h₂ heq
    have e₁ := Function.invFun_eq (Set.mem_range.mp h₁)
    have e₂ := Function.invFun_eq (Set.mem_range.mp h₂)
    rw [← e₁, ← e₂]
    exact hdet _ _ heq
  have hcard : (Set.range Φ).ncard
      ≤ N * Nat.card ((↥(kKernel k a) → ↥(Set.range a)) × (↥(kKernel k a) → ↥(Set.range a))) := by
    have h1 : (Set.range Φ).ncard ≤ Nat.card (Fin N × (↥(kKernel k a) → ↥(Set.range a))
        × (↥(kKernel k a) → ↥(Set.range a))) := by
      rw [← Set.ncard_univ]
      exact Set.ncard_le_ncard (Set.subset_univ _) (Set.toFinite _)
    rwa [Nat.card_prod, Nat.card_eq_fintype_card, Fintype.card_fin] at h1
  calc complexity a m ≤ (Set.range Φ).ncard := hinj
    _ ≤ N * Nat.card ((↥(kKernel k a) → ↥(Set.range a)) × (↥(kKernel k a) → ↥(Set.range a))) :=
        hcard
    _ ≤ (k * m) * Nat.card ((↥(kKernel k a) → ↥(Set.range a))
          × (↥(kKernel k a) → ↥(Set.range a))) := Nat.mul_le_mul_right _ hik
    _ = (k * Nat.card ((↥(kKernel k a) → ↥(Set.range a))
          × (↥(kKernel k a) → ↥(Set.range a)))) * m := by rw [Nat.mul_right_comm]

/-- **The contrapositive**: a sequence whose subword complexity beats *every* linear function
is not automatic.  This — never a linear lower bound, however large its constant — is what
refutes automaticity ([B1E2] §4). -/
@[category research solved, AMS 11 68, ref "Cob72" "AS03", group "cobham_linear_complexity"]
theorem not_automatic_of_complexity_superlinear {a : ℕ → ℕ}
    (h : ∀ C, ∃ m, 1 ≤ m ∧ C * m < complexity a m) : ¬ IsAutomatic a := by
  intro hauto
  obtain ⟨C, hC⟩ := complexity_linear_of_automatic hauto
  obtain ⟨m, hm, hlt⟩ := h C
  exact absurd (hC m hm) (by omega)

/-! ## Sanity -/

/-- Why `complexity_linear_of_automatic` needs `1 ≤ m`: the empty word is the unique length-`0`
factor, so `p_a(0) = 1 > C·0` for every `C`. -/
@[category test, AMS 11 68, ref "AS03", group "cobham_linear_complexity"]
theorem complexity_zero (a : ℕ → ℕ) : complexity a 0 = 1 := by
  unfold complexity
  rw [Set.ncard_eq_one]
  refine ⟨factor a 0 0, ?_⟩
  ext w
  simp only [Set.mem_range, Set.mem_singleton_iff]
  exact ⟨fun _ => Subsingleton.elim _ _, fun h => ⟨0, h ▸ rfl⟩⟩

/-- The definition is not degenerate: the alternating sequence has both letters as factors. -/
@[category test, AMS 11 68, ref "AS03", group "cobham_linear_complexity"]
theorem complexity_alternating : complexity (fun n => n % 2) 1 = 2 := by
  unfold complexity
  have hset : (Set.range fun n => factor (fun n => n % 2) 1 n) = {fun _ => 0, fun _ => 1} := by
    ext w
    simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro ⟨n, rfl⟩
      rcases Nat.even_or_odd n with he | ho
      · left; funext u; simp [factor, Nat.even_iff.mp he]
      · right; funext u; simp [factor, Nat.odd_iff.mp ho]
    · rintro (rfl | rfl)
      · exact ⟨0, by funext u; simp [factor]⟩
      · exact ⟨1, by funext u; simp [factor]⟩
  rw [hset, Set.ncard_pair]
  intro h
  have := congrFun h ⟨0, by omega⟩
  simp at this

end AS
