/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import BertinPisot.SetSTU
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.Algebra.Order.Round
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Dubickas's Theorem 2: a periodic word forces a Pisot or Salem base ([Dub09])

The cited half of the *rigidity* statement for ceiling orbits `xₙ = ⌈βxₙ₋₁⌉` of an algebraic
base `β > 1`: if the associated integer word is ultimately periodic, `β` cannot be an arbitrary
algebraic number — it must lie in `Bertin.U = S ∪ T` (Pisot ∪ Salem).

## The theorem, verbatim

> **THEOREM 2** ([Dub09] p. 244).  Let `β > 1` be an algebraic number with minimal polynomial
> `b_d X^d + ⋯ + b_1 X + b_0 ∈ ℤ[X]`.  If the sequence
> `wₙ = b_d x_{n+d} + ⋯ + b_1 x_{n+1} + b_0 xₙ`, `n = 0, 1, 2, …`, is ultimately periodic, then
> `β` must be either a Pisot number or a Salem number.

Here `xₙ = T_{β,γ}(x_{n−1}) = ⌊βx_{n−1} + γ⌋` from a positive integer `x₀` with
`(β − 1)x₀ ≥ 1 − γ`.  Immediately after the theorem [Dub09] p. 244 records:

> We remark that the same statements as those of Theorems 1 and 2 hold if we replace the map
> `T_{β,γ} : x ↦ ⌊βx + γ⌋` by the map `U_{β,γ} : x ↦ ⌈βx + γ⌉`, where `(β − 1)x₀ + γ > 0`.

The corpus needs the **ceiling** map at `γ = 0` — `xₙ = ⌈βxₙ₋₁⌉`, the orbit of `RB.pisotOrbit`
and of [Dub09] §6 — so it is that variant which is transcribed below, with the side condition
`(β − 1)x₀ > 0` supplied by `1 < β` and `0 < x₀`.  Dubickas applies exactly this variant himself
on p. 245 to conclude that the word of `x ↦ ⌈px/q⌉` is not ultimately periodic.

## Why an axiom, and why now

**This reverses an explicit earlier decision, on purpose.**  In 2026-07 the corpus declined to
axiomatize [Dub09] Thm 2 even though policy allowed it (refereed, literature-proved), for one
reason: *its only consumer would have been a statement already proved* — aperiodicity at
`β = 3/2`, which `RB.not_eventually_periodic` obtains axiom-free by 2-adic descent ([AFS08]
Prop 26).  That reason has now expired.  `RB.Alg.not_isPRecursive_word_of_not_mem_U`
([B1E2b] WP5) is a *family* statement covering every algebraic `β ∉ U`, and there is no other
route to it in this corpus: the 2-adic descent is specific to rational bases (it is `RB.Gen`'s
business, [B1E2b] WP4), and nothing else in the literature gives the general-degree conclusion.

**Do not axiomatize the converse.**  "Pisot ⇒ the word is ultimately periodic" is *not* [Dub09]
Thm 2 and is not known in general; the quadratic case is proved in `RB.pisotWord_constant`
([Dub09] §6) and the general case is open ([B1E2b] WP12, shift-radix-system territory).

## The shape of the statement

The orbit enters as a hypothesis (`hrec : ∀ n, x (n + 1) = ⌈β * x n⌉`) rather than as a
definition, so the axiom is usable against any formalization of the ceiling orbit — in
particular against `RB.pisotOrbit`, for which `hrec` holds by `rfl`.

The minimal polynomial enters through `IsMinimalIntPoly`: a nonzero `P ∈ ℤ[X]` annihilating `β`
of least degree among all such.  This pins `P` down to a rational multiple of `minpoly ℚ β`, and
scaling `P` by a nonzero constant scales the word by the same constant, so it does not affect
ultimate periodicity — the extra generality over "primitive minimal polynomial" is vacuous.
Note `minpoly ℤ β` is *not* usable here: `β` need not be an algebraic integer (`β = 3/2` is the
motivating case), and `minpoly ℤ` is junk off `IsIntegral ℤ`.

## Contents

* `Dubickas.IsMinimalIntPoly` — a least-degree integer annihilator of `β`.
* `Dubickas.word` — `wₙ = ∑_{i≤d} bᵢ x_{n+i}`, the word of Theorems 1 and 2.
* **`Dubickas.periodic_imp_mem_U`** — the cited axiom ([Dub09] Thm 2, ceiling variant).

## References

* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J. **51**
  (2009), 243–252.  **Thm 2, p. 244**, with the `U_{β,γ}` remark on the same page.  (Local copy:
  `papers/dubickas-2009-glasgow.pdf`.)
* [Sch80] K. Schmidt. *On periodic expansions of Pisot numbers and Salem numbers.* Bull. LMS
  **12** (1980), 269–278.  (Same conclusion for `β`-expansions; [Dub09] p. 244 notes the
  agreement.)
* [Ber92] M.-J. Bertin et al. *Pisot and Salem numbers.* Birkhäuser 1992.  (Def 5.1 `U`;
  `Bertin.U_eq_S_union_T` is the "Pisot or Salem" form of the conclusion.)
* [B1E2b] `plans/plan-B1E2b.html` (2026-07-28): WP5, risk R2 (this reversal).
-/

namespace Dubickas

open Polynomial

/-- `P` is a **minimal integer polynomial** of `β`: a nonzero `P ∈ ℤ[X]` with `P(β) = 0` of least
degree among all nonzero integer polynomials annihilating `β`.

Such a `P` is a rational multiple of `minpoly ℚ β`, and is unique up to sign once it is primitive.
Unlike `minpoly ℤ β` this makes sense for algebraic `β` that are not algebraic integers, which is
the case of interest (`β = p/q`). -/
@[category API, AMS 11 12, ref "Dub09", group "dubickas_thm2"]
def IsMinimalIntPoly (P : Polynomial ℤ) (β : ℝ) : Prop :=
  P ≠ 0 ∧ aeval β P = 0 ∧
    ∀ Q : Polynomial ℤ, Q ≠ 0 → aeval β Q = 0 → P.natDegree ≤ Q.natDegree

/-- The **Dubickas word** `wₙ = b_d x_{n+d} + ⋯ + b_0 xₙ` of an integer sequence `x` against the
coefficients `bᵢ = P.coeff i` ([Dub09] Thms 1 and 2). -/
@[category API, AMS 11 68, ref "Dub09", group "dubickas_thm2"]
def word (P : Polynomial ℤ) (x : ℕ → ℤ) (n : ℕ) : ℤ :=
  ∑ i ∈ Finset.range (P.natDegree + 1), P.coeff i * x (n + i)

/-- **[Dub09] Theorem 2** (ceiling variant, p. 244): if the word of the ceiling orbit
`xₙ = ⌈βxₙ₋₁⌉` against the minimal integer polynomial of an algebraic `β > 1` is ultimately
periodic, then `β ∈ Bertin.U`, i.e. `β` is a Pisot or a Salem number
(`Bertin.U_eq_S_union_T`).

Recorded as a cited `axiom` on the authority of [Dub09] (refereed; Glasgow Math. J.).  See the
module doc for the transcription of the source statement, for why the ceiling variant is the
right one to cite, and for why this reverses an earlier decision not to axiomatize it. -/
@[category research solved, AMS 11 68 12, ref "Dub09" "Sch80", group "dubickas_thm2"]
axiom periodic_imp_mem_U {β : ℝ} (hβ : 1 < β) {x : ℕ → ℤ} (hx₀ : 0 < x 0)
    (hrec : ∀ n, x (n + 1) = ⌈β * x n⌉) {P : Polynomial ℤ} (hP : IsMinimalIntPoly P β)
    (hper : ∃ N p, 0 < p ∧ ∀ n, N ≤ n → word P x (n + p) = word P x n) :
    β ∈ Bertin.U

end Dubickas
