/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import TH.Solenoid.Haar
import ForMathlib.Dynamics.KolmogorovSinai
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# `×2, ×3` rigidity on the solenoid `Σ₆`, in decomposition form (Rudolph; Einsiedler–Lindenstrauss)

The one cited axiom of the plan-A1+ bridge lane: every `σ₂, σ₃`-invariant probability measure on
`Σ₆` splits as `c · Haar + (1 - c) · ν₀` with `ν₀` of zero `σ₂`-entropy, and the Haar mass `c` is
**linear in the entropy**, `c = h_μ(σ₂) / log 2`.

## The source statement (gate G1, pinned 2026-08-02)

* **[Rud90] Thm 4.9, p. 405.**  For `p, q ≥ 2` coprime, a measure on `𝕋` invariant under `×p` and
  `×q` and **ergodic for the semigroup they generate** is either Lebesgue or has zero entropy for
  both maps.  (Ergodicity is joint, not per-map: abstract p. 395, §3 p. 399.  `h_μ(T) = h_μ(T, P)`
  is Lemma 3.5, p. 399.)
* **[EL03] Thm 1.1, p. 99.**  *"Let `α` be a totally irreducible, not virtually-cyclic `ℤ^d`-action
  by automorphisms of a solenoid `X`.  Let `μ` be an `α`-ergodic measure.  Then either `μ = λ` is
  the Haar measure of `X`, or the entropy `h_μ(α^n) = 0` vanishes for all `n ∈ ℤ^d`."*
* **[EL03] p. 100**, the paragraph after Thm 1.2, states the corollary shape used here: *"every
  positive entropy measure is a convex combination of the Lebesgue measure and a zero entropy
  measure."*

**The side conditions hold for this action** (checked in gate G1; `Σ₆` is a solenoid in [EL03]'s
sense because `Σ̂₆ = ℤ[1/6] ⊂ ℚ`, and it is connected because that dual is torsion-free):

* *irreducible* — a closed `α`-invariant `Y ⊆ Σ₆` has annihilator `H ≤ ℤ[1/6]` stable under
  `×2^{±1}, ×3^{±1}`, hence a `ℤ[1/6]`-submodule `h·ℤ[1/6]`, hence of finite index, so `Y` is
  finite;
* *totally irreducible* — for `Λ ⊇ N ℤ²` the multipliers contain `2^{±N}, 3^{±N}`, which generate
  the ring `ℤ[1/6]`, so the same argument runs;
* *not virtually cyclic* — `(a, b) ↦ 2^a 3^b` is injective with rank-2 image on every finite-index
  `Λ`, while `{α^{k n}}` has rank `≤ 1`.

Total non-symplecticity is **not** required: [EL03] p. 100 records TNS (and an extra ergodicity
assumption) as Katok–Spatzier's hypotheses, which Thm 1.1 exists to remove, and p. 99 adds
"we do not assume any hyperbolicity in Theorem 1.1".  The group/semigroup distinction is
load-bearing: the image of `{0} × ℤ₂ × ℤ₃` in `Σ₆` is a proper infinite closed subgroup with
`σ₂(K) ⊊ K`, i.e. `ℕ²`-invariant but *not* `ℤ²`-invariant, so irreducibility holds only because
[EL03]'s actions are by automorphisms.

[EL03] is an ERA *announcement* (full proofs announced as its [5], p. 108).  For this particular
`X` the dependency is avoidable: `Σ₆ = lim← (𝕋, ×6)` is the invertible extension of the `ℕ²`-action
generated by `×2, ×3` ([EW11] Exercise 8.1.3(1), p. 235), under which invariant measures,
ergodicity and entropy correspond — so [Rud90] Thm 4.9, a complete published proof, transfers.
Both keys are carried.

## What the axiom folds in (three standard steps, none of them formalized here)

1. **Ergodic decomposition of the `ℤ²`-action** — [EW11] Thm 8.20, pp. 266–267 (continuous actions
   of `σ`-compact metric *groups*; it covers `ℤ² ↷ Σ₆` and not the `ℕ²`-semigroup on `𝕋`).
2. **Affinity of entropy** (Jacobs) over that decomposition, `h_μ(σ₂) = ∫ h_{μ_x}(σ₂)`, for a
   decomposition into `σ₂`-*invariant* — not `σ₂`-ergodic — components.  Standard, but stated in
   none of the four G1 sources.  `ForMathlib/Dynamics/KolmogorovSinai.lean` proves no affinity
   lemma, so this cannot currently be discharged.
3. **`h_Haar(σ₂) = log 2`** — [LW88], `h(α) = ∑_v log⁺|α|_v`.  This is *not* a consequence of the
   decomposition below (see `CITED/LindWard.lean`, which carries it, and the proof there that the
   decomposition alone is consistent with `h_Haar(σ₂) = 0`).

## What is deliberately **not** axiomatized

Nothing about the *orbit*.  The axiom speaks only about measures invariant under both `σ₂` and
`σ₃`; the open inputs of the bridge (`TH.S6.TransverseRecovery`, `TH.S6.EntropyProduction`) are
`def`s in `TH/Solenoid/Bridge.lean`, never axioms — house precedent `RB.EAll`.

## References

* [Rud90] D. J. Rudolph, "×2 and ×3 invariant measures and entropy", *Ergodic Theory Dynam.
  Systems* **10** (1990), 395–406.
* [EL03] M. Einsiedler & E. Lindenstrauss, "Rigidity properties of `ℤ^d`-actions on tori and
  solenoids", *Electron. Res. Announc. Amer. Math. Soc.* **9** (2003), 99–110.
* [EW11] M. Einsiedler & T. Ward, *Ergodic Theory with a View Towards Number Theory*, GTM 259,
  Springer 2011, Ch. 8.
* Plan A1+ §4 L7 and the gate-G1 verdict box.
-/

namespace EL

open MeasureTheory TH.S6

/-- **Rudolph–Einsiedler–Lindenstrauss rigidity, decomposition form** ([Rud90] Thm 4.9 p. 405;
[EL03] Thm 1.1 p. 99 and the corollary shape p. 100).

Every `σ₂`- and `σ₃`-invariant probability measure on `Σ₆` is a convex combination
`μ = c · Haar + (1 - c) · ν₀` of Haar measure and a `σ₂, σ₃`-invariant measure of zero
`σ₂`-entropy, and the mass of the Haar component is linear in the entropy:
`h_μ(σ₂) = c · log 2`, i.e. `c = h_μ(σ₂)/log 2`.

Recorded as a cited `axiom`.  Ergodic decomposition, affinity of entropy and the value
`h_Haar(σ₂) = log 2` are folded into the citation (module doc, items 1–3); no ergodicity
hypothesis appears, which is exactly what the fold buys. -/
@[category research solved, AMS 37 28 11, ref "Rud90" "EL03", group "el_rigidity"]
axiom rigidity_decomposition (μ : Measure S6) [IsProbabilityMeasure μ]
    (h2 : Measure.map σ2 μ = μ) (h3 : Measure.map σ3 μ = μ) :
    ∃ (c : ℝ) (ν₀ : Measure S6), IsProbabilityMeasure ν₀ ∧ 0 ≤ c ∧ c ≤ 1 ∧
      Measure.map σ2 ν₀ = ν₀ ∧ Measure.map σ3 ν₀ = ν₀ ∧
      μ = ENNReal.ofReal c • haar + ENNReal.ofReal (1 - c) • ν₀ ∧
      kolmogorovSinai σ2 ν₀ = 0 ∧
      kolmogorovSinai σ2 μ = ENNReal.ofReal (c * Real.log 2)

end EL
