/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Z32.ModelEntropy
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# The three experiments opened by gate G-0 of `plans/plan-z32-transform.html`

`plans/note-z32transform-X.html` is the write-up; `Z32/xg0.py` regenerates every number in it
into `Z32/data/xg0_*.txt`.  This file is the part the kernel checks: three certificates, all
`decide`-checked, no `native_decide`, no cited axiom.

## X-238 — the two-cell family, and the `1/5` ceiling that was not one

`Z32/BlockCert.lean` carries `Z32.two_cell_fifth_empty`: no `ξ ≠ 0` has `‖ξ(3/2)ⁿ‖ < 1/5` for
every `n`.  Gate G-0 found that this is behind print — [Dub06JNT], quoted as Theorem 3.14 of
Bugeaud's Cambridge Tract 193, gives every `ξ ≠ 0` a limit point of `(‖ξ(3/2)ⁿ‖)` at least
`0.238117…` — and the engine was reported as failing already at `c = 0.21`.

That report was an artifact of the *default* certificate search, which merges the surviving
components into interval hulls.  The **rank-stratified** search — the same `funcOk` relaxation
that `Z32.dubickas_2008_cor_1_2` needs — certifies `c = 0.21` at funnel depth **1**, and climbs
to `c = 0.238` at depth 7.  `Z32.two_cell_238_empty` is that entry, and it supersedes
`Z32.two_cell_fifth_empty`.

The mechanism is exact and is a statement about the interval model, not about the search: the
two-cell hold set acquires its periodic orbits one at a time, at

| orbit | period | enters `‖·‖ < c` at |
| --- | --- | --- |
| `{0}` | 1 | `0` |
| `{1/5, 4/5}` | 2 | `1/5 = 0.2` |
| `{2/13, 3/13, 10/13, 11/13}` | 4 | `3/13 = 0.230769…` |
| `{14,17,21,23,74,76,80,83}/97` | 8 | `23/97 = 0.237113…` |
| one orbit, denominator `3¹⁶−2¹⁶` | 16 | `10233015/42981185 = 0.238081…` |
| two orbits, denominator `3¹²−2¹²` | 12 | `25115/105469 = 0.238126…` |

— a period-doubling cascade — and the funnel a certificate needs grows with the orbit count
(depth 1 with two orbits, 7 with four, 15 with five).  Measured, the ceiling of the search lies
in `(0.2381175, 0.2381177]`, and the printed constant `0.238117…` lies in `[0.238117, 0.238118)`:
the two brackets **overlap**, so print is not beaten, but the gap G-0 priced at `0.038` is
`2·10⁻⁶`.  Whether the two numbers coincide is an open question about [Dub06JNT]'s proof.

## X-D19 — [Dub19] Theorem 1.2, missed by one grid unit

Dubickas proves `Z_{3/2}(8/57, 805/1539) = ∅`, a window of length `31/81 = 0.38271…`.  The engine
refuses it at every depth to 61, in both modes, and the reason is a single point: the **left
endpoint** `8/57` satisfies `(3·8/57)/2 = 4/19`, so it is a preimage of the 3-cycle
`4/19 → 6/19 → 9/19` — the very cycle that the corpus's own `Z32.ZSet_three_two_sixth_3_8` is
built around.  Its backward orbit inside the window is infinite, the component count is exactly
`k+1` at every depth `k`, and no finite rank stratification exists.

Move that endpoint by **one unit of `1/1539`** and the certificate appears at depth 11 with three
blocks: `Z32.ZSet_three_two_d19_shift`, length `196/513 = 0.38206…`.  Shrinking the *right*
endpoint instead changes nothing at all, at any value tested.  So the printed theorem is sharp at
its left end by construction, and that sharpness — not the length — is what this certificate class
cannot pay for.

## X-KP — Mahler's conjecture is out of reach of this family, provably

[KP18] Corollary 18 reduces Mahler's problem to the emptiness of `U = [0,1/6) ∪ [1/3,2/3)`, of
total length only `1/2`.  The hold set of that union is

`H = [0, 1/15) ∪ [1/3, 2/5) ∪ [5/9, 3/5)`, of measure `8/45`,

which is **exactly invariant** (a finite check: `prune(H, H) = H`), so no depth ever empties it,
and whose transition graph has characteristic polynomial `x(x² - x - 1)`: the golden-mean shift.
Its periodic points of period dividing `n` are the Lucas numbers `1, 3, 4, 7, 11, 18, 29, …`, so
the hold set carries **infinitely many periodic orbits** — and Theorem B of `Z32/README.md`
milestone M7 then forbids every block certificate for it, archimedean or product, at every level.

`Z32.horseKP` is the quantitative form: twenty-one words of length eight on `K = [0, 399/6305]`,
so `φ_model ≥ (log 21)/8 = 0.38063…`, against the true `log((1+√5)/2) = 0.48121…`.  Through
`Z32.not_cert_and_horse` it also gives the no-go directly for unstratified certificates.
-/

namespace Z32.BlockCert

/-- **X-238.**  The rank-stratified certificate for `‖·‖ < 0.238`, i.e. for
`[0, 119/500) ∪ [381/500, 1)`: funnel depth 7, 84 blocks in 18 rank strata, over
`D = 1000·3⁷`.  Generated by `Z32/gencert.py --ranked 1000 0 238 762 1000`. -/
def certTwoCell238 : Cert where
  D := 2187000
  U := [(0, 520506), (1666494, 2187000)]
  levels := [
    [(0, 347004), (381996, 520506), (1666494, 1805004), (1839996, 2187000)],
    [(0, 231336), (254664, 347004), (381996, 474336), (497664, 520506), (1666494, 1689336), (1712664, 1805004), (1839996, 1932336), (1955664, 2187000)],
    [(0, 154224), (169776, 231336), (254664, 316224), (331776, 347004), (381996, 397224), (412776, 474336), (497664, 520506), (1666494, 1689336), (1712664, 1774224), (1789776, 1805004), (1839996, 1855224), (1870776, 1932336), (1955664, 2017224), (2032776, 2187000)],
    [(0, 102816), (113184, 154224), (169776, 210816), (221184, 231336), (254664, 264816), (275184, 316224), (331776, 347004), (381996, 397224), (412776, 453816), (464184, 474336), (497664, 507816), (518184, 520506), (1666494, 1668816), (1679184, 1689336), (1712664, 1722816), (1733184, 1774224), (1789776, 1805004), (1839996, 1855224), (1870776, 1911816), (1922184, 1932336), (1955664, 1965816), (1976184, 2017224), (2032776, 2073816), (2084184, 2187000)],
    [(0, 68544), (75456, 102816), (113184, 140544), (147456, 154224), (169776, 176544), (183456, 210816), (221184, 231336), (254664, 264816), (275184, 302544), (309456, 316224), (331776, 338544), (345456, 347004), (381996, 383544), (390456, 397224), (412776, 419544), (426456, 453816), (464184, 474336), (497664, 507816), (518184, 520506), (1666494, 1668816), (1679184, 1689336), (1712664, 1722816), (1733184, 1760544), (1767456, 1774224), (1789776, 1796544), (1803456, 1805004), (1839996, 1841544), (1848456, 1855224), (1870776, 1877544), (1884456, 1911816), (1922184, 1932336), (1955664, 1965816), (1976184, 2003544), (2010456, 2017224), (2032776, 2039544), (2046456, 2073816), (2084184, 2111544), (2118456, 2187000)],
    [(0, 45696), (50304, 68544), (75456, 93696), (98304, 102816), (113184, 117696), (122304, 140544), (147456, 154224), (169776, 176544), (183456, 201696), (206304, 210816), (221184, 225696), (230304, 231336), (254664, 255696), (260304, 264816), (275184, 279696), (284304, 302544), (309456, 316224), (331776, 338544), (345456, 347004), (381996, 383544), (390456, 397224), (412776, 419544), (426456, 444696), (449304, 453816), (464184, 468696), (473304, 474336), (497664, 498696), (503304, 507816), (518184, 520506), (1666494, 1668816), (1679184, 1683696), (1688304, 1689336), (1712664, 1713696), (1718304, 1722816), (1733184, 1737696), (1742304, 1760544), (1767456, 1774224), (1789776, 1796544), (1803456, 1805004), (1839996, 1841544), (1848456, 1855224), (1870776, 1877544), (1884456, 1902696), (1907304, 1911816), (1922184, 1926696), (1931304, 1932336), (1955664, 1956696), (1961304, 1965816), (1976184, 1980696), (1985304, 2003544), (2010456, 2017224), (2032776, 2039544), (2046456, 2064696), (2069304, 2073816), (2084184, 2088696), (2093304, 2111544), (2118456, 2136696), (2141304, 2187000)],
    [(0, 30464), (33536, 45696), (50304, 62464), (65536, 68544), (75456, 78464), (81536, 93696), (98304, 102816), (113184, 117696), (122304, 134464), (137536, 140544), (147456, 150464), (153536, 154224), (169776, 170464), (173536, 176544), (183456, 186464), (189536, 201696), (206304, 210816), (221184, 225696), (230304, 231336), (254664, 255696), (260304, 264816), (275184, 279696), (284304, 296464), (299536, 302544), (309456, 312464), (315536, 316224), (331776, 332464), (335536, 338544), (345456, 347004), (381996, 383544), (390456, 393464), (396536, 397224), (412776, 413464), (416536, 419544), (426456, 429464), (432536, 444696), (449304, 453816), (464184, 468696), (473304, 474336), (497664, 498696), (503304, 507816), (518184, 520506), (1666494, 1668816), (1679184, 1683696), (1688304, 1689336), (1712664, 1713696), (1718304, 1722816), (1733184, 1737696), (1742304, 1754464), (1757536, 1760544), (1767456, 1770464), (1773536, 1774224), (1789776, 1790464), (1793536, 1796544), (1803456, 1805004), (1839996, 1841544), (1848456, 1851464), (1854536, 1855224), (1870776, 1871464), (1874536, 1877544), (1884456, 1887464), (1890536, 1902696), (1907304, 1911816), (1922184, 1926696), (1931304, 1932336), (1955664, 1956696), (1961304, 1965816), (1976184, 1980696), (1985304, 1997464), (2000536, 2003544), (2010456, 2013464), (2016536, 2017224), (2032776, 2033464), (2036536, 2039544), (2046456, 2049464), (2052536, 2064696), (2069304, 2073816), (2084184, 2088696), (2093304, 2105464), (2108536, 2111544), (2118456, 2121464), (2124536, 2136696), (2141304, 2153464), (2156536, 2187000)]]
  strata := [
    [(315536, 316224), (381996, 383544), (473304, 474336), (518184, 520506), (1666494, 1668816), (1712664, 1713696), (1803456, 1805004), (1870776, 1871464)],
    [(254664, 255696), (345456, 347004), (412776, 413464), (1773536, 1774224), (1839996, 1841544), (1931304, 1932336)],
    [(169776, 170464), (230304, 231336), (497664, 498696), (1688304, 1689336), (1955664, 1956696), (2016536, 2017224)],
    [(153536, 154224), (331776, 332464), (396536, 397224), (1789776, 1790464), (1854536, 1855224), (2032776, 2033464)],
    [(335536, 338544), (503304, 507816), (1679184, 1683696), (1848456, 1851464)],
    [(221184, 225696), (390456, 393464), (1793536, 1796544), (1961304, 1965816)],
    [(147456, 150464), (260304, 264816), (464184, 468696), (1718304, 1722816), (1922184, 1926696), (2036536, 2039544)],
    [(98304, 102816), (173536, 176544), (309456, 312464), (416536, 419544), (1767456, 1770464), (1874536, 1877544), (2010456, 2013464), (2084184, 2088696)],
    [(65536, 68544), (113184, 117696), (206304, 210816), (275184, 279696), (449304, 453816), (1733184, 1737696), (1907304, 1911816), (1976184, 1980696), (2069304, 2073816), (2118456, 2121464)],
    [(75456, 78464), (137536, 140544), (183456, 186464), (299536, 302544), (426456, 429464), (1757536, 1760544), (1884456, 1887464), (2000536, 2003544), (2046456, 2049464), (2108536, 2111544)],
    [(432536, 444696), (1742304, 1754464)],
    [(284304, 296464), (1890536, 1902696)],
    [(189536, 201696), (1985304, 1997464)],
    [(122304, 134464), (2052536, 2064696)],
    [(81536, 93696), (2093304, 2105464)],
    [(50304, 62464), (2124536, 2136696)],
    [(33536, 45696), (2141304, 2153464)],
    [(0, 30464), (2156536, 2187000)]]

@[category API, AMS 11 37, ref "Dub09AA" "Dub10", group "z32_block_cert"]
theorem certTwoCell238_ok : certTwoCell238.ok = true := by decide

/-- **X-D19.**  [Dub19] Theorem 1.2's window with its left endpoint moved by one unit of
`1/1539`: `[217/1539, 805/1539)`, length `196/513 = 0.38206…`.  Funnel depth 11, three blocks,
out-degree one — no rank stratification needed.  Generated by `Z32/gencert.py 1539 217 805`. -/
def certD19Shift : Cert where
  D := 272629233
  U := [(38440899, 142603335)]
  levels := [
    [(38440899, 95068890), (116503677, 142603335)],
    [(38440899, 63379260), (77669118, 95068890), (116503677, 142603335)],
    [(38440899, 42252840), (51779412, 63379260), (77669118, 95068890), (116503677, 133129251)],
    [(38440899, 42252840), (51779412, 63379260), (77669118, 88752834), (116503677, 119044971), (125396019, 133129251)],
    [(38440899, 42252840), (51779412, 59168556), (77669118, 79363314), (83597346, 88752834), (116503677, 119044971), (125396019, 133129251)],
    [(38440899, 39445704), (51779412, 52908876), (55731564, 59168556), (77669118, 79363314), (83597346, 88752834), (116503677, 119044971), (125396019, 130322115)],
    [(38440899, 39445704), (51779412, 52908876), (55731564, 59168556), (77669118, 79363314), (83597346, 86881410), (116503677, 117173547), (125396019, 126148995), (128030787, 130322115)],
    [(38440899, 39445704), (51779412, 52908876), (55731564, 57920940), (77669118, 78115698), (83597346, 84099330), (85353858, 86881410), (116503677, 117173547), (125396019, 126148995), (128030787, 130322115)],
    [(38440899, 38613960), (51779412, 52077132), (55731564, 56066220), (56902572, 57920940), (77669118, 78115698), (83597346, 84099330), (85353858, 86881410), (116503677, 117173547), (125396019, 126148995), (128030787, 129490371)],
    [(38440899, 38613960), (51779412, 52077132), (55731564, 56066220), (56902572, 57920940), (77669118, 78115698), (83597346, 84099330), (85353858, 86326914), (116503677, 116619051), (125396019, 125594499), (128030787, 128253891), (128811459, 129490371)],
    [(38440899, 57551276), (77669118, 86326914), (116503677, 129490371)]]

@[category API, AMS 11 37, ref "Dub19" "Dub09AA", group "z32_block_cert"]
theorem certD19Shift_ok : certD19Shift.ok = true := by decide

end Z32.BlockCert

namespace Z32

open Z32.BlockCert

/-- **X-KP.**  A horseshoe for [KP18] Corollary 18's union `[0,1/6) ∪ [1/3,2/3)`: twenty-one
words of length eight on `K = [0, 399/6305]`.  The word count at length `L` is the Fibonacci
number `F_{L-1}` (2, 3, 5, 8, 13, 21 at `L = 3…8`), so the certified rate `log N / L` climbs to
`log((1+√5)/2)`, the entropy of the golden-mean shift the hold set actually carries. -/
def horseKP : Horse where
  D := 37830
  U := [(0, 6305), (12610, 25220)]
  A := 0
  B := 2394
  words := [[-1, 1, 0, 1, 0, 1, 1, 0], [-1, 1, 0, 1, 1, -1, 1, 1], [-1, 1, 0, 1, 1, 0, 0, 0],
    [-1, 1, 1, -1, 1, 0, 1, 1], [-1, 1, 1, -1, 1, 1, 0, 0], [-1, 1, 1, 0, -1, 1, 1, 0],
    [-1, 1, 1, 0, 0, -1, 1, 1], [-1, 1, 1, 0, 0, 0, 0, 0], [0, -1, 1, 0, 1, 0, 1, 1],
    [0, -1, 1, 0, 1, 1, 0, 0], [0, -1, 1, 1, -1, 1, 1, 0], [0, -1, 1, 1, 0, -1, 1, 1],
    [0, -1, 1, 1, 0, 0, 0, 0], [0, 0, -1, 1, 0, 1, 1, 0], [0, 0, -1, 1, 1, -1, 1, 1],
    [0, 0, -1, 1, 1, 0, 0, 0], [0, 0, 0, -1, 1, 0, 1, 1], [0, 0, 0, -1, 1, 1, 0, 0],
    [0, 0, 0, 0, -1, 1, 1, 0], [0, 0, 0, 0, 0, -1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0]]

@[category API, AMS 11 37, ref "KP18" "Mah68", group "z32_phi_model"]
theorem horseKP_ok : horseKP.ok = true := by decide

@[category API, AMS 11 37, ref "KP18", group "z32_phi_model"]
theorem horseKP_uSet :
    horseKP.uSet = Set.Ico (0 : ℝ) (1 / 6) ∪ Set.Ico (1 / 3 : ℝ) (2 / 3) := by
  ext y
  constructor
  · rintro ⟨I, hI, h1, h2⟩
    simp only [horseKP, List.mem_cons, List.not_mem_nil, or_false] at hI
    rcases hI with rfl | rfl
    · simp only [horseKP, rleR] at h1 h2
      push_cast at h1 h2
      exact Or.inl ⟨by linarith, by linarith⟩
    · simp only [horseKP, rleR] at h1 h2
      push_cast at h1 h2
      exact Or.inr ⟨by linarith, by linarith⟩
  · rintro (⟨h1, h2⟩ | ⟨h1, h2⟩)
    · refine ⟨(0, 6305), by simp [horseKP], ?_, ?_⟩
      · simp only [horseKP]; push_cast; linarith
      · simp only [horseKP, rleR]; push_cast; linarith
    · refine ⟨(12610, 25220), by simp [horseKP], ?_, ?_⟩
      · simp only [horseKP]; push_cast; linarith
      · simp only [horseKP, rleR]; push_cast; linarith

/-- **The set to which [KP18] Corollary 18 reduces Mahler's problem carries model entropy at
least `(log 21)/8 = 0.38063…`.**  Its hold set is the golden-mean shift, of entropy
`log((1+√5)/2) = 0.48121…`, so this is `79 %` of the truth; what matters is that it is positive.
By `Z32.not_cert_and_horse` no block certificate with `strata = []` exists for this union, and by
Theorem B of `Z32/README.md` §M7 — the hold set carries Lucas-many periodic points, hence
infinitely many periodic orbits — none exists with a stratification either, at any product level.
So **no certificate of this family can prove Mahler's conjecture**, and the obstruction is not a
budget. -/
@[category research solved, AMS 11 37, ref "KP18" "Mah68" "Dub09AA", group "z32_phi_model"]
theorem log_twentyone_div_eight_le_phiModel_kp :
    Real.log 21 / 8 ≤ phiModel 3 2 (Set.Ico (0 : ℝ) (1 / 6) ∪ Set.Ico (1 / 3 : ℝ) (2 / 3)) := by
  have h := Horse.le_phiModel horseKP_ok
  rw [horseKP_uSet] at h
  refine le_trans (le_of_eq ?_) h
  have hw : ((horseKP.words.length : ℕ) : ℝ) = 21 := by norm_num [horseKP]
  have hl : ((horseKP.len : ℕ) : ℝ) = 8 := by norm_num [horseKP, Horse.len]
  rw [hw, hl]

/-- **X-D19, positive half.**  `Z_{3/2}(217/1539, 196/513) = ∅`: no `ξ > 0` has every
`{ξ(3/2)ⁿ}` in `[217/1539, 805/1539)`, a window of length `196/513 = 0.382066…`.

That window is [Dub19] Theorem 1.2's `[8/57, 805/1539)` with the left endpoint moved by **one
unit of `1/1539`**, and the shift is not cosmetic: `8/57` is a preimage of the cycle point `4/19`,
so the printed window drags an infinite backward orbit that no finite funnel absorbs.  See this
file's header.  Length `0.38207` is past `Z32.ZSet_three_two_sixth_3_8` (`0.375`) and below the
engine frontier `Z32.ZSet_three_two_frontier` (`0.40722`). -/
@[category research solved, AMS 11 37, ref "Dub19" "Dub09AA", group "z32_block_cert"]
theorem ZSet_three_two_d19_shift : FLP.ZSet 3 2 (217 / 1539 : ℝ) (196 / 513) = ∅ := by
  refine ZSet_eq_empty_of_cert_base certD19Shift_ok rfl rfl fun y h1 h2 => ?_
  refine ⟨(38440899, 142603335), by simp [certD19Shift], ?_, ?_⟩ <;>
    simp only [certD19Shift, rleR] <;> push_cast <;> linarith

/-- **X-238.**  No `ξ ≠ 0` has every `{ξ(3/2)ⁿ}` in `[0, 119/500) ∪ [381/500, 1)`, i.e. no
`ξ ≠ 0` has `‖ξ(3/2)ⁿ‖ < 0.238` for every `n`.  This **supersedes `Z32.two_cell_fifth_empty`**
(the same statement at `1/5 = 0.2`), and closes all but `1.7·10⁻⁵` of the gap to the printed
`0.238117…` of [Dub06JNT] (Bugeaud, Cambridge Tract 193, Theorem 3.14). -/
@[category research solved, AMS 11 37, ref "Dub06JNT" "Dub09AA" "Dub10", group "z32_block_cert"]
theorem two_cell_238_empty {ξ : ℝ} (hξ : ξ ≠ 0) :
    ¬ ∀ n : ℕ, Int.fract (ξ * ((3 : ℝ) / 2) ^ n) ∈
      Set.Ico (0 : ℝ) (119 / 500) ∪ Set.Ico (381 / 500 : ℝ) 1 := by
  intro h
  refine not_confined_base certTwoCell238_ok (3 / 2) (by norm_num [certTwoCell238]) hξ
    fun n => ?_
  rcases h n with ⟨h1, h2⟩ | ⟨h1, h2⟩
  · refine ⟨(0, 520506), by simp [certTwoCell238], ?_, ?_⟩ <;>
      simp only [certTwoCell238, rleR] <;> push_cast <;> linarith
  · refine ⟨(1666494, 2187000), by simp [certTwoCell238], ?_, ?_⟩ <;>
      simp only [certTwoCell238, rleR] <;> push_cast <;> linarith

/-- **The eventual form** of `Z32.two_cell_238_empty`. -/
@[category research solved, AMS 11 37, ref "Dub06JNT" "Dub09AA" "Dub10", group "z32_block_cert"]
theorem not_eventually_two_cell_238 {ξ : ℝ} (hξ : ξ ≠ 0) {N : ℕ} :
    ¬ ∀ n : ℕ, N ≤ n → Int.fract (ξ * ((3 : ℝ) / 2) ^ n) ∈
      Set.Ico (0 : ℝ) (119 / 500) ∪ Set.Ico (381 / 500 : ℝ) 1 := by
  intro h
  refine Cert.not_eventually_confined certTwoCell238_ok hξ (N := N) fun n hn => ?_
  have hb : ((certTwoCell238.p : ℝ) / certTwoCell238.q) = 3 / 2 := by
    norm_num [certTwoCell238]
  rw [hb]
  rcases h n hn with ⟨h1, h2⟩ | ⟨h1, h2⟩
  · refine ⟨(0, 520506), by simp [certTwoCell238], ?_, ?_⟩ <;>
      simp only [certTwoCell238, rleR] <;> push_cast <;> linarith
  · refine ⟨(1666494, 2187000), by simp [certTwoCell238], ?_, ?_⟩ <;>
      simp only [certTwoCell238, rleR] <;> push_cast <;> linarith

/-- **`‖ξ(3/2)ⁿ‖ ≥ 0.238` infinitely often, for every `ξ ≠ 0`.**  The nearest-integer form of
`Z32.two_cell_238_empty`, and the strengthening of `Z32.not_forall_abs_sub_round_lt_fifth` that
experiment X-238 produced. -/
@[category research solved, AMS 11 37, ref "Dub06JNT" "Dub09AA" "Dub10", group "z32_block_cert"]
theorem not_forall_abs_sub_round_lt_238 {ξ : ℝ} (hξ : ξ ≠ 0) {N : ℕ} :
    ¬ ∀ n : ℕ, N ≤ n → |ξ * ((3 : ℝ) / 2) ^ n - round (ξ * ((3 : ℝ) / 2) ^ n)| < 119 / 500 := by
  intro h
  refine not_eventually_two_cell_238 hξ (N := N) fun n hnN => ?_
  have hn := h n hnN
  rw [abs_sub_round_eq_min, min_lt_iff] at hn
  have h0 := Int.fract_nonneg (ξ * ((3 : ℝ) / 2) ^ n)
  have h1 := Int.fract_lt_one (ξ * ((3 : ℝ) / 2) ^ n)
  simp only [Set.mem_union, Set.mem_Ico]
  rcases hn with h2 | h2
  · exact Or.inl ⟨h0, h2⟩
  · exact Or.inr ⟨by linarith, h1⟩

end Z32
