/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import TH.RepetitionIdentity
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Set.Card
import Mathlib.Order.Interval.Finset.Nat
import Mathlib.Data.Int.Interval
import Mathlib.Tactic.Push

/-!
# T0.1: the elementary complexity floor `p_T(k) ≳ (41/24)·k` (M4/A3 Stage 0)

Stage 0 of the M4/A3 program, part 3 ([M4A3] §3.3).  The **subword complexity**
`p_T(k)` counts the distinct length-`k` factors of the steering word.  The growth
ceiling of `TH.RepetitionIdentity` (`2^(k+c+1) ≤ 3^(c+1)`) says two equal factors
must sit `≳ k/log₂(3/2)` apart, so the first `≈ 1.7095·k` windows are pairwise
distinct — strictly above the universal Morse–Hedlund floor `k + 1`.

House-style integer certificate: `3^41 ≤ 2^65` (checked by `norm_num`; this encodes
`log₂ 3 ≤ 65/41`, giving the rational slope `41/24 = 1.7083… < 1/log₂(3/2) =
1.7095…`).  The final statement is pure arithmetic:

  `41·k ≤ 24·p_T(k) + 72`      (`factor_complexity_lower`, **T0.1**)

**T0.4 (parity-word partial, honesty boundary)**: the parity word `b` is the
letter-to-letter image of `T`, so `p_b ≤ p_T` and T0.1 says nothing about `p_b`.
What survives ([M4A3] §3.3): a `b`-repetition either propagates to a
`T`-repetition (then T0.1 applies), or the two windows first disagree at some step
`j` where the steering letters differ by an even nonzero amount
(`b_repetition_dichotomy`); while synchronized, the `ε`-difference expands by
exactly `3/2` per step (`eps_sub_of_sync`), and a maximal desynchronization
(`|Δt| = 4`) certifies `|ε_c − ε_a| ≥ (2/3)^(j+1)` (`desync_eps_lower`).  An
accidental `b`-repetition with immediate `|Δt| = 2` desynchronization carries no
constraint — this is the precise sense in which M4-for-`b` is strictly harder, and
no unconditional linear bound for `p_b` is claimed.

Novelty status (M-0 gate, resolved 2026-07-05): the linear bound with exactly the
constant `1/log₂(3/2)` is **Dubickas's** — [Dub09] Thm 3 proves
`liminf p_w(l)/l ≥ log q / log(p/q)` for the digit words of `⌈(p/q)·⌉`-orbits
(the AFS minimal words; restated as eq. (1.3) of [AEV]), and Cor 4/Thm 5 give the
conditional Collatz-word version.  Kopra (TCS **851** (2021), Thm 3.15/Ex. 3.16)
bounds the enveloping trace subshift: `P(k) = 4·3^k − 3·2^k`, the upper
environment for `p_T`.  Not previously stated for the nearest-integer steering
word of the orbit of 1 (for which only aperiodicity was on record); T0.1 here is
a transport of [Dub09] to that word — with a certified rational slope in place of
logarithms — plus, to our knowledge, its first formalization.

## Contents

* `TH.factor` — the length-`k` window at position `a`, as `Fin k → ℤ`;
  `factor_eq_iff` (windows agree ↔ repetition), `factorSet_finite`.
* `TH.complexity` — `p_T(k)`, the number of distinct length-`k` factors.
* `pow_cert` (`3^41 ≤ 2^65`), `repetition_linear_bound`
  (`41·k ≤ 24·c + 24` for a repetition at `2 ≤ a < c`).
* `factor_complexity_lower` — **T0.1**: `41·k ≤ 24·complexity k + 72`.
* `TH.IsBRepetition`, `eps_sub_of_sync`, `b_repetition_dichotomy`,
  `desync_eps_lower` — **T0.4**, the honest parity-word partials.

## References

* [M4A3] `plan-M4A3.html` (this repository, 2026-07): §3.3 (T0.1, T0.4), §10
  (M-0 verdicts).
* [Dub09] Dubickas. *On integer sequences generated by linear maps.* Glasgow
  Math. J. **51** (2009), 243–252. (Thm 3: the `1.7095·k` bound for minimal
  words; Cor 4/Thm 5: conditional Collatz-word version.)
* [AEV] Andrieu, Eliahou, Vivion. *A normality conjecture on rational base
  number systems.* arXiv:2510.11723. (Eq. (1.3); the surrounding normality
  program.)
-/

namespace TH

/-! ## Factors and complexity -/

/-- The length-`k` factor (window) of the steering word at position `a`. -/
@[category API, AMS 11 68, ref "M4A3", group "three_halves_m4"]
def factor (a k : ℕ) : Fin k → ℤ := fun i => t (a + i)

/-- Two windows agree iff they are a repetition. -/
@[category API, AMS 11 68, ref "M4A3", group "three_halves_m4"]
lemma factor_eq_iff {a c k : ℕ} : factor a k = factor c k ↔ IsRepetition a c k := by
  constructor
  · intro h i hik
    exact congrFun h ⟨i, hik⟩
  · intro h
    funext i
    exact h i i.isLt

/-- The set of length-`k` factors is finite (windows take values in `[-2, 2]`). -/
@[category API, AMS 11 68, ref "M4A3", group "three_halves_m4"]
lemma factorSet_finite (k : ℕ) : (Set.range fun a : ℕ => factor a k).Finite := by
  refine Set.Finite.subset
    (Set.Finite.pi' (t := fun _ : Fin k => Set.Icc (-2 : ℤ) 2)
      fun _ => Set.finite_Icc _ _) ?_
  rintro w ⟨a, rfl⟩
  exact fun i => Set.mem_Icc.mpr (abs_le.mp (t_abs_le _))

/-- `p_T(k)`: the subword complexity of the steering word — the number of distinct
length-`k` factors.  [M4A3] §2 (targets). -/
@[category API, AMS 11 68, ref "M4A3", group "three_halves_m4"]
noncomputable def complexity (k : ℕ) : ℕ :=
  (Set.range fun a : ℕ => factor a k).ncard

/-! ## T0.1 -/

/-- Integer certificate for `log₂ 3 ≤ 65/41` (house recipe: no reals, no logs). -/
@[category API, AMS 11 68, ref "M4A3", group "three_halves_m4"]
lemma pow_cert : (3 : ℕ) ^ 41 ≤ 2 ^ 65 := by norm_num

/-- A repetition at `2 ≤ a < c` of length `k` forces `41·k ≤ 24·c + 24`: equal
windows are linearly far apart, with certified rational slope `24/41 > log₂(3/2)`. -/
@[category research solved, AMS 11 68, ref "M4A3", group "three_halves_m4"]
theorem repetition_linear_bound {a c k : ℕ} (ha : 2 ≤ a) (hac : a < c)
    (h : IsRepetition a c k) : 41 * k ≤ 24 * c + 24 := by
  have h1 := repetition_pow_le_nat ha hac h
  have h2 : (2 : ℕ) ^ ((k + c + 1) * 41) ≤ 3 ^ ((c + 1) * 41) := by
    rw [pow_mul, pow_mul]
    exact Nat.pow_le_pow_left h1 41
  have h3 : (3 : ℕ) ^ ((c + 1) * 41) ≤ 2 ^ ((c + 1) * 65) := by
    rw [show (c + 1) * 41 = 41 * (c + 1) by ring,
      show (c + 1) * 65 = 65 * (c + 1) by ring, pow_mul, pow_mul]
    exact Nat.pow_le_pow_left pow_cert (c + 1)
  have h5 : (k + c + 1) * 41 ≤ (c + 1) * 65 :=
    (Nat.pow_le_pow_iff_right (by norm_num : 1 < 2)).mp (le_trans h2 h3)
  omega

/-- **T0.1 (complexity floor)** ([M4A3] §3.3): `41·k ≤ 24·p_T(k) + 72`, i.e.
`p_T(k) ≥ (41/24)·k − 3 ≈ 1.708·k` — strictly above the Morse–Hedlund floor
`k + 1`.  (The true constant of the method is `1/log₂(3/2) ≈ 1.7095`; `41/24` is
the certified rational slope.) -/
@[category research solved, AMS 11 68, ref "M4A3", group "three_halves_m4"]
theorem factor_complexity_lower (k : ℕ) : 41 * k ≤ 24 * complexity k + 72 := by
  rcases Nat.lt_or_ge k 2 with hk | hk
  · omega
  · set C : ℕ := (41 * k - 25) / 24 with hC
    have hCk : 24 * C + 24 < 41 * k := by omega
    have hC2 : 2 ≤ C := by omega
    have hinj : Set.InjOn (fun a => factor a k) ↑(Finset.Icc 2 C) := by
      intro x hx y hy hxy
      simp only [Finset.coe_Icc, Set.mem_Icc] at hx hy
      by_contra hne
      rcases Nat.lt_or_ge x y with hlt | hge
      · have hb := repetition_linear_bound hx.1 hlt (factor_eq_iff.mp hxy)
        omega
      · have hlt : y < x := by omega
        have hb := repetition_linear_bound hy.1 hlt (factor_eq_iff.mp hxy.symm)
        omega
    have himg : ((Finset.Icc 2 C).image fun a => factor a k).card = C - 1 := by
      rw [Finset.card_image_of_injOn hinj, Nat.card_Icc]
      omega
    have hsub : ((Finset.Icc 2 C).image fun a => factor a k)
        ⊆ (factorSet_finite k).toFinset := by
      intro w hw
      rw [Set.Finite.mem_toFinset]
      obtain ⟨x, _, rfl⟩ := Finset.mem_image.mp hw
      exact ⟨x, rfl⟩
    have hcard := Finset.card_le_card hsub
    have hncard : complexity k = (factorSet_finite k).toFinset.card :=
      Set.ncard_eq_toFinset_card _ (factorSet_finite k)
    omega

/-! ## T0.4: the parity-word partials (honesty boundary) -/

/-- A length-`k` repetition of the **parity** word at positions `a`, `c`. -/
@[category API, AMS 11 68, ref "M4A3", group "three_halves_m4"]
def IsBRepetition (a c k : ℕ) : Prop := ∀ i < k, b (a + i) = b (c + i)

/-- Every `T`-repetition reduces to a `b`-repetition (the converse fails —
that is the whole point of T0.4). -/
@[category API, AMS 11 68, ref "M4A3", group "three_halves_m4"]
lemma isBRepetition_of_isRepetition {a c k : ℕ} (h : IsRepetition a c k) :
    IsBRepetition a c k := fun i hik => by
  rw [b_eq_t_emod_two, b_eq_t_emod_two, h i hik]

/-- While two orbit windows are `t`-synchronized, their `ε`-difference expands by
exactly `3/2` per step: `ε_{c+j} − ε_{a+j} = (3/2)^j (ε_c − ε_a)`. -/
@[category research solved, AMS 11 68, ref "M4A3", group "three_halves_m4"]
lemma eps_sub_of_sync {a c : ℕ} :
    ∀ j, (∀ i < j, t (a + i) = t (c + i)) →
      eps (c + j) - eps (a + j) = (3 / 2 : ℚ) ^ j * (eps c - eps a) := by
  intro j
  induction j with
  | zero =>
    intro _
    simp
  | succ n ih =>
    intro h
    have hsync := ih fun i hi => h i (by omega)
    have hn : ((t (a + n) : ℚ)) = t (c + n) := by exact_mod_cast h n (by omega)
    rw [show c + (n + 1) = (c + n) + 1 from rfl,
      show a + (n + 1) = (a + n) + 1 from rfl, eps_succ, eps_succ]
    linear_combination (3 / 2 : ℚ) * hsync + (1 / 2 : ℚ) * hn

/-- **T0.4, dichotomy** ([M4A3] §3.3): a `b`-repetition either propagates to a
`T`-repetition (T0.1 applies), or the windows first desynchronize at a step `j`
where the steering letters differ by an even nonzero amount. -/
@[category research solved, AMS 11 68, ref "M4A3", group "three_halves_m4"]
theorem b_repetition_dichotomy {a c k : ℕ} (hb : IsBRepetition a c k) :
    IsRepetition a c k ∨
      ∃ j < k, (∀ i < j, t (a + i) = t (c + i)) ∧ t (a + j) ≠ t (c + j) ∧
        (t (c + j) - t (a + j)) % 2 = 0 := by
  by_cases h : IsRepetition a c k
  · exact Or.inl h
  · right
    have hex : ∃ i, i < k ∧ t (a + i) ≠ t (c + i) := by
      by_contra hall
      push Not at hall
      exact h fun i hik => hall i hik
    obtain ⟨i0, hi0k, hi0⟩ := hex
    have hexP : ∃ i, t (a + i) ≠ t (c + i) := ⟨i0, hi0⟩
    have hjP : t (a + Nat.find hexP) ≠ t (c + Nat.find hexP) := Nat.find_spec hexP
    have hjmin : ∀ i < Nat.find hexP, t (a + i) = t (c + i) := fun i hi =>
      not_not.mp (Nat.find_min hexP hi)
    have hjk : Nat.find hexP < k := by
      have hji : Nat.find hexP ≤ i0 := Nat.find_min' hexP hi0
      omega
    have hpar : (t (c + Nat.find hexP) - t (a + Nat.find hexP)) % 2 = 0 := by
      have h1 := t_emod_two (a + Nat.find hexP)
      have h2 := t_emod_two (c + Nat.find hexP)
      have h3 := hb (Nat.find hexP) hjk
      unfold b at h3
      omega
    exact ⟨Nat.find hexP, hjk, hjmin, hjP, hpar⟩

/-- **T0.4, quantitative branch** ([M4A3] §3.3): a maximal desynchronization
(`|Δt| = 4`) after `j` synchronized steps certifies that the starting points were
far apart: `|ε_c − ε_a| ≥ (2/3)^(j+1)`.  (The `|Δt| = 2` branch carries no such
constraint — an accidental `b`-repetition can desynchronize at zero cost, which is
why no unconditional `p_b` bound drops out.) -/
@[category research solved, AMS 11 68, ref "M4A3", group "three_halves_m4"]
theorem desync_eps_lower {a c j : ℕ} (hsync : ∀ i < j, t (a + i) = t (c + i))
    (hdesync : |t (c + j) - t (a + j)| = 4) :
    (2 / 3 : ℚ) ^ (j + 1) ≤ |eps c - eps a| := by
  have hd := eps_sub_of_sync j hsync
  have hΔ : ((t (c + j) : ℚ)) - t (a + j)
      = 3 * (eps (c + j) - eps (a + j)) - 2 * (eps (c + j + 1) - eps (a + j + 1)) := by
    rw [t_eq_eps (c + j), t_eq_eps (a + j)]
    ring
  have h4 : |(t (c + j) : ℚ) - (t (a + j) : ℚ)| = 4 := by exact_mod_cast hdesync
  have habs' := abs_eps_sub_lt_one (c + j + 1) (a + j + 1)
  set X := eps (c + j) - eps (a + j) with hX
  set Y := eps (c + j + 1) - eps (a + j + 1) with hY
  have htri : |3 * X - 2 * Y| ≤ |3 * X| + |2 * Y| := by
    calc |3 * X - 2 * Y| = |3 * X + -(2 * Y)| := by rw [sub_eq_add_neg]
      _ ≤ |3 * X| + |-(2 * Y)| := abs_add_le _ _
      _ = |3 * X| + |2 * Y| := by rw [abs_neg]
  have e3 : |(3 : ℚ) * X| = 3 * |X| := by
    rw [abs_mul]
    norm_num
  have e4 : |(2 : ℚ) * Y| = 2 * |Y| := by
    rw [abs_mul]
    norm_num
  have heq4 : |3 * X - 2 * Y| = 4 := by
    rw [← hΔ]
    exact h4
  have h5 : (4 : ℚ) ≤ 3 * |X| + 2 * |Y| := by
    rw [e3, e4] at htri
    linarith [htri, heq4.symm.le]
  have h6 : (2 / 3 : ℚ) < |X| := by linarith [habs']
  rw [hd, abs_mul, abs_of_nonneg (by positivity : (0 : ℚ) ≤ (3 / 2 : ℚ) ^ j)] at h6
  have hone : ((2 : ℚ) / 3) ^ j * ((3 : ℚ) / 2) ^ j = 1 := by
    rw [← mul_pow]
    norm_num
  have hpos : (0 : ℚ) ≤ ((2 : ℚ) / 3) ^ j := by positivity
  calc ((2 : ℚ) / 3) ^ (j + 1) = (2 / 3 : ℚ) ^ j * (2 / 3) := by rw [pow_succ]
    _ ≤ (2 / 3 : ℚ) ^ j * ((3 / 2 : ℚ) ^ j * |eps c - eps a|) :=
        mul_le_mul_of_nonneg_left h6.le hpos
    _ = (((2 : ℚ) / 3) ^ j * ((3 : ℚ) / 2) ^ j) * |eps c - eps a| := by ring
    _ = |eps c - eps a| := by rw [hone, one_mul]

end TH
