/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.NumberTheory.Real.Irrational
import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.Topology.Algebra.InfiniteSum.Basic
import CITED.AlloucheShallitBasic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Adamczewski–Bugeaud — Irrational automatic numbers are transcendental (AB07, Theorem 2)

Boris Adamczewski and Yann Bugeaud, *On the complexity of algebraic numbers I. Expansions in
integer bases*, Annals of Mathematics **165** (2007), 547–565.

This file records **Theorem 2** of that paper. The theorem has two equivalent phrasings:

> *Let `b ≥ 2` be an integer. The `b`-adic expansion of any irrational algebraic number cannot be
> generated by a finite automaton. In other words, **irrational automatic numbers are
> transcendental**.*

We formalise the second phrasing (`irrational_automatic_transcendental`): if the base-`b` digit
sequence of a real number `α ∈ [0,1)` is automatic (generated by a finite automaton) and `α` is
irrational, then `α` is transcendental over `ℚ`. This is the contrapositive of "an irrational
algebraic number has a non-automatic `b`-adic expansion", and is the special case of the
Loxton–van der Poorten conjecture that the paper settles. It follows in the paper from Theorem 1
(a lower bound on the complexity function) together with Cobham's theorem (`p(n) = O(n)` for an
automatic sequence). It is recorded here as a **cited `axiom`** on the authority of the literature;
the deep transcendence proof (via the Schmidt Subspace Theorem) is not reconstructed.

The **automatic sequence** notions (`AS.kKernel`, `AS.IsAutomatic`) used below are recorded in
`AS/Basic.lean` (Allouche–Shallit); recall that a sequence is *automatic* iff it is generated by a
deterministic finite automaton with output, equivalently its `k`-kernel is finite for some `k ≥ 2`.

## Notions

* **`b`-adic value** (`baseValue`). The real number `∑ₙ aₙ · b^{-(n+1)} ∈ [0,1)` whose base-`b`
  expansion is the digit sequence `a` (with `aₙ < b`). The paper's "automatic number" is exactly
  the value of an automatic digit sequence (cf. Becker's `∑ₖ uₖ b^{-k}`).

The irrationality hypothesis is essential: a rational number has an eventually periodic — hence
automatic — `b`-adic expansion, yet is not transcendental.

## Contents
* `baseValue` — the real number defined by a base-`b` digit sequence.
* **`irrational_automatic_transcendental`** — Theorem 2 (cited): irrational automatic ⇒ transcendental.

## References
* [AB07] Adamczewski, Boris, and Yann Bugeaud. *On the complexity of algebraic numbers I. Expansions
  in integer bases.* Annals of Mathematics 165 (2007), 547–565.
* [Eil74] Eilenberg, Samuel. *Automata, Languages, and Machines, Vol. A.* Academic Press, 1974
  (the finite-`k`-kernel characterization of `k`-automatic sequences).
* [Cob72] Cobham, Alan. *Uniform tag sequences.* Math. Systems Theory 6 (1972), 164–192.
-/

namespace AB

open AS

/-- The real number in `[0,1)` whose base-`b` expansion is the digit sequence `a` (digits `aₙ < b`):
`∑ₙ aₙ · b^{-(n+1)}`. This is the paper's notion of an "automatic number" when `a` is automatic. -/
@[category API, AMS 11, ref "AB07"]
noncomputable def baseValue (b : ℕ) (a : ℕ → ℕ) : ℝ :=
  ∑' n, (a n : ℝ) / (b : ℝ) ^ (n + 1)

/-- **Theorem 2 (Adamczewski–Bugeaud 2007).** *Irrational automatic numbers are transcendental.*

If `b ≥ 2`, `a` is a base-`b` digit sequence (`aₙ < b`) that is **automatic**, and the real number
`baseValue b a` it defines is **irrational**, then `baseValue b a` is **transcendental** over `ℚ`.
Equivalently: the `b`-adic expansion of an irrational algebraic number cannot be generated by a
finite automaton.

Recorded as a cited `axiom`: the proof in [AB07] derives this from their complexity lower bound
(Theorem 1) and Cobham's theorem, ultimately resting on the Schmidt Subspace Theorem. -/
@[category research solved, AMS 11 68, ref "AB07",
  group "ab_complexity_thm2"]
axiom irrational_automatic_transcendental
    (b : ℕ) (hb : 2 ≤ b) (a : ℕ → ℕ) (ha : ∀ n, a n < b)
    (hauto : IsAutomatic a) (hirr : Irrational (baseValue b a)) :
    Transcendental ℚ (baseValue b a)

end AB
