/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import AS.Basic
import Mathlib.NumberTheory.Padics.PadicNumbers
import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.Topology.Algebra.InfiniteSum.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Adamczewski–Bugeaud — Irrational automatic p-adic numbers are transcendental (AB07, Theorem 2B)

Boris Adamczewski and Yann Bugeaud, *On the complexity of algebraic numbers I. Expansions in
integer bases*, Annals of Mathematics **165** (2007), 547–565, **Section 6** ("Transcendence of
`p`-adic numbers").

This file records **Theorem 2B**, the `p`-adic counterpart of Theorem 2
([[ab-complexity-corpus-root]], `AB.irrational_automatic_transcendental`). The ambient field shifts
from `ℝ` to the field `ℚ_p` of `p`-adic numbers (`Padic p`, `p` prime). Every `α ∈ ℚ_p` has a
**Hensel expansion**

  `α = ∑_{k=-m}^{+∞} aₖ pᵏ`,    `aₖ ∈ {0, 1, …, p-1}`,

and the paper (Theorem 1B / Theorem 6) studies the complexity of the digit sequence `(aₖ)_{k≥-m}`.
Theorem 2B is the automata-theoretic shadow, parallel to Theorem 2:

> *Let `p` be a prime. The Hensel expansion of any irrational algebraic number in `ℚ_p` cannot be
> generated by a finite automaton. In other words, an **irrational automatic `p`-adic number is
> transcendental** (over `ℚ`).*

It is recorded as a **cited `axiom`** (`irrational_automatic_padic_transcendental`), on the authority
of the literature. The proof in [AB07, §6] mirrors the real case (Theorem 6, derived from their
`p`-adic transcendence criterion) but invokes a `p`-adic version of the Schmidt Subspace Theorem due
to Schlickewei [Sch77]; it is not reconstructed here.

## Notions

* **Hensel value** (`henselValue p m a`). The `p`-adic number `∑ₙ aₙ · p^{n-m} ∈ ℚ_p` of the digit
  sequence `a : ℕ → ℕ` reindexed from `k = -m`, i.e. `aₙ` is the digit of `pⁿ⁻ᵐ` (so `a 0` is the
  digit of `p⁻ᵐ`). Taking `m = 0` gives a `p`-adic *integer* (`ℤ_p`); a positive `m` accommodates the
  finite "fractional" tail of a general element of `ℚ_p`. The series converges in `ℚ_p`.
* **Automatic** (`IsAutomatic`, from `AB.ExpansionsInIntegerBases`). The digit sequence is generated
  by a finite automaton — the finite-`k`-kernel (Eilenberg) characterization; the same notion as in
  the real Theorem 2, since it is a property of the sequence `ℕ → ℕ` alone.
* **`p`-adic irrational** (`PadicIrrational`). `α ∈ ℚ_p` is irrational iff it is not the image of a
  rational, `α ∉ range (ℚ → ℚ_p)` — the exact `p`-adic analogue of `Irrational` on `ℝ`.

As over `ℝ`, the irrationality hypothesis is essential: the Hensel expansion of a rational is
eventually periodic, hence automatic, yet a rational is not transcendental.

## Contents
* `henselValue` — the `p`-adic number defined by a Hensel digit sequence.
* `PadicIrrational` — "not in `ℚ`", the `p`-adic analogue of `Irrational`.
* **`irrational_automatic_padic_transcendental`** — Theorem 2B (cited): irrational automatic ⇒
  transcendental, over `ℚ_p`.

## References
* [AB07] Adamczewski, Boris, and Yann Bugeaud. *On the complexity of algebraic numbers I. Expansions
  in integer bases.* Annals of Mathematics 165 (2007), 547–565 (Section 6).
* [Sch77] Schlickewei, Hans Peter. *The `p`-adic Thue–Siegel–Roth–Schmidt theorem.* Arch. Math.
  (Basel) 29 (1977), 267–270.
-/

namespace AB

open AS

variable (p : ℕ) [Fact p.Prime]

/-- The `p`-adic number with **Hensel expansion** `a`: `∑ₙ aₙ · p^{n-m} ∈ ℚ_p`, where the digit
`aₙ` (`< p`) sits at the power `pⁿ⁻ᵐ`. With `m = 0` this is a `p`-adic integer in `ℤ_p`; `m > 0`
allows the finite negative-power tail of a general `α ∈ ℚ_p`. -/
@[category API, AMS 11, ref "AB07"]
noncomputable def henselValue (m : ℕ) (a : ℕ → ℕ) : Padic p :=
  ∑' n, (a n : Padic p) * (p : Padic p) ^ ((n : ℤ) - m)

/-- A `p`-adic number is **irrational** iff it is not the image of a rational number — the `p`-adic
analogue of `Irrational` on `ℝ`. -/
@[category API, AMS 11, ref "AB07"]
def PadicIrrational (α : Padic p) : Prop := α ∉ Set.range ((↑) : ℚ → Padic p)

/-- **Theorem 2B (Adamczewski–Bugeaud 2007, §6).** *Irrational automatic `p`-adic numbers are
transcendental.*

If `p` is prime, `a` is a Hensel digit sequence (`aₙ < p`) that is **automatic**, and the `p`-adic
number `henselValue p m a` it defines is **irrational** (not in `ℚ`), then `henselValue p m a` is
**transcendental** over `ℚ`. Equivalently: the Hensel expansion of an irrational algebraic number in
`ℚ_p` cannot be generated by a finite automaton.

Recorded as a cited `axiom`: the proof in [AB07, §6] follows the real case (Theorem 6) but rests on
Schlickewei's `p`-adic Subspace Theorem [Sch77]. -/
@[category research solved, AMS 11 68, ref "AB07" "Sch77",
  group "ab_complexity_thm2b"]
axiom irrational_automatic_padic_transcendental
    (m : ℕ) (a : ℕ → ℕ) (ha : ∀ n, a n < p)
    (hauto : IsAutomatic a) (hirr : PadicIrrational p (henselValue p m a)) :
    Transcendental ℚ (henselValue p m a)

end AB
