/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Z32.ModelEntropy
import ForMathlib.Combinatorics.PathGrowth
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Exact entropy certificates for anchored windows: the type graph

`Z32/ModelEntropy.lean` measures the model system of the base `3/2` with
`φ_model(U)`, the growth rate of the carry language of the orbits confined to
`U`, and supplies its two extreme colours: block certificates giving
`φ_model = 0`, and horseshoes giving `φ_model > 0`.  This file fills the gap
between them for the **anchored windows** `U = [0, ℓ)` with `ℓ ≤ 1/2` — the
family Mahler's Z-numbers live at the top of (`ℓ = 1/2`, `Z32/FlattoCount.lean`)
— with two-sided enclosures sharp to eight decimals, and it does so with an
*exact* finite model, not an over-approximation.

## The type coordinate

For `ℓ ≤ 1/2` the carry of a confined model orbit is forced into `{0,1}`
(`TypeCert.carry_eq`), so the system is the greedy `3/2`-transformation
restricted to the window.  The cylinder of a carry word — the set of starting
points realising it — is an interval, and the *image* of that interval under the
composed map is an interval whose left endpoint is always `0`.  Hence a
cylinder's entire future is determined by a single rational number, the image's
right endpoint `t`; call it the cylinder's **type**.  Types transform by

`t --s--> min (ℓ, (3t − s)/2)`, kept exactly when the result is positive,

which is `TypeCert.child2` after clearing the common denominator `D`
(`t = a/D`, `ℓ = L/D`) and doubling, so that the whole transition is the
division-free integer identity `2 · child = min (2L) (3a − sD)`.

Two facts make this a *finite exact* model rather than an approximation.

* **Exactness.**  The length-`k` words of the type graph are exactly the
  length-`k` carry words of the window: `card_modelLang_eq`.  Soundness
  (`exists_state_path`) is the forward inclusion; realizability
  (`exists_orbit_of_mem_words`) is the reverse, and is where the certificate
  earns its lower bounds.  There is no over-counting to fight, so the *same*
  finite graph carries both bounds.
* **Finiteness.**  For every rational `ℓ < 1/2` the reachable type set is
  finite — measured over the whole grid of `§ Measurements`, sizes `3…936`.
  Only `ℓ = 1/2` itself is infinite (there the types are Flatto's aperiodic
  `f^k 1 / 2`), and that case is exactly what `Z32/FlattoCount.lean` computes by
  hand.

On top of the graph sit the vector certificates of
`ForMathlib/Combinatorics/PathGrowth.lean`: a weight `v` and rationals `a/b`,
`a'/b'` with `b·(Mv) ≤ a·v` and `a'·v ≤ b'·(Mv)` entrywise in `ℕ`, giving
`log(a'/b') ≤ φ_model([0,ℓ)) ≤ log(a/b)`.  The graph is deterministic (source
and label determine the target — a corollary of the transition identity, not a
separate check), which is what makes the lower bound available at all.

## Main results

* `TypeCert`, `TypeCert.ok` — the certificate and its integer-only validity
  check; `decide`-checkable, no `native_decide`, no floating point, no rational
  arithmetic in the kernel.
* `TypeCert.card_modelLang_eq` — the exact identity
  `Nat.card (modelLang 3 2 [0,ℓ) k) = #(words (type graph) k)`.
* `TypeCert.phiModel_le`, `TypeCert.le_phiModel` — the two enclosures.
* `phiModel_band_mem_Icc` — the flagship: `φ_model([0, 5/12))` to eight
  decimals, `0.32228460… ∈ [log 1.38027756, log 1.38027757]`.  This supersedes
  the ledger entry `Z32.log_fourteen_div_ten_le_phiModel_band`
  (`(log 14)/10 = 0.2639…`) and is the first *upper* bound on that window.
* `phiModel_top_band_mem_Icc` — the same at `ℓ = 23/48 = 0.47916…`, a
  three-state certificate small enough to check by hand.  Five further windows
  are certified in `§ The entries`, giving a seven-row atlas across
  `[0.4, 0.48]`.

## Measurements (plan-B10 WP3)

Generated by `Z32/entcert.py`, re-checked independently by
`Z32/verify_entcert.py` (full-interval cylinder enumeration, transition
identity, completeness, closure, both row inequalities, and the bracket against
an exact big-integer growth measurement at depth 400).  Data in
`Z32/data/b10_typecerts.txt`.

```
   ℓ        states  edges   φ_model([0,ℓ)) ∈
  2/5          22     25    [0.2872663486, 0.2872663561]
  13/32        10     12    [0.3059169641, 0.3059169715]
  5/12          4      5    [0.3222846094, 0.3222846166]   ← flagship
  7/16         11     13    [0.3361212036, 0.3361212107]
  9/20          8     10    [0.3556156551, 0.3556156621]
  11/24        42     52    [0.3659409308, 0.3659409377]
  23/48         3      4    [0.3822450846, 0.3822450914]
  47/96       280    327    [0.3938061121, 0.3938061188]
  63/128      111    133    [0.3968621082, 0.3968621149]
  127/256     164    198    [0.4012535519, 0.4012535586]
  255/512     836   1013    [0.4034056155, 0.4034056222]
  511/1024    936   1123    [0.4044426656, 0.4044426723]
  1/2           ∞      —     0.4054651081 = log(3/2), exactly (FlattoCount)
```

The column is monotone and converges to `log(3/2)` — an independent check of
`Z32.Flatto.phiModel_zCell` from the other side of the window family.

**G-Budget (the plan's gate).**  Kernel `decide` on `TypeCert.ok`, measured on
this machine at `LEAN_NUM_THREADS=3`:

```
   ℓ         states  edges  D digits   term    decide     (before the
                                                           row-Nodup fix)
   23/48        3      4        3      0.6 kB   0.01 s
   5/12         4      5        2      0.6 kB   0.06 s
   9/20         8     10        4      0.8 kB   0.03 s
   7/16        11     13        5      1.0 kB   0.07 s
   13/32       10     12        5      1.0 kB   0.10 s
   2/5         22     25        8      1.7 kB   0.30 s
   11/24       42     52       14      4.0 kB   1.1  s
   63/128     111    133       36       18 kB    23  s        44 s
   127/256    164    198       52       35 kB   414  s
```

(Wall time of `lake env lean` on a one-`decide` file, minus the `1.51 s` import
baseline.  All seven shipped entries together cost under `2 s`.)

The gate **passes for the sizes the atlas needs**, but three things the plan
assumed are wrong, and the first one was worth `20 s` of the largest
certificate:

* *A global `Nodup` on the edge list is not what soundness consumes.*  The
  `List.sum_toFinset` step needs each **row** to be duplicate-free, and a row
  has at most two entries.  Checking `ed.Nodup` instead costs `#edges²`
  comparisons of `36`-digit triples — measured `20 s` at `133` edges, against
  `≈ 0` for the per-row check that replaced it (`okWeights`).  This is a general
  lesson for the certificate discipline, not a local one: *check the hypothesis
  the proof uses, not a convenient global strengthening of it.*
* *The cost is not the state count.*  Deep type chains push the common
  denominator up by a factor of `2` per link, so `D` carries `≈ 0.3 · #states`
  decimal digits and the certificate term is quadratic in the state count.
  Worse, the measured time is not a clean power of the state count — the
  exponent rises from `≈ 3` between `42` and `111` states to `≈ 7` between `111`
  and `164`.
* *The envelope is `≈ 110` states, not the `1000` the plan budgeted*, with a
  cliff immediately after it (`164` states already costs seven minutes).  The
  `47/96`, `255/512` and `511/1024` certificates are generated and
  independently verified, but are not shipped as Lean terms.

None of this costs coverage, because type-set size is wildly non-monotone in `ℓ`
(`23/48 ↦ 3`, `11/24 ↦ 42`, `47/96 ↦ 280`): a grid chosen by *certificate size*
rather than by uniform steps in `ℓ` covers the band densely and cheaply, which
is how the seven entries below were picked.

## What is *not* claimed

* Nothing here is about genuine Z-numbers.  `φ_model` is the entropy of the
  **model**, which forgets that a real orbit is `ξ(3/2)ⁿ` for one `ξ`; the model
  has positive entropy on windows where the genuine problem may well have no
  orbits at all.  The whole point of `Z32/BlockCert.lean` is that the gap
  between the two is where the theorems live.
* No dimension statement.  These are counting exponents for the model language.
* The finiteness of the type set is verified per certificate by the kernel (the
  certificate *is* the finite graph); the empirical regularity "finite for every
  rational `ℓ < 1/2`" is a measurement, not a theorem here, and is not used.

## Plan corrections recorded (for plan-B10 WP7)

1. **§4 D1 and the whole upper-certificate design are replaced.**  The planned
   upper certificate — a block graph on a rational partition with the
   `Z32.BlockCert.hits` edge test — is sound but quantitatively vacuous, and
   mesh refinement does not repair it.  The image of a mesh cell is `1.5` cells
   wide, so it meets `2` of them at *every* mesh, and the over-count compounds
   geometrically.  Measured `λ` for `[0,ℓ)` on a uniform mesh of `N` cells:

   ```
     ℓ \ N      8       16      32      64      128     256     512
     2/5      1.895   1.734   1.679   1.810   1.753   1.779   1.798
     5/12     1.981   1.823   1.866   1.930   1.942   1.930   1.916
     11/24    2.095   1.913   2.021   1.992   2.011   1.999   2.010
     1/2      2.000   2.000   2.000   2.000   2.000   2.000   2.000
   ```

   Every entry exceeds `3/2`, so every such certificate is *worse than free*:
   monotonicity of `φ_model` in `U` plus `Z32.Flatto.phiModel_zCell` already
   give `φ_model([0,ℓ)) ≤ log(3/2)` for all `ℓ ≤ 1/2` with no certificate at
   all.  The `ℓ = 1/2` row is exactly `2` at every `N` because a uniform mesh is
   self-similar under a piecewise-linear map of slope `3/2`: refinement is not a
   small improvement, it is no improvement.  The replacement is this file.
2. **§4 D1's "at the Z-cell they pinch `log(3/2)`" is false** for one-step
   interval graphs, and the type graph does not pinch there either — `ℓ = 1/2`
   is the one member of the family with an infinite type set.  The pinch that
   does happen is the *column* above converging to `log(3/2)` from below as
   `ℓ ↑ 1/2`, which is a statement about the window family, not about mesh
   refinement.
3. **§7 G-Budget is re-scored**: passes for the atlas, with the envelope
   (`≈ 110` states, not `1000`) and the cost model corrected as in
   `§ Measurements`, and with the plan's own fallback list amended — the fix
   that mattered was not "coarser partitions" but dropping a global `Nodup`
   check the soundness proof never needed.
4. **§5's `Z32/entcert.c` is not needed.**  Every quantity is exact integer or
   `Fraction` arithmetic on graphs of `≤ 10³` states; the Python generator runs
   the whole grid in seconds.  No C was written, and no floating point enters
   the emitted certificates (the weights are exact integer power-iterates
   `M^k 1`, and the ratios are the exact Collatz–Wielandt extrema, rounded
   outwards to eight decimals for readability).
5. **§6 WP4's grid must be chosen by type-set size**, not by uniform steps in
   `ℓ`; see `§ Measurements`.
6. **The lower bound needed no horseshoe.**  The plan routed `T-B10.3`'s lower
   side through `Z32.Horse` "upgraded to the quantitative form".  Realizability
   on the type graph is elementary — prepend one branch to a shorter orbit,
   `exists_orbit_of_mem_words` — and the zero orbit at `y = 0` supplies the
   infinite tail, so no fixed-point or intermediate-value argument appears
   anywhere in this file.

## References

* L. Flatto, *Z-numbers and β-transformations*, Contemp. Math. **135** (1992),
  181–201 — the type/renewal structure at `ℓ = 1/2`.
* A. Dubickas, *Arithmetical properties of powers of algebraic numbers*, Bull.
  LMS **38** (2006) [Dub09AA in this corpus] — the model and its windows.
* W. Parry, *On the β-expansions of real numbers*, Acta Math. Hungar. **11**
  (1960) — admissibility, of which the type graph is the finite shadow here.
* `plans/plan-B10.html` §2 (F1, F2), §4 (D1, D2), §6 (WP3), §7 (G-Budget).
* `Z32/FlattoCount.lean` (the `ℓ = 1/2` endpoint), `Z32/ModelEntropy.lean`
  (`φ_model`, the two extreme colours), `Z32/entcert.py`,
  `Z32/verify_entcert.py`, `Z32/data/b10_typecerts.txt`.
-/

namespace Z32.EntropyCert

open Filter Topology

/-! ## The certificate -/

/-- Twice the child of the scaled type `a` under the carry `s`: the type
recursion `t ↦ min (ℓ, (3t − s)/2)` scaled by `D` and doubled, so that no
division reaches the kernel.  The child is *live* exactly when this is positive.
-/
def child2 (D L a s : ℤ) : ℤ := min (2 * L) (3 * a - s * D)

/-- A **type certificate** for the anchored window `[0, L/D)` at the base `3/2`:
the common denominator, the window, the states with their weights, the labelled
edges, and the two certified ratios `a/b` (upper) and `a'/b'` (lower). -/
structure TypeCert where
  /-- The common denominator of the window and every state. -/
  D : ℤ
  /-- The window is `[0, L/D)`; `ok` checks `0 < 2L ≤ D`, i.e. `ℓ ≤ 1/2`. -/
  L : ℤ
  /-- The states — scaled cylinder-image right endpoints — with their weights. -/
  st : List (ℤ × ℕ)
  /-- The edges `(source, carry, target)`. -/
  ed : List (ℤ × ℤ × ℤ)
  /-- Numerator of the certified upper ratio. -/
  a : ℕ
  /-- Denominator of the certified upper ratio. -/
  b : ℕ
  /-- Numerator of the certified lower ratio. -/
  a' : ℕ
  /-- Denominator of the certified lower ratio. -/
  b' : ℕ
  /-- Lower bound for the weights; `ok` checks `0 < m`. -/
  m : ℕ
  /-- Upper bound for the weights. -/
  M : ℕ

namespace TypeCert

variable (c : TypeCert)

/-- The state values. -/
def states : List ℤ := c.st.map Prod.fst

/-- The weight of a state, defaulting to `m` off the state list — the shape the
*upper* certificate needs, where the weight must be bounded below by `m > 0`
everywhere. -/
def wt (x : ℤ) : ℕ := (c.st.lookup x).getD c.m

/-- The weight of a state, defaulting to `0` off the state list — the shape the
*lower* certificate needs, where a state with no outgoing edges must be allowed
to carry no weight. -/
def wt0 (x : ℤ) : ℕ := (c.st.lookup x).getD 0

/-- The edges out of `x`, as a list. -/
def outL (x : ℤ) : List (ℤ × ℤ × ℤ) := c.ed.filter fun e => decide (e.1 = x)

/-- The edge set, as the labelled digraph of `PathGrowth`. -/
def E : Finset (ℤ × ℤ × ℤ) := c.ed.toFinset

/-- The window the certificate speaks about. -/
def window : Set ℝ := Set.Ico 0 ((c.L : ℝ) / (c.D : ℝ))

/-- Base checks: a positive denominator, a window inside `[0,1/2]`, a listed
root, usable weight bounds and ratios, and no repeated edge. -/
def okBase : Bool :=
  decide (0 < c.D) && decide (0 < c.L) && decide (2 * c.L ≤ c.D) &&
    decide (c.L ∈ c.states) && decide (0 < c.m) && decide (c.m ≤ c.M) &&
    decide (0 < c.b) && decide (c.b ≤ c.a) && decide (0 < c.b') && decide (c.b' ≤ c.a')

/-- Every state is a live type inside the window, with an in-range weight. -/
def okStates : Bool :=
  c.st.all fun x =>
    decide (0 < x.1) && decide (x.1 ≤ c.L) && decide (c.m ≤ x.2) && decide (x.2 ≤ c.M)

/-- Every listed edge is a true transition between listed states, carrying one of
the two forced carries.  The alphabet clause is not decoration: an edge labelled
`−5` can satisfy the transition identity (the `min` is then attained by `2L`),
and it would inflate the word count with a transition no orbit can perform,
breaking the lower bound. -/
def okEdges : Bool :=
  c.ed.all fun e =>
    decide (e.1 ∈ c.states) && decide (e.2.2 ∈ c.states) && decide (0 < e.2.2) &&
      decide (e.2.1 = 0 ∨ e.2.1 = 1) &&
      decide (2 * e.2.2 = child2 c.D c.L e.1 e.2.1)

/-- Every true transition is listed: for each state and each of the two possible
carries, either the child is dead or an edge carries it.  With `okEdges` this
pins the graph down to *the* type graph. -/
def okTotal : Bool :=
  c.states.all fun x =>
    (decide (child2 c.D c.L x 0 ≤ 0) ||
      c.ed.any fun e => decide (e.1 = x) && decide (e.2.1 = 0)) &&
    (decide (child2 c.D c.L x 1 ≤ 0) ||
      c.ed.any fun e => decide (e.1 = x) && decide (e.2.1 = 1))

/-- The two vector inequalities, entrywise in `ℕ`, together with the only
duplication constraint the development needs: within one row the labels are
distinct.  A global `Nodup` on the edge list would do as well and is what the
first version checked, but it costs `#edges²` comparisons of big integers —
measured at `20 s` for `133` edges, half the total budget of the largest
certificate — whereas this costs `#edges` per state and is what
`List.sum_toFinset` actually consumes. -/
def okWeights : Bool :=
  c.states.all fun x =>
    decide (((c.outL x).map fun e => e.2.1).Nodup) &&
    decide (c.b * ((c.outL x).map fun e => c.wt e.2.2).sum ≤ c.a * c.wt x) &&
      decide (c.a' * c.wt0 x ≤ c.b' * ((c.outL x).map fun e => c.wt0 e.2.2).sum)

/-- The certificate is valid.  Every clause is a decidable statement about
integers, so `decide` checks it in the kernel. -/
def ok : Bool := c.okBase && c.okStates && c.okEdges && c.okTotal && c.okWeights

end TypeCert

/-! ## Unpacking `ok` -/

namespace TypeCert

variable {c : TypeCert}

private theorem of_mem_lookup {l : List (ℤ × ℕ)} {x : ℤ} {v : ℕ}
    (h : l.lookup x = some v) : (x, v) ∈ l := by
  induction l with
  | nil => simp [List.lookup] at h
  | cons p t ih =>
    rcases p with ⟨u, w⟩
    by_cases hx : x == u
    · have hux : x = u := by simpa using hx
      simp only [List.lookup, hx, Option.some.injEq] at h
      subst hux; subst h; exact List.mem_cons_self ..
    · simp only [List.lookup, hx] at h
      exact List.mem_cons_of_mem _ (ih h)

/-- Everything `okBase` certifies, unpacked once. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem base_parts (h : c.ok = true) :
    0 < c.D ∧ 0 < c.L ∧ 2 * c.L ≤ c.D ∧ c.L ∈ c.states ∧ 0 < c.m ∧ c.m ≤ c.M ∧
      0 < c.b ∧ c.b ≤ c.a ∧ 0 < c.b' ∧ c.b' ≤ c.a' := by
  simp only [ok, okBase, Bool.and_eq_true, decide_eq_true_eq] at h
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> tauto

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem D_pos (h : c.ok = true) : 0 < c.D := (base_parts h).1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem L_pos (h : c.ok = true) : 0 < c.L := (base_parts h).2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem two_L_le_D (h : c.ok = true) : 2 * c.L ≤ c.D := (base_parts h).2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem L_mem (h : c.ok = true) : c.L ∈ c.states := (base_parts h).2.2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem m_pos (h : c.ok = true) : 0 < c.m := (base_parts h).2.2.2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem m_le_M (h : c.ok = true) : c.m ≤ c.M := (base_parts h).2.2.2.2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem b_pos (h : c.ok = true) : 0 < c.b := (base_parts h).2.2.2.2.2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem b_le_a (h : c.ok = true) : c.b ≤ c.a := (base_parts h).2.2.2.2.2.2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem b'_pos (h : c.ok = true) : 0 < c.b' := (base_parts h).2.2.2.2.2.2.2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem b'_le_a' (h : c.ok = true) : c.b' ≤ c.a' := (base_parts h).2.2.2.2.2.2.2.2.2



@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem state_parts (h : c.ok = true) {p : ℤ × ℕ} (hp : p ∈ c.st) :
    0 < p.1 ∧ p.1 ≤ c.L ∧ c.m ≤ p.2 ∧ p.2 ≤ c.M := by
  simp only [ok, okStates, Bool.and_eq_true, List.all_eq_true, decide_eq_true_eq] at h
  have := h.1.1.1.2 p hp
  exact ⟨this.1.1.1, this.1.1.2, this.1.2, this.2⟩

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem edge_parts (h : c.ok = true) {e : ℤ × ℤ × ℤ} (he : e ∈ c.ed) :
    e.1 ∈ c.states ∧ e.2.2 ∈ c.states ∧ 0 < e.2.2 ∧ (e.2.1 = 0 ∨ e.2.1 = 1) ∧
      2 * e.2.2 = child2 c.D c.L e.1 e.2.1 := by
  simp only [ok, okEdges, Bool.and_eq_true, List.all_eq_true, decide_eq_true_eq] at h
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> have := h.1.1.2 e he <;> tauto

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem exists_edge (h : c.ok = true) {x s : ℤ} (hx : x ∈ c.states)
    (hs : s = 0 ∨ s = 1) (hlive : 0 < child2 c.D c.L x s) :
    ∃ w, (x, s, w) ∈ c.ed := by
  simp only [ok, okTotal, Bool.and_eq_true, List.all_eq_true, Bool.or_eq_true,
    decide_eq_true_eq, List.any_eq_true] at h
  have hall := h.1.2 x hx
  have hpick : ∃ e ∈ c.ed, e.1 = x ∧ e.2.1 = s := by
    rcases hs with rfl | rfl
    · rcases hall.1 with hdead | ⟨e, he, h1, h2⟩
      · exact absurd hlive (by omega)
      · exact ⟨e, he, h1, h2⟩
    · rcases hall.2 with hdead | ⟨e, he, h1, h2⟩
      · exact absurd hlive (by omega)
      · exact ⟨e, he, h1, h2⟩
  obtain ⟨e, he, h1, h2⟩ := hpick
  refine ⟨e.2.2, ?_⟩
  obtain ⟨e1, e2, e3⟩ := e
  simp only at h1 h2
  subst h1; subst h2
  exact he

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem weight_parts (h : c.ok = true) {x : ℤ} (hx : x ∈ c.states) :
    ((c.outL x).map fun e => e.2.1).Nodup ∧
      c.b * ((c.outL x).map fun e => c.wt e.2.2).sum ≤ c.a * c.wt x ∧
      c.a' * c.wt0 x ≤ c.b' * ((c.outL x).map fun e => c.wt0 e.2.2).sum := by
  simp only [ok, okWeights, Bool.and_eq_true, List.all_eq_true, decide_eq_true_eq] at h
  refine ⟨?_, ?_, ?_⟩ <;> have := h.2 x hx <;> tauto

/-- Each row is duplicate-free: distinct entries carry distinct labels. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem outL_nodup (h : c.ok = true) {x : ℤ} (hx : x ∈ c.states) : (c.outL x).Nodup :=
  List.Nodup.of_map _ (weight_parts h hx).1

/-! ### The weight functions are globally bounded

`wt` defaults to `m` and `wt0` to `0`, so both are bounded by `M` everywhere and
`wt` is bounded below by `m` everywhere — which is what `PathGrowth` asks for,
since its certificates quantify over the whole state type. -/

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem m_le_wt (h : c.ok = true) (x : ℤ) : c.m ≤ c.wt x := by
  rcases hl : c.st.lookup x with _ | v
  · simp [wt, hl]
  · simpa [wt, hl] using (state_parts h (of_mem_lookup hl)).2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem wt_le_M (h : c.ok = true) (x : ℤ) : c.wt x ≤ c.M := by
  rcases hl : c.st.lookup x with _ | v
  · simpa [wt, hl] using m_le_M h
  · simpa [wt, hl] using (state_parts h (of_mem_lookup hl)).2.2.2

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem wt0_le_M (h : c.ok = true) (x : ℤ) : c.wt0 x ≤ c.M := by
  rcases hl : c.st.lookup x with _ | v
  · simp [wt0, hl]
  · simpa [wt0, hl] using (state_parts h (of_mem_lookup hl)).2.2.2

private theorem lookup_isSome {l : List (ℤ × ℕ)} {x : ℤ} (hx : x ∈ l.map Prod.fst) :
    ∃ v, l.lookup x = some v := by
  induction l with
  | nil => simp at hx
  | cons p t ih =>
    by_cases hxp : x == p.1
    · exact ⟨p.2, by simp [List.lookup, hxp]⟩
    · have hxt : x ∈ t.map Prod.fst := by
        simp only [List.map_cons, List.mem_cons] at hx
        rcases hx with rfl | h
        · exact absurd (by simp) hxp
        · exact h
      obtain ⟨v, hv⟩ := ih hxt
      exact ⟨v, by simp [List.lookup, hxp, hv]⟩

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem wt0_pos_of_mem (h : c.ok = true) {x : ℤ} (hx : x ∈ c.states) : 0 < c.wt0 x := by
  obtain ⟨v, hl⟩ := lookup_isSome (l := c.st) (x := x) hx
  simpa [wt0, hl] using lt_of_lt_of_le (m_pos h) (state_parts h (of_mem_lookup hl)).2.2.1

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem state_pos (h : c.ok = true) {u : ℤ} (hu : u ∈ c.states) : 0 < u ∧ u ≤ c.L := by
  obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hu
  exact ⟨(state_parts h hp).1, (state_parts h hp).2.1⟩

/-! ## The geometry: one step of the type recursion -/

/-- The window lies in `[0, 1/2]`, which is what forces the carry alphabet. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem window_le_half (h : c.ok = true) : (c.L : ℝ) / (c.D : ℝ) ≤ 1 / 2 := by
  have hD : (0 : ℝ) < c.D := by exact_mod_cast D_pos h
  have h2 : (2 : ℝ) * c.L ≤ (c.D : ℝ) := by exact_mod_cast two_L_le_D h
  rw [div_le_div_iff₀ hD (by norm_num)]
  linarith

/-- On a window inside `[0,1/2)` the carry of a model orbit is forced into
`{0,1}`: this is plan-B10 §2's **F1**, at the level of the certificate. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem carry_eq (h : c.ok = true) {y : ℕ → ℝ} {s : ℕ → ℤ}
    (horb : IsModelOrbit 3 2 c.window y s) (n : ℕ) : s n = 0 ∨ s n = 1 := by
  obtain ⟨hw, -, hrec⟩ := horb
  have hhalf := window_le_half h
  have h0 : (0 : ℝ) ≤ y n := (hw n).1
  have h0' : (0 : ℝ) ≤ y (n + 1) := (hw (n + 1)).1
  have h1 : y n < 1 / 2 := lt_of_lt_of_le (hw n).2 hhalf
  have h1' : y (n + 1) < 1 / 2 := lt_of_lt_of_le (hw (n + 1)).2 hhalf
  have hr : (2 : ℝ) * y (n + 1) = 3 * y n - (s n : ℝ) := by
    have := hrec n; push_cast at this ⊢; linarith
  have hlt : ((s n : ℤ) : ℝ) < 2 := by linarith
  have hgt : ((-1 : ℤ) : ℝ) < ((s n : ℤ) : ℝ) := by push_cast; linarith
  have h2 : s n < 2 := by exact_mod_cast hlt
  have h3 : (-1 : ℤ) < s n := by exact_mod_cast hgt
  omega

/-- **The type invariant, one step.**  If the orbit is below the state `u` and
the carry `s` leads to the state `w`, the next point is below `w`.  This is the
whole geometric content of the certificate: `w` is a `min`, and the two branches
of that `min` are exactly the two ways the next point is constrained — by the
window, and by the image of `[0, u/D)`. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem step_lt (h : c.ok = true) {u w s : ℤ} (hw : 2 * w = child2 c.D c.L u s)
    {y y' : ℝ} (hy : y < (u : ℝ) / (c.D : ℝ)) (hy' : y' < (c.L : ℝ) / (c.D : ℝ))
    (hrec : 2 * y' = 3 * y - (s : ℝ)) : y' < (w : ℝ) / (c.D : ℝ) := by
  have hD : (0 : ℝ) < c.D := by exact_mod_cast D_pos h
  have hyD : y * (c.D : ℝ) < (u : ℝ) := (lt_div_iff₀ hD).mp hy
  have hy'D : y' * (c.D : ℝ) < (c.L : ℝ) := (lt_div_iff₀ hD).mp hy'
  have hmin : ((2 * w : ℤ) : ℝ) = min ((2 * c.L : ℤ) : ℝ) ((3 * u - s * c.D : ℤ) : ℝ) := by
    rw [hw]; simp only [child2, Int.cast_min]
  refine (lt_div_iff₀ hD).mpr ?_
  have hlt : 2 * (y' * (c.D : ℝ)) < ((2 * w : ℤ) : ℝ) := by
    rw [hmin]
    refine lt_min (by push_cast; linarith) ?_
    push_cast
    nlinarith [hrec]
  push_cast at hlt
  linarith

/-! ## Soundness: a confined orbit walks the graph -/

/-- **The block path, for the type graph.**  Every model orbit confined to the
window follows a path of the certificate's graph, starting at the root, with the
orbit staying below the current state throughout. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem exists_state_path (h : c.ok = true) {y : ℕ → ℝ} {s : ℕ → ℤ}
    (horb : IsModelOrbit 3 2 c.window y s) :
    ∃ A : ℕ → ℤ, A 0 = c.L ∧ (∀ n, A n ∈ c.states) ∧
      (∀ n, y n < (A n : ℝ) / (c.D : ℝ)) ∧ ∀ n, (A n, s n, A (n + 1)) ∈ c.ed := by
  classical
  have hD : (0 : ℝ) < c.D := by exact_mod_cast D_pos h
  have hLpos : (0 : ℝ) < (c.L : ℝ) / (c.D : ℝ) :=
    div_pos (by exact_mod_cast L_pos h) hD
  set g : ℕ → ℤ → ℤ :=
    fun n u => if hex : ∃ w, (u, s n, w) ∈ c.ed then hex.choose else 0 with hgdef
  set A : ℕ → ℤ := fun n => Nat.rec c.L (fun k ih => g k ih) n with hAdef
  have hA0 : A 0 = c.L := rfl
  have hAs : ∀ n, A (n + 1) = g n (A n) := fun _ => rfl
  -- the child is live at every step, because the orbit continues
  have hlive : ∀ n, A n ∈ c.states → y n < (A n : ℝ) / (c.D : ℝ) →
      0 < child2 c.D c.L (A n) (s n) := by
    intro n hmem hlt
    obtain ⟨hw, -, hrec⟩ := horb
    have hr : (2 : ℝ) * y (n + 1) = 3 * y n - (s n : ℝ) := by
      have := hrec n; push_cast at this ⊢; linarith
    have hyD : y n * (c.D : ℝ) < ((A n : ℤ) : ℝ) := (lt_div_iff₀ hD).mp hlt
    have h0' : (0 : ℝ) ≤ y (n + 1) := (hw (n + 1)).1
    have h2 : ((s n * c.D : ℤ) : ℝ) < ((3 * A n : ℤ) : ℝ) := by
      push_cast
      nlinarith
    have h3 : s n * c.D < 3 * A n := by exact_mod_cast h2
    simp only [child2, lt_min_iff]
    exact ⟨by linarith [L_pos h], by omega⟩
  -- the invariant, by induction
  have inv : ∀ n, A n ∈ c.states ∧ y n < (A n : ℝ) / (c.D : ℝ) := by
    intro n
    induction n with
    | zero => exact ⟨hA0 ▸ L_mem h, hA0 ▸ (horb.1 0).2⟩
    | succ n ih =>
      have hex : ∃ w, (A n, s n, w) ∈ c.ed :=
        exists_edge h ih.1 (carry_eq h horb n) (hlive n ih.1 ih.2)
      have hpick : (A n, s n, A (n + 1)) ∈ c.ed := by
        rw [hAs n, hgdef]
        simp only [dite_eq_left hex]
        exact hex.choose_spec
      refine ⟨(edge_parts h hpick).2.1, step_lt h (edge_parts h hpick).2.2.2.2 ih.2
        (horb.1 (n + 1)).2 ?_⟩
      have := horb.2.2 n; push_cast at this ⊢; linarith
  refine ⟨A, hA0, fun n => (inv n).1, fun n => (inv n).2, fun n => ?_⟩
  have hex : ∃ w, (A n, s n, w) ∈ c.ed :=
    exists_edge h (inv n).1 (carry_eq h horb n) (hlive n (inv n).1 (inv n).2)
  rw [hAs n, hgdef]
  simp only [dite_eq_left hex]
  exact hex.choose_spec

/-! ## The bridge to `PathGrowth`

The graph is deterministic — not by a check, but because the transition identity
determines the target from the source and the label.  That is what makes the
lower vector certificate applicable, and hence the lower bound available. -/

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem mem_ed_of_mem_E {e : ℤ × ℤ × ℤ} (he : e ∈ c.E) : e ∈ c.ed :=
  List.mem_toFinset.mp he

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem mem_E_of_mem_ed {e : ℤ × ℤ × ℤ} (he : e ∈ c.ed) : e ∈ c.E :=
  List.mem_toFinset.mpr he

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem deterministic (h : c.ok = true) : PathGrowth.Deterministic c.E := by
  intro e he f hf h1 h2
  have p1 := (edge_parts h (mem_ed_of_mem_E he)).2.2.2.2
  have p2 := (edge_parts h (mem_ed_of_mem_E hf)).2.2.2.2
  rw [h1, h2] at p1
  omega

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem outEdges_eq (x : ℤ) : PathGrowth.outEdges c.E x = (c.outL x).toFinset := by
  ext e
  simp [PathGrowth.outEdges, E, outL]

/-- The row sum of `PathGrowth` is the list sum the certificate checks.  This is
where `ed.Nodup` is spent: the `Finset` dedups, the list does not. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem sum_outEdges (h : c.ok = true) (f : ℤ → ℕ) {x : ℤ} (hx : x ∈ c.states) :
    ∑ e ∈ PathGrowth.outEdges c.E x, f e.2.2 = ((c.outL x).map fun e => f e.2.2).sum := by
  rw [outEdges_eq]
  exact List.sum_toFinset _ (outL_nodup h hx)

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem outEdges_eq_empty (h : c.ok = true) {x : ℤ} (hx : x ∉ c.states) :
    PathGrowth.outEdges c.E x = ∅ := by
  refine Finset.eq_empty_of_forall_notMem fun e he => ?_
  simp only [PathGrowth.outEdges, Finset.mem_filter] at he
  exact hx (he.2 ▸ (edge_parts h (mem_ed_of_mem_E he.1)).1)

/-- The **upper** vector inequality, at every state of the ambient type `ℤ`:
off the state list there are no outgoing edges and `wt` is the constant `m`. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert_upper (h : c.ok = true) (x : ℤ) :
    c.b * ∑ e ∈ PathGrowth.outEdges c.E x, c.wt e.2.2 ≤ c.a * c.wt x := by
  by_cases hx : x ∈ c.states
  · rw [sum_outEdges h _ hx]; exact (weight_parts h hx).2.1
  · rw [outEdges_eq_empty h hx]; simp

/-- The **lower** vector inequality.  Here `wt0` vanishes off the state list,
which is exactly what makes the inequality `a' · 0 ≤ b' · 0` there. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert_lower (h : c.ok = true) (x : ℤ) :
    c.a' * c.wt0 x ≤ c.b' * ∑ e ∈ PathGrowth.outEdges c.E x, c.wt0 e.2.2 := by
  by_cases hx : x ∈ c.states
  · rw [sum_outEdges h _ hx]; exact (weight_parts h hx).2.2
  · have h0 : c.wt0 x = 0 := by
      rcases hl : c.st.lookup x with _ | v
      · simp [wt0, hl]
      · exact absurd (List.mem_map_of_mem (f := Prod.fst) (of_mem_lookup hl)) hx
    rw [outEdges_eq_empty h hx, h0]
    simp

/-! ## Exactness: the graph's words are the window's words -/

/-- A path realises its label word. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem word_mem_words {A : ℕ → ℤ} {s : ℕ → ℤ} (hpath : ∀ n, (A n, s n, A (n + 1)) ∈ c.ed) :
    ∀ (k n : ℕ), (List.ofFn fun i : Fin k => s (n + (i : ℕ))) ∈ PathGrowth.words c.E (A n) k := by
  intro k
  induction k with
  | zero => intro n; simp
  | succ k ih =>
    intro n
    rw [PathGrowth.words_succ, Finset.mem_biUnion]
    refine ⟨(A n, s n, A (n + 1)), ?_, ?_⟩
    · simp only [PathGrowth.outEdges, Finset.mem_filter]
      exact ⟨mem_E_of_mem_ed (hpath n), trivial⟩
    · refine Finset.mem_image.mpr
        ⟨List.ofFn fun i : Fin k => s (n + 1 + (i : ℕ)), ih (n + 1), ?_⟩
      rw [List.ofFn_succ]
      have htail : (fun i : Fin k => s (n + 1 + (i : ℕ)))
          = fun i : Fin k => s (n + ((i.succ : Fin (k + 1)) : ℕ)) := by
        funext i; congr 1; simp [Fin.val_succ]; omega
      simp [htail]

/-- **Realizability.**  Every word of the graph is the carry word of a genuine
confined model orbit.  The construction is one branch prepended to a shorter
orbit; the infinite tail is supplied by the fixed point `y ≡ 0`, which is
confined to every anchored window.  No fixed-point or intermediate-value
argument is needed anywhere. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem exists_orbit_of_mem_words (h : c.ok = true) :
    ∀ (k : ℕ) (u : ℤ), u ∈ c.states → ∀ w ∈ PathGrowth.words c.E u k,
      ∃ (y : ℕ → ℝ) (s : ℕ → ℤ), IsModelOrbit 3 2 c.window y s ∧
        y 0 < (u : ℝ) / (c.D : ℝ) ∧ w = List.ofFn fun i : Fin k => s (i : ℕ) := by
  have hD : (0 : ℝ) < c.D := by exact_mod_cast D_pos h
  have hLpos : (0 : ℝ) < (c.L : ℝ) / (c.D : ℝ) := div_pos (by exact_mod_cast L_pos h) hD
  have hhalf := window_le_half h
  intro k
  induction k with
  | zero =>
    intro u hu w hw
    simp only [PathGrowth.words_zero, Finset.mem_singleton] at hw
    refine ⟨fun _ => 0, fun _ => 0, ⟨fun n => ⟨le_refl 0, hLpos⟩,
      fun n => ⟨le_refl 0, one_pos⟩, fun n => by push_cast; ring⟩,
      div_pos (by exact_mod_cast (state_pos h hu).1) hD, by simp [hw]⟩
  | succ k ih =>
    intro u hu w hw
    rw [PathGrowth.words_succ, Finset.mem_biUnion] at hw
    obtain ⟨e, he, hw⟩ := hw
    obtain ⟨v, hv, rfl⟩ := Finset.mem_image.mp hw
    simp only [PathGrowth.outEdges, Finset.mem_filter] at he
    obtain ⟨hemem, hesrc⟩ := he
    obtain ⟨hsrc, htgt, hpos, hlab, hid⟩ := edge_parts h (mem_ed_of_mem_E hemem)
    obtain ⟨y, s, horb, hy0, rfl⟩ := ih e.2.2 htgt v hv
    -- the numeric facts
    have hs0 : (0 : ℝ) ≤ (e.2.1 : ℝ) := by rcases hlab with h' | h' <;> simp [h']
    have hidle : 2 * e.2.2 ≤ 3 * u - e.2.1 * c.D := by
      rw [hid, hesrc]; exact min_le_right _ _
    have hy0D : y 0 * (c.D : ℝ) < ((e.2.2 : ℤ) : ℝ) := (lt_div_iff₀ hD).mp hy0
    have hidR : (2 : ℝ) * (e.2.2 : ℝ) ≤ 3 * (u : ℝ) - (e.2.1 : ℝ) * (c.D : ℝ) := by
      have : ((2 * e.2.2 : ℤ) : ℝ) ≤ ((3 * u - e.2.1 * c.D : ℤ) : ℝ) := by exact_mod_cast hidle
      push_cast at this; linarith
    have hnew0 : (0 : ℝ) ≤ (2 * y 0 + (e.2.1 : ℝ)) / 3 := by
      have := (horb.1 0).1; positivity
    have hnewu : (2 * y 0 + (e.2.1 : ℝ)) / 3 < (u : ℝ) / (c.D : ℝ) := by
      rw [lt_div_iff₀ hD, div_mul_eq_mul_div, div_lt_iff₀ (by norm_num : (0:ℝ) < 3)]
      nlinarith
    have huL : (u : ℝ) / (c.D : ℝ) ≤ (c.L : ℝ) / (c.D : ℝ) := by
      have huLZ : (u : ℝ) ≤ (c.L : ℝ) := by exact_mod_cast (state_pos h hu).2
      gcongr
    -- the orbit, one branch prepended
    set Y : ℕ → ℝ := fun n => Nat.rec ((2 * y 0 + (e.2.1 : ℝ)) / 3) (fun j _ => y j) n with hYdef
    set S : ℕ → ℤ := fun n => Nat.rec e.2.1 (fun j _ => s j) n with hSdef
    have hY0 : Y 0 = (2 * y 0 + (e.2.1 : ℝ)) / 3 := rfl
    have hYs : ∀ j, Y (j + 1) = y j := fun _ => rfl
    have hS0 : S 0 = e.2.1 := rfl
    have hSs : ∀ j, S (j + 1) = s j := fun _ => rfl
    have hY0u : Y 0 < (u : ℝ) / (c.D : ℝ) := by rw [hY0]; exact hnewu
    refine ⟨Y, S, ⟨fun n => ?_, fun n => ?_, fun n => ?_⟩, hY0u, ?_⟩
    · cases n with
      | zero => exact Set.mem_Ico.mpr ⟨hY0 ▸ hnew0, lt_of_lt_of_le hY0u huL⟩
      | succ j => rw [hYs]; exact horb.1 j
    · cases n with
      | zero =>
        refine Set.mem_Ico.mpr ⟨hY0 ▸ hnew0, ?_⟩
        have := lt_of_lt_of_le hY0u huL
        linarith
      | succ j => rw [hYs]; exact horb.2.1 j
    · cases n with
      | zero => rw [hYs, hY0, hS0]; push_cast; ring
      | succ j =>
        rw [hYs, hYs, hSs]
        have := horb.2.2 j
        push_cast at this ⊢
        linarith
    · rw [List.ofFn_succ]
      simp [hS0, hSs]

/-- **The certificate counts the window exactly, from above.** -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem card_modelLang_le (h : c.ok = true) (k : ℕ) :
    Nat.card (modelLang 3 2 c.window k) ≤ (PathGrowth.words c.E c.L k).card := by
  classical
  have hmem : ∀ v : modelLang 3 2 c.window k,
      (List.ofFn fun i : Fin k => (v.1 i)) ∈ PathGrowth.words c.E c.L k := by
    rintro ⟨v, y, s, horb, hval⟩
    obtain ⟨A, hA0, hAmem, hAlt, hpath⟩ := exists_state_path h horb
    have hw := word_mem_words (c := c) hpath k 0
    rw [hA0] at hw
    have hfun : (fun i : Fin k => s (0 + (i : ℕ))) = fun i : Fin k => v i := by
      funext i; rw [Nat.zero_add]; exact hval i
    rwa [hfun] at hw
  have hinj : Function.Injective fun v : modelLang 3 2 c.window k =>
      (⟨List.ofFn fun i : Fin k => (v.1 i), hmem v⟩ :
        {x // x ∈ PathGrowth.words c.E c.L k}) := by
    intro v v' hvv
    exact Subtype.ext (List.ofFn_injective (congrArg Subtype.val hvv))
  calc Nat.card (modelLang 3 2 c.window k)
      ≤ Nat.card {x // x ∈ PathGrowth.words c.E c.L k} := Nat.card_le_card_of_injective _ hinj
    _ = (PathGrowth.words c.E c.L k).card := by rw [Nat.card_eq_fintype_card, Fintype.card_coe]

/-- **…and from below**, which is realizability cashed in. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem le_card_modelLang (h : c.ok = true) (k : ℕ) :
    (PathGrowth.words c.E c.L k).card ≤ Nat.card (modelLang 3 2 c.window k) := by
  classical
  have hfin : Finite (modelLang 3 2 c.window k) :=
    (modelLang_finite (p := 3) (q := 2) (by norm_num) (by norm_num) c.window k).to_subtype
  have hchoice : ∀ w : {x // x ∈ PathGrowth.words c.E c.L k},
      ∃ v : Fin k → ℤ, v ∈ modelLang 3 2 c.window k ∧ w.1 = List.ofFn v := by
    rintro ⟨w, hw⟩
    obtain ⟨y, s, horb, -, hword⟩ := exists_orbit_of_mem_words h k c.L (L_mem h) w hw
    exact ⟨fun i : Fin k => s (i : ℕ), ⟨y, s, horb, fun _ => rfl⟩, hword⟩
  choose f hf1 hf2 using hchoice
  have hinj : Function.Injective fun w => (⟨f w, hf1 w⟩ : modelLang 3 2 c.window k) := by
    intro w w' hww
    have hf : f w = f w' := by simpa using congrArg Subtype.val hww
    exact Subtype.ext (by rw [hf2 w, hf2 w', hf])
  calc (PathGrowth.words c.E c.L k).card = Nat.card {x // x ∈ PathGrowth.words c.E c.L k} := by
        rw [Nat.card_eq_fintype_card, Fintype.card_coe]
    _ ≤ Nat.card (modelLang 3 2 c.window k) := Nat.card_le_card_of_injective _ hinj

/-- **The type graph is an exact model of the window's language.**  This is what
distinguishes the certificate from an enclosure: the same finite graph carries
both bounds, because it makes no error at all. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem card_modelLang_eq (h : c.ok = true) (k : ℕ) :
    Nat.card (modelLang 3 2 c.window k) = (PathGrowth.words c.E c.L k).card :=
  le_antisymm (card_modelLang_le h k) (le_card_modelLang h k)

end TypeCert

/-! ## From a geometric word count to `φ_model`

Two general facts about `phiModel`, stated here because this is the first file
that needs them; they belong upstream in `Z32/ModelEntropy.lean` next to
`Z32.phiModel_eq_zero_of_card_le`, which is their degenerate case. -/

/-- A language with at most `C · λⁿ` words of length `n` has growth rate at most
`log λ`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_le_of_card_le {p q : ℕ} {U : Set ℝ} {C lam : ℝ}
    (hC : 1 ≤ C) (hlam : 1 ≤ lam)
    (hcard : ∀ n, (Nat.card (modelLang p q U n) : ℝ) ≤ C * lam ^ n) :
    phiModel p q U ≤ Real.log lam := by
  have hC0 : (0 : ℝ) < C := lt_of_lt_of_le one_pos hC
  have hlogC : 0 ≤ Real.log C := Real.log_nonneg hC
  have hloglam : 0 ≤ Real.log lam := Real.log_nonneg hlam
  have hle : ∀ n : ℕ, Real.log (Nat.card (modelLang p q U n)) / n
      ≤ Real.log C / n + Real.log lam := by
    intro n
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · simpa using hloglam
    have hn' : (0 : ℝ) < n := by exact_mod_cast hn
    rcases Nat.eq_zero_or_pos (Nat.card (modelLang p q U n)) with h0 | h0
    · rw [h0, Nat.cast_zero, Real.log_zero, zero_div]
      have h2 : 0 ≤ Real.log C / n := by positivity
      linarith
    · have h1 : Real.log (Nat.card (modelLang p q U n)) ≤ Real.log C + n * Real.log lam := by
        calc Real.log (Nat.card (modelLang p q U n))
            ≤ Real.log (C * lam ^ n) := Real.log_le_log (by exact_mod_cast h0) (hcard n)
          _ = Real.log C + n * Real.log lam := by
              rw [Real.log_mul (ne_of_gt hC0) (by positivity), Real.log_pow]
      rw [div_le_iff₀ hn', add_mul, div_mul_cancel₀ _ (ne_of_gt hn')]
      linarith
  have hg : Filter.Tendsto (fun n : ℕ => Real.log C / n + Real.log lam) Filter.atTop
      (nhds (Real.log lam)) := by
    simpa using (tendsto_const_div_atTop_nhds_zero_nat (Real.log C)).add
      (tendsto_const_nhds (x := Real.log lam) (f := Filter.atTop (α := ℕ)))
  refine le_trans (Filter.limsup_le_limsup (Filter.Eventually.of_forall hle) ?_ ?_)
    (le_of_eq hg.limsup_eq)
  · refine Filter.IsBoundedUnder.isCoboundedUnder_le ⟨0, ?_⟩
    simp only [Filter.eventually_map]
    filter_upwards with n
    exact div_nonneg (Real.log_natCast_nonneg _) (Nat.cast_nonneg n)
  · exact hg.isBoundedUnder_le

/-- A language with at least `C · λⁿ` words of length `n` has growth rate at
least `log λ`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem le_phiModel_of_le_card {p q : ℕ} (hp : 0 < p) (hq : 0 < q) {U : Set ℝ} {C lam : ℝ}
    (hC : 0 < C) (hlam : 0 < lam)
    (hcard : ∀ n, C * lam ^ n ≤ (Nat.card (modelLang p q U n) : ℝ)) :
    Real.log lam ≤ phiModel p q U := by
  have hle : ∀ᶠ n : ℕ in Filter.atTop, Real.log C / n + Real.log lam
      ≤ Real.log (Nat.card (modelLang p q U n)) / n := by
    filter_upwards [Filter.eventually_gt_atTop 0] with n hn
    have hn' : (0 : ℝ) < n := by exact_mod_cast hn
    have hpos : (0 : ℝ) < C * lam ^ n := by positivity
    have h0 : (0 : ℝ) < (Nat.card (modelLang p q U n) : ℝ) := lt_of_lt_of_le hpos (hcard n)
    have h1 : Real.log C + n * Real.log lam ≤ Real.log (Nat.card (modelLang p q U n)) := by
      calc Real.log C + n * Real.log lam = Real.log (C * lam ^ n) := by
            rw [Real.log_mul (ne_of_gt hC) (by positivity), Real.log_pow]
        _ ≤ Real.log (Nat.card (modelLang p q U n)) := Real.log_le_log hpos (hcard n)
    rw [div_add' _ _ _ (ne_of_gt hn'), div_le_div_iff_of_pos_right hn']
    linarith
  have hg : Filter.Tendsto (fun n : ℕ => Real.log C / n + Real.log lam) Filter.atTop
      (nhds (Real.log lam)) := by
    simpa using (tendsto_const_div_atTop_nhds_zero_nat (Real.log C)).add
      (tendsto_const_nhds (x := Real.log lam) (f := Filter.atTop (α := ℕ)))
  refine le_trans (ge_of_eq hg.limsup_eq) (Filter.limsup_le_limsup hle ?_ ?_)
  · exact hg.isBoundedUnder_ge.isCoboundedUnder_le
  · exact isBoundedUnder_phiModel hp hq U

namespace TypeCert

variable {c : TypeCert}

/-- **The certified upper enclosure.** -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_le (h : c.ok = true) :
    phiModel 3 2 c.window ≤ Real.log ((c.a : ℝ) / (c.b : ℝ)) := by
  have hb : (0 : ℝ) < c.b := by exact_mod_cast b_pos h
  have hm : (0 : ℝ) < c.m := by exact_mod_cast m_pos h
  refine phiModel_le_of_card_le (C := (c.M : ℝ) / (c.m : ℝ)) ?_ ?_ fun n => ?_
  · rw [le_div_iff₀ hm, one_mul]; exact_mod_cast m_le_M h
  · rw [le_div_iff₀ hb, one_mul]; exact_mod_cast b_le_a h
  · calc (Nat.card (modelLang 3 2 c.window n) : ℝ)
        ≤ ((PathGrowth.words c.E c.L n).card : ℝ) := by exact_mod_cast card_modelLang_le h n
      _ ≤ (c.M : ℝ) / (c.m : ℝ) * ((c.a : ℝ) / (c.b : ℝ)) ^ n :=
          PathGrowth.card_words_le_pow c.E c.wt c.a c.b c.m c.M (b_pos h) (m_pos h)
            (m_le_wt h) (wt_le_M h) (cert_upper h) n c.L

/-- **The certified lower enclosure.**  This is the half that needs the graph to
be exact and deterministic. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem le_phiModel (h : c.ok = true) :
    Real.log ((c.a' : ℝ) / (c.b' : ℝ)) ≤ phiModel 3 2 c.window := by
  have hm0 : (0 : ℝ) < c.m := by exact_mod_cast m_pos h
  have hmM : (c.m : ℝ) ≤ (c.M : ℝ) := by exact_mod_cast m_le_M h
  have hM0 : (0 : ℝ) < c.M := lt_of_lt_of_le hm0 hmM
  have hb'0 : (0 : ℝ) < c.b' := by exact_mod_cast b'_pos h
  have ha'0 : (0 : ℝ) < c.a' := lt_of_lt_of_le hb'0 (by exact_mod_cast b'_le_a' h)
  have hroot : (0 : ℝ) < c.wt0 c.L := by exact_mod_cast wt0_pos_of_mem h (L_mem h)
  refine le_phiModel_of_le_card (by norm_num) (by norm_num)
    (C := (c.wt0 c.L : ℝ) / (c.M : ℝ)) (div_pos hroot hM0) (div_pos ha'0 hb'0) fun n => ?_
  have hraw : ((c.a' : ℝ)) ^ n * (c.wt0 c.L : ℝ)
      ≤ (c.M : ℝ) * (((c.b' : ℝ)) ^ n * ((PathGrowth.words c.E c.L n).card : ℝ)) := by
    exact_mod_cast PathGrowth.le_card_words (deterministic h) c.wt0 c.a' c.b' c.M
      (wt0_le_M h) (cert_lower h) n c.L
  have hcard : ((PathGrowth.words c.E c.L n).card : ℝ)
      ≤ (Nat.card (modelLang 3 2 c.window n) : ℝ) := by
    exact_mod_cast le_card_modelLang h n
  have hstep : (c.M : ℝ) * ((c.b' : ℝ) ^ n * ((PathGrowth.words c.E c.L n).card : ℝ))
      ≤ (c.M : ℝ) * ((c.b' : ℝ) ^ n * (Nat.card (modelLang 3 2 c.window n) : ℝ)) := by
    have hbn : (0 : ℝ) < (c.b' : ℝ) ^ n := pow_pos hb'0 n
    gcongr
  rw [div_pow, div_mul_div_comm, div_le_iff₀ (by positivity)]
  calc (c.wt0 c.L : ℝ) * (c.a' : ℝ) ^ n = (c.a' : ℝ) ^ n * (c.wt0 c.L : ℝ) := by ring

    _ ≤ (c.M : ℝ) * ((c.b' : ℝ) ^ n * ((PathGrowth.words c.E c.L n).card : ℝ)) := hraw
    _ ≤ (c.M : ℝ) * ((c.b' : ℝ) ^ n * (Nat.card (modelLang 3 2 c.window n) : ℝ)) := hstep
    _ = (Nat.card (modelLang 3 2 c.window n) : ℝ) * ((c.M : ℝ) * (c.b' : ℝ) ^ n) := by ring

/-- The two enclosures as one bracket — the shape the entries below report. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem mem_Icc (h : c.ok = true) :
    phiModel 3 2 c.window ∈
      Set.Icc (Real.log ((c.a' : ℝ) / (c.b' : ℝ))) (Real.log ((c.a : ℝ) / (c.b : ℝ))) :=
  ⟨le_phiModel h, phiModel_le h⟩

end TypeCert


/-! ## The entries

Seven anchored windows spanning the band, each certificate generated by
`Z32/entcert.py` and independently re-checked by `Z32/verify_entcert.py`.  Every
bracket is the exact Collatz–Wielandt extremum of an exact integer power-iterate
`M^k 1`, rounded outwards to eight decimals; the two bounds of a row therefore
differ only in the eighth decimal, and the row is a *measurement* of
`φ_model([0,ℓ))`, not an estimate of it. -/

/-- Entropy certificate for the window `[0, 2/5)`: 22 states,
25 edges, common denominator `10485760`.  Generated by
`Z32/entcert.py 2 5`. -/
def cert25 : TypeCert where
  D := 10485760
  L := 4194304
  st := [(65536, 8542960710158405072), (98304, 11385879938300624366), (147456, 15174863418866302789), (221184, 20224741612338897017), (331776, 26955113993140023529), (425824, 30485838939322044374), (497664, 35925213993334864162), (638736, 40630890596130274407), (746496, 47880376272768549942), (958104, 54152003949129942408), (1048576, 56859548710910154362), (1119744, 63813967327994942341), (1437156, 72172661949621685268), (1572864, 75781221163589028446), (1679616, 85049925316781979049), (2155734, 96190219253705879836), (2359296, 100999631745984159144), (2519424, 113352767415494316072), (3233601, 128200318931488655609), (3538944, 134610203638757360059), (3779136, 151074205331675142259), (4194304, 170862712463380213663)]
  ed := [(65536, 0, 98304), (98304, 0, 147456), (147456, 0, 221184), (221184, 0, 331776), (331776, 0, 497664), (425824, 0, 638736), (497664, 0, 746496), (638736, 0, 958104), (746496, 0, 1119744), (958104, 0, 1437156), (1048576, 0, 1572864), (1119744, 0, 1679616), (1437156, 0, 2155734), (1572864, 0, 2359296), (1679616, 0, 2519424), (2155734, 0, 3233601), (2359296, 0, 3538944), (2519424, 0, 3779136), (3233601, 0, 4194304), (3538944, 0, 4194304), (3538944, 1, 65536), (3779136, 0, 4194304), (3779136, 1, 425824), (4194304, 0, 4194304), (4194304, 1, 1048576)]
  a := 33319479
  b := 25000000
  a' := 26655583
  b' := 20000000
  m := 8542960710158405072
  M := 170862712463380213663

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert25_ok : cert25.ok = true := by decide

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert25_window : cert25.window = Set.Ico (0 : ℝ) (2 / 5) := by
  norm_num [TypeCert.window, cert25]

/-- `φ_model([0, 2/5))`, to eight decimals. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_two_fifths_mem_Icc :
    phiModel 3 2 (Set.Ico (0 : ℝ) (2 / 5)) ∈
      Set.Icc (Real.log (26655583 / 20000000))
        (Real.log (33319479 / 25000000)) := by
  have h := TypeCert.mem_Icc cert25_ok
  rw [cert25_window] at h
  refine ⟨le_trans (le_of_eq ?_) h.1, le_trans h.2 (le_of_eq ?_)⟩ <;>
    norm_num [cert25]

/-- Entropy certificate for the window `[0, 13/32)`: 10 states,
12 edges, common denominator `16384`.  Generated by
`Z32/entcert.py 13 32`. -/
def cert1332 : TypeCert where
  D := 16384
  L := 6656
  st := [(880, 29044303970068409100), (1320, 39438375972066296342), (1792, 47981737310608131126), (1980, 53552169847724982683), (2688, 65152940066968606264), (2970, 72716860791398503227), (4032, 88469193432716768530), (4455, 98740011065681553312), (6048, 120129623906312333569), (6656, 134076054427313394875)]
  ed := [(880, 0, 1320), (1320, 0, 1980), (1792, 0, 2688), (1980, 0, 2970), (2688, 0, 4032), (2970, 0, 4455), (4032, 0, 6048), (4455, 0, 6656), (6048, 0, 6656), (6048, 1, 880), (6656, 0, 6656), (6656, 1, 1792)]
  a := 33946739
  b := 25000000
  a' := 27157391
  b' := 20000000
  m := 29044303970068409100
  M := 134076054427313394875

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert1332_ok : cert1332.ok = true := by decide

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert1332_window : cert1332.window = Set.Ico (0 : ℝ) (13 / 32) := by
  norm_num [TypeCert.window, cert1332]

/-- `φ_model([0, 13/32))`, to eight decimals. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_thirteen_32_mem_Icc :
    phiModel 3 2 (Set.Ico (0 : ℝ) (13 / 32)) ∈
      Set.Icc (Real.log (27157391 / 20000000))
        (Real.log (33946739 / 25000000)) := by
  have h := TypeCert.mem_Icc cert1332_ok
  rw [cert1332_window] at h
  refine ⟨le_trans (le_of_eq ?_) h.1, le_trans h.2 (le_of_eq ?_)⟩ <;>
    norm_num [cert1332]

/-- Entropy certificate for the window `[0, 5/12)`: 4 states,
5 edges, common denominator `96`.  Generated by
`Z32/entcert.py 5 12`. -/
def certBand : TypeCert where
  D := 96
  L := 40
  st := [(12, 41077848883267427697), (18, 56698833400355507771), (27, 78260127936513310484), (40, 108020699145478871712)]
  ed := [(12, 0, 18), (18, 0, 27), (27, 0, 40), (40, 0, 40), (40, 1, 12)]
  a := 138027757
  b := 100000000
  a' := 34506939
  b' := 25000000
  m := 41077848883267427697
  M := 108020699145478871712

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem certBand_ok : certBand.ok = true := by decide

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem certBand_window : certBand.window = Set.Ico (0 : ℝ) (5 / 12) := by
  norm_num [TypeCert.window, certBand]

/-- `φ_model([0, 5/12))`, to eight decimals. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_band_mem_Icc :
    phiModel 3 2 (Set.Ico (0 : ℝ) (5 / 12)) ∈
      Set.Icc (Real.log (34506939 / 25000000))
        (Real.log (138027757 / 100000000)) := by
  have h := TypeCert.mem_Icc certBand_ok
  rw [certBand_window] at h
  refine ⟨le_trans (le_of_eq ?_) h.1, le_trans h.2 (le_of_eq ?_)⟩ <;>
    norm_num [certBand]

/-- **Consistency with the ledger, and the size of the improvement.**  The band
window is the one `Z32/ModelEntropy.lean` already had a horseshoe for, giving
`φ_model ≥ (log 14)/10 = 0.26392…`.  The new lower bound `0.32228…` is strictly
larger, so the two are consistent and this one is sharper — and it now comes
with a matching upper bound, which the horseshoe method cannot produce. -/
@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem log_fourteen_div_ten_lt_band_lower :
    Real.log 14 / 10 < Real.log (34506939 / 25000000) := by
  have hpow : (14 : ℝ) < (34506939 / 25000000 : ℝ) ^ 10 := by norm_num
  have h := Real.log_lt_log (by norm_num) hpow
  rw [Real.log_pow] at h
  push_cast at h
  linarith

/-- Entropy certificate for the window `[0, 7/16)`: 11 states,
13 edges, common denominator `16384`.  Generated by
`Z32/entcert.py 7 16`. -/
def cert716 : TypeCert where
  D := 16384
  L := 7168
  st := [(448, 15954956465510451704), (672, 22329099546691162909), (1008, 31249767910293824777), (1512, 43734320428158036574), (2268, 61206559639207808235), (2560, 67027174509273027756), (3402, 85659109509242766833), (3840, 93805110354659614248), (5103, 119880664509955343049), (5760, 131281063137048920924), (7168, 167774026670190522136)]
  ed := [(448, 0, 672), (672, 0, 1008), (1008, 0, 1512), (1512, 0, 2268), (2268, 0, 3402), (2560, 0, 3840), (3402, 0, 5103), (3840, 0, 5760), (5103, 0, 7168), (5760, 0, 7168), (5760, 1, 448), (7168, 0, 7168), (7168, 1, 2560)]
  a := 27990173
  b := 20000000
  a' := 8746929
  b' := 6250000
  m := 15954956465510451704
  M := 167774026670190522136

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert716_ok : cert716.ok = true := by decide

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert716_window : cert716.window = Set.Ico (0 : ℝ) (7 / 16) := by
  norm_num [TypeCert.window, cert716]

/-- `φ_model([0, 7/16))`, to eight decimals. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_seven_16_mem_Icc :
    phiModel 3 2 (Set.Ico (0 : ℝ) (7 / 16)) ∈
      Set.Icc (Real.log (8746929 / 6250000))
        (Real.log (27990173 / 20000000)) := by
  have h := TypeCert.mem_Icc cert716_ok
  rw [cert716_window] at h
  refine ⟨le_trans (le_of_eq ?_) h.1, le_trans h.2 (le_of_eq ?_)⟩ <;>
    norm_num [cert716]

/-- Entropy certificate for the window `[0, 9/20)`: 8 states,
10 edges, common denominator `2560`.  Generated by
`Z32/entcert.py 9 20`. -/
def cert920 : TypeCert where
  D := 2560
  L := 1152
  st := [(232, 29835561182829786431), (348, 42577105060811701265), (448, 52843275174879015209), (522, 60760039479420293363), (672, 75410469576587707016), (783, 86708159050922842150), (1008, 107615186661724176323), (1152, 123737655709499948137)]
  ed := [(232, 0, 348), (348, 0, 522), (448, 0, 672), (522, 0, 783), (672, 0, 1008), (783, 0, 1152), (1008, 0, 1152), (1008, 1, 232), (1152, 0, 1152), (1152, 1, 448)]
  a := 142705897
  b := 100000000
  a' := 17838237
  b' := 12500000
  m := 29835561182829786431
  M := 123737655709499948137

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert920_ok : cert920.ok = true := by decide

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert920_window : cert920.window = Set.Ico (0 : ℝ) (9 / 20) := by
  norm_num [TypeCert.window, cert920]

/-- `φ_model([0, 9/20))`, to eight decimals. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_nine_20_mem_Icc :
    phiModel 3 2 (Set.Ico (0 : ℝ) (9 / 20)) ∈
      Set.Icc (Real.log (17838237 / 12500000))
        (Real.log (142705897 / 100000000)) := by
  have h := TypeCert.mem_Icc cert920_ok
  rw [cert920_window] at h
  refine ⟨le_trans (le_of_eq ?_) h.1, le_trans h.2 (le_of_eq ?_)⟩ <;>
    norm_num [cert920]

/-- Entropy certificate for the window `[0, 11/24)`: 42 states,
52 edges, common denominator `52776558133248`.  Generated by
`Z32/entcert.py 11 24`. -/
def cert1124 : TypeCert where
  D := 52776558133248
  L := 24189255811072
  st := [(3155253657600, 16444065941056699738), (3226482078096, 16660212448220603187), (4313220907008, 21547835359910207036), (4732880486400, 23710206572344908179), (4839723117144, 24021861752585480180), (5835759550464, 27826424027842343075), (5849829361920, 27876432514188252988), (6365242195968, 30459890126535680007), (6469831360512, 31069178961071529334), (7009386627072, 33698582305923300224), (7099320729600, 34187037300772640602), (7259584675716, 34636403578512630194), (8753639325696, 40122088067192987536), (8774744042880, 40194193807092246918), (9096740732928, 41824688192682879751), (9547863293952, 43919204025320474252), (9552032126976, 43935886686338361556), (9704747040768, 44797719362150854659), (9895604649984, 45878136061752976335), (10514079940608, 48588977357096635613), (10648981094400, 49293265996578054724), (10889377013574, 49941193784635488411), (13130458988544, 57850838083286569781), (13162116064320, 57954805191797938646), (13645111099392, 60305766251913901559), (14321794940928, 63325785950137665401), (14328048190464, 63349840179811001827), (14557120561152, 64592490923705840086), (14843406974976, 66150311430118221384), (15771119910912, 70058992368751741052), (15973471641600, 71074485081352000850), (16334065520361, 72008712768949014084), (19695688482816, 83413392177740927993), (19743174096480, 83563299240165112669), (20467666649088, 86953079637464133124), (21482692411392, 91307555662682226560), (21492072285696, 91342238736597014748), (21835680841728, 93133979656430062517), (22265110462464, 95380154425010538880), (23656679866368, 101015964498539905645), (23960207462400, 102480173051021441635), (24189255811072, 103827207995902467692)]
  ed := [(3155253657600, 0, 4732880486400), (3226482078096, 0, 4839723117144), (4313220907008, 0, 6469831360512), (4732880486400, 0, 7099320729600), (4839723117144, 0, 7259584675716), (5835759550464, 0, 8753639325696), (5849829361920, 0, 8774744042880), (6365242195968, 0, 9547863293952), (6469831360512, 0, 9704747040768), (7009386627072, 0, 10514079940608), (7099320729600, 0, 10648981094400), (7259584675716, 0, 10889377013574), (8753639325696, 0, 13130458988544), (8774744042880, 0, 13162116064320), (9096740732928, 0, 13645111099392), (9547863293952, 0, 14321794940928), (9552032126976, 0, 14328048190464), (9704747040768, 0, 14557120561152), (9895604649984, 0, 14843406974976), (10514079940608, 0, 15771119910912), (10648981094400, 0, 15973471641600), (10889377013574, 0, 16334065520361), (13130458988544, 0, 19695688482816), (13162116064320, 0, 19743174096480), (13645111099392, 0, 20467666649088), (14321794940928, 0, 21482692411392), (14328048190464, 0, 21492072285696), (14557120561152, 0, 21835680841728), (14843406974976, 0, 22265110462464), (15771119910912, 0, 23656679866368), (15973471641600, 0, 23960207462400), (16334065520361, 0, 24189255811072), (19695688482816, 0, 24189255811072), (19695688482816, 1, 3155253657600), (19743174096480, 0, 24189255811072), (19743174096480, 1, 3226482078096), (20467666649088, 0, 24189255811072), (20467666649088, 1, 4313220907008), (21482692411392, 0, 24189255811072), (21482692411392, 1, 5835759550464), (21492072285696, 0, 24189255811072), (21492072285696, 1, 5849829361920), (21835680841728, 0, 24189255811072), (21835680841728, 1, 6365242195968), (22265110462464, 0, 24189255811072), (22265110462464, 1, 7009386627072), (23656679866368, 0, 24189255811072), (23656679866368, 1, 9096740732928), (23960207462400, 0, 24189255811072), (23960207462400, 1, 9552032126976), (24189255811072, 0, 24189255811072), (24189255811072, 1, 9895604649984)]
  a := 1126461
  b := 781250
  a' := 144187007
  b' := 100000000
  m := 16444065941056699738
  M := 103827207995902467692

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert1124_ok : cert1124.ok = true := by decide

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert1124_window : cert1124.window = Set.Ico (0 : ℝ) (11 / 24) := by
  norm_num [TypeCert.window, cert1124]

/-- `φ_model([0, 11/24))`, to eight decimals. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_eleven_24_mem_Icc :
    phiModel 3 2 (Set.Ico (0 : ℝ) (11 / 24)) ∈
      Set.Icc (Real.log (144187007 / 100000000))
        (Real.log (1126461 / 781250)) := by
  have h := TypeCert.mem_Icc cert1124_ok
  rw [cert1124_window] at h
  refine ⟨le_trans (le_of_eq ?_) h.1, le_trans h.2 (le_of_eq ?_)⟩ <;>
    norm_num [cert1124]

/-- Entropy certificate for the window `[0, 23/48)`: 3 states,
4 edges, common denominator `192`.  Generated by
`Z32/entcert.py 23 48`. -/
def cert2348 : TypeCert where
  D := 192
  L := 92
  st := [(42, 50959194632488457965), (63, 74684329652984094451), (92, 109455205011414534460)]
  ed := [(42, 0, 63), (63, 0, 92), (92, 0, 92), (92, 1, 42)]
  a := 36639281
  b := 25000000
  a' := 146557123
  b' := 100000000
  m := 50959194632488457965
  M := 109455205011414534460

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert2348_ok : cert2348.ok = true := by decide

@[category API, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem cert2348_window : cert2348.window = Set.Ico (0 : ℝ) (23 / 48) := by
  norm_num [TypeCert.window, cert2348]

/-- `φ_model([0, 23/48))`, to eight decimals. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_phi_model"]
theorem phiModel_top_band_mem_Icc :
    phiModel 3 2 (Set.Ico (0 : ℝ) (23 / 48)) ∈
      Set.Icc (Real.log (146557123 / 100000000))
        (Real.log (36639281 / 25000000)) := by
  have h := TypeCert.mem_Icc cert2348_ok
  rw [cert2348_window] at h
  refine ⟨le_trans (le_of_eq ?_) h.1, le_trans h.2 (le_of_eq ?_)⟩ <;>
    norm_num [cert2348]

end Z32.EntropyCert
