/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Z32.EntropyCert
import Z32.FlattoCount
import Mathlib.Analysis.SpecialFunctions.Log.Base
import Mathlib.Topology.Algebra.Order.LiminfLimsup
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Pressure, the Bowen zero, and a certified exponent atlas for the model system

`Z32/EntropyCert.lean` brackets `φ_model([0,ℓ))` — the growth rate of the carry language of the
model system of the base `3/2` on an anchored window — to eight decimals, by an exact finite type
graph.  This file puts the thermodynamic layer on top: the pressure `P(t)` of the geometric
potential, its unique zero (the **Bowen zero**), and the two exponent readings the zero carries.

## The pressure is affine, and that is a theorem

The branches of the model system are `y ↦ (p·y − s)/q`: affine, all with the same slope `p/q`
(`modelBranch_sub`).  So `|T'|` is a *constant*, the geometric potential `−t·log|T'|` is the
constant `−t·log(p/q)`, its Birkhoff sum over a length-`k` word is `−t·k·log(p/q)`, and the
partition function degenerates to a product:

`Z_k(t) = ∑_{w ∈ modelLang k} exp(S_k φ_t) = #modelLang(k) · exp(−t·k·log(p/q))`.

Hence `modelPressure_eq`:

`P(t) = φ_model(U) − t·log(p/q)`,   for every real `t`.

This is not a modelling shortcut, it is what a single-slope conformal repeller does; and it is
better news than the two-sided enclosure at each rational `t` that was planned for, because *one*
certificate now encloses the whole pressure function at once, on both sides, at every real `t`
(`TypeCert.modelPressure_mem_Icc`).  At the operator level the same degeneracy is
`TypeCert.psum_eq_card_modelLang`: weighting every edge of the type graph by `θ` multiplies the
transfer operator's output by exactly `θ^k`, so the leading eigenvalue is `θ·λ` and nothing about
the spectrum is new.  The general weighted certificates that make this a theorem rather than an
identification live in `ForMathlib/Combinatorics/PathGrowth.lean` (`psum`, `psum_le`, `le_psum`);
they are what a non-affine variant would consume.

## Two exponents, one number

`modelExponent p q U r = φ_model(U) / log r` is the exponent of the language count in base `r`.
Two bases matter here and they are related by a constant:

* `modelBowen U = modelExponent 3 2 U (3/2)` — the **Bowen zero**, the unique `t` with `P(t) = 0`.
  This is the conformal exponent: a depth-`k` cylinder has diameter `(2/3)^k` times its image's
  (`abs_back_sub`), so this is the exponent Bowen's formula attaches to the survivor set.
* `flattoExponent U = modelExponent 3 2 U 2` — the **dyadic counting exponent**, the exponent in
  Flatto's `#Z(x) ≤ 3·x^s` at the Z-cell.

They differ by the factor `log₂(3/2)` (`flattoExponent_eq`), and at the Z-cell the first is
*exactly 1* (`modelBowen_zCell`) while the second is *exactly* `log₂(3/2) = 0.5849…`
(`flattoExponent_zCell`).  That is plan-B10's F2 wall in dimension language: the conformal exponent
of the model saturates at the top of the window family, so all the information sits in the dyadic
reading — and the `0.585` of the wall and the `0.585` of Table C's `s₀` are literally the same
number, obtained here from `Z32.Flatto.phiModel_zCell`.

## No logarithm reaches the kernel

Every bound below is a rational power comparison.  For `r, x > 1`,

`n/d ≤ log x / log r  ⟺  r^n ≤ x^d`   (`div_le_log_div_log`, `log_div_log_le_div`),

so a seven-decimal bracket on an exponent is two integer inequalities, discharged by `norm_num`
over GMP-accelerated numerals.  Nothing rounds, nothing floats, and no interval-arithmetic library
is involved.

## Main results

* `modelPressure`, `modelPressure_eq` — the pressure and its affine closed form.
* `strictAnti_modelPressure`, `modelBowen_mem_Icc` — strict monotonicity in `t`, hence a unique
  zero and the **monotone interval bracketing**: `0 ≤ P(t₁)` and `P(t₂) ≤ 0` give
  `t₁ ≤ t* ≤ t₂`.
* `TypeCert.modelPressure_mem_Icc` — `P_lo(t) ≤ P(t) ≤ P_hi(t)` at every real `t`, from one
  certificate.
* `TypeCert.modelPressure_nonneg_of_pow`, `TypeCert.modelPressure_nonpos_of_pow` — the sign of the
  pressure at a rational `t`, decided by integer arithmetic; and
  `TypeCert.modelBowen_mem_Icc_of_pow`, which brackets the Bowen zero by running the two.
* `bowen_band_mem_Icc` and its six siblings — the atlas, to seven decimals.
* `modelBowen_zCell`, `flattoExponent_zCell`, `modelPressure_zCell` — the Z-cell endpoint, exact.

## The atlas (plan-B10 WP4′ / report2-weyl.html B5)

Generated by `Z32/pressure.py` from the certificates of `Z32/entcert.py`, independently re-checked
by `Z32/verify_entcert.py`.  Both columns are certified in this file by the two power comparisons
shown for the flagship row.

```
   ℓ        φ_model([0,ℓ))   Bowen zero t*(ℓ)   dyadic s₀(ℓ)
  2/5         0.2872663         0.7084860         0.4144378
  13/32       0.3059170         0.7544841         0.4413449
  5/12        0.3222846         0.7948517         0.4649584   ← flagship
  7/16        0.3361212         0.8289769         0.4849204
  9/20        0.3556157         0.8770561         0.5130449
  11/24       0.3659409         0.9025214         0.5279411
  23/48       0.3822451         0.9427324         0.5514631
  1/2         0.4054651         1                 0.5849625   = log₂(3/2), both exact
```

Each entry is the midpoint of the certified interval, rounded to seven decimals; the interval
itself is the `Set.Icc` of the corresponding theorem and is narrower than `2 · 10⁻⁷` in every row.
Both exponent columns are monotone in `ℓ` and approach their Z-cell values; the Bowen column
reaching `1` is the saturation described above, and is why the plan's `δ < 0.585` target lives in
the third column, not the second.

**Cost.**  The pressure layer adds no `decide` at all: it reuses the seven certificates of WP3
verbatim, and its own kernel work is numeral exponentiation.  Measured on this machine at
`LEAN_NUM_THREADS=3`: the twenty-eight power comparisons of the atlas — integers of up to
`51 202` decimal digits — cost `0.27 s` in isolation (`1.51 s` against a `1.24 s` import
baseline), and the whole file elaborates in `2.3 s` over its own `1.6 s` import baseline.

## What is *not* claimed

* **No Hausdorff-dimension statement.**  `modelBowen` is the zero of the pressure, and the file
  says so; identifying it with `dimH` of the survivor set needs Bowen's formula, which Mathlib does
  not have in any form.  The geometry is in place — `abs_back_sub` says the inverse branches
  contract by exactly `q/p`, and for `ℓ < 1/2` the type set is finite so the cylinder-to-image
  ratio is bounded away from `0` and `∞`, making the survivor set a strongly separated
  graph-directed self-similar set of constant ratio — but the measure-theoretic half is not
  formalised here.  See `§ Plan corrections` item 6.
* Nothing here is about genuine Z-numbers, for the reasons `Z32/EntropyCert.lean` records: this is
  the entropy, and now the pressure, of the **carry model**.
* `flattoExponent U` is *defined* for every window, but the counting theorem behind the name
  (`Z32.Flatto.card_zNumbers_le`) exists only at the Z-cell.  For `ℓ < 1/2` the number is an
  exponent of the model language in base `2`, nothing more.

## Plan corrections recorded (for plan-B10 WP7)

1. **The `t`-weighted grid is not a grid.**  §8-O2 and Table E's B5 row price "a weighted
   extension of `PathGrowth`'s two vector-certificate lemmas" plus "pressure enclosures at rational
   `t`".  The extension is delivered (`PathGrowth.psum` and its two certificates, which are
   *cheaper* than the unweighted ones: the lower bound needs no determinism and neither needs
   extreme-weight constants).  But for this system the weights are constant, so the enclosure at
   one `t` gives the enclosure at all of them: `modelPressure_eq` is a closed form, not a grid.
2. **Trigger (j) does not bind.**  The gate watches the `t`-weighted certificates staying inside
   WP3's `D ≲ 20`-digit envelope.  `t`-weighting never touches `TypeCert.ok`; the seven WP3
   certificates are reused unchanged and the new kernel work is numeral exponentiation, which is
   GMP-accelerated — `51 202`-digit comparisons cost milliseconds.  B5 holds at `0.85–0.95` and
   the envelope clause is inapplicable, not merely satisfied.
3. **No ball arithmetic anywhere.**  The plan's original B10 sketch wanted "a rigorous
   ball-arithmetic (Arb) enclosure"; WP3 retired that for the eigenvalue, and the equivalence
   `n/d ≤ log x / log r ⟺ r^n ≤ x^d` retires it for the pressure and the exponents too.
4. **The two `0.585`s are one number, and the Bowen zero at the Z-cell is `1`.**  WP5's planned
   cross-reference ("the wall at depth `0.585 n` and this `0.585` are the same number seen twice")
   is `flattoExponent_zCell` together with `modelBowen_zCell`: the conformal exponent saturates at
   `1`, and `s₀ = t* · log₂(3/2)`.
5. **B-portfolio item 4's `TH/Pressure/Pressure.lean` is this file**, `Z32/Pressure.lean`: its
   content is the Z32 model system, it consumes two Z32 files, and `TH/` is not an Extract corpus
   root.
6. **Named next step.**  `dimH (survivor set) = modelBowen` — Bowen's formula for a strongly
   separated graph-directed self-similar set of constant ratio.  Mathlib has `dimH` and the
   Hausdorff measures but no Moran-type theorem; the covering (upper) half is reachable from
   `abs_back_sub` plus `Metric.hausdorffMeasure`, the mass-distribution (lower) half is a session
   of its own.  Nothing else in B5 depends on it, which is why it is recorded rather than
   attempted here.

## References

* R. Bowen, *Hausdorff dimension of quasi-circles*, Publ. IHÉS **50** (1979) — the zero of the
  pressure; W. Parry and M. Pollicott, *Zeta functions and the periodic orbit structure of
  hyperbolic dynamics*, Astérisque **187–188** (1990) — the transfer-operator formalism this file
  degenerates.
* L. Flatto, *Z-numbers and β-transformations*, Contemp. Math. **135** (1992) — the dyadic
  exponent.
* A. Dubickas [Dub09AA in this corpus] — the model and its windows.
* `plans/plan-B10.html` §6 (WP4′), §8-O2; `plans/report2-weyl.html` §7 (B5), Table E's B5 row and
  trigger (j).
* `Z32/EntropyCert.lean`, `Z32/FlattoCount.lean`, `ForMathlib/Combinatorics/PathGrowth.lean`,
  `Z32/pressure.py` (generator), `Z32/verify_pressure.py` (independent re-check of every bracket
  in `§ The atlas`, reading the numbers out of this file), `Z32/data/b10_pressure.txt`.
-/

namespace Z32.Pressure

open Filter Topology

set_option exponentiation.threshold 100000

/-! ## The branches are affine with a single slope

This is the whole reason the pressure below is affine, so it is worth having as a theorem rather
than as a remark. -/

/-- One forward branch of the model system: `y ↦ (p·y − s)/q`. -/
noncomputable def modelBranch (p q : ℕ) (s : ℤ) (y : ℝ) : ℝ :=
  ((p : ℝ) * y - (s : ℝ)) / (q : ℝ)

/-- A model orbit is a chain of branch applications. -/
@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem modelBranch_apply {p q : ℕ} (hq : 0 < q) {U : Set ℝ} {y s}
    (h : IsModelOrbit p q U y s) (n : ℕ) : y (n + 1) = modelBranch p q (s n) (y n) := by
  have hqR : (0 : ℝ) < q := by exact_mod_cast hq
  have := h.2.2 n
  rw [modelBranch, eq_div_iff (ne_of_gt hqR)]
  linarith

/-- **Every branch has the same slope `p/q`**, whichever carry `s` it belongs to: the difference
quotient is the constant `p/q`.  Hence `|T'| ≡ p/q`, the geometric potential `−t·log|T'|` is the
constant `−t·log(p/q)`, and its Birkhoff sum over a length-`k` word is `−t·k·log(p/q)`.  That is
the whole reason `modelPressure` below is affine in `t`. -/
@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem modelBranch_sub {q : ℕ} (hq : 0 < q) (p : ℕ) (s : ℤ) (y y' : ℝ) :
    modelBranch p q s y - modelBranch p q s y' = ((p : ℝ) / (q : ℝ)) * (y - y') := by
  have hqR : (0 : ℝ) < q := by exact_mod_cast hq
  rw [modelBranch, modelBranch]
  field_simp
  ring

/-- **The cylinders contract by exactly `(q/p)^k`.**  `back p q · w` is the composed inverse
branch along the word `w`; it is affine with ratio `q/p`, so the interval of starting points
realising `w` has `(q/p)^{|w|}` times the diameter of its image.  This is the geometry that makes
`modelBowen` a conformal exponent. -/
@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem abs_back_sub {p q : ℕ} (hp : 0 < p) (z z' : ℝ) (w : List ℤ) :
    |back p q z w - back p q z' w| = ((q : ℝ) / (p : ℝ)) ^ w.length * |z - z'| := by
  have hpR : (0 : ℝ) < p := by exact_mod_cast hp
  induction w with
  | nil => simp
  | cons s t ih =>
    have key : back p q z (s :: t) - back p q z' (s :: t)
        = ((q : ℝ) / (p : ℝ)) * (back p q z t - back p q z' t) := by
      rw [back_cons, back_cons]
      field_simp
      ring
    rw [key, abs_mul, abs_of_nonneg (by positivity), ih, List.length_cons]
    ring

/-! ## The language is never empty on a window containing `0` -/

/-- The fixed point `y ≡ 0` is a model orbit of every window containing `0`, so its language has
at least the all-zero word at every length.  This is what lets the partition function be
logarithmed. -/
@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem card_modelLang_pos {p q : ℕ} (hp : 0 < p) (hq : 0 < q) {U : Set ℝ}
    (h0 : (0 : ℝ) ∈ U) (k : ℕ) : 0 < Nat.card (modelLang p q U k) := by
  have hmem : (fun _ : Fin k => (0 : ℤ)) ∈ modelLang p q U k := by
    refine ⟨fun _ => 0, fun _ => 0, ⟨fun _ => h0, fun _ => ?_, fun _ => ?_⟩, fun _ => rfl⟩
    · exact Set.mem_Ico.mpr ⟨le_refl 0, one_pos⟩
    · simp
  exact Nat.card_pos_iff.mpr ⟨⟨⟨_, hmem⟩⟩, (modelLang_finite hp hq U k).to_subtype⟩

/-! ## The partition function and the pressure -/

/-- The **partition function** of the model system at inverse temperature `t`, for the geometric
potential `−t·log|T'|`.  All branches have slope `p/q` (`deriv_modelBranch`), so the Birkhoff sum
over a length-`k` word is the constant `−t·k·log(p/q)` and the sum over the language collapses to
a product. -/
noncomputable def modelPartition (p q : ℕ) (U : Set ℝ) (t : ℝ) (k : ℕ) : ℝ :=
  (Nat.card (modelLang p q U k) : ℝ) * Real.exp (-(t * k * Real.log ((p : ℝ) / (q : ℝ))))

/-- The **topological pressure** of the geometric potential on the hold set `U`. -/
noncomputable def modelPressure (p q : ℕ) (U : Set ℝ) (t : ℝ) : ℝ :=
  limsup (fun k : ℕ => Real.log (modelPartition p q U t k) / k) atTop

/-- **The pressure in closed form.**  A single-slope repeller has an affine pressure: one
certificate for `φ_model` encloses `P(t)` at *every* real `t`, on both sides. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelPressure_eq {p q : ℕ} (hp : 0 < p) (hq : 0 < q) {U : Set ℝ}
    (h0 : (0 : ℝ) ∈ U) (t : ℝ) :
    modelPressure p q U t = phiModel p q U - t * Real.log ((p : ℝ) / (q : ℝ)) := by
  set L := Real.log ((p : ℝ) / (q : ℝ)) with hL
  have heq : ∀ᶠ k : ℕ in atTop,
      Real.log (modelPartition p q U t k) / k
        = Real.log (Nat.card (modelLang p q U k)) / k + -(t * L) := by
    filter_upwards [eventually_ge_atTop 1] with k hk
    have hc : (0 : ℝ) < (Nat.card (modelLang p q U k) : ℝ) := by
      exact_mod_cast card_modelLang_pos hp hq h0 k
    have hk0 : (k : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
    rw [modelPartition, Real.log_mul (ne_of_gt hc) (Real.exp_ne_zero _), Real.log_exp]
    field_simp
    ring
  have hbd := isBoundedUnder_phiModel hp hq U
  have hcb : IsCoboundedUnder (· ≤ ·) atTop
      (fun k : ℕ => Real.log (Nat.card (modelLang p q U k)) / k) :=
    Filter.isCoboundedUnder_le_of_le atTop (x := 0) fun k =>
      div_nonneg (Real.log_natCast_nonneg _) (Nat.cast_nonneg k)
  rw [modelPressure, limsup_congr heq, limsup_add_const atTop _ _ hbd hcb, phiModel]
  ring

/-! ### The base `3/2` -/

@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem log_three_halves_pos : 0 < Real.log (3 / 2 : ℝ) := Real.log_pos (by norm_num)

@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem log_two_pos : 0 < Real.log (2 : ℝ) := Real.log_pos (by norm_num)

/-- `modelPressure_eq` at `(p,q) = (3,2)`, with the cast cleared. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelPressure_three_two {U : Set ℝ} (h0 : (0 : ℝ) ∈ U) (t : ℝ) :
    modelPressure 3 2 U t = phiModel 3 2 U - t * Real.log (3 / 2) := by
  have hc : ((3 : ℕ) : ℝ) / ((2 : ℕ) : ℝ) = 3 / 2 := by norm_num
  have h := modelPressure_eq (p := 3) (q := 2) (by norm_num) (by norm_num) h0 t
  rw [hc] at h
  exact h

/-! ## The Bowen zero and the two exponent readings -/

/-- `modelExponent p q U r` — the exponent of the language count in base `r`: the count grows like
`r ^ (modelExponent · k)`. -/
noncomputable def modelExponent (p q : ℕ) (U : Set ℝ) (r : ℝ) : ℝ :=
  phiModel p q U / Real.log r

/-- The **Bowen zero**: the unique `t` at which the pressure vanishes.  Equivalently the exponent
of the language count in the base `3/2` — the reciprocal of the cylinders' contraction ratio, by
`abs_back_sub`. -/
noncomputable def modelBowen (U : Set ℝ) : ℝ := modelExponent 3 2 U (3 / 2)

/-- The **dyadic counting exponent**: the exponent of the language count in base `2`.  At the
Z-cell this is Flatto's `s` in `#Z(x) ≤ 3·x^s`. -/
noncomputable def flattoExponent (U : Set ℝ) : ℝ := modelExponent 3 2 U 2

/-- The two readings differ by the constant `log₂(3/2)`. -/
@[category research solved, AMS 11 37, ref "Fla92", group "z32_model_pressure"]
theorem flattoExponent_eq (U : Set ℝ) :
    flattoExponent U = modelBowen U * Real.logb 2 (3 / 2) := by
  rw [flattoExponent, modelBowen, modelExponent, modelExponent, Real.logb]
  field_simp

/-- **The pressure vanishes exactly at the Bowen zero.** -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelPressure_modelBowen {U : Set ℝ} (h0 : (0 : ℝ) ∈ U) :
    modelPressure 3 2 U (modelBowen U) = 0 := by
  rw [modelPressure_three_two h0, modelBowen, modelExponent]
  field_simp
  ring

/-- The pressure is strictly decreasing, so its zero is unique. -/
@[category research solved, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem strictAnti_modelPressure {U : Set ℝ} (h0 : (0 : ℝ) ∈ U) :
    StrictAnti (modelPressure 3 2 U) := by
  intro s t hst
  rw [modelPressure_three_two h0, modelPressure_three_two h0]
  have h := mul_lt_mul_of_pos_right hst log_three_halves_pos
  linarith

@[category research solved, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem modelBowen_of_pressure_eq_zero {U : Set ℝ} (h0 : (0 : ℝ) ∈ U) {t : ℝ}
    (ht : modelPressure 3 2 U t = 0) : t = modelBowen U := by
  rw [modelPressure_three_two h0] at ht
  rw [modelBowen, modelExponent, eq_div_iff (ne_of_gt log_three_halves_pos)]
  linarith

/-- **Monotone interval bracketing.**  The pressure is strictly decreasing, so a sign test at two
points brackets its zero — this is the whole of the "interval arithmetic" the Bowen zero needs. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelBowen_mem_Icc {U : Set ℝ} (h0 : (0 : ℝ) ∈ U) {t₁ t₂ : ℝ}
    (h1 : 0 ≤ modelPressure 3 2 U t₁) (h2 : modelPressure 3 2 U t₂ ≤ 0) :
    modelBowen U ∈ Set.Icc t₁ t₂ := by
  rw [modelPressure_three_two h0] at h1 h2
  have hL := log_three_halves_pos
  constructor
  · rw [modelBowen, modelExponent, le_div_iff₀ hL]; linarith
  · rw [modelBowen, modelExponent, div_le_iff₀ hL]; linarith

/-! ## Exponent bounds are rational power comparisons

`n/d ≤ log x / log r` is equivalent to `r^n ≤ x^d`, so nothing below ever evaluates a logarithm. -/

@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem div_le_log_div_log {r x : ℝ} (hr : 1 < r) (_hx : 0 < x) {n d : ℕ} (hd : 0 < d)
    (h : r ^ n ≤ x ^ d) : (n : ℝ) / d ≤ Real.log x / Real.log r := by
  have hlr : 0 < Real.log r := Real.log_pos hr
  have hd' : (0 : ℝ) < d := by exact_mod_cast hd
  have hlog := Real.log_le_log (pow_pos (by linarith) n) h
  rw [Real.log_pow, Real.log_pow] at hlog
  rw [div_le_div_iff₀ hd' hlr]
  linarith

@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem log_div_log_le_div {r x : ℝ} (hr : 1 < r) (hx : 0 < x) {n d : ℕ} (hd : 0 < d)
    (h : x ^ d ≤ r ^ n) : Real.log x / Real.log r ≤ (n : ℝ) / d := by
  have hlr : 0 < Real.log r := Real.log_pos hr
  have hd' : (0 : ℝ) < d := by exact_mod_cast hd
  have hlog := Real.log_le_log (pow_pos hx d) h
  rw [Real.log_pow, Real.log_pow] at hlog
  rw [div_le_div_iff₀ hlr hd']
  linarith

/-! ## The certificate layer -/

namespace TypeCert

open Z32.EntropyCert Z32.EntropyCert.TypeCert

variable {c : Z32.EntropyCert.TypeCert}

/-- Every anchored window contains `0`, so the pressure machinery applies to it. -/
@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem zero_mem_window (h : c.ok = true) : (0 : ℝ) ∈ c.window := by
  have hD : (0 : ℝ) < (c.D : ℝ) := by exact_mod_cast D_pos h
  have hL : (0 : ℝ) < (c.L : ℝ) := by exact_mod_cast L_pos h
  simp only [Z32.EntropyCert.TypeCert.window, Set.mem_Ico]
  exact ⟨le_refl 0, by positivity⟩

@[category API, AMS 11 37, ref "Dub09AA", group "z32_model_pressure"]
theorem ratio_pos (h : c.ok = true) : (0 : ℝ) < (c.a : ℝ) / (c.b : ℝ) := by
  have hb : (0 : ℝ) < (c.b : ℝ) := by exact_mod_cast b_pos h
  have ha : (0 : ℝ) < (c.a : ℝ) := by
    have := b_pos h; have := b_le_a h; exact_mod_cast lt_of_lt_of_le ‹0 < c.b› ‹c.b ≤ c.a›
  positivity

/-- **The certified pressure enclosure, at every real `t`.**  `P_lo(t) ≤ P(t) ≤ P_hi(t)` with the
two bounds differing only by the certificate's own bracket on `φ_model`: the `t`-dependence is
common to both sides, which is what "the pressure is affine" buys. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelPressure_mem_Icc (h : c.ok = true) (t : ℝ) :
    modelPressure 3 2 c.window t ∈
      Set.Icc (Real.log ((c.a' : ℝ) / (c.b' : ℝ)) - t * Real.log (3 / 2))
        (Real.log ((c.a : ℝ) / (c.b : ℝ)) - t * Real.log (3 / 2)) := by
  have hb := Z32.EntropyCert.TypeCert.mem_Icc h
  rw [modelPressure_three_two (zero_mem_window h)]
  exact ⟨by linarith [hb.1], by linarith [hb.2]⟩

/-- **The pressure at a rational `t` is nonnegative, decided by an integer comparison.** -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelPressure_nonneg_of_pow (h : c.ok = true) {u : ℝ} (hu : 0 < u)
    (hu' : u ≤ (c.a' : ℝ) / (c.b' : ℝ)) {n d : ℕ} (hd : 0 < d)
    (hpow : ((3 : ℝ) / 2) ^ n ≤ u ^ d) : 0 ≤ modelPressure 3 2 c.window ((n : ℝ) / d) := by
  have hL := log_three_halves_pos
  have hd' : (0 : ℝ) < d := by exact_mod_cast hd
  have h1 : (n : ℝ) / d ≤ Real.log u / Real.log (3 / 2) :=
    div_le_log_div_log (by norm_num) hu hd hpow
  have h2 : Real.log u ≤ phiModel 3 2 c.window :=
    le_trans (Real.log_le_log hu hu') (Z32.EntropyCert.TypeCert.mem_Icc h).1
  have h3 : ((n : ℝ) / d) * Real.log (3 / 2) ≤ Real.log u := by
    rw [div_mul_eq_mul_div, div_le_iff₀ hd']
    rw [div_le_div_iff₀ hd' hL] at h1
    linarith
  rw [modelPressure_three_two (zero_mem_window h)]
  linarith

/-- **The pressure at a rational `t` is nonpositive, decided by an integer comparison.** -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelPressure_nonpos_of_pow (h : c.ok = true) {v : ℝ}
    (hv' : (c.a : ℝ) / (c.b : ℝ) ≤ v) {n d : ℕ} (hd : 0 < d)
    (hpow : v ^ d ≤ ((3 : ℝ) / 2) ^ n) : modelPressure 3 2 c.window ((n : ℝ) / d) ≤ 0 := by
  have hL := log_three_halves_pos
  have hd' : (0 : ℝ) < d := by exact_mod_cast hd
  have hv : (0 : ℝ) < v := lt_of_lt_of_le (ratio_pos h) hv'
  have h1 : Real.log v / Real.log (3 / 2) ≤ (n : ℝ) / d :=
    log_div_log_le_div (by norm_num) hv hd hpow
  have h2 : phiModel 3 2 c.window ≤ Real.log v :=
    le_trans (Z32.EntropyCert.TypeCert.mem_Icc h).2 (Real.log_le_log (ratio_pos h) hv')
  have h3 : Real.log v ≤ ((n : ℝ) / d) * Real.log (3 / 2) := by
    rw [div_mul_eq_mul_div, le_div_iff₀ hd']
    rw [div_le_div_iff₀ hL hd'] at h1
    linarith
  rw [modelPressure_three_two (zero_mem_window h)]
  linarith

/-- **The Bowen zero, bracketed by two integer comparisons.**  Run the sign test at `n₁/d₁` and at
`n₂/d₂`; monotonicity of the pressure does the rest. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelBowen_mem_Icc_of_pow (h : c.ok = true) {u v : ℝ} (hu : 0 < u)
    (hu' : u ≤ (c.a' : ℝ) / (c.b' : ℝ)) (hv' : (c.a : ℝ) / (c.b : ℝ) ≤ v)
    {n₁ d₁ n₂ d₂ : ℕ} (hd₁ : 0 < d₁) (hd₂ : 0 < d₂)
    (hp₁ : ((3 : ℝ) / 2) ^ n₁ ≤ u ^ d₁) (hp₂ : v ^ d₂ ≤ ((3 : ℝ) / 2) ^ n₂) :
    modelBowen c.window ∈ Set.Icc ((n₁ : ℝ) / d₁) ((n₂ : ℝ) / d₂) :=
  modelBowen_mem_Icc (zero_mem_window h)
    (modelPressure_nonneg_of_pow h hu hu' hd₁ hp₁)
    (modelPressure_nonpos_of_pow h hv' hd₂ hp₂)

/-- The same for the exponent in an arbitrary base `r > 1` — the dyadic reading is `r = 2`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem modelExponent_mem_Icc_of_pow (h : c.ok = true) {r u v : ℝ} (hr : 1 < r) (hu : 0 < u)
    (hu' : u ≤ (c.a' : ℝ) / (c.b' : ℝ)) (hv' : (c.a : ℝ) / (c.b : ℝ) ≤ v)
    {n₁ d₁ n₂ d₂ : ℕ} (hd₁ : 0 < d₁) (hd₂ : 0 < d₂)
    (hp₁ : r ^ n₁ ≤ u ^ d₁) (hp₂ : v ^ d₂ ≤ r ^ n₂) :
    modelExponent 3 2 c.window r ∈ Set.Icc ((n₁ : ℝ) / d₁) ((n₂ : ℝ) / d₂) := by
  have hlr : 0 < Real.log r := Real.log_pos hr
  have hv : (0 : ℝ) < v := lt_of_lt_of_le (ratio_pos h) hv'
  have hb := Z32.EntropyCert.TypeCert.mem_Icc h
  constructor
  · calc (n₁ : ℝ) / d₁ ≤ Real.log u / Real.log r := div_le_log_div_log hr hu hd₁ hp₁
      _ ≤ modelExponent 3 2 c.window r := by
          rw [modelExponent]
          gcongr
          exact le_trans (Real.log_le_log hu hu') hb.1
  · calc modelExponent 3 2 c.window r ≤ Real.log v / Real.log r := by
          rw [modelExponent]
          gcongr
          exact le_trans hb.2 (Real.log_le_log (ratio_pos h) hv')
      _ ≤ (n₂ : ℝ) / d₂ := log_div_log_le_div hr hv hd₂ hp₂

/-! ### The weighted transfer operator, and why it factors

`PathGrowth.psum c.E (fun _ => θ) g` is the `θ`-weighted transfer operator of the type graph.  A
constant weight is all a single-slope map produces, and it factors out. -/

/-- Weighting every edge by `θ` multiplies the count by exactly `θ^k` — combined with
`card_modelLang_eq`, the operator statement of "the pressure is affine". -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem psum_eq_card_modelLang (h : c.ok = true) (θ k : ℕ) :
    PathGrowth.psum c.E (fun _ => θ) (fun _ => 1) c.L k
      = θ ^ k * Nat.card (modelLang 3 2 c.window k) := by
  rw [PathGrowth.psum_const (deterministic h) θ k c.L, card_modelLang_eq h k]

/-- The upper certificate transports to the `θ`-weighted operator with the ratio multiplied by
`θ`.  (The general lemma is `PathGrowth.psum_le_pow`; only the row inequality is re-checked.) -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem weighted_psum_le (h : c.ok = true) (θ k : ℕ) :
    ((PathGrowth.psum c.E (fun _ => θ) c.wt c.L k : ℕ) : ℝ)
      ≤ (((θ * c.a : ℕ) : ℝ) / (c.b : ℝ)) ^ k * (c.wt c.L : ℝ) := by
  refine PathGrowth.psum_le_pow c.E _ c.wt c.wt (θ * c.a) c.b (b_pos h) (fun _ => le_refl _)
    (fun x => ?_) k c.L
  calc c.b * ∑ e ∈ PathGrowth.outEdges c.E x, θ * c.wt e.2.2
      = θ * (c.b * ∑ e ∈ PathGrowth.outEdges c.E x, c.wt e.2.2) := by
        rw [← Finset.mul_sum]; ring
    _ ≤ θ * (c.a * c.wt x) := Nat.mul_le_mul_left _ (cert_upper h x)
    _ = θ * c.a * c.wt x := by ring

/-- The lower certificate likewise. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem weighted_le_psum (h : c.ok = true) (θ k : ℕ) :
    (((θ * c.a' : ℕ) : ℝ) / (c.b' : ℝ)) ^ k * (c.wt0 c.L : ℝ)
      ≤ ((PathGrowth.psum c.E (fun _ => θ) c.wt0 c.L k : ℕ) : ℝ) := by
  refine PathGrowth.pow_le_psum c.E _ c.wt0 c.wt0 (θ * c.a') c.b' (b'_pos h) (fun _ => le_refl _)
    (fun x => ?_) k c.L
  calc θ * c.a' * c.wt0 x = θ * (c.a' * c.wt0 x) := by ring
    _ ≤ θ * (c.b' * ∑ e ∈ PathGrowth.outEdges c.E x, c.wt0 e.2.2) :=
        Nat.mul_le_mul_left _ (cert_lower h x)
    _ = c.b' * ∑ e ∈ PathGrowth.outEdges c.E x, θ * c.wt0 e.2.2 := by
        rw [← Finset.mul_sum]; ring

end TypeCert

/-! ## The Z-cell: the exact endpoint of the family -/

@[category API, AMS 11 37, ref "Fla92", group "z32_model_pressure"]
theorem zero_mem_zCell : (0 : ℝ) ∈ Flatto.zCell := by
  simp [Flatto.zCell]

/-- **The pressure at the Z-cell, exactly.**  `P(t) = (1 − t)·log(3/2)`, so the Bowen zero is
`t = 1`. -/
@[category research solved, AMS 11 37, ref "Fla92" "Dub09AA", group "z32_model_pressure",
  formal_uses modelPressure_three_two]
theorem modelPressure_zCell (t : ℝ) :
    modelPressure 3 2 Flatto.zCell t = (1 - t) * Real.log (3 / 2) := by
  rw [modelPressure_three_two zero_mem_zCell, Flatto.phiModel_zCell]
  ring

/-- **The conformal exponent saturates at the Z-cell**: the Bowen zero is exactly `1`.  This is
plan-B10's F2 wall in dimension language — the model's own geometry cannot see anything below the
top of the window family, which is why the informative reading is the dyadic one below. -/
@[category research solved, AMS 11 37, ref "Fla92" "Dub09AA", group "z32_model_pressure",
  formal_uses modelPressure_zCell]
theorem modelBowen_zCell : modelBowen Flatto.zCell = 1 := by
  rw [modelBowen, modelExponent, Flatto.phiModel_zCell]
  exact div_self (ne_of_gt log_three_halves_pos)

/-- **The dyadic exponent at the Z-cell is exactly `log₂(3/2) = 0.5849…`** — Flatto's `s₀`, and the
`0.585` that plan-B10's wall and Table C's M3¾ constant both name. -/
@[category research solved, AMS 11 37, ref "Fla92", group "z32_model_pressure",
  formal_uses flattoExponent_eq modelBowen_zCell]
theorem flattoExponent_zCell : flattoExponent Flatto.zCell = Real.logb 2 (3 / 2) := by
  rw [flattoExponent_eq, modelBowen_zCell, one_mul]

/-! ## The atlas

Seven windows, each with its Bowen zero and its dyadic exponent bracketed to seven decimals.  The
data is generated by `Z32/pressure.py`; each row is two `norm_num` comparisons of integers, and
carries no floating point at any stage. -/

/-- The Bowen zero of `[0, 2/5)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem bowen_two_fifths_mem_Icc :
    modelBowen (Set.Ico (0 : ℝ) (2 / 5)) ∈
      Set.Icc ((2321 : ℝ) / 3276) ((2513 : ℝ) / 3547) := by
  have h := TypeCert.modelBowen_mem_Icc_of_pow (c := EntropyCert.cert25) EntropyCert.cert25_ok
    (u := 54512 / 40901) (v := 116241 / 87217) (n₁ := 2321) (d₁ := 3276) (n₂ := 2513) (d₂ := 3547)
    (by norm_num) (by norm_num [EntropyCert.cert25]) (by norm_num [EntropyCert.cert25])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert25_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The dyadic exponent of `[0, 2/5)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem flatto_two_fifths_mem_Icc :
    flattoExponent (Set.Ico (0 : ℝ) (2 / 5)) ∈
      Set.Icc ((1441 : ℝ) / 3477) ((3037 : ℝ) / 7328) := by
  have h := TypeCert.modelExponent_mem_Icc_of_pow (c := EntropyCert.cert25) EntropyCert.cert25_ok
    (r := 2) (u := 54512 / 40901) (v := 116241 / 87217)
    (n₁ := 1441) (d₁ := 3477) (n₂ := 3037) (d₂ := 7328) (by norm_num) (by norm_num)
    (by norm_num [EntropyCert.cert25]) (by norm_num [EntropyCert.cert25])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert25_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The Bowen zero of `[0, 13/32)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem bowen_thirteen_32_mem_Icc :
    modelBowen (Set.Ico (0 : ℝ) (13 / 32)) ∈
      Set.Icc ((3239 : ℝ) / 4293) ((3912 : ℝ) / 5185) := by
  have h := TypeCert.modelBowen_mem_Icc_of_pow (c := EntropyCert.cert1332)
    EntropyCert.cert1332_ok (u := 76611 / 56420) (v := 116383 / 85710)
    (n₁ := 3239) (d₁ := 4293) (n₂ := 3912) (d₂ := 5185)
    (by norm_num) (by norm_num [EntropyCert.cert1332]) (by norm_num [EntropyCert.cert1332])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert1332_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The dyadic exponent of `[0, 13/32)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem flatto_thirteen_32_mem_Icc :
    flattoExponent (Set.Ico (0 : ℝ) (13 / 32)) ∈
      Set.Icc ((3006 : ℝ) / 6811) ((2389 : ℝ) / 5413) := by
  have h := TypeCert.modelExponent_mem_Icc_of_pow (c := EntropyCert.cert1332)
    EntropyCert.cert1332_ok (r := 2) (u := 76611 / 56420) (v := 116383 / 85710)
    (n₁ := 3006) (d₁ := 6811) (n₂ := 2389) (d₂ := 5413) (by norm_num) (by norm_num)
    (by norm_num [EntropyCert.cert1332]) (by norm_num [EntropyCert.cert1332])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert1332_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- **The flagship.**  The Bowen zero of `[0, 5/12)` is `0.7948516…` — the pressure form of
`Z32.EntropyCert.phiModel_band_mem_Icc`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem bowen_band_mem_Icc :
    modelBowen (Set.Ico (0 : ℝ) (5 / 12)) ∈
      Set.Icc ((4045 : ℝ) / 5089) ((5064 : ℝ) / 6371) := by
  have h := TypeCert.modelBowen_mem_Icc_of_pow (c := EntropyCert.certBand)
    EntropyCert.certBand_ok (u := 131782 / 95475) (v := 42467 / 30767)
    (n₁ := 4045) (d₁ := 5089) (n₂ := 5064) (d₂ := 6371)
    (by norm_num) (by norm_num [EntropyCert.certBand]) (by norm_num [EntropyCert.certBand])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.certBand_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The dyadic exponent of `[0, 5/12)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem flatto_band_mem_Icc :
    flattoExponent (Set.Ico (0 : ℝ) (5 / 12)) ∈
      Set.Icc ((2123 : ℝ) / 4566) ((2740 : ℝ) / 5893) := by
  have h := TypeCert.modelExponent_mem_Icc_of_pow (c := EntropyCert.certBand)
    EntropyCert.certBand_ok (r := 2) (u := 131782 / 95475) (v := 42467 / 30767)
    (n₁ := 2123) (d₁ := 4566) (n₂ := 2740) (d₂ := 5893) (by norm_num) (by norm_num)
    (by norm_num [EntropyCert.certBand]) (by norm_num [EntropyCert.certBand])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.certBand_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The Bowen zero of `[0, 7/16)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem bowen_seven_16_mem_Icc :
    modelBowen (Set.Ico (0 : ℝ) (7 / 16)) ∈
      Set.Icc ((1110 : ℝ) / 1339) ((8119 : ℝ) / 9794) := by
  have h := TypeCert.modelBowen_mem_Icc_of_pow (c := EntropyCert.cert716) EntropyCert.cert716_ok
    (u := 85447 / 61055) (v := 95133 / 67976) (n₁ := 1110) (d₁ := 1339) (n₂ := 8119) (d₂ := 9794)
    (by norm_num) (by norm_num [EntropyCert.cert716]) (by norm_num [EntropyCert.cert716])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert716_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The dyadic exponent of `[0, 7/16)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem flatto_seven_16_mem_Icc :
    flattoExponent (Set.Ico (0 : ℝ) (7 / 16)) ∈
      Set.Icc ((1431 : ℝ) / 2951) ((3473 : ℝ) / 7162) := by
  have h := TypeCert.modelExponent_mem_Icc_of_pow (c := EntropyCert.cert716)
    EntropyCert.cert716_ok (r := 2) (u := 85447 / 61055) (v := 95133 / 67976)
    (n₁ := 1431) (d₁ := 2951) (n₂ := 3473) (d₂ := 7162) (by norm_num) (by norm_num)
    (by norm_num [EntropyCert.cert716]) (by norm_num [EntropyCert.cert716])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert716_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The Bowen zero of `[0, 9/20)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem bowen_nine_20_mem_Icc :
    modelBowen (Set.Ico (0 : ℝ) (9 / 20)) ∈
      Set.Icc ((4159 : ℝ) / 4742) ((6185 : ℝ) / 7052) := by
  have h := TypeCert.modelBowen_mem_Icc_of_pow (c := EntropyCert.cert920) EntropyCert.cert920_ok
    (u := 61599 / 43165) (v := 103115 / 72257) (n₁ := 4159) (d₁ := 4742) (n₂ := 6185) (d₂ := 7052)
    (by norm_num) (by norm_num [EntropyCert.cert920]) (by norm_num [EntropyCert.cert920])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert920_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The dyadic exponent of `[0, 9/20)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem flatto_nine_20_mem_Icc :
    flattoExponent (Set.Ico (0 : ℝ) (9 / 20)) ∈
      Set.Icc ((3107 : ℝ) / 6056) ((2989 : ℝ) / 5826) := by
  have h := TypeCert.modelExponent_mem_Icc_of_pow (c := EntropyCert.cert920)
    EntropyCert.cert920_ok (r := 2) (u := 61599 / 43165) (v := 103115 / 72257)
    (n₁ := 3107) (d₁ := 6056) (n₂ := 2989) (d₂ := 5826) (by norm_num) (by norm_num)
    (by norm_num [EntropyCert.cert920]) (by norm_num [EntropyCert.cert920])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert920_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The Bowen zero of `[0, 11/24)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem bowen_eleven_24_mem_Icc :
    modelBowen (Set.Ico (0 : ℝ) (11 / 24)) ∈
      Set.Icc ((8555 : ℝ) / 9479) ((7481 : ℝ) / 8289) := by
  have h := TypeCert.modelBowen_mem_Icc_of_pow (c := EntropyCert.cert1124)
    EntropyCert.cert1124_ok (u := 34912 / 24213) (v := 87187 / 60468)
    (n₁ := 8555) (d₁ := 9479) (n₂ := 7481) (d₂ := 8289)
    (by norm_num) (by norm_num [EntropyCert.cert1124]) (by norm_num [EntropyCert.cert1124])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert1124_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The dyadic exponent of `[0, 11/24)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem flatto_eleven_24_mem_Icc :
    flattoExponent (Set.Ico (0 : ℝ) (11 / 24)) ∈
      Set.Icc ((4941 : ℝ) / 9359) ((359 : ℝ) / 680) := by
  have h := TypeCert.modelExponent_mem_Icc_of_pow (c := EntropyCert.cert1124)
    EntropyCert.cert1124_ok (r := 2) (u := 34912 / 24213) (v := 87187 / 60468)
    (n₁ := 4941) (d₁ := 9359) (n₂ := 359) (d₂ := 680) (by norm_num) (by norm_num)
    (by norm_num [EntropyCert.cert1124]) (by norm_num [EntropyCert.cert1124])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert1124_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The Bowen zero of `[0, 23/48)`, the top of the shipped band. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem bowen_top_band_mem_Icc :
    modelBowen (Set.Ico (0 : ℝ) (23 / 48)) ∈
      Set.Icc ((3885 : ℝ) / 4121) ((3671 : ℝ) / 3894) := by
  have h := TypeCert.modelBowen_mem_Icc_of_pow (c := EntropyCert.cert2348)
    EntropyCert.cert2348_ok (u := 138070 / 94209) (v := 131025 / 89402)
    (n₁ := 3885) (d₁ := 4121) (n₂ := 3671) (d₂ := 3894)
    (by norm_num) (by norm_num [EntropyCert.cert2348]) (by norm_num [EntropyCert.cert2348])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert2348_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

/-- The dyadic exponent of `[0, 23/48)`: `0.5514630…`, already within `0.034` of the Z-cell's
`log₂(3/2)`. -/
@[category research solved, AMS 11 37, ref "Dub09AA" "Fla92", group "z32_model_pressure"]
theorem flatto_top_band_mem_Icc :
    flattoExponent (Set.Ico (0 : ℝ) (23 / 48)) ∈
      Set.Icc ((2695 : ℝ) / 4887) ((4881 : ℝ) / 8851) := by
  have h := TypeCert.modelExponent_mem_Icc_of_pow (c := EntropyCert.cert2348)
    EntropyCert.cert2348_ok (r := 2) (u := 138070 / 94209) (v := 131025 / 89402)
    (n₁ := 2695) (d₁ := 4887) (n₂ := 4881) (d₂ := 8851) (by norm_num) (by norm_num)
    (by norm_num [EntropyCert.cert2348]) (by norm_num [EntropyCert.cert2348])
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  rw [EntropyCert.cert2348_window] at h
  exact ⟨le_trans (le_of_eq (by norm_num)) h.1, le_trans h.2 (le_of_eq (by norm_num))⟩

end Z32.Pressure
