/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import CC.Parity
import Mathlib.Dynamics.Ergodic.Ergodic
import Mathlib.MeasureTheory.Group.Measure
import Mathlib.NumberTheory.Padics.RingHoms
import Mathlib.Probability.ProductMeasure
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Bernstein–Lagarias — The 3x+1 map and the 2-adic shift (BL96, §1)

Daniel J. Bernstein and Jeffrey C. Lagarias, *The 3x+1 conjugacy map*, Canadian Journal of
Mathematics **48** (1996), no. 6, 1154–1169.

Foundation file for the `BL` corpus. It formalises the opening statements of the paper (§1): the
3x+1 function `(1.1)`, its extension to the 2-adic integers, the 2-adic shift map `(1.2)`, the
ergodic theory of the 3x+1 map, and the topological conjugacy `(1.3)` between the two maps.

## The 3x+1 function (1.1)

The **3x+1 function** is `T(x) = (3x+1)/2` for `x ≡ 1 (mod 2)` and `T(x) = x/2` for `x ≡ 0 (mod 2)`,
on the integers `ℤ`. On `ℕ` this is `CC.T` (from `CC.Parity`, which re-exports
`CC.Terras`), written in the compact form `T n = (n·3^{X n} + X n) / 2` with `X n = n mod 2`. The
parity-vector machinery of `CC.Parity` (`V`, `E_vec`, `q`, `num_odd_steps`) is used for the bridges
below. The **3x+1 Conjecture** asserts
that for each positive integer `n` some iterate `Tᵏ(n)` equals `1`, i.e. every orbit on the positive
integers reaches the cycle `{1, 2}` (`T 1 = 2`, `T 2 = 1`). We do not name the conjecture; where it
is needed it is written inline as `∀ n, 0 < n → ∃ j, T_iter j n = 1` (`CC.T_iter`).

## The 2-adic integers `ℤ₂`: the 3x+1 map and the shift

Both maps extend/live on the domain `ℤ₂ = ℤ_[2]` of 2-adic integers, where each is "an even
numerator, halved" (`ℤ₂` is a domain, so halving an even element is unique — `half`):

* the **3x+1 map** `(1.1)` extends to `T₂`, with even numerator `x·3^{parity x} + parity x`
  (`two_mul_T₂ : 2·T₂ x = numer x`); it agrees with the integer map on `ℕ ⊂ ℤ₂`
  (`T₂_natCast : T₂ ↑n = ↑(CC.T n)`).
* the **2-adic shift map** `(1.2)` `S(x) = (x-1)/2` for `x ≡ 1`, `S(x) = x/2` for `x ≡ 0`, with even
  numerator `x - parity x` (`two_mul_S : 2·S x = x - parity x`). It deletes the lowest binary digit:
  `S(∑ bᵢ2ⁱ) = ∑ bᵢ₊₁2ⁱ`, equivalently `x = parity x + 2·(S x)` (`parity_add_two_mul_S`); on
  `ℕ ⊂ ℤ₂` it is `n ↦ ⌊n/2⌋` (`S_natCast`).

## Dynamics and conjugacy

Bernstein and Lagarias recall that `T₂` is **measure-preserving** on `ℤ₂` for the 2-adic (Haar,
normalised) measure and is **strongly mixing**, hence **ergodic**; this is [Lag85] (the paper's
reference [8]). We define `StronglyMixing` and prove (sorry-free) that it implies ergodicity
(`StronglyMixing.ergodic`); strong mixing of `T₂` is the single cited `axiom` `T₂_stronglyMixing`,
from which `T₂_measurePreserving` and `T₂_ergodic` are **derived**. *More is true* `(1.3)`: `T` is
topologically conjugate to the shift `S` — there is a homeomorphism `Φ : ℤ₂ → ℤ₂` with
`Φ ∘ S ∘ Φ⁻¹ = T` (`exists_conjugacy`). This `Φ` is the titular **3x+1 conjugacy map**; its explicit
construction (the parity-vector map) is the subject of the later sections. In fact this `Φ` can be
taken **measure-preserving** for the 2-adic measure, so `T` is **metrically conjugate** to `S` — now
**proved** as `exists_metric_conjugacy` in `BL.MetricConjugacy` (the constructed `Φ` is a 2-adic
isometry, and a surjective isometry of `ℤ₂` preserves the Haar measure); and as the 2-adic shift is
the one-sided Bernoulli `(½,½)` shift (`S_bernoulli`, cited [Kin09] — the classical p-adic digit fact,
against the genuine product-measure model `IsBernoulli`), `T` is **Bernoulli** — also **proved**, as
`T₂_bernoulli` (`BL.MetricConjugacy`). Thus the only cited `axiom`s among the dynamics are now the
genuinely deep / unconstructed inputs (`T₂_stronglyMixing` and `S_bernoulli`), per the corpus
literature-axiom policy; the metric conjugacy and Bernoulli conclusions are derived.

## Rigidity of `Φ`: the shift automorphism `V`

`Φ` is determined by `(1.3)` only **up to right-multiplication by an automorphism of `S`**
(`conjugacy_unique`). That automorphism group is `ℤ/2ℤ` ([Hed69, Thm 6.9], [BFK90];
`shiftAut_eq_id_or_V`), generated by the **bit-complement** `V x = -1 - x` (`-1 = …111₂`, so `V`
flips every binary digit). We define `V` and prove it is an involution (`V_involutive`) commuting
with `S` (`V_semiconj_S`), with `V ≠ id` (`V_ne_id`) — i.e. `Aut(S) = {id, V}`; so there are exactly
two conjugacy maps, `Φ` and `Φ ∘ V`.

## Link to the Collatz parity vectors (`CC.Parity`)

The **inverse** conjugacy map `Φ⁻¹` is Lagarias's **parity-vector map** `Q∞`: `Φ⁻¹ x` packs the
forward parity sequence `k ↦ parity (T₂ᵏ x)` of the `T₂`-orbit of `x` as its binary digits (the
explicit formula `(1.5)`, `BL.ConjugacyMap.Q`). On `ℕ ⊂ ℤ₂` this digit sequence is exactly the
Collatz parity vector of `CC.Parity`: the `k`-th 2-adic parity digit of the orbit of `n` equals the
`k`-th vector entry, `parity (T₂ᵏ ↑n) = X (Tᵏ n)` (`parity_T₂_iterate_natCast`), matching both the
`ℕ`-valued `E_vec` (`parity_T₂_iterate_eq_E_vec`) and the `Bool` word `V` (`getElem_V_eq_parity`);
the digit count is `num_odd_steps` (`num_odd_steps_eq_sum_parity`). These bridges (resting on
`T₂_iterate_natCast : T₂ᵏ ↑n = ↑(Tᵏ n)`) make `CC.Parity`'s finite parity vectors the truncations of
`Φ⁻¹` (the explicit `Q∞` of `(1.5)`, `BL.ConjugacyMap.Q`).

## Contents
* `parity`, `half`, `two_mul_half` — the parity `x mod 2` and the unique half of an even 2-adic integer.
* `numer`, `even_numer`, `T₂`, `two_mul_T₂`, `T₂_natCast` — the 3x+1 map on `ℤ₂` extending `(1.1)`.
* `shiftNumer`, `even_shiftNumer`, `S`, `two_mul_S`, `parity_add_two_mul_S`, `S_natCast` — the shift `(1.2)`.
* `parity_natCast`, `T₂_iterate_natCast`, `parity_T₂_iterate_natCast`, `parity_T₂_iterate_eq_E_vec`,
  `getElem_V_eq_parity`, `num_odd_steps_eq_sum_parity` — bridges to `CC.Parity`: the 2-adic parity
  digits of the `T₂`-orbit are the Collatz parity vectors (the `Q∞`/`Φ⁻¹` truncations).
* `StronglyMixing`, `StronglyMixing.ergodic` — strong mixing and the (proved) implication to ergodicity.
* `seqShift`, `uniformBool`, `bernoulliSeqMeasure`, `IsBernoulli` — the one-sided Bernoulli `(½,½)`
  shift on `ℕ → Bool` and the "is a Bernoulli system" predicate.
* `T₂_stronglyMixing` (cited) ⇒ `T₂_measurePreserving`, `T₂_ergodic` (derived): `T₂`'s 2-adic dynamics.
* `(1.3)` `T₂` is topologically conjugate to the shift `S` — now **proved** as `exists_conjugacy`
  in `BL.ConjugacyMap` (via the `qMap` construction), no longer a cited axiom here.
* `S_bernoulli` — cited [Kin09]: the 2-adic shift `S` is the one-sided Bernoulli `(½,½)` shift.
* `exists_metric_conjugacy`, `T₂_bernoulli` — now **proved** downstream in `BL.MetricConjugacy`
  (the conjugacy `Φ` is measure-preserving, so `T` is metrically conjugate to `S` and `T₂` is Bernoulli).
* `V`, `V_apply_zero`, `V_involutive`, `parity_V`, `V_semiconj_S`, `V_ne_id` — the shift automorphism
  `V x = -1 - x` (bit-complement): proved to be an involution flipping parity and commuting with `S`.
* `shiftAut_eq_id_or_V` — cited: `Aut(S) ≅ ℤ/2ℤ = {id, V}`.
* `conjugacy_unique` — **proved** (general fact about conjugacies, Mathlib only): `Φ` is unique up to
  right-multiplication by `Aut(S)`.

## References
* [BL96] Bernstein, Daniel J., and Jeffrey C. Lagarias. *The 3x+1 conjugacy map.* Canadian Journal
  of Mathematics 48 (1996), no. 6, 1154–1169.
* [Kin09] Kingsbery, James, et al. "Dynamics of the $ p $-adic shift and applications."
  arXiv preprint arXiv:0903.4226 (2009).
* [Lag85] Lagarias, Jeffrey C. *The 3x+1 problem and its generalizations.* American Mathematical
  Monthly 92 (1985), no. 1, 3–23 (the paper's reference [8]: `T` is measure-preserving and ergodic
  on `ℤ₂`).
* [Hed69] Hedlund, Gustav A. *Endomorphisms and automorphisms of the shift dynamical system.*
  Mathematical Systems Theory 3 (1969), no. 4, 320–375 (the paper's reference [6]: `Aut(S) ≅ ℤ/2ℤ`,
  Theorem 6.9).
* [BFK90] Boyle, Mike, John Franks, and Bruce Kitchens. *Automorphisms of one-sided subshifts of
  finite type.* Ergodic Theory and Dynamical Systems 10 (1990), no. 3, 421–449 (the paper's
  reference [3]).
* [Ter76] Terras, Riho. *A stopping time problem on the positive integers.* Acta Arithmetica 30
  (1976), 241–252 (the map `T = CC.T`, via `CC.Parity ⊃ CC.Terras`).
-/

namespace BL

open PadicInt MeasureTheory Filter Topology

/-- The **parity** of a 2-adic integer: `0` if even, `1` if odd — the value of `x mod 2` under the
residue map `ℤ₂ → ZMod 2`. The 2-adic analogue of `CC.X` on `ℕ`. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def parity (x : ℤ_[2]) : ℕ := (PadicInt.toZMod x).val

/-- The residue of the (cast) parity equals the residue of `x`: `toZMod ↑(parity x) = toZMod x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem toZMod_natCast_parity (x : ℤ_[2]) :
    PadicInt.toZMod ((parity x : ℤ_[2])) = PadicInt.toZMod x := by
  unfold parity; rw [map_natCast, ZMod.natCast_val, ZMod.cast_id]

/-- On `ℕ ⊂ ℤ₂` the 2-adic parity is the Collatz parity `CC.X`: `parity ↑n = X n`
(`= n mod 2`). Base case of the parity-vector bridge to `CC.Parity`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_natCast (n : ℕ) : parity (n : ℤ_[2]) = CC.X n := by
  unfold parity; rw [map_natCast, ZMod.val_natCast, CC.X_eq_mod]

/-- The unique **half** of an even 2-adic integer (`ℤ₂` is a domain, so `2·y = x` has at most one
solution). Used to define both the 3x+1 map and the shift as "even numerator, halved". -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def half {x : ℤ_[2]} (h : (2 : ℤ_[2]) ∣ x) : ℤ_[2] := h.choose

/-- Defining property of `half`: `2 · half h = x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem two_mul_half {x : ℤ_[2]} (h : (2 : ℤ_[2]) ∣ x) : 2 * half h = x := h.choose_spec.symm

/-! ### The 3x+1 map on `ℤ₂` (extension of (1.1)) -/

/-- The **numerator** `x · 3^{parity x} + parity x` of the 3x+1 map (cf. the `ℕ` form
`n·3^{X n} + X n = 2·T n`). It is always even, so the 3x+1 map `T₂` is `numer / 2`. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def numer (x : ℤ_[2]) : ℤ_[2] := x * 3 ^ parity x + (parity x : ℤ_[2])

/-- The numerator `x·3^{parity x} + parity x` is even in `ℤ₂`: modulo `2` it is `x + x ≡ 0`, since
`3 ≡ 1`. Hence `T₂` is well defined. -/
@[category API, AMS 11 37, ref "BL96"]
theorem even_numer (x : ℤ_[2]) : (2 : ℤ_[2]) ∣ numer x := by
  have h3 : PadicInt.toZMod (3 : ℤ_[2]) = 1 := by
    have : (3 : ℤ_[2]) = ((3 : ℕ) : ℤ_[2]) := by norm_num
    rw [this, map_natCast]; decide
  have hz : PadicInt.toZMod (numer x) = 0 := by
    unfold numer
    rw [map_add, map_mul, map_pow, h3, one_pow, mul_one, toZMod_natCast_parity]
    exact CharTwo.add_self_eq_zero _
  have hk : numer x ∈ RingHom.ker (PadicInt.toZMod (p := 2)) := hz
  rw [PadicInt.ker_toZMod, PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hk
  simpa using hk

/-- The **3x+1 function on the 2-adic integers** `ℤ₂`, the extension of `(1.1)`/`CC.T`
to `ℤ_[2]`: `T₂ x` is the (unique) half of the even numerator `numer x`. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def T₂ (x : ℤ_[2]) : ℤ_[2] := half (even_numer x)

/-- Defining identity of `T₂`: `2 · T₂ x = x · 3^{parity x} + parity x`. On odd `x` this is
`2·T₂ x = 3x+1`, on even `x` it is `2·T₂ x = x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem two_mul_T₂ (x : ℤ_[2]) : 2 * T₂ x = numer x := two_mul_half (even_numer x)

/-- `T₂` extends the integer map: on `ℕ ⊂ ℤ₂` it agrees with `CC.T`. So `(1.1)` really
is the restriction of `T₂` to the integers. -/
@[category API, AMS 11 37, ref "BL96"]
theorem T₂_natCast (n : ℕ) : T₂ (n : ℤ_[2]) = (CC.T n : ℤ_[2]) := by
  have hcancel : (2 : ℤ_[2]) * T₂ (n : ℤ_[2]) = 2 * (CC.T n : ℤ_[2]) := by
    rw [two_mul_T₂]
    unfold numer
    rw [parity_natCast]
    have hexp := CC.T_expand n
    have hcast : 2 * ((CC.T n : ℕ) : ℤ_[2])
        = ((3 ^ CC.X n * n + CC.X n : ℕ) : ℤ_[2]) := by
      rw [← hexp]; push_cast; ring
    rw [hcast]; push_cast; ring
  exact mul_left_cancel₀ (by norm_num) hcancel

/-! ### The 2-adic shift map (1.2) -/

/-- The **numerator** `x - parity x` of the shift map: even (`x ≡ parity x mod 2`), so `S` is
`(x - parity x)/2` — i.e. `x/2` if even, `(x-1)/2` if odd. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def shiftNumer (x : ℤ_[2]) : ℤ_[2] := x - (parity x : ℤ_[2])

/-- The shift numerator `x - parity x` is even in `ℤ₂` (`x ≡ parity x mod 2`). -/
@[category API, AMS 11 37, ref "BL96"]
theorem even_shiftNumer (x : ℤ_[2]) : (2 : ℤ_[2]) ∣ shiftNumer x := by
  have hz : PadicInt.toZMod (shiftNumer x) = 0 := by
    unfold shiftNumer
    rw [map_sub, toZMod_natCast_parity, sub_self]
  have hk : shiftNumer x ∈ RingHom.ker (PadicInt.toZMod (p := 2)) := hz
  rw [PadicInt.ker_toZMod, PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hk
  simpa using hk

/-- The **2-adic shift map** `(1.2)` `S : ℤ₂ → ℤ₂`, `S(x) = (x-1)/2` for odd `x` and `x/2` for even
`x`: the (unique) half of the even numerator `x - parity x`. It deletes the lowest binary digit. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def S (x : ℤ_[2]) : ℤ_[2] := half (even_shiftNumer x)

/-- Defining identity of the shift: `2 · S x = x - parity x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem two_mul_S (x : ℤ_[2]) : 2 * S x = x - (parity x : ℤ_[2]) := two_mul_half (even_shiftNumer x)

/-- The shift deletes the lowest binary digit: `x = parity x + 2 · S x`. With `x = ∑ bᵢ2ⁱ` this says
`S x = ∑ bᵢ₊₁2ⁱ` (the lowest digit `b₀ = parity x` is dropped and the rest shift down). -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_add_two_mul_S (x : ℤ_[2]) : (parity x : ℤ_[2]) + 2 * S x = x := by
  rw [two_mul_S]; ring

/-- On `ℕ ⊂ ℤ₂` the shift is integer division by `2`: `S ↑n = ↑⌊n/2⌋`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem S_natCast (n : ℕ) : S (n : ℤ_[2]) = ((n / 2 : ℕ) : ℤ_[2]) := by
  have hpar : parity (n : ℤ_[2]) = n % 2 := by unfold parity; rw [map_natCast, ZMod.val_natCast]
  have hcancel : (2 : ℤ_[2]) * S (n : ℤ_[2]) = 2 * ((n / 2 : ℕ) : ℤ_[2]) := by
    rw [two_mul_S, hpar, ← Nat.cast_sub (Nat.mod_le n 2)]
    have h2 : n - n % 2 = 2 * (n / 2) := by omega
    rw [h2]; push_cast; ring
  exact mul_left_cancel₀ (by norm_num) hcancel

/-! ### Bridges to the Collatz parity vectors (`CC.Parity`)

The inverse conjugacy map `Φ⁻¹`/`Q∞` sends `x` to the parity sequence `k ↦ parity (T₂ᵏ x)`. On `ℕ` these
digits are exactly `CC.Parity`'s finite parity vectors of the Collatz orbit. -/

/-- Iterating `T₂` on `ℕ ⊂ ℤ₂` is iterating the integer map: `T₂ᵏ ↑n = ↑(Tᵏ n)`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem T₂_iterate_natCast (k n : ℕ) :
    (T₂^[k]) (n : ℤ_[2]) = ((CC.T_iter k n : ℕ) : ℤ_[2]) := by
  induction k with
  | zero => rfl
  | succ k ih => rw [Function.iterate_succ', Function.comp_apply, ih, T₂_natCast]; rfl

/-- **Parity-vector bridge.** The `k`-th parity digit of the `T₂`-orbit of `↑n` is the `k`-th entry
of the Collatz parity vector: `parity (T₂ᵏ ↑n) = X (Tᵏ n)`. This is `Q∞`/`Φ⁻¹` (at digit `k`) on `ℕ`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_T₂_iterate_natCast (k n : ℕ) :
    parity (T₂^[k] (n : ℤ_[2])) = CC.X (CC.T_iter k n) := by
  rw [T₂_iterate_natCast, parity_natCast]

/-- The 2-adic parity digits of the `T₂`-orbit are the `ℕ`-valued parity vector `CC.Parity.E_vec`:
`parity (T₂ⁱ ↑n) = E_vec k n i`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_T₂_iterate_eq_E_vec (k n : ℕ) (i : Fin k) :
    parity (T₂^[i.val] (n : ℤ_[2])) = CC.E_vec k n i := by
  rw [parity_T₂_iterate_natCast, CC.E_vec_apply]

/-- The 2-adic parity digits are the `Bool` parity word `CC.Parity.V` (the literal `Q∞` truncation):
its `i`-th entry is `decide (parity (T₂ⁱ ↑n) = 1)`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem getElem_V_eq_parity (j n : ℕ) (i : Fin j) :
    (CC.V j n).get ⟨i.val, by simp⟩ = decide (parity (T₂^[i.val] (n : ℤ_[2])) = 1) := by
  rw [CC.V_get, parity_T₂_iterate_natCast]

/-- The number of odd Collatz iterates is the sum of the 2-adic parity digits of the `T₂`-orbit:
`num_odd_steps k n = ∑_{i<k} parity (T₂ⁱ ↑n)` (the weight `q` of the parity vector). -/
@[category API, AMS 11 37, ref "BL96"]
theorem num_odd_steps_eq_sum_parity (k n : ℕ) :
    CC.num_odd_steps k n = ∑ i ∈ Finset.range k, parity (T₂^[i] (n : ℤ_[2])) := by
  rw [CC.num_odd_steps]
  exact Finset.sum_congr rfl (fun i _ => (parity_T₂_iterate_natCast i n).symm)

/-! ### Strong mixing and Bernoulli systems (general)

General measure-theoretic notions (not specific to the 3x+1 map), used to state — and partly to
derive — the cited ergodic-theoretic facts about `T₂` below. -/

/-- A measure-preserving system `(f, μ)` is **strongly mixing** if `μ (f⁻ⁿ A ∩ B) → μ A · μ B` for
all measurable `A, B` (this bundles measure preservation). -/
@[category API, AMS 37 28, ref "BL96"]
def StronglyMixing {α : Type*} [MeasurableSpace α] (f : α → α) (μ : Measure α) : Prop :=
  MeasurePreserving f μ μ ∧ ∀ A B, MeasurableSet A → MeasurableSet B →
    Tendsto (fun n => μ (f^[n] ⁻¹' A ∩ B)) atTop (𝓝 (μ A * μ B))

/-- **Strong mixing implies ergodicity.** For an invariant set `s` (`f⁻¹ s = s`), mixing with
`A = B = s` gives `μ s = μ s · μ s`, forcing `μ s ∈ {0, 1}`. A genuine (sorry-free) proof. -/
@[category API, AMS 37 28, ref "BL96"]
theorem StronglyMixing.ergodic {α : Type*} [MeasurableSpace α] {f : α → α} {μ : Measure α}
    [IsProbabilityMeasure μ] (h : StronglyMixing f μ) : Ergodic f μ := by
  refine ⟨h.1, ⟨fun s hs hinv => ?_⟩⟩
  have hiter : ∀ n, f^[n] ⁻¹' s = s := by
    intro n
    induction n with
    | zero => simp
    | succ k ih => rw [Function.iterate_succ', Set.preimage_comp, hinv, ih]
  have hmix := h.2 s s hs hs
  have hconst : (fun n => μ (f^[n] ⁻¹' s ∩ s)) = fun _ => μ s := by
    funext n; rw [hiter n, Set.inter_self]
  rw [hconst] at hmix
  have huniq : μ s = μ s * μ s := tendsto_nhds_unique tendsto_const_nhds hmix
  have hdich : μ s = 0 ∨ μ s = 1 := by
    rcases eq_or_ne (μ s) 0 with h0 | h0
    · exact Or.inl h0
    · exact Or.inr ((ENNReal.mul_eq_left h0 (measure_ne_top μ s)).mp huniq.symm)
  rw [eventuallyConst_set]
  rcases hdich with h0 | hs1
  · exact Or.inr (by rw [ae_iff]; simpa using h0)
  · refine Or.inl (by rw [ae_iff, show {a | a ∉ s} = sᶜ from rfl,
      measure_compl hs (measure_ne_top μ s), measure_univ, hs1, tsub_self])

/-- The one-sided shift on `Bool`-sequences (drop the `0`th coordinate). -/
@[category API, AMS 37 28, ref "BL96"]
def seqShift (x : ℕ → Bool) : ℕ → Bool := fun n => x (n + 1)

/-- The uniform `(½,½)` measure on `Bool`. -/
@[category API, AMS 37 28, ref "BL96"]
noncomputable def uniformBool : Measure Bool :=
  (1 / 2 : ENNReal) • Measure.dirac true + (1 / 2 : ENNReal) • Measure.dirac false

/-- The one-sided **Bernoulli `(½,½)` measure** on `ℕ → Bool`: i.i.d. uniform binary digits. -/
@[category API, AMS 37 28, ref "BL96"]
noncomputable def bernoulliSeqMeasure : Measure (ℕ → Bool) :=
  Measure.infinitePi (fun _ => uniformBool)

/-- A measure-preserving system `(f, μ)` is **Bernoulli** if it is isomorphic — via a
measure-preserving measurable equivalence `e` intertwining the dynamics (`Semiconj e f seqShift`) —
to the one-sided Bernoulli `(½,½)` shift `(seqShift, bernoulliSeqMeasure)` on `ℕ → Bool`. -/
@[category API, AMS 37 28, ref "BL96"]
def IsBernoulli {α : Type*} [MeasurableSpace α] (f : α → α) (μ : Measure α) : Prop :=
  ∃ e : α ≃ᵐ (ℕ → Bool),
    MeasurePreserving (⇑e) μ bernoulliSeqMeasure ∧ Function.Semiconj (⇑e) f seqShift

/-! ### Ergodic theory and conjugacy of `T₂` (cited) -/

/-- **(Bernstein–Lagarias, §1; cited.)** The 3x+1 map `T₂` is **strongly mixing** on `ℤ₂` for the
2-adic measure (normalised additive Haar on the Borel `σ`-algebra). This is the paper's reference
[8] = [Lag85]; recorded as a cited `axiom`, from which measure preservation and ergodicity are
derived below. -/
@[category research solved, AMS 37 28, ref "BL96" "Lag85", group "bl_2adic_dynamics"]
axiom T₂_stronglyMixing [MeasurableSpace ℤ_[2]] [BorelSpace ℤ_[2]]
    (μ : Measure ℤ_[2]) [μ.IsAddHaarMeasure] [IsProbabilityMeasure μ] :
    StronglyMixing T₂ μ

/-- `T₂` is **measure-preserving** on `ℤ₂` for the 2-adic measure — the first component of strong
mixing (`T₂_stronglyMixing`). -/
@[category research solved, AMS 37 28, ref "BL96" "Lag85", group "bl_2adic_dynamics"]
theorem T₂_measurePreserving [MeasurableSpace ℤ_[2]] [BorelSpace ℤ_[2]]
    (μ : Measure ℤ_[2]) [μ.IsAddHaarMeasure] [IsProbabilityMeasure μ] :
    MeasurePreserving T₂ μ μ :=
  (T₂_stronglyMixing μ).1

/-- `T₂` is **ergodic** on `ℤ₂` for the 2-adic measure: it is strongly mixing
(`T₂_stronglyMixing`), hence ergodic by `StronglyMixing.ergodic`. (Genuinely derived, not assumed.) -/
@[category research solved, AMS 37 28, ref "BL96" "Lag85", group "bl_2adic_dynamics"]
theorem T₂_ergodic [MeasurableSpace ℤ_[2]] [BorelSpace ℤ_[2]]
    (μ : Measure ℤ_[2]) [μ.IsAddHaarMeasure] [IsProbabilityMeasure μ] :
    Ergodic T₂ μ :=
  (T₂_stronglyMixing μ).ergodic

-- **Theorem (1.3)** `exists_conjugacy` (the topological conjugacy `Φ ∘ S = T₂ ∘ Φ`, non-normalised)
-- is now **PROVED** and lives in `BL.ConjugacyMap` (discharged via the `BL.ParityVectorMap` `qMap`
-- construction), rather than a cited axiom here. The measure-preserving strengthening below stays cited.

-- **Metric conjugacy** `exists_metric_conjugacy` (the conjugacy `Φ` of `(1.3)` can be taken
-- **measure-preserving** for the 2-adic Haar measure) is now **PROVED** and lives downstream in
-- `BL.MetricConjugacy`, not a cited `axiom` here: `Φ` is a 2-adic isometry (`Φ_isometry`, from
-- `corollary_A3`), and a surjective isometry of `ℤ₂` preserves any finite left-invariant measure
-- (`ForMathlib.MeasureTheory.measurePreserving_of_surjective_isometry`). It must live below the
-- `Φ`-construction; the Bernoulli conclusion `T₂_bernoulli` it feeds moved there with it.

/-- **(classical; cited.)** **The 2-adic shift `S` is the one-sided Bernoulli `(½,½)` shift.** The
binary-digit expansion `ℤ₂ ≃ᵐ (ℕ → Bool)` carries the 2-adic (normalised Haar) measure to the i.i.d.
uniform product measure `bernoulliSeqMeasure` and intertwines `S` with the coordinate shift
`seqShift` (the lowest digit is dropped). This is the classical fact that the binary digits of a
Haar-random 2-adic integer are independent fair coin flips; BL96 §1 invokes it to conclude that
`T₂` is Bernoulli. Formalising the Haar-to-product pushforward is a separate undertaking, so the
statement is recorded as a cited `axiom`; the conclusion `T₂_bernoulli` is then **derived** from it. -/
@[category research solved, AMS 37 28, ref "Kin09", group "bl_conjugacy"]
axiom S_bernoulli [MeasurableSpace ℤ_[2]] [BorelSpace ℤ_[2]]
    (μ : Measure ℤ_[2]) [μ.IsAddHaarMeasure] [IsProbabilityMeasure μ] :
    IsBernoulli S μ

-- **`T₂_bernoulli`** (`T₂` is a **Bernoulli** system, against the product model `IsBernoulli`) is
-- **PROVED** downstream in `BL.MetricConjugacy` — it depends on the now-downstream
-- `exists_metric_conjugacy`. It transports the Bernoulli structure of `S` (`S_bernoulli`, above)
-- across the measure-preserving conjugacy `Φ` (the map `e ∘ Φ⁻¹` conjugates `(T₂, μ)` to the
-- Bernoulli shift, using `Φ⁻¹ ∘ T₂ = S ∘ Φ⁻¹`).

/-! ### The shift automorphism `V` and rigidity of `Φ`

The conjugacy `Φ` of `(1.3)` is unique only up to the automorphisms of the shift `S`. That
automorphism group is `ℤ/2ℤ`, generated by the bit-complement `V`. -/

/-- The nontrivial **automorphism of the shift** `S`: `V x = -1 - x`. As `-1 = …111` in `ℤ₂`, `V`
flips every binary digit (bit-complement). It is an involution (`V_involutive`) commuting with `S`
(`V_semiconj_S`), and `{id, V}` is the full automorphism group `Aut(S) ≅ ℤ/2ℤ`. -/
@[category API, AMS 37 11, ref "BL96"]
noncomputable def V (x : ℤ_[2]) : ℤ_[2] := -1 - x

/-- `V 0 = -1`; in particular `V ≠ id`. -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_apply_zero : V 0 = -1 := by show -1 - 0 = -1; ring

/-- `V` is an **involution**: `V (V x) = x`. So `⟨id, V⟩` is a `ℤ/2ℤ`. -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_involutive : Function.Involutive V := fun x => by show -1 - (-1 - x) = x; ring

/-- `V` **flips parity**: `parity x + parity (V x) = 1` (it complements the lowest — and every —
binary digit). -/
@[category API, AMS 37 11, ref "BL96"]
theorem parity_V (x : ℤ_[2]) : parity x + parity (V x) = 1 := by
  have hc : PadicInt.toZMod (V x) = -1 - PadicInt.toZMod x := by
    show PadicInt.toZMod (-1 - x) = -1 - PadicInt.toZMod x
    simp only [map_sub, map_one, map_neg]
  unfold parity
  rw [hc]
  generalize PadicInt.toZMod x = c
  revert c
  decide

/-- `V` is an **automorphism of the shift**: `V ∘ S = S ∘ V` (`Function.Semiconj V S S`). Proved via
`2 · V (S x) = 2 · S (V x)`, using that `V` flips parity (`parity_V`). -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_semiconj_S : Function.Semiconj V S S := by
  intro x
  have key : (parity x : ℤ_[2]) + (parity (V x) : ℤ_[2]) = 1 := by exact_mod_cast parity_V x
  have hL : (2 : ℤ_[2]) * V (S x) = -2 - (x - (parity x : ℤ_[2])) := by
    show (2 : ℤ_[2]) * (-1 - S x) = -2 - (x - (parity x : ℤ_[2]))
    rw [← two_mul_S x]; ring
  have hR : (2 : ℤ_[2]) * S (V x) = (-1 - x) - (parity (V x) : ℤ_[2]) := by
    rw [two_mul_S]; rfl
  refine mul_left_cancel₀ (a := (2 : ℤ_[2])) (by norm_num) ?_
  rw [hL, hR]; linear_combination key

/-- `V ≠ id` (they differ at `0`), so the shift automorphism group is genuinely nontrivial. -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_ne_id : V ≠ id := fun h => by
  have h0 : V 0 = (0 : ℤ_[2]) := by rw [h]; rfl
  rw [V_apply_zero] at h0; exact absurd h0 (by norm_num)

/-- **(cited; [6] = [Hed69], Theorem 6.9, and [3] = [BFK90].)** The **automorphism group of the
shift `S` is `ℤ/2ℤ`**: every homeomorphism of `ℤ₂` commuting with `S` is either the identity or the
bit-complement `V`. Together with `V_involutive`/`V_ne_id` this exhibits `Aut(S) = {id, V} ≅ ℤ/2ℤ`. -/
@[category research solved, AMS 37 11, ref "Hed69" "BFK90", group "bl_conjugacy"]
axiom shiftAut_eq_id_or_V (ψ : ℤ_[2] ≃ₜ ℤ_[2]) (hψ : Function.Semiconj (⇑ψ) S S) :
    ⇑ψ = id ∨ ⇑ψ = V

/-- **Rigidity of `Φ` (PROVED).** The conjugacy map `Φ` of `(1.3)` is determined **up to
right-multiplication by an automorphism of `S`**: any two solutions `Φ, Φ'` of `Φ ∘ S ∘ Φ⁻¹ = T₂`
satisfy `Φ' = Φ ∘ ψ` for some `ψ ∈ Aut(S)`. Take `ψ := Φ⁻¹ ∘ Φ'` (a homeomorphism, `Φ'.trans Φ.symm`):
then `Φ' = Φ ∘ ψ`, and `ψ` commutes with `S` because `Φ⁻¹ ∘ T₂ = S ∘ Φ⁻¹` (a rearrangement of `hΦ`),
so `ψ ∘ S = Φ⁻¹ ∘ T₂ ∘ Φ' = S ∘ Φ⁻¹ ∘ Φ' = S ∘ ψ`. With `shiftAut_eq_id_or_V` there are then exactly
two solutions: `Φ` and `Φ ∘ V`. (Formerly a cited `axiom`; this is a general fact about conjugacies,
needing only Mathlib.) -/
@[category research solved, AMS 37 11, ref "BL96", group "bl_conjugacy"]
theorem conjugacy_unique (Φ Φ' : ℤ_[2] ≃ₜ ℤ_[2])
    (hΦ : Function.Semiconj (⇑Φ) S T₂) (hΦ' : Function.Semiconj (⇑Φ') S T₂) :
    ∃ ψ : ℤ_[2] ≃ₜ ℤ_[2], Function.Semiconj (⇑ψ) S S ∧ ⇑Φ' = ⇑Φ ∘ ⇑ψ := by
  refine ⟨Φ'.trans Φ.symm, ?_, ?_⟩
  · intro x
    show Φ.symm (Φ' (S x)) = S (Φ.symm (Φ' x))
    rw [hΦ' x]
    have h := hΦ (Φ.symm (Φ' x))
    rw [Φ.apply_symm_apply] at h
    rw [← h, Φ.symm_apply_apply]
  · funext x
    show Φ' x = Φ (Φ.symm (Φ' x))
    rw [Φ.apply_symm_apply]

end BL
