/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import CC.Parity
import Mathlib.Dynamics.Ergodic.Ergodic
import Mathlib.MeasureTheory.Group.Measure
import Mathlib.NumberTheory.Padics.RingHoms
import ForMathlib.Dynamics.Bernoulli
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Bernstein–Lagarias — The 3x+1 map and the 2-adic shift (BL96, §1)

Daniel J. Bernstein and Jeffrey C. Lagarias, *The 3x+1 conjugacy map*, Canadian Journal of
Mathematics **48** (1996), no. 6, 1154–1169.

Foundation file for the `BL` corpus. It formalises the opening statements of the paper (§1): the
3x+1 function `(1.1)`, its extension to the 2-adic integers, the 2-adic shift map `(1.2)`, the
ergodic theory of the 3x+1 map, and the topological conjugacy `(1.3)` between the two maps.

## The 3x+1 function (1.1)

The **3x+1 function** is `T(x) = (3x+1)/2` for `x ≡ 1 (mod 2)` and `T(x) = x/2` for `x ≡ 0 (mod 2)`,
on the integers `ℤ`. On `ℕ` this is `CC.T` (from `CC.Parity`, which re-exports
`CC.Terras`), written in the compact form `T n = (n·3^{X n} + X n) / 2` with `X n = n mod 2`. The
parity-vector machinery of `CC.Parity` (`V`, `E_vec`, `q`, `num_odd_steps`) is used for the bridges
below. The **3x+1 Conjecture** asserts
that for each positive integer `n` some iterate `Tᵏ(n)` equals `1`, i.e. every orbit on the positive
integers reaches the cycle `{1, 2}` (`T 1 = 2`, `T 2 = 1`). We do not name the conjecture; where it
is needed it is written inline as `∀ n, 0 < n → ∃ j, T_iter j n = 1` (`CC.T_iter`).

## The 2-adic integers `ℤ₂`: the 3x+1 map and the shift

Both maps extend/live on the domain `ℤ₂ = ℤ_[2]` of 2-adic integers, where each is "an even
numerator, halved" (`ℤ₂` is a domain, so halving an even element is unique — `half`):

* the **3x+1 map** `(1.1)` extends to `T₂`, with even numerator `x·3^{parity x} + parity x`
  (`two_mul_T₂ : 2·T₂ x = numer x`); it agrees with the integer map on `ℕ ⊂ ℤ₂`
  (`T₂_natCast : T₂ ↑n = ↑(CC.T n)`).
* the **2-adic shift map** `(1.2)` `S(x) = (x-1)/2` for `x ≡ 1`, `S(x) = x/2` for `x ≡ 0`, with even
  numerator `x - parity x` (`two_mul_S : 2·S x = x - parity x`). It deletes the lowest binary digit:
  `S(∑ bᵢ2ⁱ) = ∑ bᵢ₊₁2ⁱ`, equivalently `x = parity x + 2·(S x)` (`parity_add_two_mul_S`); on
  `ℕ ⊂ ℤ₂` it is `n ↦ ⌊n/2⌋` (`S_natCast`).

## Dynamics and conjugacy

Bernstein and Lagarias recall that `T₂` is **measure-preserving** on `ℤ₂` for the 2-adic (Haar,
normalised) measure and is **strongly mixing**, hence **ergodic**; this is [Lag85] (the paper's
reference [8]). The general ergodic-theory notions are now in `ForMathlib`
(`MeasureTheory.IsStronglyMixing` with `IsStronglyMixing.ergodic`, and `MeasureTheory.IsBernoulli`
with `IsBernoulli.isStronglyMixing`); strong mixing of `T₂` itself (`T₂_stronglyMixing`, with
`T₂_measurePreserving` and `T₂_ergodic` derived from it) is **proved** downstream in
`BL.MetricConjugacy` — `T₂` is Bernoulli and any Bernoulli shift is strongly mixing [Quas09] — no
longer a cited axiom. *More is true* `(1.3)`: `T` is
topologically conjugate to the shift `S` — there is a homeomorphism `Φ : ℤ₂ → ℤ₂` with
`Φ ∘ S ∘ Φ⁻¹ = T` (`exists_conjugacy`). This `Φ` is the titular **3x+1 conjugacy map**; its explicit
construction (the parity-vector map) is the subject of the later sections. In fact this `Φ` can be
taken **measure-preserving** for the 2-adic measure, so `T` is **metrically conjugate** to `S` — now
**proved** as `exists_metric_conjugacy` in `BL.MetricConjugacy` (the constructed `Φ` is a 2-adic
isometry, and a surjective isometry of `ℤ₂` preserves the Haar measure); and as the 2-adic shift is
Bernoulli (`S_bernoulli`, cited [Kin09] — the classical p-adic digit fact, against the general
product-measure model `MeasureTheory.IsBernoulli`), `T` is **Bernoulli** — also **proved**, as
`T₂_bernoulli` (`BL.MetricConjugacy`). Thus the **only** cited `axiom` among the dynamics is now
`S_bernoulli` ([Kin09], the 2-adic shift is Bernoulli); the metric conjugacy, the mixing/ergodicity,
and the Bernoulli conclusion are all derived (mixing rests additionally on the cited [Quas09] fact
that a Bernoulli shift is strongly mixing, in `ForMathlib`).

## Rigidity of `Φ`: the shift automorphism `V`

`Φ` is determined by `(1.3)` only **up to right-multiplication by an automorphism of `S`**
(`conjugacy_unique`). That automorphism group is `ℤ/2ℤ` ([Hed69, Thm 6.9], [BFK90];
`shiftAut_eq_id_or_V`), generated by the **bit-complement** `V x = -1 - x` (`-1 = …111₂`, so `V`
flips every binary digit). We define `V` and prove it is an involution (`V_involutive`) commuting
with `S` (`V_semiconj_S`), with `V ≠ id` (`V_ne_id`) — i.e. `Aut(S) = {id, V}`; so there are exactly
two conjugacy maps, `Φ` and `Φ ∘ V`.

## Link to the Collatz parity vectors (`CC.Parity`)

The **inverse** conjugacy map `Φ⁻¹` is Lagarias's **parity-vector map** `Q∞`: `Φ⁻¹ x` packs the
forward parity sequence `k ↦ parity (T₂ᵏ x)` of the `T₂`-orbit of `x` as its binary digits (the
explicit formula `(1.5)`, `BL.ConjugacyMap.Q`). On `ℕ ⊂ ℤ₂` this digit sequence is exactly the
Collatz parity vector of `CC.Parity`: the `k`-th 2-adic parity digit of the orbit of `n` equals the
`k`-th vector entry, `parity (T₂ᵏ ↑n) = X (Tᵏ n)` (`parity_T₂_iterate_natCast`), matching both the
`ℕ`-valued `E_vec` (`parity_T₂_iterate_eq_E_vec`) and the `Bool` word `V` (`getElem_V_eq_parity`);
the digit count is `num_odd_steps` (`num_odd_steps_eq_sum_parity`). These bridges (resting on
`T₂_iterate_natCast : T₂ᵏ ↑n = ↑(Tᵏ n)`) make `CC.Parity`'s finite parity vectors the truncations of
`Φ⁻¹` (the explicit `Q∞` of `(1.5)`, `BL.ConjugacyMap.Q`).

## Contents
* `parity`, `half`, `two_mul_half` — the parity `x mod 2` and the unique half of an even 2-adic integer.
* `numer`, `even_numer`, `T₂`, `two_mul_T₂`, `T₂_natCast` — the 3x+1 map on `ℤ₂` extending `(1.1)`.
* `shiftNumer`, `even_shiftNumer`, `S`, `two_mul_S`, `parity_add_two_mul_S`, `S_natCast` — the shift `(1.2)`.
* `parity_natCast`, `T₂_iterate_natCast`, `parity_T₂_iterate_natCast`, `parity_T₂_iterate_eq_E_vec`,
  `getElem_V_eq_parity`, `num_odd_steps_eq_sum_parity` — bridges to `CC.Parity`: the 2-adic parity
  digits of the `T₂`-orbit are the Collatz parity vectors (the `Q∞`/`Φ⁻¹` truncations).
* `(1.3)` `T₂` is topologically conjugate to the shift `S` — now **proved** as `exists_conjugacy`
  in `BL.ConjugacyMap` (via the `qMap` construction), no longer a cited axiom here.
* `S_bernoulli` — cited [Kin09]: the 2-adic shift `S` is Bernoulli (`MeasureTheory.IsBernoulli`). The
  general Bernoulli-system machinery (`MeasureTheory.{seqShift, IsBernoulli, IsBernoulli.isStronglyMixing}`,
  and strong mixing of a Bernoulli shift) lives in `ForMathlib/Dynamics/{StronglyMixing, Bernoulli}.lean`.
* `exists_metric_conjugacy`, `T₂_bernoulli`, and `T₂_stronglyMixing` ⇒ `T₂_measurePreserving`,
  `T₂_ergodic` — now all **proved** downstream in `BL.MetricConjugacy`: the conjugacy `Φ` is
  measure-preserving (so `T` metrically conjugate to `S`), `T₂` is Bernoulli, and being Bernoulli it
  is strongly mixing ([Quas09], via `ForMathlib`), hence measure-preserving and ergodic.
* `V`, `V_apply_zero`, `V_involutive`, `parity_V`, `V_semiconj_S`, `V_ne_id` — the shift automorphism
  `V x = -1 - x` (bit-complement): proved to be an involution flipping parity and commuting with `S`.
* `shiftAut_eq_id_or_V` — cited: `Aut(S) ≅ ℤ/2ℤ = {id, V}`.
* `conjugacy_unique` — **proved** (general fact about conjugacies, Mathlib only): `Φ` is unique up to
  right-multiplication by `Aut(S)`.

## References
* [BL96] Bernstein, Daniel J., and Jeffrey C. Lagarias. *The 3x+1 conjugacy map.* Canadian Journal
  of Mathematics 48 (1996), no. 6, 1154–1169.
* [Kin09] Kingsbery, James, et al. "Dynamics of the $ p $-adic shift and applications."
  arXiv preprint arXiv:0903.4226 (2009).
* [Lag85] Lagarias, Jeffrey C. *The 3x+1 problem and its generalizations.* American Mathematical
  Monthly 92 (1985), no. 1, 3–23 (the paper's reference [8]: `T` is measure-preserving and ergodic
  on `ℤ₂`).
* [Hed69] Hedlund, Gustav A. *Endomorphisms and automorphisms of the shift dynamical system.*
  Mathematical Systems Theory 3 (1969), no. 4, 320–375 (the paper's reference [6]: `Aut(S) ≅ ℤ/2ℤ`,
  Theorem 6.9).
* [BFK90] Boyle, Mike, John Franks, and Bruce Kitchens. *Automorphisms of one-sided subshifts of
  finite type.* Ergodic Theory and Dynamical Systems 10 (1990), no. 3, 421–449 (the paper's
  reference [3]).
* [Ter76] Terras, Riho. *A stopping time problem on the positive integers.* Acta Arithmetica 30
  (1976), 241–252 (the map `T = CC.T`, via `CC.Parity ⊃ CC.Terras`).
-/

namespace BL

open PadicInt MeasureTheory Filter Topology

/-- The **parity** of a 2-adic integer: `0` if even, `1` if odd — the value of `x mod 2` under the
residue map `ℤ₂ → ZMod 2`. The 2-adic analogue of `CC.X` on `ℕ`. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def parity (x : ℤ_[2]) : ℕ := (PadicInt.toZMod x).val

/-- The residue of the (cast) parity equals the residue of `x`: `toZMod ↑(parity x) = toZMod x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem toZMod_natCast_parity (x : ℤ_[2]) :
    PadicInt.toZMod ((parity x : ℤ_[2])) = PadicInt.toZMod x := by
  unfold parity; rw [map_natCast, ZMod.natCast_val, ZMod.cast_id]

/-- On `ℕ ⊂ ℤ₂` the 2-adic parity is the Collatz parity `CC.X`: `parity ↑n = X n`
(`= n mod 2`). Base case of the parity-vector bridge to `CC.Parity`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_natCast (n : ℕ) : parity (n : ℤ_[2]) = CC.X n := by
  unfold parity; rw [map_natCast, ZMod.val_natCast, CC.X_eq_mod]

/-- The unique **half** of an even 2-adic integer (`ℤ₂` is a domain, so `2·y = x` has at most one
solution). Used to define both the 3x+1 map and the shift as "even numerator, halved". -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def half {x : ℤ_[2]} (h : (2 : ℤ_[2]) ∣ x) : ℤ_[2] := h.choose

/-- Defining property of `half`: `2 · half h = x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem two_mul_half {x : ℤ_[2]} (h : (2 : ℤ_[2]) ∣ x) : 2 * half h = x := h.choose_spec.symm

/-! ### The 3x+1 map on `ℤ₂` (extension of (1.1)) -/

/-- The **numerator** `x · 3^{parity x} + parity x` of the 3x+1 map (cf. the `ℕ` form
`n·3^{X n} + X n = 2·T n`). It is always even, so the 3x+1 map `T₂` is `numer / 2`. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def numer (x : ℤ_[2]) : ℤ_[2] := x * 3 ^ parity x + (parity x : ℤ_[2])

/-- The numerator `x·3^{parity x} + parity x` is even in `ℤ₂`: modulo `2` it is `x + x ≡ 0`, since
`3 ≡ 1`. Hence `T₂` is well defined. -/
@[category API, AMS 11 37, ref "BL96"]
theorem even_numer (x : ℤ_[2]) : (2 : ℤ_[2]) ∣ numer x := by
  have h3 : PadicInt.toZMod (3 : ℤ_[2]) = 1 := by
    have : (3 : ℤ_[2]) = ((3 : ℕ) : ℤ_[2]) := by norm_num
    rw [this, map_natCast]; decide
  have hz : PadicInt.toZMod (numer x) = 0 := by
    unfold numer
    rw [map_add, map_mul, map_pow, h3, one_pow, mul_one, toZMod_natCast_parity]
    exact CharTwo.add_self_eq_zero _
  have hk : numer x ∈ RingHom.ker (PadicInt.toZMod (p := 2)) := hz
  rw [PadicInt.ker_toZMod, PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hk
  simpa using hk

/-- The **3x+1 function on the 2-adic integers** `ℤ₂`, the extension of `(1.1)`/`CC.T`
to `ℤ_[2]`: `T₂ x` is the (unique) half of the even numerator `numer x`. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def T₂ (x : ℤ_[2]) : ℤ_[2] := half (even_numer x)

/-- Defining identity of `T₂`: `2 · T₂ x = x · 3^{parity x} + parity x`. On odd `x` this is
`2·T₂ x = 3x+1`, on even `x` it is `2·T₂ x = x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem two_mul_T₂ (x : ℤ_[2]) : 2 * T₂ x = numer x := two_mul_half (even_numer x)

/-- `T₂` extends the integer map: on `ℕ ⊂ ℤ₂` it agrees with `CC.T`. So `(1.1)` really
is the restriction of `T₂` to the integers. -/
@[category API, AMS 11 37, ref "BL96"]
theorem T₂_natCast (n : ℕ) : T₂ (n : ℤ_[2]) = (CC.T n : ℤ_[2]) := by
  have hcancel : (2 : ℤ_[2]) * T₂ (n : ℤ_[2]) = 2 * (CC.T n : ℤ_[2]) := by
    rw [two_mul_T₂]
    unfold numer
    rw [parity_natCast]
    have hexp := CC.T_expand n
    have hcast : 2 * ((CC.T n : ℕ) : ℤ_[2])
        = ((3 ^ CC.X n * n + CC.X n : ℕ) : ℤ_[2]) := by
      rw [← hexp]; push_cast; ring
    rw [hcast]; push_cast; ring
  exact mul_left_cancel₀ (by norm_num) hcancel

/-! ### The 2-adic shift map (1.2) -/

/-- The **numerator** `x - parity x` of the shift map: even (`x ≡ parity x mod 2`), so `S` is
`(x - parity x)/2` — i.e. `x/2` if even, `(x-1)/2` if odd. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def shiftNumer (x : ℤ_[2]) : ℤ_[2] := x - (parity x : ℤ_[2])

/-- The shift numerator `x - parity x` is even in `ℤ₂` (`x ≡ parity x mod 2`). -/
@[category API, AMS 11 37, ref "BL96"]
theorem even_shiftNumer (x : ℤ_[2]) : (2 : ℤ_[2]) ∣ shiftNumer x := by
  have hz : PadicInt.toZMod (shiftNumer x) = 0 := by
    unfold shiftNumer
    rw [map_sub, toZMod_natCast_parity, sub_self]
  have hk : shiftNumer x ∈ RingHom.ker (PadicInt.toZMod (p := 2)) := hz
  rw [PadicInt.ker_toZMod, PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hk
  simpa using hk

/-- The **2-adic shift map** `(1.2)` `S : ℤ₂ → ℤ₂`, `S(x) = (x-1)/2` for odd `x` and `x/2` for even
`x`: the (unique) half of the even numerator `x - parity x`. It deletes the lowest binary digit. -/
@[category API, AMS 11 37, ref "BL96"]
noncomputable def S (x : ℤ_[2]) : ℤ_[2] := half (even_shiftNumer x)

/-- Defining identity of the shift: `2 · S x = x - parity x`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem two_mul_S (x : ℤ_[2]) : 2 * S x = x - (parity x : ℤ_[2]) := two_mul_half (even_shiftNumer x)

/-- The shift deletes the lowest binary digit: `x = parity x + 2 · S x`. With `x = ∑ bᵢ2ⁱ` this says
`S x = ∑ bᵢ₊₁2ⁱ` (the lowest digit `b₀ = parity x` is dropped and the rest shift down). -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_add_two_mul_S (x : ℤ_[2]) : (parity x : ℤ_[2]) + 2 * S x = x := by
  rw [two_mul_S]; ring

/-- On `ℕ ⊂ ℤ₂` the shift is integer division by `2`: `S ↑n = ↑⌊n/2⌋`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem S_natCast (n : ℕ) : S (n : ℤ_[2]) = ((n / 2 : ℕ) : ℤ_[2]) := by
  have hpar : parity (n : ℤ_[2]) = n % 2 := by unfold parity; rw [map_natCast, ZMod.val_natCast]
  have hcancel : (2 : ℤ_[2]) * S (n : ℤ_[2]) = 2 * ((n / 2 : ℕ) : ℤ_[2]) := by
    rw [two_mul_S, hpar, ← Nat.cast_sub (Nat.mod_le n 2)]
    have h2 : n - n % 2 = 2 * (n / 2) := by omega
    rw [h2]; push_cast; ring
  exact mul_left_cancel₀ (by norm_num) hcancel

/-! ### Bridges to the Collatz parity vectors (`CC.Parity`)

The inverse conjugacy map `Φ⁻¹`/`Q∞` sends `x` to the parity sequence `k ↦ parity (T₂ᵏ x)`. On `ℕ` these
digits are exactly `CC.Parity`'s finite parity vectors of the Collatz orbit. -/

/-- Iterating `T₂` on `ℕ ⊂ ℤ₂` is iterating the integer map: `T₂ᵏ ↑n = ↑(Tᵏ n)`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem T₂_iterate_natCast (k n : ℕ) :
    (T₂^[k]) (n : ℤ_[2]) = ((CC.T_iter k n : ℕ) : ℤ_[2]) := by
  induction k with
  | zero => rfl
  | succ k ih => rw [Function.iterate_succ', Function.comp_apply, ih, T₂_natCast]; rfl

/-- **Parity-vector bridge.** The `k`-th parity digit of the `T₂`-orbit of `↑n` is the `k`-th entry
of the Collatz parity vector: `parity (T₂ᵏ ↑n) = X (Tᵏ n)`. This is `Q∞`/`Φ⁻¹` (at digit `k`) on `ℕ`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_T₂_iterate_natCast (k n : ℕ) :
    parity (T₂^[k] (n : ℤ_[2])) = CC.X (CC.T_iter k n) := by
  rw [T₂_iterate_natCast, parity_natCast]

/-- The 2-adic parity digits of the `T₂`-orbit are the `ℕ`-valued parity vector `CC.Parity.E_vec`:
`parity (T₂ⁱ ↑n) = E_vec k n i`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem parity_T₂_iterate_eq_E_vec (k n : ℕ) (i : Fin k) :
    parity (T₂^[i.val] (n : ℤ_[2])) = CC.E_vec k n i := by
  rw [parity_T₂_iterate_natCast, CC.E_vec_apply]

/-- The 2-adic parity digits are the `Bool` parity word `CC.Parity.V` (the literal `Q∞` truncation):
its `i`-th entry is `decide (parity (T₂ⁱ ↑n) = 1)`. -/
@[category API, AMS 11 37, ref "BL96"]
theorem getElem_V_eq_parity (j n : ℕ) (i : Fin j) :
    (CC.V j n).get ⟨i.val, by simp⟩ = decide (parity (T₂^[i.val] (n : ℤ_[2])) = 1) := by
  rw [CC.V_get, parity_T₂_iterate_natCast]

/-- The number of odd Collatz iterates is the sum of the 2-adic parity digits of the `T₂`-orbit:
`num_odd_steps k n = ∑_{i<k} parity (T₂ⁱ ↑n)` (the weight `q` of the parity vector). -/
@[category API, AMS 11 37, ref "BL96"]
theorem num_odd_steps_eq_sum_parity (k n : ℕ) :
    CC.num_odd_steps k n = ∑ i ∈ Finset.range k, parity (T₂^[i] (n : ℤ_[2])) := by
  rw [CC.num_odd_steps]
  exact Finset.sum_congr rfl (fun i _ => (parity_T₂_iterate_natCast i n).symm)

/-! ### The 2-adic shift is Bernoulli

The general Bernoulli-system notions (`MeasureTheory.seqShift`, `MeasureTheory.IsBernoulli`, and the
fact that a Bernoulli system is strongly mixing) live in `ForMathlib/Dynamics/{StronglyMixing,
Bernoulli}.lean` — they are not 2-adic-specific. The only `BL`-specific item is the fact that the
2-adic shift `S` is Bernoulli (`BL.S_bernoulli`), now **proved** (no longer a cited axiom) in
`BL.ShiftBernoulli`: the binary-digit map `ℤ₂ ≃ᵐ (ℕ → ZMod 2)` carries Haar to the i.i.d. uniform
`(½,½)` product measure (via `PadicInt.measure_toZModPow_fiber`) and intertwines `S` with `seqShift`. -/

/-! ### The shift automorphism `V` and rigidity of `Φ`

The conjugacy `Φ` of `(1.3)` is unique only up to the automorphisms of the shift `S`. That
automorphism group is `ℤ/2ℤ`, generated by the bit-complement `V`. -/

/-- The nontrivial **automorphism of the shift** `S`: `V x = -1 - x`. As `-1 = …111` in `ℤ₂`, `V`
flips every binary digit (bit-complement). It is an involution (`V_involutive`) commuting with `S`
(`V_semiconj_S`), and `{id, V}` is the full automorphism group `Aut(S) ≅ ℤ/2ℤ`. -/
@[category API, AMS 37 11, ref "BL96"]
noncomputable def V (x : ℤ_[2]) : ℤ_[2] := -1 - x

/-- `V 0 = -1`; in particular `V ≠ id`. -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_apply_zero : V 0 = -1 := by show -1 - 0 = -1; ring

/-- `V` is an **involution**: `V (V x) = x`. So `⟨id, V⟩` is a `ℤ/2ℤ`. -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_involutive : Function.Involutive V := fun x => by show -1 - (-1 - x) = x; ring

/-- `V` **flips parity**: `parity x + parity (V x) = 1` (it complements the lowest — and every —
binary digit). -/
@[category API, AMS 37 11, ref "BL96"]
theorem parity_V (x : ℤ_[2]) : parity x + parity (V x) = 1 := by
  have hc : PadicInt.toZMod (V x) = -1 - PadicInt.toZMod x := by
    show PadicInt.toZMod (-1 - x) = -1 - PadicInt.toZMod x
    simp only [map_sub, map_one, map_neg]
  unfold parity
  rw [hc]
  generalize PadicInt.toZMod x = c
  revert c
  decide

/-- `V` is an **automorphism of the shift**: `V ∘ S = S ∘ V` (`Function.Semiconj V S S`). Proved via
`2 · V (S x) = 2 · S (V x)`, using that `V` flips parity (`parity_V`). -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_semiconj_S : Function.Semiconj V S S := by
  intro x
  have key : (parity x : ℤ_[2]) + (parity (V x) : ℤ_[2]) = 1 := by exact_mod_cast parity_V x
  have hL : (2 : ℤ_[2]) * V (S x) = -2 - (x - (parity x : ℤ_[2])) := by
    show (2 : ℤ_[2]) * (-1 - S x) = -2 - (x - (parity x : ℤ_[2]))
    rw [← two_mul_S x]; ring
  have hR : (2 : ℤ_[2]) * S (V x) = (-1 - x) - (parity (V x) : ℤ_[2]) := by
    rw [two_mul_S]; rfl
  refine mul_left_cancel₀ (a := (2 : ℤ_[2])) (by norm_num) ?_
  rw [hL, hR]; linear_combination key

/-- `V ≠ id` (they differ at `0`), so the shift automorphism group is genuinely nontrivial. -/
@[category API, AMS 37 11, ref "BL96"]
theorem V_ne_id : V ≠ id := fun h => by
  have h0 : V 0 = (0 : ℤ_[2]) := by rw [h]; rfl
  rw [V_apply_zero] at h0; exact absurd h0 (by norm_num)

/-- **(cited; [6] = [Hed69], Theorem 6.9, and [3] = [BFK90].)** The **automorphism group of the
shift `S` is `ℤ/2ℤ`**: every homeomorphism of `ℤ₂` commuting with `S` is either the identity or the
bit-complement `V`. Together with `V_involutive`/`V_ne_id` this exhibits `Aut(S) = {id, V} ≅ ℤ/2ℤ`. -/
@[category research solved, AMS 37 11, ref "Hed69" "BFK90", group "bl_conjugacy"]
axiom shiftAut_eq_id_or_V (ψ : ℤ_[2] ≃ₜ ℤ_[2]) (hψ : Function.Semiconj (⇑ψ) S S) :
    ⇑ψ = id ∨ ⇑ψ = V

/-- **Rigidity of `Φ` (PROVED).** The conjugacy map `Φ` of `(1.3)` is determined **up to
right-multiplication by an automorphism of `S`**: any two solutions `Φ, Φ'` of `Φ ∘ S ∘ Φ⁻¹ = T₂`
satisfy `Φ' = Φ ∘ ψ` for some `ψ ∈ Aut(S)`. Take `ψ := Φ⁻¹ ∘ Φ'` (a homeomorphism, `Φ'.trans Φ.symm`):
then `Φ' = Φ ∘ ψ`, and `ψ` commutes with `S` because `Φ⁻¹ ∘ T₂ = S ∘ Φ⁻¹` (a rearrangement of `hΦ`),
so `ψ ∘ S = Φ⁻¹ ∘ T₂ ∘ Φ' = S ∘ Φ⁻¹ ∘ Φ' = S ∘ ψ`. With `shiftAut_eq_id_or_V` there are then exactly
two solutions: `Φ` and `Φ ∘ V`. (Formerly a cited `axiom`; this is a general fact about conjugacies,
needing only Mathlib.) -/
@[category research solved, AMS 37 11, ref "BL96", group "bl_conjugacy"]
theorem conjugacy_unique (Φ Φ' : ℤ_[2] ≃ₜ ℤ_[2])
    (hΦ : Function.Semiconj (⇑Φ) S T₂) (hΦ' : Function.Semiconj (⇑Φ') S T₂) :
    ∃ ψ : ℤ_[2] ≃ₜ ℤ_[2], Function.Semiconj (⇑ψ) S S ∧ ⇑Φ' = ⇑Φ ∘ ⇑ψ := by
  refine ⟨Φ'.trans Φ.symm, ?_, ?_⟩
  · intro x
    show Φ.symm (Φ' (S x)) = S (Φ.symm (Φ' x))
    rw [hΦ' x]
    have h := hΦ (Φ.symm (Φ' x))
    rw [Φ.apply_symm_apply] at h
    rw [← h, Φ.symm_apply_apply]
  · funext x
    show Φ' x = Φ (Φ.symm (Φ' x))
    rw [Φ.apply_symm_apply]

end BL
