/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import CITED.Dubickas
import RB.E2
import RB.EventuallyPeriodic
import RB.QuadraticPisot
import Mathlib.Algebra.BigOperators.Group.Finset.Sigma
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Ceiling orbits of an algebraic base: the word is bounded, and non-holonomic off `U`
([B1E2b] WP5)

Let `β > 1` be algebraic with minimal integer polynomial `b_d X^d + ⋯ + b_0`, let `x₀ ≥ 1`, and
let `xₙ = ⌈βxₙ₋₁⌉` (`RB.pisotOrbit`).  The **Dubickas word** is

  `wₙ = b_d x_{n+d} + ⋯ + b_0 xₙ`   (`Dubickas.word`, here `RB.Alg.word`).

This file proves the two facts that make that word a symbolic object at all, and then combines
them with the engine of `RB.EventuallyPeriodic` to get the family statement:

* **`RB.Alg.word_eq_tau_combination`** — the *exact cancellation*: `wₙ = ∑_{j<d} cⱼ τ_{n+j}` with
  `cⱼ = ∑_{i>j} bᵢ β^{i−1−j}` and `τₙ = x_{n+1} − βxₙ ∈ [0,1)` the rounding defect.  The huge,
  unknown orbit values disappear; only `d` defects remain.  This is the general-degree form of
  [Dub09] §6's computation, which `RB.pisotWord_eq` formalizes at `d = 2`.
* **`RB.Alg.word_bounded`**, **`RB.Alg.finite_range_word`** — hence `|wₙ| ≤ ∑_{j<d} |cⱼ|`, a bound
  independent of `n`, so the word is a sequence over a *finite alphabet* ([Dub09] Thm 1's easy
  direction, proved here, not cited).
* **`RB.Alg.not_isPRecursive_word_of_not_mem_U`** — **Theorem B, general half**: if `β ∉ Bertin.U`
  (neither Pisot nor Salem) then `w` is **not P-recursive**, hence (`+ Stanley`) its generating
  function is not algebraic.

Non-vacuity is checked: `RB.Alg.not_isPRecursive_word_three_halves` instantiates the family
theorem at the corpus's own base `β = 3/2` (`d = 1`, `P = 2X − 3`, off `U` because `3/2` is not an
algebraic integer).

## Footprints

`word_eq_tau_combination`, `word_bounded`, `finite_range_word`, `isMinimalIntPoly_three_halves`
and the `d = 2` bridge are `std3`.  `not_isPRecursive_word_of_not_mem_U` and its `3/2` instance
consume `Dubickas.periodic_imp_mem_U` ([Dub09] Thm 2) and nothing else;
`not_isAlgebraic_wordSeries_of_not_mem_U` additionally consumes
`Stanley.pRecursive_of_isAlgebraic`.  See `CITED.Dubickas` for why that axiom is now carried,
reversing an earlier decision recorded in `RB.E2`.

## Relation to the rest of the corpus

* At `β = 3/2` this recovers nothing new: `RB.not_isPRecursive_wmin` is `std3` and its aperiodicity
  input is proved by 2-adic descent.  The point of this file is the *family*: every algebraic
  `β ∉ U`, every degree.
* At `d = 2` the word here is literally `RB.pisotWord` (`RB.Alg.word_quadratic`), so the two
  formalizations agree where they overlap; `RB.pisotWord_constant` is the converse direction in
  the quadratic Pisot case, showing the `U`-exemption is populated, not vacuous.
* **Definitions are reused, not duplicated.** [B1E2b] WP5 proposed fresh `RB.Alg.orbit`/`RB.Alg.tau`;
  `RB.pisotOrbit` and `RB.pisotTau` (in `RB.QuadraticPisot`) are already exactly these objects for
  arbitrary real `β` — the `pisot` prefix records where they were first needed, not a hypothesis —
  so this file extends their API instead of forking it.  That is what makes `word_quadratic` a
  one-liner.

## References

* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J. **51**
  (2009), 243–252.  Thm 1 (boundedness), **Thm 2** (the cited axiom), §6 (the `d = 2` examples).
* [Ber92] M.-J. Bertin et al. *Pisot and Salem numbers.* Birkhäuser 1992.  (`U`, `S`, `T`.)
* [Sta80] R. P. Stanley.  European J. Combin. **1** (1980), 175–188.  (The algebraicity corollary.)
* [B1E2b] `plans/plan-B1E2b.html` (2026-07-28): WP5.
-/

namespace RB.Alg

open Stanley Polynomial

/-! ## The rounding defect, and the τ-expansion of the orbit -/

/-- The rounding defect is non-negative: `τₙ = ⌈βxₙ⌉ − βxₙ ≥ 0`.  (Companion of
`RB.pisotTau_lt_one`; unlike `RB.pisotTau_pos` it needs no irrationality.) -/
@[category API, AMS 11, ref "Dub09", group "rb_algebraic_base"]
lemma pisotTau_nonneg (β : ℝ) (x₀ : ℤ) (n : ℕ) : 0 ≤ pisotTau β x₀ n := by
  rw [pisotTau, pisotOrbit_succ]
  have := Int.le_ceil (β * (pisotOrbit β x₀ n : ℝ))
  linarith

/-- **The τ-expansion of the orbit**: `x_{n+i} = βⁱxₙ + ∑_{j<i} β^{i−1−j} τ_{n+j}`.

Iterating `x_{m+1} = βx_m + τ_m`; this is what makes the word a combination of defects only. -/
@[category API, AMS 11, ref "Dub09", group "rb_algebraic_base"]
theorem orbit_add (β : ℝ) (x₀ : ℤ) (n i : ℕ) :
    (pisotOrbit β x₀ (n + i) : ℝ)
      = β ^ i * pisotOrbit β x₀ n
        + ∑ j ∈ Finset.range i, β ^ (i - 1 - j) * pisotTau β x₀ (n + j) := by
  induction i with
  | zero => simp
  | succ i ih =>
    have hstep : (pisotOrbit β x₀ (n + i + 1) : ℝ)
        = β * pisotOrbit β x₀ (n + i) + pisotTau β x₀ (n + i) := by
      rw [pisotTau]; ring
    have hidx : n + (i + 1) = n + i + 1 := by omega
    rw [hidx, hstep, ih, Finset.sum_range_succ, mul_add, Finset.mul_sum]
    have hsum : ∑ j ∈ Finset.range i, β * (β ^ (i - 1 - j) * pisotTau β x₀ (n + j))
        = ∑ j ∈ Finset.range i, β ^ (i + 1 - 1 - j) * pisotTau β x₀ (n + j) :=
      Finset.sum_congr rfl fun j hj => by
        have hj' : j < i := Finset.mem_range.mp hj
        have hexp : i + 1 - 1 - j = (i - 1 - j) + 1 := by omega
        rw [hexp, pow_succ]; ring
    have hlast : i + 1 - 1 - i = 0 := by omega
    rw [hsum, hlast, pow_zero, pow_succ]
    ring

/-! ## The word, and the exact cancellation -/

/-- The **Dubickas word** of the ceiling orbit: `wₙ = ∑_{i≤d} bᵢ x_{n+i}` with `bᵢ = P.coeff i`. -/
@[category API, AMS 11 68, ref "Dub09", group "rb_algebraic_base"]
noncomputable def word (P : Polynomial ℤ) (β : ℝ) (x₀ : ℤ) (n : ℕ) : ℤ :=
  Dubickas.word P (pisotOrbit β x₀) n

/-- The coefficients of the τ-expansion of the word: `cⱼ = ∑_{i>j} bᵢ β^{i−1−j}`. -/
@[category API, AMS 11 68, ref "Dub09", group "rb_algebraic_base"]
noncomputable def tauCoeff (P : Polynomial ℤ) (β : ℝ) (j : ℕ) : ℝ :=
  ∑ i ∈ Finset.Ioc j P.natDegree, (P.coeff i : ℝ) * β ^ (i - 1 - j)

/-- **The exact cancellation** ([Dub09] §3, general degree): `wₙ = ∑_{j<d} cⱼ τ_{n+j}`.

The `xₙ`-coefficient of the expanded word is `∑ᵢ bᵢβⁱ = P(β) = 0` — the minimal-polynomial
relation annihilates it exactly — so the unbounded orbit values drop out and the word is a fixed
linear combination of the `d` rounding defects starting at `n`.

Only `P(β) = 0` is used; minimality of `P` is not needed for the identity. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_algebraic_base"]
theorem word_eq_tau_combination {β : ℝ} {P : Polynomial ℤ} (hP : aeval β P = 0) (x₀ : ℤ) (n : ℕ) :
    (word P β x₀ n : ℝ)
      = ∑ j ∈ Finset.range P.natDegree, tauCoeff P β j * pisotTau β x₀ (n + j) := by
  have h1 : (word P β x₀ n : ℝ)
      = ∑ i ∈ Finset.range (P.natDegree + 1),
          ((P.coeff i : ℝ) * β ^ i * pisotOrbit β x₀ n
            + ∑ j ∈ Finset.range i,
                (P.coeff i : ℝ) * β ^ (i - 1 - j) * pisotTau β x₀ (n + j)) := by
    rw [word, Dubickas.word]
    push_cast
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [orbit_add, mul_add, Finset.mul_sum]
    exact congrArg₂ (· + ·) (by ring) (Finset.sum_congr rfl fun j _ => by ring)
  have h2 : ∑ i ∈ Finset.range (P.natDegree + 1), (P.coeff i : ℝ) * β ^ i = 0 := by
    rw [← hP, aeval_eq_sum_range]
    exact Finset.sum_congr rfl fun i _ => by rw [zsmul_eq_mul]
  rw [h1, Finset.sum_add_distrib, ← Finset.sum_mul, h2, zero_mul, zero_add,
    Finset.sum_comm' (s := Finset.range (P.natDegree + 1)) (t := fun i => Finset.range i)
      (t' := Finset.range P.natDegree) (s' := fun j => Finset.Ioc j P.natDegree)
      (fun i j => by simp only [Finset.mem_range, Finset.mem_Ioc]; omega)]
  exact Finset.sum_congr rfl fun j _ => by rw [tauCoeff, Finset.sum_mul]

/-! ## Boundedness: the word is a sequence over a finite alphabet -/

/-- **[Dub09] Thm 1, the easy direction** (proved, not cited): the word is bounded by
`∑_{j<d} |cⱼ|`, a constant independent of `n`.

Immediate from the cancellation and `0 ≤ τₙ < 1`. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_algebraic_base"]
theorem word_bounded {β : ℝ} {P : Polynomial ℤ} (hP : aeval β P = 0) (x₀ : ℤ) (n : ℕ) :
    |(word P β x₀ n : ℝ)| ≤ ∑ j ∈ Finset.range P.natDegree, |tauCoeff P β j| := by
  rw [word_eq_tau_combination hP]
  refine le_trans (Finset.abs_sum_le_sum_abs _ _) (Finset.sum_le_sum fun j _ => ?_)
  rw [abs_mul]
  have h0 : 0 ≤ pisotTau β x₀ (n + j) := pisotTau_nonneg β x₀ (n + j)
  have h1 : |pisotTau β x₀ (n + j)| ≤ 1 := by
    rw [abs_of_nonneg h0]; linarith [pisotTau_lt_one β x₀ (n + j)]
  nlinarith [abs_nonneg (tauCoeff P β j), abs_nonneg (pisotTau β x₀ (n + j))]

/-- The word takes only finitely many values: it is an integer sequence bounded by a constant. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_algebraic_base"]
theorem finite_range_word {β : ℝ} {P : Polynomial ℤ} (hP : aeval β P = 0) (x₀ : ℤ) :
    (Set.range fun n => ((word P β x₀ n : ℤ) : ℚ)).Finite := by
  set M : ℤ := ⌈∑ j ∈ Finset.range P.natDegree, |tauCoeff P β j|⌉ with hM
  have hbd : ∀ n, |word P β x₀ n| ≤ M := by
    intro n
    have h : ((|word P β x₀ n| : ℤ) : ℝ) ≤ ∑ j ∈ Finset.range P.natDegree, |tauCoeff P β j| := by
      push_cast
      exact word_bounded hP x₀ n
    exact_mod_cast h.trans (Int.le_ceil _)
  refine Set.Finite.subset ((Set.finite_Icc (-M) M).image (fun m : ℤ => (m : ℚ))) ?_
  rintro _ ⟨n, rfl⟩
  exact ⟨word P β x₀ n, Set.mem_Icc.mpr (abs_le.mp (hbd n)), rfl⟩

/-! ## Theorem B, general half: non-holonomy off `U` -/

/-- **[B1E2b] WP5, Theorem B (general half)**: for an algebraic `β > 1` that is *neither Pisot nor
Salem*, the word of the ceiling orbit `xₙ = ⌈βxₙ₋₁⌉` is **not P-recursive**.

Two inputs: the word lives over a finite alphabet (proved here, `finite_range_word`), and it is
not ultimately periodic — which is [Dub09] Thm 2 contraposed, the file's one cited axiom.  The
engine `RB.not_isPRecursive_of_not_eventuallyPeriodic` does the rest.

Footprint: `std3 + Dubickas.periodic_imp_mem_U`.

At `β = 3/2` the aperiodicity input is available axiom-free (`RB.not_eventually_periodic`, 2-adic
descent), and `RB.not_isPRecursive_wmin` is the corresponding `std3` statement; the axiom buys the
*family*, not that instance. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_algebraic_base"]
theorem not_isPRecursive_word_of_not_mem_U {β : ℝ} (hβ : 1 < β) {x₀ : ℤ} (hx₀ : 0 < x₀)
    {P : Polynomial ℤ} (hP : Dubickas.IsMinimalIntPoly P β) (hU : β ∉ Bertin.U) :
    ¬ IsPRecursive (fun n => (word P β x₀ n : ℚ)) := by
  refine not_isPRecursive_of_not_eventuallyPeriodic (finite_range_word hP.2.1 x₀) ?_
  rintro ⟨N, p, hp, hper⟩
  exact hU (Dubickas.periodic_imp_mem_U hβ (x := pisotOrbit β x₀) hx₀ (fun n => rfl) hP
    ⟨N, p, hp, fun n hn => by exact_mod_cast hper n hn⟩)

/-- The generating function of the word is not algebraic over `ℚ(z)`, for every algebraic `β > 1`
outside `Bertin.U`.

Footprint: `std3 + Dubickas.periodic_imp_mem_U + Stanley.pRecursive_of_isAlgebraic`. -/
@[category research solved, AMS 11 68 05, ref "Dub09" "Sta80" "B1E2b", group "rb_algebraic_base"]
theorem not_isAlgebraic_wordSeries_of_not_mem_U {β : ℝ} (hβ : 1 < β) {x₀ : ℤ} (hx₀ : 0 < x₀)
    {P : Polynomial ℤ} (hP : Dubickas.IsMinimalIntPoly P β) (hU : β ∉ Bertin.U) :
    ¬ IsAlgebraic (Polynomial ℚ) (PowerSeries.mk fun n => (word P β x₀ n : ℚ)) := fun halg =>
  not_isPRecursive_word_of_not_mem_U hβ hx₀ hP hU (by simpa using pRecursive_of_isAlgebraic halg)

/-! ## A witness: the hypotheses are satisfiable, at the corpus's own base -/

/-- `2X − 3` is a minimal integer polynomial of `3/2` — the `d = 1` instance.  (`minpoly ℤ (3/2)`
is *not* available: `3/2` is not an algebraic integer, which is exactly why it is off `U`.) -/
@[category API, AMS 11 12, ref "Dub09", group "rb_algebraic_base"]
theorem isMinimalIntPoly_three_halves :
    Dubickas.IsMinimalIntPoly (C 2 * X - C 3) ((3 : ℝ) / 2) := by
  have hlin : (C 2 * X - C 3 : Polynomial ℤ) = C 2 * X + C (-3) := by
    simp only [C_neg]; ring
  have hdeg : (C 2 * X - C 3 : Polynomial ℤ).natDegree = 1 := by
    rw [hlin]; exact natDegree_linear (by norm_num)
  refine ⟨fun h => by rw [h] at hdeg; simp at hdeg, ?_, fun Q hQ hQ0 => ?_⟩
  · simp only [map_sub, map_mul, aeval_C, aeval_X]
    norm_num
  rw [hdeg, Nat.one_le_iff_ne_zero]
  intro hQdeg
  refine hQ ?_
  have hQC : Q = C (Q.coeff 0) := eq_C_of_natDegree_eq_zero hQdeg
  have : ((Q.coeff 0 : ℤ) : ℝ) = 0 := by rw [hQC] at hQ0; simpa using hQ0
  rw [hQC, show Q.coeff 0 = 0 by exact_mod_cast this, map_zero]

/-- **Non-vacuity**: the corpus's own base `β = 3/2` satisfies every hypothesis of
`not_isPRecursive_word_of_not_mem_U`, so the family theorem has content.

`3/2 ∉ Bertin.U` is `RB.three_halves_not_mem_Bertin_U` (it is not even an algebraic integer).
This is *not* a new result — `RB.not_isPRecursive_wmin` is the same statement about the same word,
`std3` instead of on an axiom — but it is the check that the general machinery specialises
correctly.  Identifying this word with `RB.wmin` on the nose needs the `(3,2)` orbit bridge
(`pisotOrbit (3/2) = RB.x`), which was [B1E2b] WP4's business.

*Update ([B1E2b] WP4, 2026-07-28):* delivered, downstream in `RB.GeneralBase` — the bridge is
`RB.Gen.pisotOrbit_three_halves_eq` and the word identification is `RB.Gen.alg_word_eq_wmin`, so
this theorem and `RB.not_isPRecursive_wmin` are now formally the same statement.  More generally
`RB.Gen.not_isPRecursive_word` proves the conclusion below for *every* rational base `p/q`
(`p > q ≥ 2`, coprime) **without** `Dubickas.periodic_imp_mem_U`, even though
`RB.Gen.isMinimalIntPoly_rational` and `RB.Gen.not_mem_Bertin_U` show the axiomatic route does
apply there. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_algebraic_base"]
theorem not_isPRecursive_word_three_halves {x₀ : ℤ} (hx₀ : 0 < x₀) :
    ¬ IsPRecursive (fun n => (word (C 2 * X - C 3) ((3 : ℝ) / 2) x₀ n : ℚ)) :=
  not_isPRecursive_word_of_not_mem_U (by norm_num) hx₀ isMinimalIntPoly_three_halves
    three_halves_not_mem_Bertin_U

/-! ## The `d = 2` bridge -/

/-- At `d = 2` the general word *is* `RB.pisotWord`: for `P = X² − aX + b`,
`wₙ = x_{n+2} − a·x_{n+1} + b·xₙ`.

So this file and `RB.QuadraticPisot` ([Dub09] §6) speak about the same object where they overlap. -/
@[category API, AMS 11 68, ref "Dub09", group "rb_algebraic_base"]
theorem word_quadratic (β : ℝ) (a b x₀ : ℤ) (n : ℕ) :
    word (X ^ 2 - C a * X + C b) β x₀ n = pisotWord β a b x₀ n := by
  have hpoly : (X ^ 2 - C a * X + C b : Polynomial ℤ) = C 1 * X ^ 2 + C (-a) * X + C b := by
    simp only [C_neg, map_one, one_mul, neg_mul]
    ring
  have hdeg : (X ^ 2 - C a * X + C b : Polynomial ℤ).natDegree = 2 := by
    rw [hpoly]; exact natDegree_quadratic one_ne_zero
  have hc0 : (X ^ 2 - C a * X + C b : Polynomial ℤ).coeff 0 = b := by
    simp only [coeff_add, coeff_sub, coeff_C_mul, coeff_X_pow, coeff_X_zero, coeff_C]; norm_num
  have hc1 : (X ^ 2 - C a * X + C b : Polynomial ℤ).coeff 1 = -a := by
    simp only [coeff_add, coeff_sub, coeff_C_mul, coeff_X_pow, coeff_X_one, coeff_C]; norm_num
  have hc2 : (X ^ 2 - C a * X + C b : Polynomial ℤ).coeff 2 = 1 := by
    simp only [coeff_add, coeff_sub, coeff_C_mul, coeff_X_pow, coeff_X, coeff_C]; norm_num
  rw [word, Dubickas.word, hdeg, pisotWord]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Nat.add_zero, hc0, hc1, hc2]
  ring

end RB.Alg
