/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Linarith
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# The rational-base orbit `xₙ = ⌈3xₙ₋₁/2⌉` and its minimal word (plan-B1E2, WP0)

The model API of the `3/2` rational base number system ([AFS08]): the integer orbit

  `x₀ ∈ ℕ`,  `xₙ = ⌈3xₙ₋₁/2⌉`,

its **minimal word** `w`, and the real constant `K = ω_{3/2}` that the orbit encodes.

## The word, and a naming hazard

The carry `wₙ := 2xₙ₊₁ − 3xₙ` (Dubickas' phrasing `wₙ = q xₙ₊₁ − p xₙ` at `(p,q) = (3,2)`)
is just the parity of `xₙ`:

  `2xₙ₊₁ = 3xₙ + wₙ`,   `wₙ = xₙ mod 2 ∈ {0,1}`   (`two_mul_x_succ`, `wmin_eq_x_mod_two`),

so `w` *is* the mod-2 reduction of the orbit — [Dub09] Cor 4's `Xₙ = xₙ (mod 2)`.  For `x₀ = 1`
the orbit is **A061419** (`1,2,3,5,8,12,18,27,41,…`; [Dub09] names it) and `w` is the word
[AFS08] call `g_{3/2}` (Def 20, Remark 32) — the *minimal* element of the language `W_{3/2}`,
whence the name `wmin`.

**Do not confuse this with Rowland–Shallit's `w_{3/2}`**, an unrelated word of the same name;
this is why the declaration here is `RB.wmin` and never `RB.w`.

## The algebra is `TH`'s, transplanted

`2xₙ₊₁ = 3xₙ + wₙ` is literally `TH.two_mul_m_succ` (`2mₙ₊₁ = 3mₙ + tₙ`) under `x ↔ m`,
`w ↔ t`, so the circuit-sum layer transplants verbatim: `W`/`W_succ`/`circuit_sum` mirror
`TH.W`/`TH.W_succ`/`TH.circuit_sum`.  The models differ in the *selection rule* — `TH.m` is
`round`, `RB.x` is `⌈·⌉` — hence `TH.t ∈ {-2,…,2}` against `RB.wmin ∈ {0,1}`.

## The constant `K`

Dividing `circuit_sum` at `a = 0` by `3ⁿ` gives the exact partial-sum form (`x_mul_pow`)

  `xₙ(2/3)ⁿ = x₀ + (1/3)·Σ_{j<n} wⱼ(2/3)ʲ`,

whose limit is `K x₀` — for `x₀ = 1`, `ω_{3/2} = K(3) = 1.6222705028…` (**A083286**,
[AFS08] Example 3).  `K` is *defined* by the series and the limit is then a theorem, because
the series is exactly what the transcendence input of plan-B1E2 (`AF17` Cor 1.8 at `α = 2/3`)
consumes: `tsum_wmin_eq` states `Σⱼ wⱼ(2/3)ʲ = 3(K − x₀)`, the plan's T1a interface.

Tail bounds `0 ≤ K − xₙ(2/3)ⁿ ≤ (2/3)ⁿ` (`le_K`, `K_sub_le`) sharpen to the AFS orbit
characterization `xₙ ≤ K(3/2)ⁿ ≤ xₙ + 1` (`x_le_K_mul_pow`, `K_mul_pow_le`).

Everything here is `ℕ`-arithmetic except the `K` section; `(p,q)` is fixed to `(3,2)` — the
downstream consumers (the `2`-adic rigidity of `RB.Rigidity`, regularity at the *rational*
point `2/3`) are all base-specific, and the general `(p,q)` recursion is the same algebra with
`wₙ = (−p xₙ) mod q ∈ {0,…,q−1}`.

## Contents

* `RB.x`, `RB.wmin` — the orbit and its minimal word; `two_mul_x_succ` (the selection rule),
  `wmin_le_one`, `wmin_eq_x_mod_two`.
* `RB.W` — the circuit sum; `W_succ`, `circuit_sum`, `circuit_sum_zero`.
* growth: `three_pow_mul_le` (`3ⁿx₀ ≤ 2ⁿxₙ`), `two_pow_mul_x_add_one_le`
  (`2ⁿ(xₙ+1) ≤ 3ⁿ(x₀+1)`, i.e. `xₙ < (x₀+1)(3/2)ⁿ`), `x_pos`, `x_strictMono`.
* `RB.K` — the constant; `x_mul_pow`, `summable_wmin`, **`tsum_wmin_eq`** (T1a interface),
  `le_K`, `K_sub_le`, `x_le_K_mul_pow`, `K_mul_pow_le`, `tendsto_x_mul_pow`.
* sanity: `x_sanity` (A061419), `wmin_sanity`.

## References

* [AFS08] Akiyama, Frougny, Sakarovitch. *Powers of rationals modulo 1 and rational base
  number systems.* Israel J. Math. **168** (2008), 53–91.  (Def 20 = A061419; Remark 32 =
  our `w`; Example 3 = `ω_{3/2} = K(3)`; Cor 31 = the closed form.)
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J.
  **51** (2009), 243–252.  (Thm 3, p. 245 = the general `liminf` floor; Cor 4, p. 245 =
  the `3/2` record `P(𝒳,n) > 1.70951129n`, where `𝒳ₙ = xₙ mod 2` is our `wmin`.)
* [B1E2] `plans/plan-B1E2.html` (this repository, rev. 2, 2026-07): §2.2 (the archimedean
  identity), WP0.
* [M4A3] `plans/plan-M4A3.html`: the `TH` twin whose circuit-sum algebra this mirrors.
-/

namespace RB

/-- The orbit `xₙ = ⌈3xₙ₋₁/2⌉` from `x 0 = x₀`.  In `ℕ`-division `⌈3a/2⌉ = (3a+1)/2`.
[AFS08] Def 20; for `x₀ = 1` this is A061419. -/
@[category API, AMS 11 68, ref "AFS08" "Dub09", group "rb_rational_base"]
def x (x₀ : ℕ) : ℕ → ℕ
  | 0 => x₀
  | n + 1 => (3 * x x₀ n + 1) / 2

/-- The **minimal word** `wₙ = 2xₙ₊₁ − 3xₙ = xₙ mod 2` — [AFS08]'s `g_{3/2}` (Remark 32),
[Dub09] Cor 4's `𝒳ₙ`.  Named `wmin`, not `w`, to avoid collision with Rowland–Shallit's
unrelated `w_{3/2}`. -/
@[category API, AMS 11 68, ref "AFS08" "Dub09", group "rb_rational_base"]
def wmin (x₀ : ℕ) (n : ℕ) : ℕ := x x₀ n % 2

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base", simp]
lemma x_zero (x₀ : ℕ) : x x₀ 0 = x₀ := rfl

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
lemma x_succ (x₀ n : ℕ) : x x₀ (n + 1) = (3 * x x₀ n + 1) / 2 := rfl

/-- The orbit is **shift-invariant**: running `n+j` steps from `x₀` is running `j` steps from
`x_n`.  What makes `x_n` a legitimate initial condition, hence the shifted families. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem x_add (x₀ n j : ℕ) : x x₀ (n + j) = x (x x₀ n) j := by
  induction j with
  | zero => rfl
  | succ j ih =>
    have e : n + (j + 1) = (n + j) + 1 := by omega
    rw [e, x_succ, x_succ, ih]

/-- The word inherits shift-invariance from the orbit. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem wmin_add (x₀ n j : ℕ) : wmin x₀ (n + j) = wmin (x x₀ n) j := by
  unfold wmin; rw [x_add]

/-- The selection rule: `2xₙ₊₁ = 3xₙ + wₙ`.  The `RB` twin of `TH.two_mul_m_succ`. -/
@[category API, AMS 11 68, ref "AFS08" "Dub09", group "rb_rational_base"]
theorem two_mul_x_succ (x₀ n : ℕ) : 2 * x x₀ (n + 1) = 3 * x x₀ n + wmin x₀ n := by
  unfold wmin
  show 2 * ((3 * x x₀ n + 1) / 2) = _
  omega

/-- The alphabet is `{0,1}` (the `RB` twin of `TH.t_abs_le`'s 5-letter alphabet). -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem wmin_le_one (x₀ n : ℕ) : wmin x₀ n ≤ 1 := by unfold wmin; omega

/-- The word is the parity of the orbit. -/
@[category API, AMS 11 68, ref "Dub09", group "rb_rational_base"]
theorem wmin_eq_x_mod_two (x₀ n : ℕ) : wmin x₀ n = x x₀ n % 2 := rfl

/-! ## The circuit sum -/

/-- `W x₀ a k = Σ_{i<k} 3^(k-1-i)·2^i·w_{a+i}` — mirror of `TH.W`. -/
@[category API, AMS 11 68, ref "AFS08" "M4A3", group "rb_rational_base"]
def W (x₀ a k : ℕ) : ℕ := ∑ i ∈ Finset.range k, 3 ^ (k - 1 - i) * 2 ^ i * wmin x₀ (a + i)

@[category API, AMS 11 68, ref "M4A3", group "rb_rational_base", simp]
lemma W_zero (x₀ a : ℕ) : W x₀ a 0 = 0 := by simp [W]

/-- Mirror of `TH.W_succ`. -/
@[category API, AMS 11 68, ref "M4A3", group "rb_rational_base"]
theorem W_succ (x₀ a k : ℕ) : W x₀ a (k + 1) = 3 * W x₀ a k + 2 ^ k * wmin x₀ (a + k) := by
  unfold W
  rw [Finset.sum_range_succ, Finset.mul_sum]
  simp only [Nat.add_sub_cancel, Nat.sub_self, pow_zero, one_mul]
  congr 1
  refine Finset.sum_congr rfl fun i hi => ?_
  have hik : i < k := Finset.mem_range.mp hi
  have hki : k - i = (k - 1 - i) + 1 := by omega
  rw [hki, pow_succ]
  ring

/-- **The exact identity** `2^k·x_{a+k} = 3^k·x_a + W(a,k)` — mirror of `TH.circuit_sum`. -/
@[category research solved, AMS 11 68, ref "AFS08" "M4A3", group "rb_rational_base"]
theorem circuit_sum (x₀ a k : ℕ) : 2 ^ k * x x₀ (a + k) = 3 ^ k * x x₀ a + W x₀ a k := by
  induction k with
  | zero => simp
  | succ k ih =>
    have h := two_mul_x_succ x₀ (a + k)
    have e : a + (k + 1) = (a + k) + 1 := by omega
    calc 2 ^ (k + 1) * x x₀ (a + (k + 1))
        = 2 ^ k * (2 * x x₀ ((a + k) + 1)) := by rw [e]; ring
      _ = 2 ^ k * (3 * x x₀ (a + k) + wmin x₀ (a + k)) := by rw [h]
      _ = 3 * (2 ^ k * x x₀ (a + k)) + 2 ^ k * wmin x₀ (a + k) := by ring
      _ = 3 * (3 ^ k * x x₀ a + W x₀ a k) + 2 ^ k * wmin x₀ (a + k) := by rw [ih]
      _ = 3 ^ (k + 1) * x x₀ a + W x₀ a (k + 1) := by rw [W_succ]; ring

/-- The base-point form `2ⁿxₙ = 3ⁿx₀ + Σ_{j<n} 3^{n-1-j}2^j wⱼ` (the plan's WP0 identity). -/
@[category research solved, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem circuit_sum_zero (x₀ n : ℕ) : 2 ^ n * x x₀ n = 3 ^ n * x₀ + W x₀ 0 n := by
  simpa using circuit_sum x₀ 0 n

/-! ## Growth and monotonicity -/

/-- Lower growth: `3ⁿx₀ ≤ 2ⁿxₙ` (the word only ever pushes the orbit up). -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem three_pow_mul_le (x₀ n : ℕ) : 3 ^ n * x₀ ≤ 2 ^ n * x x₀ n := by
  rw [circuit_sum_zero]; omega

/-- Upper growth: `2ⁿ(xₙ+1) ≤ 3ⁿ(x₀+1)`, i.e. `xₙ < (x₀+1)(3/2)ⁿ`.  The shift by `1` is
what makes the estimate exact: `xₙ+1` is *submultiplicative* under the `⌈·⌉` rule. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem two_pow_mul_x_add_one_le (x₀ n : ℕ) : 2 ^ n * (x x₀ n + 1) ≤ 3 ^ n * (x₀ + 1) := by
  induction n with
  | zero => simp
  | succ n ih =>
    have h := two_mul_x_succ x₀ n
    have hw := wmin_le_one x₀ n
    have step : 2 ^ (n + 1) * (x x₀ (n + 1) + 1) ≤ 3 * (2 ^ n * (x x₀ n + 1)) := by
      have e1 : 2 ^ (n + 1) * (x x₀ (n + 1) + 1) = 2 ^ n * (2 * x x₀ (n + 1) + 2) := by ring
      have e2 : 3 * (2 ^ n * (x x₀ n + 1)) = 2 ^ n * (3 * x x₀ n + 3) := by ring
      rw [e1, h, e2]
      exact Nat.mul_le_mul_left _ (by omega)
    calc 2 ^ (n + 1) * (x x₀ (n + 1) + 1) ≤ 3 * (2 ^ n * (x x₀ n + 1)) := step
      _ ≤ 3 * (3 ^ n * (x₀ + 1)) := Nat.mul_le_mul_left _ ih
      _ = 3 ^ (n + 1) * (x₀ + 1) := by ring

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem x_pos {x₀ : ℕ} (hx₀ : 0 < x₀) (n : ℕ) : 0 < x x₀ n := by
  induction n with
  | zero => simpa using hx₀
  | succ n ih => have := two_mul_x_succ x₀ n; omega

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem x_lt_x_succ {x₀ : ℕ} (hx₀ : 0 < x₀) (n : ℕ) : x x₀ n < x x₀ (n + 1) := by
  have h := two_mul_x_succ x₀ n
  have := x_pos hx₀ n
  omega

/-- Strict monotonicity ([Dub09] Cor 4's `0 < x₀ < x₁ < x₂ < ⋯`). -/
@[category API, AMS 11 68, ref "Dub09", group "rb_rational_base"]
theorem x_strictMono {x₀ : ℕ} (hx₀ : 0 < x₀) : StrictMono (x x₀) :=
  strictMono_nat_of_lt_succ (x_lt_x_succ hx₀)

/-! ## The constant `K = ω_{3/2}` -/

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
lemma two_mul_x_succ_real (x₀ n : ℕ) : 2 * (x x₀ (n + 1) : ℝ) = 3 * x x₀ n + wmin x₀ n := by
  exact_mod_cast congrArg (Nat.cast (R := ℝ)) (two_mul_x_succ x₀ n)

/-- **Partial-sum form**: `xₙ(2/3)ⁿ = x₀ + (1/3)·Σ_{j<n} wⱼ(2/3)ʲ`.  This is `circuit_sum_zero`
divided by `3ⁿ`, proved directly by induction to keep the `ℕ`-subtraction of `W` out of `ℝ`. -/
@[category research solved, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem x_mul_pow (x₀ n : ℕ) :
    (x x₀ n : ℝ) * (2 / 3) ^ n
      = x₀ + (1 / 3) * ∑ j ∈ Finset.range n, (2 / 3 : ℝ) ^ j * wmin x₀ j := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [Finset.sum_range_succ]
    have h := two_mul_x_succ_real x₀ n
    have e : ((2 : ℝ) / 3) ^ (n + 1) = (2 / 3) * (2 / 3) ^ n := by ring
    rw [e]
    linear_combination ih + ((2 : ℝ) / 3) ^ n / 3 * h

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
lemma wmin_nonneg (x₀ j : ℕ) : (0 : ℝ) ≤ (2 / 3 : ℝ) ^ j * wmin x₀ j := by positivity

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
lemma wmin_term_le (x₀ j : ℕ) : (2 / 3 : ℝ) ^ j * wmin x₀ j ≤ (2 / 3 : ℝ) ^ j := by
  have h1 : (wmin x₀ j : ℝ) ≤ 1 := by exact_mod_cast wmin_le_one x₀ j
  nlinarith [pow_pos (by norm_num : (0 : ℝ) < 2 / 3) j]

@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem summable_wmin (x₀ : ℕ) : Summable (fun j => (2 / 3 : ℝ) ^ j * wmin x₀ j) :=
  Summable.of_nonneg_of_le (wmin_nonneg x₀) (wmin_term_le x₀)
    (summable_geometric_of_lt_one (by norm_num) (by norm_num))

/-- The constant `K = lim xₙ/(3/2)ⁿ`, *defined* by the series that [AF17] Cor 1.8 consumes
(`tendsto_x_mul_pow` recovers the limit description).  `K 1 = ω_{3/2} = K(3) = 1.6222705028…`
(A083286, [AFS08] Example 3). -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
noncomputable def K (x₀ : ℕ) : ℝ := x₀ + (1 / 3) * ∑' j, (2 / 3 : ℝ) ^ j * wmin x₀ j

/-- **The T1a interface** ([B1E2] §2.2): the archimedean value of the word at `α = 2/3` is
`Σⱼ wⱼ(2/3)ʲ = 3(K − x₀)`.  Plan-B1E2's capstone feeds exactly this to [AF17] Cor 1.8. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2", group "rb_rational_base"]
theorem tsum_wmin_eq (x₀ : ℕ) : ∑' j, (2 / 3 : ℝ) ^ j * wmin x₀ j = 3 * (K x₀ - x₀) := by
  unfold K; ring

/-- Tail, lower half: the orbit never overshoots `K`. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem le_K (x₀ n : ℕ) : (x x₀ n : ℝ) * (2 / 3) ^ n ≤ K x₀ := by
  have hs := summable_wmin x₀
  have hsplit := hs.sum_add_tsum_nat_add n
  have hx := x_mul_pow x₀ n
  have : (0 : ℝ) ≤ ∑' i, (2 / 3 : ℝ) ^ (i + n) * wmin x₀ (i + n) :=
    tsum_nonneg fun i => wmin_nonneg x₀ (i + n)
  unfold K; rw [hx]; linarith

/-- Tail, upper half: `K − xₙ(2/3)ⁿ ≤ (2/3)ⁿ`. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem K_sub_le (x₀ n : ℕ) : K x₀ - (x x₀ n : ℝ) * (2 / 3) ^ n ≤ (2 / 3) ^ n := by
  have hs := summable_wmin x₀
  have hsplit := hs.sum_add_tsum_nat_add n
  have hx := x_mul_pow x₀ n
  have hgeom : Summable (fun i : ℕ => (2 / 3 : ℝ) ^ n * (2 / 3 : ℝ) ^ i) :=
    (summable_geometric_of_lt_one (by norm_num) (by norm_num)).mul_left _
  have hle : ∑' i, (2 / 3 : ℝ) ^ (i + n) * wmin x₀ (i + n)
      ≤ ∑' i, (2 / 3 : ℝ) ^ n * (2 / 3 : ℝ) ^ i := by
    refine Summable.tsum_le_tsum (fun i => ?_) (hs.comp_injective (add_left_injective n)) hgeom
    calc (2 / 3 : ℝ) ^ (i + n) * wmin x₀ (i + n) ≤ (2 / 3 : ℝ) ^ (i + n) := wmin_term_le x₀ (i + n)
      _ = (2 / 3 : ℝ) ^ n * (2 / 3 : ℝ) ^ i := by rw [pow_add]; ring
  rw [tsum_mul_left, tsum_geometric_of_lt_one (by norm_num) (by norm_num)] at hle
  norm_num at hle
  unfold K; rw [hx]; linarith

/-- The AFS orbit characterization, lower half: `xₙ ≤ K(3/2)ⁿ`. -/
@[category research solved, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem x_le_K_mul_pow (x₀ n : ℕ) : (x x₀ n : ℝ) ≤ K x₀ * (3 / 2) ^ n := by
  have h := le_K x₀ n
  have hp : (0 : ℝ) < (3 / 2) ^ n := by positivity
  have e : ((2 : ℝ) / 3) ^ n * (3 / 2) ^ n = 1 := by rw [← mul_pow]; norm_num
  nlinarith [h, hp]

/-- The AFS orbit characterization, upper half: `K(3/2)ⁿ ≤ xₙ + 1`.  With `x_le_K_mul_pow`,
the orbit is pinned to the unit window below `K(3/2)ⁿ`. -/
@[category research solved, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem K_mul_pow_le (x₀ n : ℕ) : K x₀ * (3 / 2) ^ n ≤ (x x₀ n : ℝ) + 1 := by
  have h := K_sub_le x₀ n
  have hp : (0 : ℝ) < (3 / 2) ^ n := by positivity
  have e : ((2 : ℝ) / 3) ^ n * (3 / 2) ^ n = 1 := by rw [← mul_pow]; norm_num
  nlinarith [h, hp]

/-- `K` is the limit `lim xₙ(2/3)ⁿ` — the description [AFS08] give for `ω_{3/2}`. -/
@[category research solved, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem tendsto_x_mul_pow (x₀ : ℕ) :
    Filter.Tendsto (fun n => (x x₀ n : ℝ) * (2 / 3) ^ n) Filter.atTop (nhds (K x₀)) := by
  have hgeom : Filter.Tendsto (fun n : ℕ => (2 / 3 : ℝ) ^ n) Filter.atTop (nhds 0) :=
    tendsto_pow_atTop_nhds_zero_of_lt_one (by norm_num) (by norm_num)
  have hlow : Filter.Tendsto (fun n : ℕ => K x₀ - (2 / 3 : ℝ) ^ n) Filter.atTop (nhds (K x₀)) := by
    simpa using hgeom.const_sub (K x₀)
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le hlow tendsto_const_nhds
    (fun n => by linarith [K_sub_le x₀ n]) (fun n => le_K x₀ n)

/-! ## Sanity -/

/-- The orbit from `x₀ = 1` is A061419. -/
@[category test, AMS 11 68, ref "Dub09", group "rb_rational_base"]
theorem x_sanity :
    x 1 0 = 1 ∧ x 1 1 = 2 ∧ x 1 2 = 3 ∧ x 1 3 = 5 ∧ x 1 4 = 8 ∧ x 1 5 = 12 ∧ x 1 6 = 18 ∧
      x 1 7 = 27 ∧ x 1 8 = 41 :=
  ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

/-- The first letters of `g_{3/2}`. -/
@[category test, AMS 11 68, ref "AFS08", group "rb_rational_base"]
theorem wmin_sanity :
    (wmin 1 0, wmin 1 1, wmin 1 2, wmin 1 3, wmin 1 4, wmin 1 5) = (1, 0, 1, 1, 0, 0) := rfl

end RB
