/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import RB.CollatzDictionary
import ForMathlib.Data.Rat.NearestInt
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic.LinearCombination
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# The Collatz cocycle, its constant, and the repetition contraction (plan-B2A2, WP8 / T3b)

The dynamical half of [B2A2] §3.2: a wandering Collatz orbit has no `K(3/2)ⁿ` asymptotics,
but it does carry the exact **cocycle**

  `Λₙ := 3^{Sₙ}/2ⁿ`   (`Sₙ` = number of odd steps among the first `n`),

an `S`-unit in `⟨2,3⟩`, together with the exact identity `xₙ = Λₙ·Mₙ`
(`RB.Collatz.orbit_eq`), where the **scaled orbit**

  `Mₙ := xₙ/Λₙ = n₀ + ∑_{i<n} vᵢ/(2Λ_{i+1})`   (`scaled_zero`, `scaled_sub_succ`)

is increasing.  Its limit `K` is [B2A2] §3.2's *cocycle constant*, and the whole `RB` repetition
algebra transplants with `Λₙ` in place of `(3/2)ⁿ`.

## What the hypothesis has to be, and why it is not the plan's

[B2A2] §3.2 calls an orbit *geometrically divergent* when `liminf (1/n)·log xₙ > 0` and asserts
that `K := lim xₙ/Λₙ` then exists and the `§2.1` algebra generalizes.  **The liminf form is not
enough**, and this file uses a strictly stronger hypothesis, `IsUniformlyGeometric`:

  `Λₙ ≤ B₀·ρᵐ·Λ_{n+m}` for all `n, m`, with `0 < ρ < 1`

— the cocycle grows geometrically *from every starting point*, not merely on average.  Two
places make this unavoidable, and both are invisible in the model orbit (where every step
multiplies by `3/2`, so the two notions coincide):

* **The tail defect `θₙ := δ·Λₙ − xₙ` must be bounded.**  `θₙ = ∑_{i≥n} vᵢ·Λₙ/(2Λ_{i+1})`, so
  boundedness asks for `Λₙ/Λ_{n+m}` to decay — a *window*-wise statement.  Under liminf-only
  divergence an orbit may contain longer and longer runs of even steps (each halving `Λ`) while
  keeping its global rate positive; then `θₙ` is unbounded and there is no defect to contract.
* **A repetition contracts by its own window's multiplier.**  Equal length-`k` parity windows at
  `a` and `c` give `θ_c − θ_a = (2^k/3^j)(θ_{c+k} − θ_{a+k})` (`theta_repetition`), where `j` is
  the number of odd steps *inside that window*.  This is a contraction only if that window's
  odd-step density exceeds `log 2/log 3 = 0.6309…`; a global liminf says nothing about it.

`IsUniformlyGeometric` is exactly the window-uniform form of "`Λ` grows geometrically", it
implies divergence (`cocycle_le_orbit`, `exists_le_cocycle`), and it is a *genuine* restriction:
a numerically typical divergent-looking orbit has even runs of length `≍ log n` and so fails it.
This is the honest price of the transfer, and it is recorded in the capstone's scope note
(`RB/CocycleKernel.lean`).

## Contents

* `RB.Collatz.sOdd`, `RB.Collatz.cocycle` (`Λ`), `RB.Collatz.scaled` (`M`) — the cocycle, the
  scaled orbit, and their exact relation `orbit_eq`.
* `RB.Collatz.IsUniformlyGeometric` — the window-uniform growth hypothesis, with
  `one_le_growthConst`, `cocycle_ratio_le`, `exists_le_cocycle`, `orbit_divergent`,
  `orbit_injective`.
* `RB.Collatz.IsCocycleConstant`, **`RB.Collatz.exists_cocycleConstant`** — `K = lim xₙ/Λₙ`
  exists (monotone + bounded) whenever the orbit is uniformly geometric.
* `RB.Collatz.theta`, `theta_nonneg`, `theta_le_tailBound` — the defect `θₙ ∈ [0, B]`.
* **`RB.Collatz.dist_le_of_repetition`** — repetition ⇒ cocycle kernel violator:
  `‖δ(Λ_c − Λ_a)‖ ≤ B₀·ρ^k·B`, the nearest integer being `x_c − x_a`.
* `RB.Collatz.repetition_le_add` — the growth ceiling `k ≤ c + t` for `n₀ < 2^t`.

## References

* [B2A2] `plans/plan-B2A2.html`: §3.2 (this file), WP8 / T3b.
* [Ter76] R. Terras. *A stopping time problem on the positive integers.* Acta Arith. **30**
  (1976), 241–252 (`CC.terras_periodicity`, `CC.linear_decomposition`).
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J. **51**
  (2009), 243–252.
-/

namespace RB.Collatz

open CC ForMathlib.SubwordComplexity

/-! ## The cocycle and the scaled orbit -/

/-- `Sₙ` — the number of odd steps among the first `n` steps of the orbit of `n₀`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def sOdd (n₀ n : ℕ) : ℕ := num_odd_steps n n₀

/-- **The Collatz cocycle** `Λₙ := 3^{Sₙ}/2ⁿ` ([B2A2] §3.2) — an `S`-unit in `⟨2,3⟩`, and the
exact multiplier of the orbit: `xₙ = Λₙ·(n₀ + ∑_{i<n} vᵢ/(2Λ_{i+1}))`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def cocycle (n₀ n : ℕ) : ℚ := (3 : ℚ) ^ sOdd n₀ n / 2 ^ n

/-- **The scaled orbit** `Mₙ := xₙ/Λₙ`, whose limit is the cocycle constant `K`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def scaled (n₀ n : ℕ) : ℚ := (T_iter n n₀ : ℚ) * 2 ^ n / 3 ^ sOdd n₀ n

@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma cocycle_pos (n₀ n : ℕ) : 0 < cocycle n₀ n := by
  unfold cocycle; positivity

@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma cocycle_zero (n₀ : ℕ) : cocycle n₀ 0 = 1 := by
  simp [cocycle, sOdd, num_odd_steps]

/-- `xₙ = Λₙ·Mₙ` — the cocycle really is the orbit's multiplier. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma orbit_eq (n₀ n : ℕ) : (T_iter n n₀ : ℚ) = cocycle n₀ n * scaled n₀ n := by
  unfold cocycle scaled
  have h2 : ((2 : ℚ) ^ n) ≠ 0 := by positivity
  have h3 : ((3 : ℚ) ^ sOdd n₀ n) ≠ 0 := by positivity
  field_simp

/-- Odd steps split at a window boundary: `S_{a+k} = S_a + (odd steps of the length-`k` window
at `a`)`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma sOdd_add (n₀ a k : ℕ) :
    sOdd n₀ (a + k) = sOdd n₀ a + num_odd_steps k (T_iter a n₀) := by
  unfold sOdd num_odd_steps
  rw [Finset.sum_range_add]
  congr 1
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [← T_iter_add, Nat.add_comm a i]

/-- The cocycle's window factor: `Λ_{a+k} = Λ_a·3^j/2^k` with `j` the window's odd-step count. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma cocycle_add (n₀ a k : ℕ) :
    cocycle n₀ (a + k)
      = cocycle n₀ a * 3 ^ num_odd_steps k (T_iter a n₀) / 2 ^ k := by
  unfold cocycle
  rw [sOdd_add, pow_add, pow_add]
  ring

@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma scaled_zero (n₀ : ℕ) : scaled n₀ 0 = n₀ := by
  simp [scaled, sOdd, num_odd_steps, T_iter]

/-- **The increment of the scaled orbit**: `M_{n+1} − Mₙ = vₙ/(2Λ_{n+1})` ([B2A2] §3.2's
`xₙ/Λₙ = x₀ + ∑ vᵢ/(2Λ_{i+1})`), straight from `2x_{n+1} = 3^{vₙ}xₙ + vₙ`. -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma scaled_sub_succ (n₀ n : ℕ) :
    scaled n₀ (n + 1) - scaled n₀ n
      = (X (T_iter n n₀) : ℚ) / (2 * cocycle n₀ (n + 1)) := by
  have hexp : 2 * T_iter (n + 1) n₀
      = 3 ^ X (T_iter n n₀) * T_iter n n₀ + X (T_iter n n₀) := T_expand _
  have hexpQ : 2 * (T_iter (n + 1) n₀ : ℚ)
      = 3 ^ X (T_iter n n₀) * (T_iter n n₀ : ℚ) + (X (T_iter n n₀) : ℚ) := by
    exact_mod_cast congrArg (fun m : ℕ => (m : ℚ)) hexp
  have hS : sOdd n₀ (n + 1) = sOdd n₀ n + X (T_iter n n₀) := num_odd_steps_succ n n₀
  have hne : (2 : ℚ) * cocycle n₀ (n + 1) ≠ 0 := by
    have := cocycle_pos n₀ (n + 1); positivity
  have h1 : scaled n₀ (n + 1) * (2 * cocycle n₀ (n + 1)) = 2 * (T_iter (n + 1) n₀ : ℚ) := by
    unfold scaled cocycle
    rw [hS]
    have h2 : ((2 : ℚ) ^ (n + 1)) ≠ 0 := by positivity
    have h3 : ((3 : ℚ) ^ (sOdd n₀ n + X (T_iter n n₀))) ≠ 0 := by positivity
    field_simp
  have h2 : scaled n₀ n * (2 * cocycle n₀ (n + 1))
      = 3 ^ X (T_iter n n₀) * (T_iter n n₀ : ℚ) := by
    unfold scaled cocycle
    rw [hS, pow_add, pow_succ]
    have h2 : ((2 : ℚ) ^ n) ≠ 0 := by positivity
    have h3 : ((3 : ℚ) ^ sOdd n₀ n) ≠ 0 := by positivity
    field_simp
  rw [eq_div_iff hne, sub_mul, h1, h2]
  linear_combination hexpQ

@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma scaled_mono (n₀ : ℕ) : Monotone (scaled n₀) := by
  refine monotone_nat_of_le_succ fun n => ?_
  have h := scaled_sub_succ n₀ n
  have hpos : (0 : ℚ) ≤ (X (T_iter n n₀) : ℚ) / (2 * cocycle n₀ (n + 1)) := by
    have := cocycle_pos n₀ (n + 1)
    positivity
  linarith [h ▸ hpos]

/-- The scaled orbit never drops below `n₀`, so `Λₙ ≤ xₙ` for `n₀ ≥ 1`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma cocycle_le_orbit {n₀ : ℕ} (hn₀ : 1 ≤ n₀) (n : ℕ) :
    cocycle n₀ n ≤ (T_iter n n₀ : ℚ) := by
  have hM : (1 : ℚ) ≤ scaled n₀ n := by
    have h0 : scaled n₀ 0 ≤ scaled n₀ n := scaled_mono n₀ (Nat.zero_le n)
    rw [scaled_zero] at h0
    have : (1 : ℚ) ≤ (n₀ : ℚ) := by exact_mod_cast hn₀
    linarith
  rw [orbit_eq]
  nlinarith [cocycle_pos n₀ n]

/-! ## Uniform geometric divergence -/

/-- **Uniformly geometric divergence** ([B2A2] §3.2, strengthened — see the module doc): the
cocycle grows geometrically *from every position*,

  `Λₙ ≤ B₀·ρᵐ·Λ_{n+m}`  for all `n, m`,  `0 < ρ < 1`.

Equivalently: every window of length `m` contains at least `βm − b` odd steps for some
`β > log 2/log 3`.  Strictly stronger than `liminf (1/n) log xₙ > 0`, and strictly weaker than
the model orbit's exact `(3/2)ⁿ` growth. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def IsUniformlyGeometric (n₀ : ℕ) (ρ B₀ : ℚ) : Prop :=
  0 < ρ ∧ ρ < 1 ∧ ∀ n m : ℕ, cocycle n₀ n ≤ B₀ * ρ ^ m * cocycle n₀ (n + m)

@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma one_le_growthConst {n₀ : ℕ} {ρ B₀ : ℚ} (h : IsUniformlyGeometric n₀ ρ B₀) : 1 ≤ B₀ := by
  have h0 := h.2.2 0 0
  simp only [pow_zero, mul_one, Nat.add_zero] at h0
  nlinarith [cocycle_pos n₀ 0]

/-- The window ratio bound in quotient form: `Λₙ/Λ_{n+m} ≤ B₀·ρᵐ`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma cocycle_ratio_le {n₀ : ℕ} {ρ B₀ : ℚ} (h : IsUniformlyGeometric n₀ ρ B₀) (n m : ℕ) :
    cocycle n₀ n / cocycle n₀ (n + m) ≤ B₀ * ρ ^ m :=
  (div_le_iff₀ (cocycle_pos n₀ (n + m))).mpr (h.2.2 n m)

/-- **The cocycle diverges**, geometrically: for every bound `C` all but finitely many `Λₙ`
exceed it.  (`Λ₀ = 1 ≤ B₀ρⁿΛₙ` and `ρ⁻ⁿ → ∞`.) -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem exists_le_cocycle {n₀ : ℕ} {ρ B₀ : ℚ} (h : IsUniformlyGeometric n₀ ρ B₀) (C : ℚ) :
    ∃ N : ℕ, ∀ n, N ≤ n → C ≤ cocycle n₀ n := by
  obtain ⟨hρ0, hρ1, hgeo⟩ := h
  have hB₀ : 1 ≤ B₀ := one_le_growthConst ⟨hρ0, hρ1, hgeo⟩
  have hinv : (1 : ℚ) < 1 / ρ := by rw [lt_div_iff₀ hρ0]; linarith
  obtain ⟨N, hN⟩ := pow_unbounded_of_one_lt (C * B₀) hinv
  refine ⟨N, fun n hn => ?_⟩
  have hstep := hgeo 0 n
  rw [cocycle_zero, Nat.zero_add] at hstep
  have hmono : (1 / ρ : ℚ) ^ N ≤ (1 / ρ) ^ n := pow_le_pow_right₀ (le_of_lt hinv) hn
  have hρn : (0 : ℚ) < ρ ^ n := by positivity
  have hkey : C * B₀ * ρ ^ n < 1 := by
    have h1 : C * B₀ < (1 / ρ) ^ n := lt_of_lt_of_le hN hmono
    have h2 : ((1 : ℚ) / ρ) ^ n * ρ ^ n = 1 := by
      rw [div_pow, one_pow, div_mul_cancel₀]
      positivity
    nlinarith
  nlinarith [cocycle_pos n₀ n]

/-- **Uniform geometry ⇒ divergence**, which is what justifies the name: `xₙ ≥ Λₙ ≥ ρ⁻ⁿ/B₀`, so
the orbit passes every bound.  (The converse fails — see the module doc.) -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem orbit_divergent {n₀ : ℕ} (hn₀ : 1 ≤ n₀) {ρ B₀ : ℚ}
    (h : IsUniformlyGeometric n₀ ρ B₀) (C : ℚ) :
    ∃ N : ℕ, ∀ n, N ≤ n → C ≤ (T_iter n n₀ : ℚ) := by
  obtain ⟨N, hN⟩ := exists_le_cocycle h C
  exact ⟨N, fun n hn => le_trans (hN n hn) (cocycle_le_orbit hn₀ n)⟩

/-- Under uniform geometry the orbit is **injective**: a repeated value would make it eventually
periodic, hence bounded, while `xₙ ≥ Λₙ → ∞`. -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem orbit_injective {n₀ : ℕ} (hn₀ : 1 ≤ n₀) {ρ B₀ : ℚ}
    (h : IsUniformlyGeometric n₀ ρ B₀) : Function.Injective fun n => T_iter n n₀ := by
  have hper : ∀ a c : ℕ, a < c → T_iter a n₀ = T_iter c n₀ →
      ∀ m : ℕ, T_iter (a + m * (c - a)) n₀ = T_iter a n₀ := by
    intro a c hac heq m
    induction m with
    | zero => simp
    | succ m ih =>
      have hstep : a + (m + 1) * (c - a) = (c - a) + (a + m * (c - a)) := by ring
      rw [hstep, T_iter_add, ih, ← T_iter_add, show (c - a) + a = c from by omega, ← heq]
  have hmain : ∀ a c : ℕ, a < c → T_iter a n₀ = T_iter c n₀ → False := by
    intro a c hac heq
    obtain ⟨N, hN⟩ := exists_le_cocycle h ((T_iter a n₀ : ℚ) + 1)
    obtain ⟨m, hm⟩ : ∃ m : ℕ, N ≤ a + m * (c - a) := by
      refine ⟨N, ?_⟩
      have h1 : 1 ≤ c - a := by omega
      nlinarith [Nat.zero_le a]
    have h1 := hN _ hm
    have h2 := cocycle_le_orbit hn₀ (a + m * (c - a))
    rw [hper a c hac heq m] at h2
    linarith
  intro a c hac
  rcases lt_trichotomy a c with h' | h' | h'
  · exact absurd hac (fun hh => hmain a c h' hh)
  · exact h'
  · exact absurd hac.symm (fun hh => hmain c a h' hh)

/-! ## The cocycle constant `K` -/

/-- The tail bound `B := B₀/(1−ρ)` — the uniform ceiling for the defect `θ`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def tailBound (ρ B₀ : ℚ) : ℚ := B₀ / (1 - ρ)

private lemma geom_tail_le {ρ : ℚ} (hρ0 : 0 < ρ) (hρ1 : ρ < 1) (m : ℕ) :
    ∑ u ∈ Finset.range m, ρ ^ (u + 1) ≤ 1 / (1 - ρ) := by
  have h1ρ : (0 : ℚ) < 1 - ρ := by linarith
  rw [le_div_iff₀ h1ρ]
  have key : (∑ u ∈ Finset.range m, ρ ^ (u + 1)) * (1 - ρ) = ρ * (1 - ρ ^ m) := by
    induction m with
    | zero => simp
    | succ m ih => rw [Finset.sum_range_succ, add_mul, ih]; ring
  rw [key]
  nlinarith [pow_nonneg hρ0.le m]

/-- **The tail estimate**: `Λₙ·(M_N − Mₙ) ≤ B` for `N ≥ n` — the increments `vᵢ/(2Λ_{i+1})`
are dominated by the geometric series `B₀ρ^{i+1-n}`. -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem cocycle_mul_scaled_sub_le {n₀ : ℕ} {ρ B₀ : ℚ} (h : IsUniformlyGeometric n₀ ρ B₀)
    (n N : ℕ) (hnN : n ≤ N) :
    cocycle n₀ n * (scaled n₀ N - scaled n₀ n) ≤ tailBound ρ B₀ := by
  obtain ⟨hρ0, hρ1, hgeo⟩ := h
  have hB₀ : 1 ≤ B₀ := one_le_growthConst ⟨hρ0, hρ1, hgeo⟩
  have key : ∀ N, n ≤ N → cocycle n₀ n * (scaled n₀ N - scaled n₀ n)
      ≤ B₀ * ∑ u ∈ Finset.range (N - n), ρ ^ (u + 1) := by
    intro N hN
    induction N, hN using Nat.le_induction with
    | base => simp
    | succ N hN ih =>
      have hstepbd : cocycle n₀ n * (scaled n₀ (N + 1) - scaled n₀ N) ≤ B₀ * ρ ^ (N + 1 - n) := by
        rw [scaled_sub_succ]
        have hx : (X (T_iter N n₀) : ℚ) ≤ 1 := by
          have : X (T_iter N n₀) ≤ 1 := by simp only [X_eq_mod]; omega
          exact_mod_cast this
        have hx0 : (0 : ℚ) ≤ (X (T_iter N n₀) : ℚ) := by positivity
        have hΛ : 0 < cocycle n₀ (N + 1) := cocycle_pos n₀ (N + 1)
        have hratio : cocycle n₀ n / cocycle n₀ (N + 1) ≤ B₀ * ρ ^ (N + 1 - n) := by
          have := cocycle_ratio_le ⟨hρ0, hρ1, hgeo⟩ n (N + 1 - n)
          rwa [show n + (N + 1 - n) = N + 1 from by omega] at this
        have hle : cocycle n₀ n * ((X (T_iter N n₀) : ℚ) / (2 * cocycle n₀ (N + 1)))
            ≤ cocycle n₀ n / cocycle n₀ (N + 1) := by
          rw [← mul_div_assoc, div_le_div_iff₀ (by positivity) hΛ]
          nlinarith [mul_nonneg (by linarith : (0 : ℚ) ≤ 2 - (X (T_iter N n₀) : ℚ))
            (mul_pos (cocycle_pos n₀ n) hΛ).le]
        linarith
      have hidx : N + 1 - n = (N - n) + 1 := by omega
      rw [hidx, Finset.sum_range_succ, mul_add]
      have hsplit : cocycle n₀ n * (scaled n₀ (N + 1) - scaled n₀ n)
          = cocycle n₀ n * (scaled n₀ N - scaled n₀ n)
            + cocycle n₀ n * (scaled n₀ (N + 1) - scaled n₀ N) := by ring
      rw [hsplit, show N - n + 1 = N + 1 - n from by omega]
      linarith
  have hfin := key N hnN
  have hgeoS := geom_tail_le hρ0 hρ1 (N - n)
  have hB₀0 : (0 : ℚ) < B₀ := by linarith
  calc cocycle n₀ n * (scaled n₀ N - scaled n₀ n)
      ≤ B₀ * ∑ u ∈ Finset.range (N - n), ρ ^ (u + 1) := hfin
    _ ≤ B₀ * (1 / (1 - ρ)) := by nlinarith
    _ = tailBound ρ B₀ := by unfold tailBound; ring

/-- **The cocycle constant** `K = lim xₙ/Λₙ` ([B2A2] §3.2). -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def IsCocycleConstant (n₀ : ℕ) (K : ℝ) : Prop :=
  Filter.Tendsto (fun n => ((scaled n₀ n : ℚ) : ℝ)) Filter.atTop (nhds K)

/-- **The cocycle constant exists** ([B2A2] §3.2: "`K := lim xₙ/Λₙ` exists in `[1,∞)`"): the
scaled orbit is increasing (`scaled_mono`) and bounded above by `n₀ + B`
(`cocycle_mul_scaled_sub_le` at `n = 0`, where `Λ₀ = 1`). -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem exists_cocycleConstant {n₀ : ℕ} {ρ B₀ : ℚ} (h : IsUniformlyGeometric n₀ ρ B₀) :
    ∃ K : ℝ, IsCocycleConstant n₀ K ∧ (n₀ : ℝ) ≤ K := by
  have hmono : Monotone fun n => ((scaled n₀ n : ℚ) : ℝ) := fun a b hab => by
    show ((scaled n₀ a : ℚ) : ℝ) ≤ ((scaled n₀ b : ℚ) : ℝ)
    exact_mod_cast scaled_mono n₀ hab
  have hbdd : BddAbove (Set.range fun n => ((scaled n₀ n : ℚ) : ℝ)) := by
    refine ⟨((((n₀ : ℚ) + tailBound ρ B₀ : ℚ)) : ℝ), ?_⟩
    rintro y ⟨n, rfl⟩
    have h0 := cocycle_mul_scaled_sub_le h 0 n (Nat.zero_le n)
    rw [cocycle_zero, one_mul, scaled_zero] at h0
    have hq : scaled n₀ n ≤ (n₀ : ℚ) + tailBound ρ B₀ := by linarith
    show ((scaled n₀ n : ℚ) : ℝ) ≤ ((((n₀ : ℚ) + tailBound ρ B₀ : ℚ)) : ℝ)
    exact_mod_cast hq
  refine ⟨_, tendsto_atTop_ciSup hmono hbdd, ?_⟩
  have h0 := hmono.ge_of_tendsto (tendsto_atTop_ciSup hmono hbdd) 0
  rw [scaled_zero] at h0
  exact_mod_cast h0

/-! ## The tail defect `θ` -/

/-- **The tail defect** `θₙ := δ·Λₙ − xₙ` ([B2A2] §3.2, the `RB.tail` analogue), for a
*rational* value `δ` of the cocycle constant. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def theta (n₀ : ℕ) (δ : ℚ) (n : ℕ) : ℚ := δ * cocycle n₀ n - (T_iter n n₀ : ℚ)

@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma theta_eq (n₀ : ℕ) (δ : ℚ) (n : ℕ) :
    theta n₀ δ n = cocycle n₀ n * (δ - scaled n₀ n) := by
  unfold theta
  rw [orbit_eq]
  ring

/-- `Mₙ ≤ δ` — the scaled orbit increases to its limit. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma scaled_le_of_cocycleConstant {n₀ : ℕ} {δ : ℚ} (hK : IsCocycleConstant n₀ (δ : ℝ))
    (n : ℕ) : scaled n₀ n ≤ δ := by
  have hmono : Monotone fun m => ((scaled n₀ m : ℚ) : ℝ) := fun a b hab => by
    show ((scaled n₀ a : ℚ) : ℝ) ≤ ((scaled n₀ b : ℚ) : ℝ)
    exact_mod_cast scaled_mono n₀ hab
  have := hmono.ge_of_tendsto hK n
  exact_mod_cast this

/-- `0 ≤ θₙ` — the orbit never overshoots the cocycle constant. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma theta_nonneg {n₀ : ℕ} {δ : ℚ} (hK : IsCocycleConstant n₀ (δ : ℝ)) (n : ℕ) :
    0 ≤ theta n₀ δ n := by
  rw [theta_eq]
  have h1 := scaled_le_of_cocycleConstant hK n
  have h2 := cocycle_pos n₀ n
  nlinarith

/-- `θₙ ≤ B` — the defect is uniformly bounded, by the tail estimate. -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem theta_le_tailBound {n₀ : ℕ} {ρ B₀ δ : ℚ} (h : IsUniformlyGeometric n₀ ρ B₀)
    (hK : IsCocycleConstant n₀ (δ : ℝ)) (n : ℕ) : theta n₀ δ n ≤ tailBound ρ B₀ := by
  have hpos := cocycle_pos n₀ n
  have hev : ∀ᶠ N : ℕ in Filter.atTop, ((scaled n₀ N : ℚ) : ℝ)
      ≤ ((scaled n₀ n + tailBound ρ B₀ / cocycle n₀ n : ℚ) : ℝ) := by
    filter_upwards [Filter.eventually_ge_atTop n] with N hN
    have hle := cocycle_mul_scaled_sub_le h n N hN
    have hq : scaled n₀ N ≤ scaled n₀ n + tailBound ρ B₀ / cocycle n₀ n := by
      have hsub : scaled n₀ N - scaled n₀ n ≤ tailBound ρ B₀ / cocycle n₀ n := by
        rw [le_div_iff₀ hpos, mul_comm]
        exact hle
      linarith
    show ((scaled n₀ N : ℚ) : ℝ) ≤ ((scaled n₀ n + tailBound ρ B₀ / cocycle n₀ n : ℚ) : ℝ)
    exact_mod_cast hq
  have hlim : (δ : ℝ) ≤ ((scaled n₀ n + tailBound ρ B₀ / cocycle n₀ n : ℚ) : ℝ) :=
    le_of_tendsto hK hev
  have hQ : δ ≤ scaled n₀ n + tailBound ρ B₀ / cocycle n₀ n := by exact_mod_cast hlim
  rw [theta_eq]
  calc cocycle n₀ n * (δ - scaled n₀ n)
      ≤ cocycle n₀ n * (tailBound ρ B₀ / cocycle n₀ n) := by nlinarith
    _ = tailBound ρ B₀ := by field_simp

/-- Two defects differ by at most `B`. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma abs_theta_sub_le {n₀ : ℕ} {ρ B₀ δ : ℚ} (h : IsUniformlyGeometric n₀ ρ B₀)
    (hK : IsCocycleConstant n₀ (δ : ℝ)) (m n : ℕ) :
    |theta n₀ δ m - theta n₀ δ n| ≤ tailBound ρ B₀ := by
  have h1 := theta_nonneg hK m
  have h2 := theta_le_tailBound h hK m
  have h3 := theta_nonneg hK n
  have h4 := theta_le_tailBound h hK n
  rw [abs_le]
  constructor <;> linarith

/-! ## Repetitions of the parity word -/

/-- A **repetition**: the length-`k` parity windows at `a` and at `c` coincide. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
def IsRepetition (n₀ a c k : ℕ) : Prop :=
  factor (parityWord n₀) k a = factor (parityWord n₀) k c

@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma E_vec_eq_of_repetition {n₀ a c k : ℕ} (h : IsRepetition n₀ a c k) :
    E_vec k (T_iter a n₀) = E_vec k (T_iter c n₀) := by
  rw [← factor_eq_E_vec, ← factor_eq_E_vec]
  exact h

/-- Equal windows carry equal odd-step counts — the exponent `j` of the window's `3`-part. -/
@[category API, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
lemma oddCount_eq_of_repetition {n₀ a c k : ℕ} (h : IsRepetition n₀ a c k) :
    num_odd_steps k (T_iter a n₀) = num_odd_steps k (T_iter c n₀) :=
  num_odd_steps_eq_of_E_vec_eq k _ _ (E_vec_eq_of_repetition h)

private lemma T_iter_window (a k n₀ : ℕ) : T_iter k (T_iter a n₀) = T_iter (a + k) n₀ := by
  rw [← T_iter_add, Nat.add_comm k a]

/-- **The exact window relation** ([B2A2] §3.2): equal length-`k` windows at `a` and `c` give

  `2^k·(x_{c+k} − x_{a+k}) = 3^j·(x_c − x_a)`,

the affine recurrence `2^k·T^k(m) = 3^j·m + Q` (`CC.linear_decomposition`) applied at the two
window starts, whose `j` and `Q` agree because the windows do.  This is the Collatz analogue of
`RB.W_eq_of_repetition`, and it is *unconditional*. -/
@[category research solved, AMS 11 37, ref "B2A2" "Ter76", group "rb_collatz_cocycle"]
theorem two_pow_mul_sub_eq_of_repetition {n₀ a c k : ℕ} (h : IsRepetition n₀ a c k) :
    (2 : ℤ) ^ k * ((T_iter (c + k) n₀ : ℤ) - (T_iter (a + k) n₀ : ℤ))
      = 3 ^ num_odd_steps k (T_iter a n₀)
          * ((T_iter c n₀ : ℤ) - (T_iter a n₀ : ℤ)) := by
  have ha := linear_decomposition k (T_iter a n₀)
  have hc := linear_decomposition k (T_iter c n₀)
  rw [T_iter_window] at ha hc
  rw [← oddCount_eq_of_repetition h,
    ← decomposition_correction_eq_of_E_vec_eq k _ _ (E_vec_eq_of_repetition h)] at hc
  have haZ : (2 : ℤ) ^ k * (T_iter (a + k) n₀ : ℤ)
      = 3 ^ num_odd_steps k (T_iter a n₀) * (T_iter a n₀ : ℤ)
        + (decomposition_correction k (T_iter a n₀) : ℤ) := by exact_mod_cast ha
  have hcZ : (2 : ℤ) ^ k * (T_iter (c + k) n₀ : ℤ)
      = 3 ^ num_odd_steps k (T_iter a n₀) * (T_iter c n₀ : ℤ)
        + (decomposition_correction k (T_iter a n₀) : ℤ) := by exact_mod_cast hc
  linarith [haZ, hcZ]

/-- **The defect contraction identity**: `3^j(θ_c − θ_a) = 2^k(θ_{c+k} − θ_{a+k})` — the
`δ`-terms cancel because `Λ_{a+k} = Λ_a·3^j/2^k` and `Λ_{c+k} = Λ_c·3^j/2^k` with the *same*
window factor.  The `RB.lemmaR_tail` analogue; note the contraction ratio is the window's own
multiplier `2^k/3^j`, not the model's fixed `(2/3)^k`. -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem theta_repetition {n₀ a c k : ℕ} {δ : ℚ} (h : IsRepetition n₀ a c k) :
    (3 : ℚ) ^ num_odd_steps k (T_iter a n₀) * (theta n₀ δ c - theta n₀ δ a)
      = 2 ^ k * (theta n₀ δ (c + k) - theta n₀ δ (a + k)) := by
  set j := num_odd_steps k (T_iter a n₀) with hj
  have hΛa := cocycle_add n₀ a k
  have hΛc := cocycle_add n₀ c k
  rw [← oddCount_eq_of_repetition h, ← hj] at hΛc
  have hZ := two_pow_mul_sub_eq_of_repetition h
  have hQ : (2 : ℚ) ^ k * ((T_iter (c + k) n₀ : ℚ) - (T_iter (a + k) n₀ : ℚ))
      = 3 ^ j * ((T_iter c n₀ : ℚ) - (T_iter a n₀ : ℚ)) := by exact_mod_cast hZ
  have h2 : ((2 : ℚ) ^ k) ≠ 0 := by positivity
  unfold theta
  rw [hΛa, hΛc]
  field_simp
  linear_combination hQ

/-- **Repetition ⇒ cocycle kernel violator** ([B2A2] §3.2, the deliverable): if the cocycle
constant is the rational `δ` and the parity word repeats at `(a, c)` for length `k`, then

  `‖δ·(Λ_c − Λ_a)‖ ≤ B₀·ρ^k·B`,

the nearest integer being `x_c − x_a`.  The quality is the window multiplier `Λ_a/Λ_{a+k}`,
bounded by `B₀ρ^k` exactly by uniform geometry — this is where the strengthened hypothesis is
spent (module doc).  As on the model side, rationality of the constant enters *only* here, to
land the value in `ℚ` where the Diophantine engines live ([B2A2] §2.2's gate). -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem dist_le_of_repetition {n₀ : ℕ} {ρ B₀ δ : ℚ} (hgeo : IsUniformlyGeometric n₀ ρ B₀)
    (hK : IsCocycleConstant n₀ (δ : ℝ)) {a c k : ℕ} (h : IsRepetition n₀ a c k) :
    (δ * (cocycle n₀ c - cocycle n₀ a)).distToNearestInt ≤ B₀ * ρ ^ k * tailBound ρ B₀ := by
  set j := num_odd_steps k (T_iter a n₀) with hj
  -- the contraction factor is the window multiplier `Λ_a/Λ_{a+k} = 2^k/3^j`
  have hΛa := cocycle_add n₀ a k
  have hfac : (2 : ℚ) ^ k / 3 ^ j = cocycle n₀ a / cocycle n₀ (a + k) := by
    rw [hΛa, ← hj]
    have h3 : ((3 : ℚ) ^ j) ≠ 0 := by positivity
    have h2 : ((2 : ℚ) ^ k) ≠ 0 := by positivity
    have hΛ : cocycle n₀ a ≠ 0 := (cocycle_pos n₀ a).ne'
    field_simp
  have hratio : (2 : ℚ) ^ k / 3 ^ j ≤ B₀ * ρ ^ k := by
    rw [hfac]
    exact cocycle_ratio_le hgeo a k
  -- the contraction itself
  have hid := theta_repetition (n₀ := n₀) (δ := δ) h
  have h3 : (0 : ℚ) < 3 ^ j := by positivity
  have hsub : theta n₀ δ c - theta n₀ δ a
      = (2 : ℚ) ^ k / 3 ^ j * (theta n₀ δ (c + k) - theta n₀ δ (a + k)) := by
    field_simp
    linarith [hid]
  have habs : |theta n₀ δ c - theta n₀ δ a| ≤ B₀ * ρ ^ k * tailBound ρ B₀ := by
    rw [hsub, abs_mul, abs_of_nonneg (by positivity : (0 : ℚ) ≤ (2 : ℚ) ^ k / 3 ^ j)]
    have hB := abs_theta_sub_le hgeo hK (c + k) (a + k)
    have hBnn : (0 : ℚ) ≤ tailBound ρ B₀ := le_trans (abs_nonneg _) hB
    have h2 : (0 : ℚ) ≤ (2 : ℚ) ^ k / 3 ^ j := by positivity
    calc (2 : ℚ) ^ k / 3 ^ j * |theta n₀ δ (c + k) - theta n₀ δ (a + k)|
        ≤ (2 : ℚ) ^ k / 3 ^ j * tailBound ρ B₀ := by nlinarith
      _ ≤ B₀ * ρ ^ k * tailBound ρ B₀ := by nlinarith
  -- the nearest integer is `x_c − x_a`
  refine le_trans (Rat.distToNearestInt_le_abs_sub_intCast _
    ((T_iter c n₀ : ℤ) - (T_iter a n₀ : ℤ))) ?_
  have hEq : δ * (cocycle n₀ c - cocycle n₀ a)
      - (((T_iter c n₀ : ℤ) - (T_iter a n₀ : ℤ) : ℤ) : ℚ)
      = theta n₀ δ c - theta n₀ δ a := by
    unfold theta
    push_cast
    ring
  rw [hEq]
  exact habs

/-! ## The growth ceiling -/

/-- A repetition forces `2^k ∣ x_c − x_a` (Terras, via the WP7 dictionary). -/
@[category API, AMS 11 37, ref "B2A2" "Ter76", group "rb_collatz_cocycle"]
lemma two_pow_dvd_of_repetition {n₀ : ℕ} (hn₀ : 1 ≤ n₀) {a c k : ℕ}
    (h : IsRepetition n₀ a c k) :
    (2 : ℤ) ^ k ∣ ((T_iter c n₀ : ℤ) - (T_iter a n₀ : ℤ)) := by
  have hres : (T_iter a n₀ : ZMod (2 ^ k)) = (T_iter c n₀ : ZMod (2 ^ k)) :=
    (factor_eq_iff_residue_eq hn₀ k a c).mp h
  have hmod : T_iter a n₀ ≡ T_iter c n₀ [MOD 2 ^ k] :=
    (ZMod.natCast_eq_natCast_iff _ _ _).mp hres
  have := hmod.dvd
  simpa using this

/-- **The growth ceiling** `k ≤ c + t` (for `n₀ < 2^t`): a repetition cannot be long relative to
its position.  `2^k` divides the nonzero difference `x_c − x_a` (`orbit_injective` supplies
"nonzero"), which is at most `2^c·n₀` by `T^n n₀ ≤ 2ⁿ n₀`.  The analogue of
`RB.repetition_le_add`; it is what turns "`k` large" into "`c` large". -/
@[category research solved, AMS 11 37, ref "B2A2", group "rb_collatz_cocycle"]
theorem repetition_le_add {n₀ : ℕ} (hn₀ : 1 ≤ n₀) {ρ B₀ : ℚ}
    (hgeo : IsUniformlyGeometric n₀ ρ B₀) {a c k t : ℕ} (hac : a < c) (ht : n₀ < 2 ^ t)
    (h : IsRepetition n₀ a c k) : k ≤ c + t := by
  have hne : T_iter c n₀ ≠ T_iter a n₀ := fun hh =>
    absurd (orbit_injective hn₀ hgeo hh) (by omega)
  have hdvd := two_pow_dvd_of_repetition hn₀ h
  have hsubne : ((T_iter c n₀ : ℤ) - (T_iter a n₀ : ℤ)) ≠ 0 := by
    intro hh
    apply hne
    have : (T_iter c n₀ : ℤ) = (T_iter a n₀ : ℤ) := by linarith
    exact_mod_cast this
  have hle : (2 : ℤ) ^ k ≤ |(T_iter c n₀ : ℤ) - (T_iter a n₀ : ℤ)| :=
    Int.le_of_dvd (abs_pos.mpr hsubne) ((dvd_abs _ _).mpr hdvd)
  have hbound : |(T_iter c n₀ : ℤ) - (T_iter a n₀ : ℤ)| ≤ ((2 ^ c * n₀ : ℕ) : ℤ) := by
    have hc := T_iter_le_two_pow_mul n₀ c
    have ha := T_iter_le_two_pow_mul n₀ a
    have hmono : (2 : ℕ) ^ a * n₀ ≤ 2 ^ c * n₀ :=
      Nat.mul_le_mul_right _ (Nat.pow_le_pow_right (by norm_num) (by omega))
    have hcZ : (T_iter c n₀ : ℤ) ≤ ((2 ^ c * n₀ : ℕ) : ℤ) := by exact_mod_cast hc
    have haZ : (T_iter a n₀ : ℤ) ≤ ((2 ^ c * n₀ : ℕ) : ℤ) := by
      exact_mod_cast le_trans ha hmono
    have hc0 : (0 : ℤ) ≤ (T_iter c n₀ : ℤ) := Int.natCast_nonneg _
    have ha0 : (0 : ℤ) ≤ (T_iter a n₀ : ℤ) := Int.natCast_nonneg _
    rw [abs_le]
    constructor <;> linarith
  have hleN : (2 : ℕ) ^ k ≤ 2 ^ c * n₀ := by
    have : (2 : ℤ) ^ k ≤ ((2 ^ c * n₀ : ℕ) : ℤ) := le_trans hle hbound
    exact_mod_cast this
  have hlt : (2 : ℕ) ^ k < 2 ^ (c + t) := by
    calc (2 : ℕ) ^ k ≤ 2 ^ c * n₀ := hleN
      _ < 2 ^ c * 2 ^ t := by
          exact mul_lt_mul_of_pos_left ht (by positivity)
      _ = 2 ^ (c + t) := (pow_add 2 c t).symm
  exact le_of_lt (by exact_mod_cast (Nat.pow_lt_pow_iff_right (by norm_num)).mp hlt)

end RB.Collatz
