/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import CC.Periodicity
import CC.Parity
import CITED.AlloucheShallitComplexity
import Mathlib.Data.ZMod.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# The Collatz complexity dictionary (plan-B2A2, WP7 / T3a)

The **CC-side twin of `RB/Residues.lean`**: parity-word block complexity *is* the 2-adic
residue-covering number of the Collatz orbit.  Where `RB/Residues.lean` proves this for the
ceiling model `x_{n+1} = ⌈3x_n/2⌉`, here we prove it for the accelerated Collatz map `CC.T`
(`x ↦ (x·3^{x mod 2} + x mod 2)/2`), on the same one-line mechanism: the **Terras–Everett
periodicity theorem** (`CC.terras_periodicity`) plays the role `RB.isRepetition_iff_dvd` plays
on the model side.

## The word and the dictionary

For a start value `n₀`, the *parity word* is `parityWord n₀ n := X(T^n n₀) = T^n n₀ mod 2` — the
parity of the Collatz orbit, the object of [Dub09]/[Ter76].  Its length-`m` factor at `a` is the
Terras parity vector `E_vec m (T^a n₀)`, so (for `n₀ ≥ 1`, via `terras_periodicity`)

* `factor (parityWord n₀) m a = factor (parityWord n₀) m b ↔ T^a n₀ ≡ T^b n₀ (mod 2^m)`
  (`factor_eq_iff_residue_eq`), and hence
* **`P(parityWord n₀, m) = #{T^n n₀ mod 2^m : n ∈ ℕ}`** (`complexity_eq_ncard_residues`):
  parity-word complexity is the 2-adic residue-covering number of the orbit.

## Corollaries

* **The floor is a pigeonhole** (`card_le_complexity_of_injOn`): distinct orbit values below
  `2^m` are distinct residues, so any `S` of positions with distinct values `< 2^m` gives
  `#S ≤ P(parityWord n₀, m)`.  For an orbit with no repeat (an injective — in particular a
  divergent — orbit) the growth ceiling `T^k n₀ ≤ 2^k n₀` (`T_iter_le_two_pow_mul`) turns this
  into an explicit linear floor `P(parityWord n₀, m) ≥ m − t + 1` when `n₀ < 2^t`
  (`complexity_ge_of_injective`), of slope `1`.  Unlike the model orbit — whose growth is
  *exactly* `(3/2)^n`, giving Dubickas's sharp `log 2/log(3/2) = 1.7095…` — a general Collatz
  orbit only obeys `T n ≤ 2n`, so the guaranteed slope is `1`; the sharp constant is
  orbit-dependent (it is fixed by the odd-step density).  This is the honest CC-side analogue of
  `RB.complexity_lower_bound`.
* **Automatic ⇒ linear covering** (`covering_linear_of_automatic`): if the parity word is
  automatic then the orbit visits only `O(m)` residues mod `2^m` — via
  `AS.complexity_linear_of_automatic` (Cobham's bound) and the dictionary.  Contrapositive
  (`not_automatic_of_covering_superlinear`): superlinearly many residues ⇒ the parity word is
  not automatic.  This is the interface every A.2 attack plugs into (plan-B2A2 §3.1/§3.2).

## References

* [B2A2] `plans/plan-B2A2.html`: §3.1 (this file), WP7 / T3a.
* [Ter76] R. Terras. *A stopping time problem on the positive integers.* Acta Arith. **30**
  (1976), 241–252.  (`CC.terras_periodicity`.)
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J.
  **51** (2009), 243–252.  (The parity word and its linear complexity floor.)
* [Cob72] A. Cobham. *Uniform tag sequences.* Math. Systems Theory **6** (1972), 164–192;
  [AS03] Allouche, Shallit, *Automatic Sequences*, CUP 2003 (`AS.complexity_linear_of_automatic`).
-/

namespace RB.Collatz

open CC
open ForMathlib.SubwordComplexity

/-! ## The parity word of a Collatz orbit -/

/-- **The parity word** `parityWord n₀ n := X(T^n n₀) = T^n n₀ mod 2` — the parity of the
accelerated Collatz orbit of `n₀`, Dubickas's word for the map `CC.T`. -/
@[category API, AMS 11 68, ref "B2A2", group "rb_collatz_dictionary"]
def parityWord (n₀ : ℕ) : ℕ → ℕ := fun n => X (T_iter n n₀)

/-- The letters are `{0,1}`. -/
@[category API, AMS 11 68, ref "B2A2", group "rb_collatz_dictionary"]
lemma parityWord_le_one (n₀ n : ℕ) : parityWord n₀ n ≤ 1 := by
  simp only [parityWord, X_eq_mod]; omega

/-- A length-`m` factor of the parity word at `a` *is* the Terras parity vector of `T^a n₀`:
`factor (parityWord n₀) m a = E_vec m (T^a n₀)`.  Both are `i ↦ X(T^{a+i} n₀)`. -/
@[category research solved, AMS 11 68, ref "B2A2" "Ter76", group "rb_collatz_dictionary"]
lemma factor_eq_E_vec (n₀ m a : ℕ) :
    factor (parityWord n₀) m a = E_vec m (T_iter a n₀) := by
  funext s
  simp only [factor, parityWord, E_vec_apply]
  rw [← T_iter_add, Nat.add_comm a (s : ℕ)]

/-! ## Windows are residues -/

/-- **Windows are residues**: length-`m` factors of the parity word at `a` and `b` agree iff the
orbit values agree mod `2^m`.  The CC-side counterpart of `RB.factor_eq_iff_residue_eq`, powered
by the Terras–Everett periodicity theorem `CC.terras_periodicity`. -/
@[category research solved, AMS 11 68, ref "B2A2" "Ter76", group "rb_collatz_dictionary"]
theorem factor_eq_iff_residue_eq {n₀ : ℕ} (hn₀ : 1 ≤ n₀) (m a b : ℕ) :
    factor (parityWord n₀) m a = factor (parityWord n₀) m b ↔
      (T_iter a n₀ : ZMod (2 ^ m)) = (T_iter b n₀ : ZMod (2 ^ m)) := by
  simp only [factor_eq_E_vec]
  rw [terras_periodicity m (T_iter a n₀) (T_iter b n₀) (T_iter_pos hn₀ a) (T_iter_pos hn₀ b),
      ZMod.natCast_eq_natCast_iff]
  rfl

/-- Ranges of two functions that identify the same arguments have the same `ncard`
(general helper, `= RB.ncard_range_eq`). -/
private lemma ncard_range_eq {α β : Type*} (f : ℕ → α) (g : ℕ → β)
    (h : ∀ a b : ℕ, f a = f b ↔ g a = g b) :
    (Set.range f).ncard = (Set.range g).ncard := by
  let F : Set.range f → Set.range g :=
    fun y => ⟨g (Set.rangeSplitting f y), Set.mem_range_self _⟩
  let G : Set.range g → Set.range f :=
    fun z => ⟨f (Set.rangeSplitting g z), Set.mem_range_self _⟩
  have hFG : ∀ y, G (F y) = y := by
    intro y
    apply Subtype.ext
    show f (Set.rangeSplitting g (F y)) = (y : α)
    have h2 : g (Set.rangeSplitting g (F y)) = g (Set.rangeSplitting f y) :=
      Set.apply_rangeSplitting g (F y)
    have h3 : f (Set.rangeSplitting g (F y)) = f (Set.rangeSplitting f y) := (h _ _).mpr h2
    rw [h3, Set.apply_rangeSplitting f y]
  have hGF : ∀ z, F (G z) = z := by
    intro z
    apply Subtype.ext
    show g (Set.rangeSplitting f (G z)) = (z : β)
    have h2 : f (Set.rangeSplitting f (G z)) = f (Set.rangeSplitting g z) :=
      Set.apply_rangeSplitting f (G z)
    have h3 : g (Set.rangeSplitting f (G z)) = g (Set.rangeSplitting g z) := (h _ _).mp h2
    rw [h3, Set.apply_rangeSplitting g z]
  rw [← Nat.card_coe_set_eq, ← Nat.card_coe_set_eq]
  exact Nat.card_congr ⟨F, G, hFG, hGF⟩

/-- **Parity complexity is residue counting** ([B2A2] §3.1, T3a): the subword complexity of the
parity word at length `m` is the number of residues mod `2^m` occupied by the Collatz orbit,

  `P(parityWord n₀, m) = #{T^n n₀ mod 2^m : n ≥ 0}`.

Immediate from `factor_eq_iff_residue_eq`: length-`m` windows *are* residues mod `2^m`. -/
@[category research solved, AMS 11 68, ref "B2A2" "Ter76" "Dub09", group "rb_collatz_dictionary"]
theorem complexity_eq_ncard_residues {n₀ : ℕ} (hn₀ : 1 ≤ n₀) (m : ℕ) :
    AS.complexity (parityWord n₀) m
      = (Set.range fun n => (T_iter n n₀ : ZMod (2 ^ m))).ncard :=
  ncard_range_eq _ _ (fun a b => factor_eq_iff_residue_eq hn₀ m a b)

/-! ## The floor as a pigeonhole -/

/-- The range of the factor map is finite: parity-word factors take values in `{0,1}`. -/
private lemma range_factor_finite (n₀ m : ℕ) :
    (Set.range fun a => factor (parityWord n₀) m a).Finite := by
  refine Set.Finite.subset (Set.Finite.pi fun _ : Fin m => Set.finite_Iic 1) ?_
  rintro y ⟨a, rfl⟩
  simp only [Set.mem_pi, Set.mem_univ, Set.mem_Iic, forall_const]
  intro s
  exact parityWord_le_one n₀ (a + s)

/-- **The covering pigeonhole** ([B2A2] §3.1): if the orbit values at the positions of `S` are
pairwise distinct and all `< 2^m`, then `#S ≤ P(parityWord n₀, m)`.  Distinct values below the
modulus are distinct residues (`factor_eq_iff_residue_eq`), hence distinct factors. -/
@[category research solved, AMS 11 68, ref "B2A2" "Dub09", group "rb_collatz_dictionary"]
theorem card_le_complexity_of_injOn {n₀ : ℕ} (hn₀ : 1 ≤ n₀) {m : ℕ} (S : Finset ℕ)
    (hbdd : ∀ a ∈ S, T_iter a n₀ < 2 ^ m)
    (hinj : Set.InjOn (fun a => T_iter a n₀) S) :
    S.card ≤ AS.complexity (parityWord n₀) m := by
  classical
  have hinjF : Set.InjOn (fun a => factor (parityWord n₀) m a) S := by
    intro a ha b hb hfab
    have hfab' : factor (parityWord n₀) m a = factor (parityWord n₀) m b := hfab
    have hres : (T_iter a n₀ : ZMod (2 ^ m)) = (T_iter b n₀ : ZMod (2 ^ m)) :=
      (factor_eq_iff_residue_eq hn₀ m a b).mp hfab'
    have hmod : T_iter a n₀ ≡ T_iter b n₀ [MOD 2 ^ m] :=
      (ZMod.natCast_eq_natCast_iff _ _ _).mp hres
    have hval : T_iter a n₀ = T_iter b n₀ :=
      calc T_iter a n₀ = T_iter a n₀ % 2 ^ m := (Nat.mod_eq_of_lt (hbdd a ha)).symm
        _ = T_iter b n₀ % 2 ^ m := hmod
        _ = T_iter b n₀ := Nat.mod_eq_of_lt (hbdd b hb)
    exact hinj ha hb hval
  have hcard : (S.image (fun a => factor (parityWord n₀) m a)).card = S.card :=
    Finset.card_image_of_injOn hinjF
  have hsub : (↑(S.image (fun a => factor (parityWord n₀) m a)) : Set (Fin m → ℕ))
      ⊆ Set.range (fun a => factor (parityWord n₀) m a) := by
    intro y hy
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe] at hy
    obtain ⟨a, -, rfl⟩ := hy
    exact Set.mem_range_self a
  calc S.card
      = (↑(S.image (fun a => factor (parityWord n₀) m a)) : Set (Fin m → ℕ)).ncard := by
        rw [Set.ncard_coe_finset, hcard]
    _ ≤ (Set.range (fun a => factor (parityWord n₀) m a)).ncard :=
        Set.ncard_le_ncard hsub (range_factor_finite n₀ m)
    _ = AS.complexity (parityWord n₀) m := rfl

/-- **The growth ceiling** `T n ≤ 2n`: the accelerated Collatz map at most doubles. -/
@[category API, AMS 11 68, ref "B2A2", group "rb_collatz_dictionary"]
lemma T_le_two_mul (n : ℕ) : T n ≤ 2 * n := by
  rcases Nat.even_or_odd n with ⟨k, rfl⟩ | ⟨k, rfl⟩
  · rw [T_even (by omega)]; omega
  · rw [T_odd (by omega)]; omega

/-- Iterated growth ceiling: `T^k n₀ ≤ 2^k · n₀`. -/
@[category API, AMS 11 68, ref "B2A2", group "rb_collatz_dictionary"]
lemma T_iter_le_two_pow_mul (n₀ k : ℕ) : T_iter k n₀ ≤ 2 ^ k * n₀ := by
  induction k with
  | zero => simp [T_iter]
  | succ k ih =>
    calc T_iter (k + 1) n₀ = T (T_iter k n₀) := rfl
      _ ≤ 2 * T_iter k n₀ := T_le_two_mul _
      _ ≤ 2 * (2 ^ k * n₀) := by omega
      _ = 2 ^ (k + 1) * n₀ := by rw [pow_succ']; ring

/-- **The linear floor for a non-recurrent orbit** ([B2A2] §3.1, T3a; the CC-side analogue of
`RB.complexity_lower_bound`): if the orbit map has no repeat (an *injective* — in particular a
divergent — orbit) and `n₀ < 2^t` with `t ≤ m`, then

  `P(parityWord n₀, m) ≥ m − t + 1`,

a floor of slope `1`.  The first `m − t + 1` orbit values are `< 2^m` (by `T^k n₀ ≤ 2^k n₀`) and,
being distinct, occupy distinct residues.  The slope is `1`, not the model orbit's sharp
`log 2/log(3/2) = 1.7095…`: a general Collatz orbit obeys only `T n ≤ 2n`, so the guaranteed rate
is `1` and the sharp constant is fixed by the orbit's odd-step density. -/
@[category research solved, AMS 11 68, ref "B2A2" "Dub09", group "rb_collatz_dictionary"]
theorem complexity_ge_of_injective {n₀ : ℕ} (hn₀ : 1 ≤ n₀)
    (hinj : Function.Injective fun n => T_iter n n₀) {t m : ℕ}
    (ht : n₀ < 2 ^ t) (htm : t ≤ m) :
    m - t + 1 ≤ AS.complexity (parityWord n₀) m := by
  have hbdd : ∀ a ∈ Finset.range (m - t + 1), T_iter a n₀ < 2 ^ m := by
    intro a ha
    rw [Finset.mem_range] at ha
    calc T_iter a n₀ ≤ 2 ^ a * n₀ := T_iter_le_two_pow_mul n₀ a
      _ < 2 ^ a * 2 ^ t := mul_lt_mul_of_pos_left ht (pow_pos (by norm_num) a)
      _ = 2 ^ (a + t) := (pow_add 2 a t).symm
      _ ≤ 2 ^ m := Nat.pow_le_pow_right (by norm_num) (by omega)
  have hcard := card_le_complexity_of_injOn hn₀ (Finset.range (m - t + 1)) hbdd hinj.injOn
  simpa [Finset.card_range] using hcard

/-! ## Automaticity ⇔ linear covering numbers -/

/-- **Automatic ⇒ linear covering** ([B2A2] §3.1/§3.2): if the parity word is automatic then the
Collatz orbit visits only `O(m)` residues mod `2^m`.  Cobham's bound
(`AS.complexity_linear_of_automatic`) transported across the dictionary. -/
@[category research solved, AMS 11 68, ref "B2A2" "Cob72" "AS03", group "rb_collatz_dictionary"]
theorem covering_linear_of_automatic {n₀ : ℕ} (hn₀ : 1 ≤ n₀)
    (h : AS.IsAutomatic (parityWord n₀)) :
    ∃ C, ∀ m, 1 ≤ m → (Set.range fun n => (T_iter n n₀ : ZMod (2 ^ m))).ncard ≤ C * m := by
  obtain ⟨C, hC⟩ := AS.complexity_linear_of_automatic h
  refine ⟨C, fun m hm => ?_⟩
  rw [← complexity_eq_ncard_residues hn₀ m]
  exact hC m hm

/-- **The contrapositive** ([B2A2] §3.1, the A.2 interface): a Collatz orbit that visits
superlinearly many residues mod `2^m` has a non-automatic parity word. -/
@[category research solved, AMS 11 68, ref "B2A2" "Cob72" "AS03", group "rb_collatz_dictionary"]
theorem not_automatic_of_covering_superlinear {n₀ : ℕ} (hn₀ : 1 ≤ n₀)
    (h : ∀ C, ∃ m, 1 ≤ m ∧
        C * m < (Set.range fun n => (T_iter n n₀ : ZMod (2 ^ m))).ncard) :
    ¬ AS.IsAutomatic (parityWord n₀) := by
  apply AS.not_automatic_of_complexity_superlinear
  intro C
  obtain ⟨m, hm, hlt⟩ := h C
  exact ⟨m, hm, by rwa [complexity_eq_ncard_residues hn₀ m]⟩

end RB.Collatz
