/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import RB.Rigidity
import CITED.AlloucheShallitBasic
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Finite.Prod
import Mathlib.Algebra.Order.Group.Unbundled.Int
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Cross-scale block kernels (report B1E2a-v2 §7 / §12.7, WP-H)

The block-kernel attack on non-automaticity of the minimal word, formalized to exactly the
boundary drawn in [B1E2a2] §3.7: everything except the missing lemma.

## The program

If `a` is `k`-automatic then for every fixed `m` its **`m`-block kernel** — the decimated
window sequences `n ↦ (a (kⁱn+r), …, a (kⁱn+r+m−1))` for `r < kⁱ` — is finite
(`blockKernel_finite`): every coordinate is a shift, by at most `m`, of an ordinary
`k`-kernel element, and bounded shifts of a finite kernel form a finite set.  Pigeonhole
then gives, **at every single `m`**, two distinct affine index maps `I(n) = kⁱ·n + r`,
`J(n) = kʲ·n + s` whose `m`-block sequences collide (`exists_blockSeq_collision`).

The **missing cross-scale coherence lemma** ([B1E2a2] §7; open research) would strengthen
this to a *single* pair `(I, J)` colliding at **infinitely many** `m`
(`CrossScaleCoherence`).  The obstruction is a compactness failure: countably many candidate
pairs, one collision per level, no pair forced to recur.  Per the house rule the open lemma
is **not** stated as an axiom; it enters only as the hypothesis of the conditional capstone.

## What is proved unconditionally

The minimal word can afford **no** coherent pair, at any base (`not_crossScaleCoherence`):
an `m`-block collision at position `n` is a length-`m` repetition, so window rigidity
(`RB.isRepetition_iff_dvd`) gives `2^m ∣ x_{J(n)} − x_{I(n)}`; infinitely many `m` beat the
size of the orbit values, forcing `x_{I(n)} = x_{J(n)}`; strict monotonicity
(`RB.x_strictMono`) then makes the affine maps collide at every `n`, and `n = 0, 1` collapse
`(kⁱ, r) = (kʲ, s)` — contradiction.

Hence the conditional theorem (WP-H): if the coherence lemma holds for the minimal word,
the word is **not automatic** — which would make non-automaticity (report-dubickas B.1,
[Dub09] p. 246) unconditional.  Until the lemma is proved, non-automaticity remains
available only through the arithmetic lane (`RB.not_automatic_of_K_algebraic_irrational`).
Footprint: std3, no cited axioms.

## Contents

* `RB.blockSeq` (the report's `BlockKernelSeq`), `RB.blockKernel` — decimated window
  sequences and the `m`-block kernel.
* **`RB.blockKernel_finite`** — finite `k`-kernel ⇒ every `m`-block kernel is finite.
* `RB.exists_blockSeq_collision` — the per-`m` pigeonhole collision (the obstruction, made
  precise: a colliding pair exists at every level, but the pair may depend on the level).
* `RB.CrossScaleCoherence` — one pair colliding at infinitely many `m`.
* **`RB.not_crossScaleCoherence`** — the minimal word has no coherent pair (unconditional).
* **`RB.not_automatic_of_crossScaleCoherence`** — WP-H, the conditional capstone (the
  report's `notAutomatic_of_crossScaleCoherence`).

## References

* [B1E2a2] `plans/report-B1E2a-v2.html` (2026-08-06): §3.7, §7 WP-H — the audit of the
  round-2 revision proposal `old-plans/report-B1E2a-v2.md`, whose §7/§12.7 this implements.
* [AS03] Allouche, Jean-Paul, and Jeffrey Outlaw Shallit. *Automatic Sequences: Theory,
  Applications, Generalizations.* Cambridge University Press, 2003.  (Kernel
  characterization: Thm 6.6.2.)
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J.
  **51** (2009), 243–252.  (p. 246: full complexity conjectured, so in particular the word
  is expected not to be automatic.)
-/

namespace RB

/-- The **decimated window sequence** (the report's `BlockKernelSeq`): position `n` carries
the length-`m` window of `a` starting at `kⁱ·n + r`.  For `r < kⁱ` these are the members of
the `m`-block kernel `RB.blockKernel`. -/
@[category API, AMS 11 68, ref "B1E2a2", group "rb_cross_scale"]
def blockSeq {α : Type*} (k m i r : ℕ) (a : ℕ → α) : ℕ → Fin m → α :=
  fun n t => a (k ^ i * n + r + (t : ℕ))

/-- The **`m`-block kernel** of `a`: all decimated window sequences `blockSeq k m i r a`
with `r < kⁱ`.  At `m = 1` this is the `k`-kernel `AS.kKernel'` up to the `Fin 1` wrapper. -/
@[category API, AMS 11 68, ref "B1E2a2", group "rb_cross_scale"]
def blockKernel {α : Type*} (k m : ℕ) (a : ℕ → α) : Set (ℕ → Fin m → α) :=
  {s | ∃ i r, r < k ^ i ∧ s = blockSeq k m i r a}

/-- **Finite block kernels** ([B1E2a2] §7): a finite `k`-kernel forces every `m`-block
kernel to be finite.  Coordinate `t` of `blockSeq k m i r a` is the ordinary kernel element
at offset `(r+t) mod kⁱ`, shifted by `(r+t)/kⁱ ≤ m` — so the block kernel embeds into
(kernel × bounded shifts)^`m`, a finite set. -/
@[category research solved, AMS 11 68, ref "AS03" "B1E2a2", group "rb_cross_scale"]
theorem blockKernel_finite {α : Type*} {k : ℕ} {a : ℕ → α}
    (hker : (AS.kKernel' k a).Finite) (m : ℕ) : (blockKernel k m a).Finite := by
  have hS : {f : Fin m → (ℕ → α) × ℕ |
      ∀ t, f t ∈ (AS.kKernel' k a) ×ˢ {q | q ≤ m}}.Finite :=
    Set.Finite.pi' fun _ => hker.prod (Set.finite_le_nat m)
  refine (hS.image fun f => fun n t => (f t).1 (n + (f t).2)).subset ?_
  rintro _ ⟨i, r, hr, rfl⟩
  have hk : 0 < k ^ i := lt_of_le_of_lt (Nat.zero_le r) hr
  refine ⟨fun t => ⟨fun n => a (k ^ i * n + (r + (t : ℕ)) % k ^ i), (r + (t : ℕ)) / k ^ i⟩,
    fun t => ⟨⟨i, (r + (t : ℕ)) % k ^ i, Nat.mod_lt _ hk, rfl⟩, ?_⟩, ?_⟩
  · -- the shift `(r + t) / kⁱ` is at most `m`
    have hlt : r + (t : ℕ) < k ^ i * (m + 1) := by
      calc r + (t : ℕ) < k ^ i + m := add_lt_add hr t.isLt
        _ ≤ k ^ i + k ^ i * m := Nat.add_le_add_left (Nat.le_mul_of_pos_left m hk) _
        _ = k ^ i * (m + 1) := by ring
    exact Nat.lt_succ_iff.mp (Nat.div_lt_of_lt_mul hlt)
  · funext n t
    show a (k ^ i * (n + (r + (t : ℕ)) / k ^ i) + (r + (t : ℕ)) % k ^ i)
        = a (k ^ i * n + r + (t : ℕ))
    have hdm := Nat.div_add_mod (r + (t : ℕ)) (k ^ i)
    rw [Nat.mul_add, Nat.add_assoc, hdm, ← Nat.add_assoc]

/-- **Per-level collision** ([B1E2a2] §7 — the obstruction, made precise): with a finite
`k`-kernel, *every* window length `m` admits two distinct affine index maps with identical
decimated window sequences.  The pair comes from pigeonhole (infinitely many scales, finite
block kernel) and may change with `m`; upgrading some *single* pair to infinitely many `m`
is exactly `CrossScaleCoherence`, the missing lemma. -/
@[category research solved, AMS 11 68, ref "B1E2a2", group "rb_cross_scale"]
theorem exists_blockSeq_collision {α : Type*} {k : ℕ} (hk : 2 ≤ k) {a : ℕ → α}
    (hker : (AS.kKernel' k a).Finite) (m : ℕ) :
    ∃ i r j s, r < k ^ i ∧ s < k ^ j ∧ (k ^ i, r) ≠ (k ^ j, s) ∧
      blockSeq k m i r a = blockSeq k m j s a := by
  have hmaps : Set.MapsTo (fun i => blockSeq k m i 0 a) Set.univ (blockKernel k m a) :=
    fun i _ => ⟨i, 0, pow_pos (by omega) i, rfl⟩
  obtain ⟨i, -, j, -, hij, heq⟩ :=
    (Set.infinite_univ (α := ℕ)).exists_ne_map_eq_of_mapsTo hmaps (blockKernel_finite hker m)
  refine ⟨i, 0, j, 0, pow_pos (by omega) i, pow_pos (by omega) j, fun hp => ?_, heq⟩
  exact hij (Nat.pow_right_injective hk (congrArg Prod.fst hp))

/-- **Cross-scale coherence** ([B1E2a2] §7): a single pair of *distinct* affine index maps
`I(n) = kⁱ·n + r`, `J(n) = kʲ·n + s` whose decimated window sequences agree at **infinitely
many** window lengths `m`.  The missing lemma — open research, deliberately not axiomatized —
asserts that every `k`-automatic word admits such a pair; `exists_blockSeq_collision` gives
only one level at a time. -/
@[category API, AMS 11 68, ref "B1E2a2", group "rb_cross_scale"]
def CrossScaleCoherence {α : Type*} (k : ℕ) (a : ℕ → α) : Prop :=
  ∃ i r j s, r < k ^ i ∧ s < k ^ j ∧ (k ^ i, r) ≠ (k ^ j, s) ∧
    {m | blockSeq k m i r a = blockSeq k m j s a}.Infinite

/-- **The minimal word admits no coherent pair, at any base** ([B1E2a2] §3.7,
unconditional).  A coherent collision at position `n` and level `m` is a length-`m`
repetition, so window rigidity gives `2^m ∣ x_{J(n)} − x_{I(n)}`; taking `m` beyond the
size of the orbit values forces `x_{I(n)} = x_{J(n)}`, strict monotonicity equates the
indices at every `n`, and `n = 0, 1` collapse the two affine maps into one. -/
@[category research solved, AMS 11 68, ref "B1E2a2", group "rb_cross_scale"]
theorem not_crossScaleCoherence {x₀ : ℕ} (hx₀ : 0 < x₀) (k : ℕ) :
    ¬ CrossScaleCoherence k (wmin x₀) := by
  rintro ⟨i, r, j, s, hr, hs, hne, hinf⟩
  have key : ∀ n, k ^ j * n + s = k ^ i * n + r := by
    intro n
    obtain ⟨m, hmem, hlt⟩ :
        ∃ m, blockSeq k m i r (wmin x₀) = blockSeq k m j s (wmin x₀) ∧
          x x₀ (k ^ i * n + r) + x x₀ (k ^ j * n + s) < m := by
      by_contra hcon
      push Not at hcon
      exact hinf ((Set.finite_le_nat (x x₀ (k ^ i * n + r) + x x₀ (k ^ j * n + s))).subset
        fun m hm => hcon m hm)
    have hrep : IsRepetition x₀ (k ^ i * n + r) (k ^ j * n + s) m := fun u hu =>
      congrFun (congrFun hmem n) ⟨u, hu⟩
    have hdvd := isRepetition_iff_dvd.mp hrep
    have hpow : x x₀ (k ^ i * n + r) + x x₀ (k ^ j * n + s) < 2 ^ m :=
      lt_trans hlt (Nat.lt_pow_self one_lt_two)
    have habs : |(x x₀ (k ^ j * n + s) : ℤ) - x x₀ (k ^ i * n + r)| < (2 : ℤ) ^ m := by
      have h := Int.abs_sub_lt_of_lt_lt
        (lt_of_le_of_lt (Nat.le_add_right _ _) hpow)
        (lt_of_le_of_lt (Nat.le_add_left _ _) hpow)
      exact_mod_cast h
    have hzero := Int.eq_zero_of_abs_lt_dvd hdvd habs
    exact (x_strictMono hx₀).injective (by exact_mod_cast sub_eq_zero.mp hzero)
  have h0 := key 0
  have h1 := key 1
  simp only [Nat.mul_zero, Nat.zero_add, Nat.mul_one] at h0 h1
  refine hne ?_
  have h2 : k ^ i = k ^ j := by
    rw [h0] at h1
    exact (Nat.add_right_cancel h1).symm
  rw [h2, ← h0]

/-- **WP-H, the conditional capstone** (the report's `notAutomatic_of_crossScaleCoherence`):
if the missing cross-scale coherence lemma holds for the minimal word — every base `k ≥ 2`
at which its kernel is finite admits a coherent pair — then the minimal word is **not
automatic**.  The hypothesis `hcsc` is exactly what [B1E2a2] §7's open lemma would supply;
proving it would make non-automaticity (report-dubickas B.1) unconditional.  Consumes only
window rigidity and strict monotonicity: std3, no cited axioms. -/
@[category research solved, AMS 11 68, ref "B1E2a2", group "rb_cross_scale"]
theorem not_automatic_of_crossScaleCoherence {x₀ : ℕ} (hx₀ : 0 < x₀)
    (hcsc : ∀ k, 2 ≤ k → (AS.kKernel k (wmin x₀)).Finite →
      CrossScaleCoherence k (wmin x₀)) :
    ¬ AS.IsAutomatic (wmin x₀) := by
  rintro ⟨k, hk, hfin⟩
  exact not_crossScaleCoherence hx₀ k (hcsc k hk hfin)

end RB
