/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import RB.AlgebraicBase
import RB.EventuallyPeriodic
import Mathlib.Data.Int.GCD
import Mathlib.RingTheory.Coprime.Lemmas
import Mathlib.Tactic.LinearCombination
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Ceiling orbits of an arbitrary rational base `p/q`: rigidity, aperiodicity, non-holonomy
([B1E2b] WP4)

Fix coprime integers `p > q ≥ 2` and `x₀ ≥ 1`, and iterate the ceiling map of the rational base
`β = p/q`:

  `xₙ₊₁ = ⌈p·xₙ/q⌉`,   `wₙ := q·xₙ₊₁ − p·xₙ ∈ {0,…,q−1}`.

At `(p,q) = (3,2)` this is `RB.x` / `RB.wmin` (`RB.Gen.x_eq`, `RB.Gen.wmin_eq`), the object of
`RB.Basic` and `RB.Rigidity`.  **Those files are deliberately not generalised in place** — every
existing consumer (`RB.Regularity` at the rational point `2/3`, the `2`-adic kernel files, the
companion paper) reads base-specific names — so the general system lives here, in its own
namespace `RB.Gen`, and the `(3,2)` instance is proved *equal* to the old one rather than
substituted for it.

## What is proved

Everything of `RB.Basic` + `RB.Rigidity` + the flagship of `RB.EventuallyPeriodic`, for every
admissible `(p,q)`, with `2 ⇝ q` and `3 ⇝ p`:

* `q_mul_x_succ` — the selection rule `q·xₙ₊₁ = p·xₙ + wₙ`, and `word_lt` (`wₙ < q`);
  `x_succ_eq_ceil` identifies the `ℕ`-division definition with the real ceiling (the one place
  where the `ℕ`-arithmetic has to be matched against the analytic description).
* `circuit_sum` — `q^k·x_{a+k} = p^k·x_a + W(a,k)`;
* `q_pow_mul_le` — the growth ceiling `q^n·((p−q)xₙ + q) ≤ p^n·((p−q)x₀ + q)`.  **This is where
  the `(3,2)` proof does not transfer verbatim**: `RB.two_pow_mul_x_add_one_le` uses `xₙ + 1`,
  which is submultiplicative only because `wₙ + q ≤ p` holds at `(3,2)`; in general the right
  affine shift is `xₙ + q/(p−q)`, cleared of denominators.
* **`q_pow_dvd_of_repetition`** and **`window_eq_of_dvd`** — window rigidity: length-`m` factors
  of `w` are exactly the residues `xₙ mod q^m` (`isRepetition_iff_dvd`), with the `m = 1` case
  `word_determines_residue` spelled out.  The descent needs only `q > 0`; coprimality of `p` and
  `q` is needed only for the converse, and is used through `IsCoprime (q^k) (p^k)` — **not**
  primality of `q`: `p/q = 5/4` is a legitimate base
  (`not_isPRecursive_word_five_fourths`).
* `repetition_pow_lt` — the ceiling `q^{k+c} < p^c((p−q)x₀ + q)`, stated log-free; the sharp
  slope `k ≲ c·log(p/q)/log q` is not needed and is not certified here.
* **`not_eventually_periodic`** — [AFS08] Prop 26 for every `p/q`, in-house and axiom-free.
* **`not_isPRecursive_word`** — **Theorem B, rational half**: the word of *every* base `p/q` with
  `p > q ≥ 2` coprime is not `P`-recursive.  `std3`, no cited axiom.
* `not_isAlgebraic_wordSeries` — the same statement weakened through [Sta80].

## Relation to `RB.AlgebraicBase`

`RB.Alg.not_isPRecursive_word_of_not_mem_U` proves the same conclusion for every algebraic
`β ∉ Bertin.U`, and every base admissible here qualifies: `isMinimalIntPoly_rational` supplies its
minimal-polynomial hypothesis and `not_mem_Bertin_U` its exemption hypothesis (`p/q` with `q ∤ p`
is not even an algebraic integer).  But that route buys its aperiodicity from the cited axiom
`Dubickas.periodic_imp_mem_U` ([Dub09] Thm 2).  The point of this file is that on the rational
locus the axiom is *unnecessary*: `q`-adic descent proves aperiodicity outright.  The two are
literally about the same sequence — `x_eq_pisotOrbit` identifies `RB.Gen.x p q x₀` with
`RB.pisotOrbit (p/q) x₀` and `word_eq_alg` identifies the two words — so this is a genuine axiom
elimination on a positive-dimensional family, not a parallel construction.  At `(p,q) = (3,2)`
the chain closes on the corpus's own objects: `pisotOrbit_three_halves_eq` and
`alg_word_eq_wmin` identify `RB.Alg.not_isPRecursive_word_three_halves` with the flagship
`RB.not_isPRecursive_wmin`, which is what `RB.Alg` deferred to WP4.

## References

* [AFS08] Akiyama, Frougny, Sakarovitch. *Powers of rationals modulo 1 and rational base number
  systems.* Israel J. Math. **168** (2008), 53–91.  (Prop 26: no element of `W_{p/q}` is
  eventually periodic except `0^ω`.)
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J. **51**
  (2009), 243–252.  (Thm 2 and the `U_{β,γ}` remark, p. 244.)
* [Sta80] R. P. Stanley. *Differentiably finite power series.* European J. Combin. **1** (1980),
  175–188.
* [B1E2b] `plans/plan-B1E2b.html`, WP4.
-/

namespace RB.Gen

open Stanley Polynomial

/-! ## The orbit and its word -/

/-- The ceiling orbit of the rational base `p/q`: `xₙ₊₁ = ⌈p·xₙ/q⌉`, written so that the
numerator is *visibly* divisible by `q` (`x_succ_eq_ceil` checks it is the ceiling). -/
@[category API, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
def x (p q x₀ : ℕ) : ℕ → ℕ
  | 0 => x₀
  | n + 1 => (p * x p q x₀ n + (q - p * x p q x₀ n % q) % q) / q

/-- The **word** of the base `p/q`: `wₙ = q·xₙ₊₁ − p·xₙ`, defined as the residue
`(−p·xₙ) mod q` so that `ℕ`-subtraction never appears ([B1E2b] risk R8). -/
@[category API, AMS 11 68, ref "AFS08" "Dub09", group "rb_general_rational_base"]
def word (p q x₀ n : ℕ) : ℕ := (q - p * x p q x₀ n % q) % q

@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base", simp]
lemma x_zero (p q x₀ : ℕ) : x p q x₀ 0 = x₀ := rfl

@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
lemma x_succ (p q x₀ n : ℕ) : x p q x₀ (n + 1) = (p * x p q x₀ n + word p q x₀ n) / q := rfl

@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
lemma word_def (p q x₀ n : ℕ) : word p q x₀ n = (q - p * x p q x₀ n % q) % q := rfl

/-- The alphabet is `{0,…,q−1}`. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem word_lt {q : ℕ} (hq : 0 < q) (p x₀ n : ℕ) : word p q x₀ n < q := Nat.mod_lt _ hq

/-- `c + ((−c) mod q)` is the next multiple of `q` at or above `c`. -/
private lemma dvd_add_negMod {q : ℕ} (hq : 0 < q) (c : ℕ) : q ∣ c + (q - c % q) % q := by
  have hr : c % q < q := Nat.mod_lt _ hq
  by_cases h : c % q = 0
  · simpa [h] using Nat.dvd_of_mod_eq_zero h
  · have h1 : (q - c % q) % q = q - c % q := Nat.mod_eq_of_lt (by omega)
    rw [h1]
    refine ⟨c / q + 1, ?_⟩
    have hdm := Nat.div_add_mod c q
    have hexp : q * (c / q + 1) = q * (c / q) + q := by ring
    omega

/-- **The selection rule** `q·xₙ₊₁ = p·xₙ + wₙ` — the general-base twin of
`RB.two_mul_x_succ`, and the only property of the definition that the rest of the file uses. -/
@[category research solved, AMS 11 68, ref "AFS08" "Dub09", group "rb_general_rational_base"]
theorem q_mul_x_succ {q : ℕ} (hq : 0 < q) (p x₀ n : ℕ) :
    q * x p q x₀ (n + 1) = p * x p q x₀ n + word p q x₀ n := by
  rw [x_succ]
  exact Nat.mul_div_cancel' (dvd_add_negMod hq _)

/-- The `ℕ`-division definition really is the ceiling `⌈p·xₙ/q⌉` ([B1E2b] risk R8: prove the
`ℕ`-form/ceiling-form equality once, then never divide again). -/
@[category research solved, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem x_succ_eq_ceil {q : ℕ} (hq : 0 < q) (p x₀ n : ℕ) :
    (x p q x₀ (n + 1) : ℤ) = ⌈(p : ℝ) / q * x p q x₀ n⌉ := by
  have hqR : (0 : ℝ) < q := by exact_mod_cast hq
  have hsel : (q : ℝ) * (x p q x₀ (n + 1) : ℝ)
      = (p : ℝ) * x p q x₀ n + (word p q x₀ n : ℝ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℝ)) (q_mul_x_succ hq p x₀ n)
  have hw0 : (0 : ℝ) ≤ (word p q x₀ n : ℝ) := by positivity
  have hwq : (word p q x₀ n : ℝ) < q := by exact_mod_cast word_lt hq p x₀ n
  symm
  rw [Int.ceil_eq_iff]
  refine ⟨?_, ?_⟩
  · rw [div_mul_eq_mul_div, lt_div_iff₀ hqR]
    push_cast
    nlinarith
  · rw [div_mul_eq_mul_div, div_le_iff₀ hqR]
    push_cast
    nlinarith

/-- The orbit is shift-invariant: running `n+j` steps from `x₀` is running `j` steps from `xₙ`. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem x_add (p q x₀ n j : ℕ) : x p q x₀ (n + j) = x p q (x p q x₀ n) j := by
  induction j with
  | zero => rfl
  | succ j ih =>
    have e : n + (j + 1) = (n + j) + 1 := by omega
    rw [e, x_succ, x_succ, word_def, word_def, ih]

/-- The word inherits shift-invariance from the orbit. -/
@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem word_add (p q x₀ n j : ℕ) : word p q x₀ (n + j) = word p q (x p q x₀ n) j := by
  rw [word_def, word_def, x_add]

/-! ## The circuit sum -/

/-- `W(a,k) = Σ_{i<k} p^{k−1−i}·q^i·w_{a+i}` — the general-base `RB.W`. -/
@[category API, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
def W (p q x₀ a k : ℕ) : ℕ := ∑ i ∈ Finset.range k, p ^ (k - 1 - i) * q ^ i * word p q x₀ (a + i)

@[category API, AMS 11 68, ref "B1E2b", group "rb_general_rational_base", simp]
lemma W_zero (p q x₀ a : ℕ) : W p q x₀ a 0 = 0 := by simp [W]

@[category API, AMS 11 68, ref "B1E2b", group "rb_general_rational_base"]
theorem W_succ (p q x₀ a k : ℕ) :
    W p q x₀ a (k + 1) = p * W p q x₀ a k + q ^ k * word p q x₀ (a + k) := by
  unfold W
  rw [Finset.sum_range_succ, Finset.mul_sum]
  simp only [Nat.add_sub_cancel, Nat.sub_self, pow_zero, one_mul]
  congr 1
  refine Finset.sum_congr rfl fun i hi => ?_
  have hik : i < k := Finset.mem_range.mp hi
  have hki : k - i = (k - 1 - i) + 1 := by omega
  rw [hki, pow_succ]
  ring

/-- **The exact identity** `q^k·x_{a+k} = p^k·x_a + W(a,k)`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem circuit_sum {q : ℕ} (hq : 0 < q) (p x₀ a k : ℕ) :
    q ^ k * x p q x₀ (a + k) = p ^ k * x p q x₀ a + W p q x₀ a k := by
  induction k with
  | zero => simp
  | succ k ih =>
    have h := q_mul_x_succ hq p x₀ (a + k)
    have e : a + (k + 1) = (a + k) + 1 := by omega
    calc q ^ (k + 1) * x p q x₀ (a + (k + 1))
        = q ^ k * (q * x p q x₀ ((a + k) + 1)) := by rw [e]; ring
      _ = q ^ k * (p * x p q x₀ (a + k) + word p q x₀ (a + k)) := by rw [h]
      _ = p * (q ^ k * x p q x₀ (a + k)) + q ^ k * word p q x₀ (a + k) := by ring
      _ = p * (p ^ k * x p q x₀ a + W p q x₀ a k) + q ^ k * word p q x₀ (a + k) := by rw [ih]
      _ = p ^ (k + 1) * x p q x₀ a + W p q x₀ a (k + 1) := by rw [W_succ]; ring

@[category research solved, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem circuit_sum_zero {q : ℕ} (hq : 0 < q) (p x₀ n : ℕ) :
    q ^ n * x p q x₀ n = p ^ n * x₀ + W p q x₀ 0 n := by
  simpa using circuit_sum hq p x₀ 0 n

/-! ## Growth and monotonicity -/

/-- Lower growth: `p^n·x₀ ≤ q^n·xₙ` (the word only ever pushes the orbit up). -/
@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem p_pow_mul_le {q : ℕ} (hq : 0 < q) (p x₀ n : ℕ) : p ^ n * x₀ ≤ q ^ n * x p q x₀ n := by
  rw [circuit_sum_zero hq]; exact Nat.le_add_right _ _

/-- Upper growth, cleared of denominators: `q^n·((p−q)xₙ + q) ≤ p^n·((p−q)x₀ + q)`, i.e.
`xₙ + q/(p−q) ≤ (p/q)^n (x₀ + q/(p−q))`.

The affine shift is forced: `⌈βt⌉ ≤ βt + 1`, so `t ↦ t + c` is submultiplicative under the
ceiling map exactly when `c ≥ 1/(β−1) = q/(p−q)`.  At `(p,q) = (3,2)` that constant is `2`, but
`RB.two_pow_mul_x_add_one_le` gets away with the sharper shift `1` because there `wₙ + q ≤ p`;
for `p/q = 5/4` that fails and the shift `1` bound is false. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem q_pow_mul_le {p q : ℕ} (hq : 0 < q) (hqp : q ≤ p) (x₀ n : ℕ) :
    q ^ n * ((p - q) * x p q x₀ n + q) ≤ p ^ n * ((p - q) * x₀ + q) := by
  induction n with
  | zero => simp
  | succ n ih =>
    have hstep : q * ((p - q) * x p q x₀ (n + 1) + q) ≤ p * ((p - q) * x p q x₀ n + q) := by
      have hw := word_lt hq p x₀ n
      have hqx := q_mul_x_succ hq p x₀ n
      have h1 : (p - q) * word p q x₀ n ≤ (p - q) * q := Nat.mul_le_mul_left _ (le_of_lt hw)
      have h2 : (p - q) * q + q * q = p * q := by
        have hd : p - q + q = p := by omega
        calc (p - q) * q + q * q = ((p - q) + q) * q := by ring
          _ = p * q := by rw [hd]
      calc q * ((p - q) * x p q x₀ (n + 1) + q)
          = (p - q) * (q * x p q x₀ (n + 1)) + q * q := by ring
        _ = (p - q) * (p * x p q x₀ n + word p q x₀ n) + q * q := by rw [hqx]
        _ = (p - q) * p * x p q x₀ n + ((p - q) * word p q x₀ n + q * q) := by ring
        _ ≤ (p - q) * p * x p q x₀ n + ((p - q) * q + q * q) :=
            Nat.add_le_add_left (Nat.add_le_add_right h1 _) _
        _ = (p - q) * p * x p q x₀ n + p * q := by rw [h2]
        _ = p * ((p - q) * x p q x₀ n + q) := by ring
    calc q ^ (n + 1) * ((p - q) * x p q x₀ (n + 1) + q)
        = q ^ n * (q * ((p - q) * x p q x₀ (n + 1) + q)) := by ring
      _ ≤ q ^ n * (p * ((p - q) * x p q x₀ n + q)) := Nat.mul_le_mul_left _ hstep
      _ = p * (q ^ n * ((p - q) * x p q x₀ n + q)) := by ring
      _ ≤ p * (p ^ n * ((p - q) * x₀ + q)) := Nat.mul_le_mul_left _ ih
      _ = p ^ (n + 1) * ((p - q) * x₀ + q) := by ring

@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem x_pos {p q x₀ : ℕ} (hq : 0 < q) (hp : 0 < p) (hx₀ : 0 < x₀) (n : ℕ) : 0 < x p q x₀ n := by
  induction n with
  | zero => simpa using hx₀
  | succ n ih =>
    have h := q_mul_x_succ hq p x₀ n
    rcases Nat.eq_zero_or_pos (x p q x₀ (n + 1)) with h0 | h0
    · rw [h0, Nat.mul_zero] at h
      have := Nat.mul_pos hp ih
      omega
    · exact h0

@[category API, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem x_lt_x_succ {p q x₀ : ℕ} (hq : 0 < q) (hqp : q < p) (hx₀ : 0 < x₀) (n : ℕ) :
    x p q x₀ n < x p q x₀ (n + 1) := by
  have h := q_mul_x_succ hq p x₀ n
  have hpos := x_pos hq (lt_trans hq hqp) hx₀ n
  have hlt : q * x p q x₀ n < p * x p q x₀ n := (Nat.mul_lt_mul_right hpos).mpr hqp
  have hgoal : q * x p q x₀ n < q * x p q x₀ (n + 1) := by rw [h]; omega
  exact Nat.lt_of_mul_lt_mul_left hgoal

/-- Strict monotonicity. -/
@[category API, AMS 11 68, ref "Dub09", group "rb_general_rational_base"]
theorem x_strictMono {p q x₀ : ℕ} (hq : 0 < q) (hqp : q < p) (hx₀ : 0 < x₀) :
    StrictMono (x p q x₀) :=
  strictMono_nat_of_lt_succ (x_lt_x_succ hq hqp hx₀)

/-! ## `q`-adic rigidity -/

/-- A length-`k` factor of the word occurring at positions `a` and `c`. -/
@[category API, AMS 11 68, ref "B1E2b", group "rb_general_rational_base"]
def IsRepetition (p q x₀ a c k : ℕ) : Prop := ∀ i < k, word p q x₀ (a + i) = word p q x₀ (c + i)

@[category API, AMS 11 68, ref "B1E2b", group "rb_general_rational_base"]
lemma W_eq_of_repetition {p q x₀ a c k : ℕ} (h : IsRepetition p q x₀ a c k) :
    W p q x₀ a k = W p q x₀ c k :=
  Finset.sum_congr rfl fun i hi => by rw [h i (Finset.mem_range.mp hi)]

/-- **Lemma R, integer form**: a repetition at `a`, `c` of length `k` forces
`p^k(x_c − x_a) = q^k(x_{c+k} − x_{a+k})`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem lemmaR_int {p q x₀ a c k : ℕ} (hq : 0 < q) (h : IsRepetition p q x₀ a c k) :
    (p : ℤ) ^ k * ((x p q x₀ c : ℤ) - x p q x₀ a)
      = (q : ℤ) ^ k * ((x p q x₀ (c + k) : ℤ) - x p q x₀ (a + k)) := by
  have ha : (q : ℤ) ^ k * (x p q x₀ (a + k) : ℤ)
      = (p : ℤ) ^ k * (x p q x₀ a : ℤ) + (W p q x₀ a k : ℤ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℤ)) (circuit_sum hq p x₀ a k)
  have hc : (q : ℤ) ^ k * (x p q x₀ (c + k) : ℤ)
      = (p : ℤ) ^ k * (x p q x₀ c : ℤ) + (W p q x₀ c k : ℤ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℤ)) (circuit_sum hq p x₀ c k)
  have hw : (W p q x₀ a k : ℤ) = (W p q x₀ c k : ℤ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℤ)) (W_eq_of_repetition h)
  linarith [ha, hc, hw]

/-- **Rigidity, `⟹`**: equal length-`k` windows force `q^k ∣ x_c − x_a`.

Coprimality of `p` and `q` enters here and only here — and as `IsCoprime`, not primality: `q` may
be composite (`p/q = 5/4`). -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem q_pow_dvd_of_repetition {p q x₀ a c k : ℕ} (hq : 0 < q) (hcop : Nat.Coprime p q)
    (h : IsRepetition p q x₀ a c k) : (q : ℤ) ^ k ∣ (x p q x₀ c : ℤ) - x p q x₀ a := by
  have hcopZ : IsCoprime ((q : ℤ) ^ k) ((p : ℤ) ^ k) :=
    IsCoprime.pow (Nat.isCoprime_iff_coprime.mpr hcop.symm)
  have hdvd : (q : ℤ) ^ k ∣ (p : ℤ) ^ k * ((x p q x₀ c : ℤ) - x p q x₀ a) := by
    rw [lemmaR_int hq h]; exact Dvd.intro _ rfl
  exact hcopZ.dvd_of_dvd_mul_left hdvd

/-- One step of agreement mod `q` fixes one letter: `wₙ` is a function of `xₙ mod q`. -/
@[category API, AMS 11 68, ref "B1E2b", group "rb_general_rational_base"]
lemma word_eq_of_dvd {p q x₀ a b : ℕ} (h : (q : ℤ) ∣ (x p q x₀ a : ℤ) - x p q x₀ b) :
    word p q x₀ a = word p q x₀ b := by
  have h2 : x p q x₀ b ≡ x p q x₀ a [MOD q] := (Nat.modEq_iff_dvd (n := q)).mpr (by simpa using h)
  have h3 : p * x p q x₀ b ≡ p * x p q x₀ a [MOD q] := h2.mul_left p
  simp only [word_def]
  rw [Nat.ModEq] at h3
  rw [h3]

/-- **The `q`-adic descent**: `q^m ∣ x_a − x_b` decays to `q^{m−i} ∣ x_{a+i} − x_{b+i}`.

Each step of `q·xₙ₊₁ = p·xₙ + wₙ` divides the agreement by exactly one power of `q`, and the
letters agree as long as one power survives.  Note that *no* coprimality is needed: the identity
`q·(Δ_{i+1}) = p·(Δ_i)` cancels one `q` on the left regardless of `p`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem dvd_sub_descend {p q x₀ a b m : ℕ} (hq : 0 < q)
    (h : (q : ℤ) ^ m ∣ (x p q x₀ a : ℤ) - x p q x₀ b) :
    ∀ i ≤ m, (q : ℤ) ^ (m - i) ∣ (x p q x₀ (a + i) : ℤ) - x p q x₀ (b + i) := by
  intro i
  induction i with
  | zero => intro _; simpa using h
  | succ i ih =>
    intro hi
    have hi' : i ≤ m := by omega
    have hstep := ih hi'
    have hone : (q : ℤ) ∣ (x p q x₀ (a + i) : ℤ) - x p q x₀ (b + i) :=
      dvd_trans (dvd_pow_self _ (by omega : m - i ≠ 0)) hstep
    have hw : word p q x₀ (a + i) = word p q x₀ (b + i) := word_eq_of_dvd hone
    have ha : (q : ℤ) * (x p q x₀ (a + i + 1) : ℤ)
        = (p : ℤ) * x p q x₀ (a + i) + (word p q x₀ (a + i) : ℤ) := by
      exact_mod_cast congrArg (Nat.cast (R := ℤ)) (q_mul_x_succ hq p x₀ (a + i))
    have hb : (q : ℤ) * (x p q x₀ (b + i + 1) : ℤ)
        = (p : ℤ) * x p q x₀ (b + i) + (word p q x₀ (b + i) : ℤ) := by
      exact_mod_cast congrArg (Nat.cast (R := ℤ)) (q_mul_x_succ hq p x₀ (b + i))
    have key : (q : ℤ) * ((x p q x₀ (a + i + 1) : ℤ) - x p q x₀ (b + i + 1))
        = (p : ℤ) * ((x p q x₀ (a + i) : ℤ) - x p q x₀ (b + i)) := by
      rw [hw] at ha; linarith
    have hdvd2 : (q : ℤ) ^ (m - i)
        ∣ (q : ℤ) * ((x p q x₀ (a + i + 1) : ℤ) - x p q x₀ (b + i + 1)) := by
      rw [key]; exact Dvd.dvd.mul_left hstep _
    have hsplit : (q : ℤ) ^ (m - i) = q * q ^ (m - i - 1) := by
      rw [← pow_succ']; congr 1; omega
    rw [hsplit] at hdvd2
    have hqne : (q : ℤ) ≠ 0 := Nat.cast_ne_zero.mpr hq.ne'
    have hres := (mul_dvd_mul_iff_left hqne).mp hdvd2
    have he : m - i - 1 = m - (i + 1) := by omega
    rw [he] at hres
    have hab : a + (i + 1) = a + i + 1 := by omega
    have hbb : b + (i + 1) = b + i + 1 := by omega
    rw [hab, hbb]
    exact hres

/-- **Rigidity, `⟸`**: `q^m ∣ x_a − x_b` forces the length-`m` windows at `a` and `b` to agree. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem window_eq_of_dvd {p q x₀ a b m : ℕ} (hq : 0 < q)
    (h : (q : ℤ) ^ m ∣ (x p q x₀ a : ℤ) - x p q x₀ b) : IsRepetition p q x₀ a b m := by
  intro i hi
  have hstep := dvd_sub_descend hq h i (le_of_lt hi)
  exact word_eq_of_dvd (dvd_trans (dvd_pow_self _ (by omega : m - i ≠ 0)) hstep)

/-- **Window rigidity**: length-`m` windows of the word are exactly the residues `x mod q^m`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem isRepetition_iff_dvd {p q x₀ a b m : ℕ} (hq : 0 < q) (hcop : Nat.Coprime p q) :
    IsRepetition p q x₀ a b m ↔ (q : ℤ) ^ m ∣ (x p q x₀ b : ℤ) - x p q x₀ a := by
  refine ⟨q_pow_dvd_of_repetition hq hcop, fun h => window_eq_of_dvd hq ?_⟩
  have hneg := (dvd_neg (α := ℤ)).mpr h
  rwa [neg_sub] at hneg

/-- The letter is the negative residue: `wₙ ≡ −p·xₙ (mod q)`. -/
@[category API, AMS 11 68, ref "AFS08" "Dub09", group "rb_general_rational_base"]
theorem q_dvd_add_word {q : ℕ} (hq : 0 < q) (p x₀ n : ℕ) :
    q ∣ p * x p q x₀ n + word p q x₀ n :=
  dvd_add_negMod hq _

/-- **A single letter sees exactly the residue `xₙ mod q`** — the `m = 1` case of window
rigidity, and the reason the alphabet has `q` letters and not fewer: `wₙ ≡ −p·xₙ (mod q)` and
`gcd(p,q) = 1` make `n ↦ wₙ` and `n ↦ xₙ mod q` interchangeable. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem word_determines_residue {p q x₀ a b : ℕ} (hq : 0 < q) (hcop : Nat.Coprime p q) :
    word p q x₀ a = word p q x₀ b ↔ (q : ℤ) ∣ (x p q x₀ b : ℤ) - x p q x₀ a := by
  constructor
  · intro h
    have hrep : IsRepetition p q x₀ a b 1 := by
      intro i hi
      have : i = 0 := by omega
      simpa [this] using h
    simpa using (isRepetition_iff_dvd (m := 1) hq hcop).mp hrep
  · intro h
    refine (word_eq_of_dvd (a := a) (b := b) ?_)
    have hneg := (dvd_neg (α := ℤ)).mpr h
    rwa [neg_sub] at hneg

/-! ## The repetition ceiling and aperiodicity -/

/-- **The ceiling**: a repeated length-`k` window at `a < c` obeys `q^{k+c} < p^c((p−q)x₀ + q)`.
Rigidity forces `q^k ≤ x_c − x_a`; growth caps `x_c` by `(p/q)^c`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem repetition_pow_lt {p q x₀ a c k : ℕ} (hq : 0 < q) (hqp : q < p) (hcop : Nat.Coprime p q)
    (hx₀ : 0 < x₀) (hac : a < c) (h : IsRepetition p q x₀ a c k) :
    q ^ (k + c) < p ^ c * ((p - q) * x₀ + q) := by
  have hlt : x p q x₀ a < x p q x₀ c := x_strictMono hq hqp hx₀ hac
  have hdvd := q_pow_dvd_of_repetition hq hcop h
  have hpos : (0 : ℤ) < (x p q x₀ c : ℤ) - x p q x₀ a := by
    have : (x p q x₀ a : ℤ) < (x p q x₀ c : ℤ) := by exact_mod_cast hlt
    linarith
  have hle : (q : ℤ) ^ k ≤ (x p q x₀ c : ℤ) - x p q x₀ a := Int.le_of_dvd hpos hdvd
  have hxa : 1 ≤ (x p q x₀ a : ℤ) := by exact_mod_cast x_pos hq (lt_trans hq hqp) hx₀ a
  have hZ : ((q ^ k : ℕ) : ℤ) < ((x p q x₀ c : ℕ) : ℤ) := by push_cast; linarith
  have hknat : q ^ k < x p q x₀ c := by exact_mod_cast hZ
  have hd : 0 < p - q := by omega
  have hAX : q ^ k < (p - q) * x p q x₀ c + q := by
    have h1 : x p q x₀ c ≤ (p - q) * x p q x₀ c := Nat.le_mul_of_pos_left _ hd
    omega
  have hgrow := q_pow_mul_le hq (le_of_lt hqp) x₀ c
  calc q ^ (k + c) = q ^ k * q ^ c := by rw [pow_add]
    _ < ((p - q) * x p q x₀ c + q) * q ^ c := (Nat.mul_lt_mul_right (pow_pos hq c)).mpr hAX
    _ = q ^ c * ((p - q) * x p q x₀ c + q) := by ring
    _ ≤ p ^ c * ((p - q) * x₀ + q) := hgrow

/-- **Aperiodicity for every rational base** ([AFS08] Prop 26), in-house and axiom-free: at a
fixed gap the ceiling caps *every* repetition length by one fixed number. -/
@[category research solved, AMS 11 68, ref "AFS08" "Dub09", group "rb_general_rational_base"]
theorem not_eventually_periodic {p q x₀ : ℕ} (hq : 2 ≤ q) (hqp : q < p) (hcop : Nat.Coprime p q)
    (hx₀ : 0 < x₀) :
    ¬ ∃ N P, 0 < P ∧ ∀ n, N ≤ n → word p q x₀ (n + P) = word p q x₀ n := by
  rintro ⟨N, P, hP, hper⟩
  have hq0 : 0 < q := by omega
  set c := N + P with hc
  have hac : N < c := by omega
  have hrep : ∀ k, IsRepetition p q x₀ N c k := by
    intro k i _
    have hci : c + i = (N + i) + P := by omega
    rw [hci, hper (N + i) (by omega)]
  set k := p ^ c * ((p - q) * x₀ + q) with hk
  have hbound := repetition_pow_lt hq0 hqp hcop hx₀ hac (hrep k)
  have hlt : k < 2 ^ k := Nat.lt_two_pow_self
  have h2q : (2 : ℕ) ^ k ≤ q ^ k := Nat.pow_le_pow_left hq k
  have hmono : q ^ k ≤ q ^ (k + c) := Nat.pow_le_pow_right (by omega) (by omega)
  omega

/-! ## Theorem B, rational half -/

/-- The word takes only the values `0,…,q−1`, so its range is finite. -/
@[category API, AMS 11 68, ref "B1E2b", group "rb_general_rational_base"]
lemma finite_range_word {q : ℕ} (hq : 0 < q) (p x₀ : ℕ) :
    (Set.range fun n => (word p q x₀ n : ℚ)).Finite := by
  refine Set.Finite.subset (Set.finite_range fun m : Fin q => ((m : ℕ) : ℚ)) ?_
  rintro _ ⟨n, rfl⟩
  exact ⟨⟨word p q x₀ n, word_lt hq p x₀ n⟩, rfl⟩

/-- **Theorem B, rational half** ([B1E2b] WP4): for *every* rational base `p/q` with
`p > q ≥ 2` coprime and every `x₀ ≥ 1`, the word of the ceiling orbit is **not `P`-recursive**.

Footprint: `std3`.  No cited axiom — in particular this does **not** go through
`Dubickas.periodic_imp_mem_U`, which `RB.Alg.not_isPRecursive_word_of_not_mem_U` needs for the
same conclusion at a general algebraic base.  On the rational locus the axiom is replaced by the
`q`-adic descent of `dvd_sub_descend`.

At `(p,q) = (3,2)` this is `RB.not_isPRecursive_wmin` (`wmin_eq` identifies the two words). -/
@[category research solved, AMS 11 68, ref "AFS08" "Sta80" "B1E2b", group "rb_general_rational_base"]
theorem not_isPRecursive_word {p q x₀ : ℕ} (hq : 2 ≤ q) (hqp : q < p) (hcop : Nat.Coprime p q)
    (hx₀ : 0 < x₀) : ¬ IsPRecursive (fun n => (word p q x₀ n : ℚ)) :=
  not_isPRecursive_of_not_eventuallyPeriodic (finite_range_word (q := q) (by omega) p x₀) (by
    rintro ⟨N, P, hP, hper⟩
    exact not_eventually_periodic hq hqp hcop hx₀
      ⟨N, P, hP, fun n hn => by exact_mod_cast hper n hn⟩)

/-- The generating function of the word of any admissible rational base is not algebraic over
`ℚ(z)`.  Footprint: `std3 + Stanley.pRecursive_of_isAlgebraic`. -/
@[category research solved, AMS 11 68 05, ref "Sta80" "AFS08" "B1E2b",
  group "rb_general_rational_base"]
theorem not_isAlgebraic_wordSeries {p q x₀ : ℕ} (hq : 2 ≤ q) (hqp : q < p)
    (hcop : Nat.Coprime p q) (hx₀ : 0 < x₀) :
    ¬ IsAlgebraic (Polynomial ℚ) (PowerSeries.mk fun n => (word p q x₀ n : ℚ)) := fun halg =>
  not_isPRecursive_word hq hqp hcop hx₀ (by simpa using pRecursive_of_isAlgebraic halg)

/-- **Non-vacuity, with a composite denominator**: `p/q = 5/4`.  Nothing in the descent needs `q`
prime, and the alphabet here has four letters. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem not_isPRecursive_word_five_fourths {x₀ : ℕ} (hx₀ : 0 < x₀) :
    ¬ IsPRecursive (fun n => (word 5 4 x₀ n : ℚ)) :=
  not_isPRecursive_word (by norm_num) (by norm_num) (by decide) hx₀

/-! ## The `(3,2)` bridge -/

/-- The base-`3/2` instance of the general orbit **is** `RB.x` — proved equal, not substituted
([B1E2b] risk R1). -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem x_eq (x₀ n : ℕ) : x 3 2 x₀ n = RB.x x₀ n := by
  induction n with
  | zero => rfl
  | succ n ih => rw [x_succ, word_def, ih, RB.x_succ]; omega

/-- The base-`3/2` instance of the general word **is** `RB.wmin`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_general_rational_base"]
theorem wmin_eq (x₀ n : ℕ) : word 3 2 x₀ n = RB.wmin x₀ n := by
  rw [word_def, x_eq, RB.wmin_eq_x_mod_two]; omega

/-! ## The bridge to `RB.AlgebraicBase`: same sequence, one axiom fewer

`RB.Alg.not_isPRecursive_word_of_not_mem_U` reaches the same conclusion as
`not_isPRecursive_word` for every algebraic `β ∉ Bertin.U`, hence in particular for every
`β = p/q` admissible here (`not_mem_Bertin_U`, `isMinimalIntPoly_rational`).  The identifications
below show the two theorems really are about the *same* sequence, so WP4 is an axiom elimination
on the rational locus of the family, not a parallel construction. -/

/-- The general orbit **is** the ceiling orbit of `RB.QuadraticPisot` at the real base `p/q`.
This is the identification [B1E2b] risk R8 exists to make, and the one
`RB.Alg.not_isPRecursive_word_three_halves` defers to WP4. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_general_rational_base"]
theorem x_eq_pisotOrbit {p q : ℕ} (hq : 0 < q) (x₀ n : ℕ) :
    pisotOrbit ((p : ℝ) / q) (x₀ : ℤ) n = (x p q x₀ n : ℤ) := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rw [pisotOrbit_succ, ih, x_succ_eq_ceil hq]
    congr 1

/-- The `(3,2)` case: `pisotOrbit (3/2) = RB.x`. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_general_rational_base"]
theorem pisotOrbit_three_halves_eq (x₀ n : ℕ) :
    pisotOrbit ((3 : ℝ) / 2) (x₀ : ℤ) n = (RB.x x₀ n : ℤ) := by
  have h := x_eq_pisotOrbit (p := 3) (q := 2) (by norm_num) x₀ n
  rw [x_eq] at h
  simpa using h

/-- `q·X − p` is a least-degree integer annihilator of `p/q`: nothing of degree `0` annihilates a
real number, so `Dubickas.IsMinimalIntPoly` costs only the degree computation.  This is the
hypothesis `RB.Alg.not_isPRecursive_word_of_not_mem_U` needs, at every rational base. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_general_rational_base"]
theorem isMinimalIntPoly_rational {p q : ℕ} (hq : 0 < q) :
    Dubickas.IsMinimalIntPoly (C (q : ℤ) * X - C (p : ℤ)) ((p : ℝ) / q) := by
  have hqZ : ((q : ℤ)) ≠ 0 := by exact_mod_cast hq.ne'
  have hlin : (C (q : ℤ) * X - C (p : ℤ) : Polynomial ℤ) = C (q : ℤ) * X + C (-(p : ℤ)) := by
    simp only [C_neg]; ring
  have hdeg : (C (q : ℤ) * X - C (p : ℤ) : Polynomial ℤ).natDegree = 1 := by
    rw [hlin]; exact natDegree_linear hqZ
  have hqR : ((q : ℝ)) ≠ 0 := by exact_mod_cast hq.ne'
  refine ⟨fun h => by rw [h] at hdeg; simp at hdeg, ?_, fun Q hQ hQ0 => ?_⟩
  · simp only [map_sub, map_mul, aeval_C, aeval_X]
    push_cast
    field_simp
    ring
  rw [hdeg, Nat.one_le_iff_ne_zero]
  intro hQdeg
  refine hQ ?_
  have hQC : Q = C (Q.coeff 0) := eq_C_of_natDegree_eq_zero hQdeg
  have : ((Q.coeff 0 : ℤ) : ℝ) = 0 := by rw [hQC] at hQ0; simpa using hQ0
  rw [hQC, show Q.coeff 0 = 0 by exact_mod_cast this, map_zero]

/-- The Dubickas word of `q·X − p` at the base `p/q` **is** the word of this file. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_general_rational_base"]
theorem word_eq_alg {p q : ℕ} (hq : 0 < q) (x₀ n : ℕ) :
    RB.Alg.word (C (q : ℤ) * X - C (p : ℤ)) ((p : ℝ) / q) (x₀ : ℤ) n = (word p q x₀ n : ℤ) := by
  have hqZ : ((q : ℤ)) ≠ 0 := by exact_mod_cast hq.ne'
  have hlin : (C (q : ℤ) * X - C (p : ℤ) : Polynomial ℤ) = C (q : ℤ) * X + C (-(p : ℤ)) := by
    simp only [C_neg]; ring
  have hdeg : (C (q : ℤ) * X - C (p : ℤ) : Polynomial ℤ).natDegree = 1 := by
    rw [hlin]; exact natDegree_linear hqZ
  have hc0 : (C (q : ℤ) * X - C (p : ℤ) : Polynomial ℤ).coeff 0 = -(p : ℤ) := by simp
  have hc1 : (C (q : ℤ) * X - C (p : ℤ) : Polynomial ℤ).coeff 1 = (q : ℤ) := by simp
  have hsel : (q : ℤ) * (x p q x₀ (n + 1) : ℤ)
      = (p : ℤ) * (x p q x₀ n : ℤ) + (word p q x₀ n : ℤ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℤ)) (q_mul_x_succ hq p x₀ n)
  rw [RB.Alg.word, Dubickas.word, hdeg]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Nat.add_zero, zero_add, hc0, hc1,
    x_eq_pisotOrbit hq]
  linarith

/-- The `(3,2)` case: the `RB.Alg` word at `β = 3/2` **is** `RB.wmin`, closing the identification
that `RB.Alg.not_isPRecursive_word_three_halves` left open. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_general_rational_base"]
theorem alg_word_eq_wmin (x₀ n : ℕ) :
    RB.Alg.word (C 2 * X - C 3) ((3 : ℝ) / 2) (x₀ : ℤ) n = (RB.wmin x₀ n : ℤ) := by
  have h := word_eq_alg (p := 3) (q := 2) (by norm_num) x₀ n
  rw [wmin_eq] at h
  simpa using h

/-- `p/q` is **not an algebraic integer** when `q ∤ p`: `ℤ` is integrally closed in `ℚ`.  The
general form of `RB.not_isIntegral_three_halves`. -/
@[category research solved, AMS 11, ref "Ber92", group "rb_general_rational_base"]
theorem not_isIntegral_rational {p q : ℕ} (hq : 0 < q) (hdvd : ¬ q ∣ p) :
    ¬ IsIntegral ℤ ((p : ℝ) / q) := by
  intro hint
  have hqQ : ((q : ℚ)) ≠ 0 := by exact_mod_cast hq.ne'
  have hrw : ((p : ℝ) / q) = algebraMap ℚ ℝ ((p : ℚ) / (q : ℚ)) := by
    rw [eq_ratCast]; push_cast; ring
  rw [hrw, isIntegral_algebraMap_iff (algebraMap ℚ ℝ).injective,
    IsIntegrallyClosed.isIntegral_iff] at hint
  obtain ⟨y, hy⟩ := hint
  have h1 : (y : ℚ) = (p : ℚ) / (q : ℚ) := by simpa using hy
  have h2 : (q : ℤ) * y = (p : ℤ) := by
    have : (q : ℚ) * (y : ℚ) = (p : ℚ) := by rw [h1]; field_simp
    exact_mod_cast this
  exact hdvd (Int.natCast_dvd_natCast.mp ⟨y, h2.symm⟩)

/-- **`p/q` is neither Pisot nor Salem** when `q ∤ p`, so `RB.Alg`'s family theorem does apply at
every base admissible here — but only through the cited axiom `Dubickas.periodic_imp_mem_U`.
`not_isPRecursive_word` gets the same conclusion for free. -/
@[category research solved, AMS 11, ref "Ber92" "Dub09", group "rb_general_rational_base"]
theorem not_mem_Bertin_U {p q : ℕ} (hq : 0 < q) (hdvd : ¬ q ∣ p) :
    ((p : ℝ) / q) ∉ Bertin.U := by
  rintro ⟨-, hint, -⟩
  exact not_isIntegral_rational hq hdvd hint

/-! ## Sanity -/

/-- The base `5/3` orbit from `x₀ = 1` and its word over the alphabet `{0,1,2}`. -/
@[category test, AMS 11 68, ref "AFS08", group "rb_general_rational_base"]
theorem x_sanity :
    (x 5 3 1 0, x 5 3 1 1, x 5 3 1 2, x 5 3 1 3, x 5 3 1 4) = (1, 2, 4, 7, 12) ∧
      (word 5 3 1 0, word 5 3 1 1, word 5 3 1 2, word 5 3 1 3) = (1, 2, 1, 1) :=
  ⟨rfl, rfl⟩

end RB.Gen
