/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import BertinPisot.SetSTU
import CITED.AlloucheShallitBasic
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.NumberTheory.Real.Irrational
import Mathlib.NumberTheory.Real.GoldenRatio
import Mathlib.Algebra.Order.Round
import Mathlib.Data.Nat.Fib.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Quadratic Pisot numbers give purely periodic words (plan-B1E2, WP9(v))

**[Dub09] §6, formalized**: for a **quadratic Pisot** number `β` with minimal polynomial
`X² − aX + b`, the ceiling orbit `xₙ = ⌈βxₙ₋₁⌉` from *any* positive integer `x₀` has the
associated word

  `wₙ := x_{n+2} − a·x_{n+1} + b·xₙ`

**constant** — `1` if the conjugate `β' < 0`, `0` if `β' > 0` (`pisotWord_eq_one`,
`pisotWord_eq_zero`, `pisotWord_constant`).  In particular it is purely periodic, and (this file's
point) **automatic**.

## Why this matters: it certifies E.2's sharpness

[Dub09] Thm 2 — *`w` ultimately periodic ⇒ `β` is a Pisot or a Salem number* — is E.2's periodic
case, **already proved in the literature**.  E.2 is its *automatic upgrade*: replace "ultimately
periodic" by "`k`-automatic" in the hypothesis.  Both conclusions read `β ∈ Bertin.U`
(`Bertin.U_eq_S_union_T` : `U = S ∪ T` = Pisot ∪ Salem — Bertin's Def 5.1/5.2.1/5.2.2).

This file supplies the **converse direction** in the quadratic case: every quadratic Pisot `β`
*does* produce an automatic (indeed constant) word.  So the Pisot exemption in E.2's conclusion is
**populated, not vacuous** — E.2 cannot be strengthened by dropping it, and the theorem has real
content only off `U`.  Our own `β = 3/2` is off `U` (`RB.three_halves_not_mem_Bertin_U`), which is
exactly why `RB.wmin` has a chance of being non-automatic at all.

## The quadratic case needs no Salem clause

`Bertin.no_salem_lt_four` (Salem ⇒ `minpoly` degree `≥ 4`) means **there are no quadratic Salem
numbers** (`not_mem_T_of_natDegree_two`).  So at degree `2`, "Pisot **or** Salem" collapses to
"Pisot": `mem_S_iff_mem_U_of_natDegree_two`.  The quadratic case of E.2 therefore reads

  `w` automatic  ⟺  `β ∈ Bertin.S`,

whose `⟸` half is this file (`isAutomatic_pisotWord`); the `⟹` half is E.2 proper, open.

## The proof ([Dub09] §6, p. 251)

With `x_{n+1} = βxₙ + τₙ`, `τₙ ∈ (0,1)` (strict: `βxₙ` is irrational, `pisotTau_pos`), the
minimal-polynomial relation `β² − aβ + b = 0` makes the `xₙ`-terms cancel **exactly**:

  `wₙ = (β−a)x_{n+1} + τ_{n+1} + b·xₙ = (β² − aβ + b)·xₙ + (β−a)τₙ + τ_{n+1} = τ_{n+1} + (β−a)τₙ`.

Now `β − a = −β'` where `β'` is the conjugate, and `|β'| < 1` (Pisot).  So `wₙ` is an *integer*
confined to `(0, 1−β')` if `β' < 0` — forcing `wₙ = 1` — or to `(−β', 1)` if `β' > 0` — forcing
`wₙ = 0`.  `β' ≠ 0` because `β` is irrational, so the two cases are exhaustive.

## Grounding in `BertinPisot`, not a lookalike

The hypotheses are packaged as `RB.IsQuadraticPisot β a b` (elementary: `β² − aβ + b = 0`,
`1 < β`, `Irrational β`, `|a − β| < 1`), but the name is **earned**, not asserted:
`isQuadraticPisot_of_mem_S` shows *every* degree-`2` member of `Bertin.S` satisfies it, extracting
`(a,b)` from `Bertin.quadratic_mem_S` and converting Bertin's coefficient condition
`q₁ + |1+q₀| < 0` into the conjugate bound `|β'| < 1` (they are equivalent: the condition says
exactly `f(1) < 0 ∧ f(−1) > 0`, and `f(1) = (1−β)(1−β')`, `f(−1) = (1+β)(1+β')`).  So
`pisotWord_constant_of_mem_S` is Dubickas's statement verbatim: *for every quadratic Pisot number*.

## Contents

* `RB.IsQuadraticPisot` — the elementary hypotheses; `conj`, `conj_ne_zero`.
* **`RB.isQuadraticPisot_of_mem_S`** — every degree-`2` Pisot number qualifies (the bridge).
* `RB.pisotOrbit`, `RB.pisotTau`, `RB.pisotWord`; `pisotTau_pos`, `pisotTau_lt_one`.
* **`RB.pisotWord_eq`** — `wₙ = τ_{n+1} + (β−a)τₙ` (the `xₙ`-terms cancel).
* **`RB.pisotWord_constant`**, `RB.pisotWord_purelyPeriodic` — [Dub09] §6.
* **`RB.isAutomatic_pisotWord`** — the E.2-sharpness payoff.
* `RB.not_mem_T_of_natDegree_two`, `RB.mem_S_iff_mem_U_of_natDegree_two` — no quadratic Salems.
* **`RB.goldenOrbit_eq_fib`** — `⌈φ·⌉`-orbit from `1` is `F_{n+2} − 1 = fib(n+3) − 1`.

## References

* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J. **51**
  (2009), 243–252.  **§6 (Examples), pp. 250–251** — this file.  (Local copy:
  `papers/dubickas-2009-glasgow.pdf`.)  Thm 2 (p. 244) = the periodic case of E.2.
* [Ber92] M.-J. Bertin et al. *Pisot and Salem numbers.* Birkhäuser 1992.  (Def 5.1 `U`,
  5.2.1 `S`, 5.2.2 `T`; §5.2 quadratic Pisot; no Salem below degree 4.)
* [B1E2] `plans/plan-B1E2.html` (rev. 2, 2026-07): §5 (E.2 re-scoped), WP9(v), milestone M5.
-/

namespace RB

open Polynomial

/-! ## Quadratic Pisot numbers, elementarily -/

/-- **A quadratic Pisot number**, unpacked: `β` is a root of `X² − aX + b` (`a b : ℤ`), lies above
`1`, is irrational (equivalently: the polynomial is really its *minimal* one), and its conjugate
`β' = a − β` lies in `(−1, 1)`.

This is [Dub09] §6's "let `β` be a quadratic Pisot number with minimal polynomial `X² − aX + b`",
with the conjugate condition spelled out.  It is not a lookalike: `isQuadraticPisot_of_mem_S`
proves every degree-`2` element of `Bertin.S` satisfies it. -/
@[category API, AMS 11, ref "Dub09" "Ber92", group "rb_quadratic_pisot"]
structure IsQuadraticPisot (β : ℝ) (a b : ℤ) : Prop where
  /-- `β` is a root of `X² − aX + b`. -/
  root : β ^ 2 - a * β + b = 0
  /-- `β > 1`. -/
  one_lt : 1 < β
  /-- `β` is irrational — so `X² − aX + b` is its minimal polynomial. -/
  irrational : Irrational β
  /-- The conjugate `β' = a − β` lies strictly inside `(−1, 1)`: the Pisot condition. -/
  conj_abs_lt_one : |(a : ℝ) - β| < 1

/-- The **conjugate** `β' = a − β` of a quadratic Pisot number: the other root of `X² − aX + b`,
since the roots sum to `a`. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
noncomputable def conj (β : ℝ) (a : ℤ) : ℝ := (a : ℝ) - β

/-- `β·β' = b`: the roots of `X² − aX + b` multiply to `b`. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma mul_conj {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b) : β * conj β a = b := by
  have := h.root
  unfold conj
  nlinarith [this]

/-- **`β' ≠ 0`** — free from irrationality: `β' = 0` would make `β = a` rational.  This is what
makes the two cases of `pisotWord_constant` exhaustive. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma conj_ne_zero {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b) : conj β a ≠ 0 := by
  intro hc
  unfold conj at hc
  exact h.irrational.ne_int a (by linarith [sub_eq_zero.mp hc])

/-! ## The bridge: every quadratic Pisot number qualifies -/

/-- A real number whose minimal polynomial over `ℚ` has degree `2` is irrational: a rational `r`
has minimal polynomial `X − C r`, of degree `1`. -/
@[category API, AMS 11, ref "Ber92", group "rb_quadratic_pisot"]
lemma irrational_of_minpoly_natDegree_two {θ : ℝ} (hdeg : (minpoly ℚ θ).natDegree = 2) :
    Irrational θ := by
  rintro ⟨r, rfl⟩
  rw [show ((r : ℚ) : ℝ) = algebraMap ℚ ℝ r from rfl,
    minpoly.eq_X_sub_C_of_algebraMap_inj _ (algebraMap ℚ ℝ).injective,
    Polynomial.natDegree_X_sub_C] at hdeg
  exact absurd hdeg (by norm_num)

/-- **Every degree-`2` Pisot number is an `IsQuadraticPisot`** — the bridge that earns the name.

`Bertin.quadratic_mem_S` supplies `θ² + q₁θ + q₀ = 0` with `q₁ + |1 + q₀| < 0`; put `a = −q₁`,
`b = q₀`.  Bertin's coefficient condition is exactly `f(1) < 0 ∧ f(−1) > 0` for
`f = X² + q₁X + q₀`, and since `f(1) = (1−θ)(1−θ')` and `f(−1) = (1+θ)(1+θ')` with `θ > 1`, that
converts to `θ' < 1` and `θ' > −1` — i.e. `|θ'| < 1`. -/
@[category research solved, AMS 11, ref "Ber92" "Dub09", group "rb_quadratic_pisot"]
theorem isQuadraticPisot_of_mem_S {θ : ℝ} (hθ : θ ∈ Bertin.S)
    (hdeg : (minpoly ℚ θ).natDegree = 2) : ∃ a b : ℤ, IsQuadraticPisot θ a b := by
  obtain ⟨q₁, q₀, hroot, hcoeff⟩ := Bertin.quadratic_mem_S θ hθ hdeg
  refine ⟨-q₁, q₀, ⟨by push_cast; linarith [hroot], hθ.1,
    irrational_of_minpoly_natDegree_two hdeg, ?_⟩⟩
  -- `θ' = -q₁ - θ`; Bertin's `q₁ + |1 + q₀| < 0` says `f(1) < 0 ∧ f(-1) > 0`
  have hcoeffR : (q₁ : ℝ) + |1 + (q₀ : ℝ)| < 0 := by
    have := (Int.cast_lt (R := ℝ)).mpr hcoeff
    push_cast [Int.cast_abs] at this
    linarith
  have habs := abs_nonneg (1 + (q₀ : ℝ))
  have hle := le_abs_self (1 + (q₀ : ℝ))
  have hle' := neg_abs_le (1 + (q₀ : ℝ))
  -- f(1) = 1 + q₁ + q₀ < 0 and f(-1) = 1 - q₁ + q₀ > 0
  have hf1 : (1 : ℝ) + q₁ + q₀ < 0 := by linarith
  have hfm1 : (0 : ℝ) < 1 - q₁ + q₀ := by linarith
  -- factorizations, using θ·θ' = q₀ and θ + θ' = -q₁
  have hprod : θ * (-(q₁ : ℝ) - θ) = q₀ := by nlinarith [hroot]
  have hfac1 : (1 - θ) * (1 - (-(q₁ : ℝ) - θ)) = 1 + q₁ + q₀ := by nlinarith [hprod]
  have hfacm1 : (1 + θ) * (1 + (-(q₁ : ℝ) - θ)) = 1 - q₁ + q₀ := by nlinarith [hprod]
  have hθ1 : 1 < θ := hθ.1
  rw [show ((-q₁ : ℤ) : ℝ) - θ = -(q₁ : ℝ) - θ by push_cast; ring, abs_lt]
  constructor
  · nlinarith [hfacm1, hfm1]
  · nlinarith [hfac1, hf1]

/-! ## No quadratic Salem numbers -/

/-- **There are no quadratic Salem numbers**: `Bertin.no_salem_lt_four` forces degree `≥ 4`. -/
@[category research solved, AMS 11, ref "Ber92", group "rb_quadratic_pisot"]
theorem not_mem_T_of_natDegree_two {θ : ℝ} (hdeg : (minpoly ℚ θ).natDegree = 2) :
    θ ∉ Bertin.T := by
  intro hT
  have := Bertin.no_salem_lt_four θ hT
  omega

/-- **At degree `2`, "Pisot or Salem" collapses to "Pisot"**: `θ ∈ U ↔ θ ∈ S`.

So the quadratic case of [Dub09] Thm 2 (and of E.2) needs no Salem clause at all. -/
@[category research solved, AMS 11, ref "Ber92" "Dub09", group "rb_quadratic_pisot"]
theorem mem_S_iff_mem_U_of_natDegree_two {θ : ℝ} (hdeg : (minpoly ℚ θ).natDegree = 2) :
    θ ∈ Bertin.U ↔ θ ∈ Bertin.S := by
  rw [Bertin.U_eq_S_union_T]
  exact ⟨fun h => h.resolve_right (not_mem_T_of_natDegree_two hdeg), Or.inl⟩

/-! ## The ceiling orbit and its word -/

/-- The **ceiling orbit** `xₙ = ⌈βxₙ₋₁⌉` from `x₀` ([Dub09] §6). -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
noncomputable def pisotOrbit (β : ℝ) (x₀ : ℤ) : ℕ → ℤ
  | 0 => x₀
  | n + 1 => ⌈β * pisotOrbit β x₀ n⌉

@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma pisotOrbit_zero (β : ℝ) (x₀ : ℤ) : pisotOrbit β x₀ 0 = x₀ := rfl

@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma pisotOrbit_succ (β : ℝ) (x₀ : ℤ) (n : ℕ) :
    pisotOrbit β x₀ (n + 1) = ⌈β * pisotOrbit β x₀ n⌉ := rfl

/-- The **rounding defect** `τₙ = x_{n+1} − βxₙ ∈ (0,1)` ([Dub09] §6). -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
noncomputable def pisotTau (β : ℝ) (x₀ : ℤ) (n : ℕ) : ℝ :=
  (pisotOrbit β x₀ (n + 1) : ℝ) - β * pisotOrbit β x₀ n

/-- The **word** `wₙ = x_{n+2} − a·x_{n+1} + b·xₙ` of [Dub09] Thm 2, at `d = 2`. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
noncomputable def pisotWord (β : ℝ) (a b : ℤ) (x₀ : ℤ) (n : ℕ) : ℤ :=
  pisotOrbit β x₀ (n + 2) - a * pisotOrbit β x₀ (n + 1) + b * pisotOrbit β x₀ n

/-- The orbit stays positive: `β > 1` and `x₀ > 0`. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma pisotOrbit_pos {β : ℝ} (hβ : 1 < β) {x₀ : ℤ} (hx₀ : 0 < x₀) (n : ℕ) :
    0 < pisotOrbit β x₀ n := by
  induction n with
  | zero => exact hx₀
  | succ n ih =>
    rw [pisotOrbit_succ, Int.ceil_pos]
    have : (0 : ℝ) < (pisotOrbit β x₀ n : ℝ) := by exact_mod_cast ih
    nlinarith

/-- `βxₙ` is irrational, so the ceiling is *strictly* above it: `0 < τₙ`. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma pisotTau_pos {β : ℝ} (hirr : Irrational β) (hβ : 1 < β) {x₀ : ℤ} (hx₀ : 0 < x₀) (n : ℕ) :
    0 < pisotTau β x₀ n := by
  have hne : pisotOrbit β x₀ n ≠ 0 := (pisotOrbit_pos hβ hx₀ n).ne'
  have hirr' : Irrational (β * (pisotOrbit β x₀ n : ℝ)) := Irrational.mul_intCast hirr hne
  have hlt : β * (pisotOrbit β x₀ n : ℝ) < ⌈β * (pisotOrbit β x₀ n : ℝ)⌉ :=
    lt_of_le_of_ne (Int.le_ceil _) (fun h => Irrational.ne_int hirr' _ h)
  rw [pisotTau, pisotOrbit_succ]
  linarith

/-- The ceiling is less than one above: `τₙ < 1`. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma pisotTau_lt_one (β : ℝ) (x₀ : ℤ) (n : ℕ) : pisotTau β x₀ n < 1 := by
  rw [pisotTau, pisotOrbit_succ]
  have := Int.ceil_lt_add_one (β * (pisotOrbit β x₀ n : ℝ))
  linarith

/-! ## The key algebra: the `xₙ`-terms cancel -/

/-- **[Dub09] §6's computation**: `wₙ = τ_{n+1} + (β−a)·τₙ`.

The minimal-polynomial relation `β² − aβ + b = 0` annihilates the `xₙ`-coefficient exactly — which
is why the (large, unknown) orbit values drop out and only the two defects remain. -/
@[category research solved, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem pisotWord_eq {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b) (x₀ : ℤ) (n : ℕ) :
    (pisotWord β a b x₀ n : ℝ)
      = pisotTau β x₀ (n + 1) + (β - a) * pisotTau β x₀ n := by
  have hτ1 : (pisotOrbit β x₀ (n + 2) : ℝ) = β * pisotOrbit β x₀ (n + 1) + pisotTau β x₀ (n + 1) := by
    rw [pisotTau]; ring
  have hτ0 : (pisotOrbit β x₀ (n + 1) : ℝ) = β * pisotOrbit β x₀ n + pisotTau β x₀ n := by
    rw [pisotTau]; ring
  rw [pisotWord]
  push_cast
  rw [hτ1, hτ0]
  linear_combination (pisotOrbit β x₀ n : ℝ) * h.root

/-! ## The theorem: the word is constant -/

/-- **[Dub09] §6**: if the conjugate is negative, `wₙ = 1` for every `n`.

`wₙ = τ_{n+1} + (β−a)τₙ` with `β − a = −β' > 0`, so `wₙ ∈ (0, 1 + (β−a)) ⊆ (0, 2)`; an integer
there is `1`. -/
@[category research solved, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem pisotWord_eq_one {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b)
    (hneg : conj β a < 0) {x₀ : ℤ} (hx₀ : 0 < x₀) (n : ℕ) : pisotWord β a b x₀ n = 1 := by
  have hτ0 := pisotTau_pos h.irrational h.one_lt hx₀ n
  have hτ0' := pisotTau_lt_one β x₀ n
  have hτ1 := pisotTau_pos h.irrational h.one_lt hx₀ (n + 1)
  have hτ1' := pisotTau_lt_one β x₀ (n + 1)
  have hgap : 0 < β - (a : ℝ) := by unfold conj at hneg; linarith
  have hgap' : β - (a : ℝ) < 1 := by
    have := h.conj_abs_lt_one
    rw [abs_lt] at this
    linarith [this.1]
  have hval := pisotWord_eq h x₀ n
  have hlo : (0 : ℝ) < (pisotWord β a b x₀ n : ℝ) := by rw [hval]; nlinarith
  have hhi : (pisotWord β a b x₀ n : ℝ) < 2 := by rw [hval]; nlinarith
  have h0 : (0 : ℤ) < pisotWord β a b x₀ n := by exact_mod_cast hlo
  have h2 : pisotWord β a b x₀ n < 2 := by exact_mod_cast hhi
  omega

/-- **[Dub09] §6**: if the conjugate is positive, `wₙ = 0` for every `n`.

`wₙ = τ_{n+1} + (β−a)τₙ` with `β − a = −β' < 0`, so `wₙ ∈ (β−a, 1) ⊆ (−1, 1)`; an integer there
is `0`. -/
@[category research solved, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem pisotWord_eq_zero {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b)
    (hpos : 0 < conj β a) {x₀ : ℤ} (hx₀ : 0 < x₀) (n : ℕ) : pisotWord β a b x₀ n = 0 := by
  have hτ0 := pisotTau_pos h.irrational h.one_lt hx₀ n
  have hτ0' := pisotTau_lt_one β x₀ n
  have hτ1 := pisotTau_pos h.irrational h.one_lt hx₀ (n + 1)
  have hτ1' := pisotTau_lt_one β x₀ (n + 1)
  have hgap : β - (a : ℝ) < 0 := by unfold conj at hpos; linarith
  have hgap' : -1 < β - (a : ℝ) := by
    have := h.conj_abs_lt_one
    rw [abs_lt] at this
    linarith [this.2]
  have hval := pisotWord_eq h x₀ n
  have hlo : (-1 : ℝ) < (pisotWord β a b x₀ n : ℝ) := by rw [hval]; nlinarith
  have hhi : (pisotWord β a b x₀ n : ℝ) < 1 := by rw [hval]; nlinarith
  have h0 : (-1 : ℤ) < pisotWord β a b x₀ n := by exact_mod_cast hlo
  have h1 : pisotWord β a b x₀ n < 1 := by exact_mod_cast hhi
  omega

/-- **[Dub09] §6, the statement**: for a quadratic Pisot `β` and any `x₀ > 0`, the word `w` is
**constant** — `1` if the conjugate is negative, `0` if positive.  The cases are exhaustive because
`β' ≠ 0` (`conj_ne_zero`, from irrationality). -/
@[category research solved, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem pisotWord_constant {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b) {x₀ : ℤ}
    (hx₀ : 0 < x₀) : ∃ c : ℤ, ∀ n, pisotWord β a b x₀ n = c := by
  rcases lt_or_gt_of_ne (conj_ne_zero h) with hneg | hpos
  · exact ⟨1, pisotWord_eq_one h hneg hx₀⟩
  · exact ⟨0, pisotWord_eq_zero h hpos hx₀⟩

/-- **[Dub09] §6**: the word is **purely periodic** (period `1` — it is constant). -/
@[category research solved, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem pisotWord_purelyPeriodic {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b) {x₀ : ℤ}
    (hx₀ : 0 < x₀) (n : ℕ) : pisotWord β a b x₀ (n + 1) = pisotWord β a b x₀ n := by
  obtain ⟨c, hc⟩ := pisotWord_constant h hx₀
  rw [hc, hc]

/-- **[Dub09] §6, for every quadratic Pisot number** — the statement as Dubickas gives it,
with the hypothesis in `BertinPisot`'s vocabulary rather than this file's. -/
@[category research solved, AMS 11, ref "Dub09" "Ber92", group "rb_quadratic_pisot"]
theorem pisotWord_constant_of_mem_S {θ : ℝ} (hθ : θ ∈ Bertin.S)
    (hdeg : (minpoly ℚ θ).natDegree = 2) {x₀ : ℤ} (hx₀ : 0 < x₀) :
    ∃ (a b : ℤ) (c : ℤ), ∀ n, pisotWord θ a b x₀ n = c := by
  obtain ⟨a, b, h⟩ := isQuadraticPisot_of_mem_S hθ hdeg
  obtain ⟨c, hc⟩ := pisotWord_constant h hx₀
  exact ⟨a, b, c, hc⟩

/-! ## E.2 sharpness: the word is automatic -/

/-- A constant sequence is automatic: its `k`-kernel is the singleton `{a}`. -/
@[category research solved, AMS 11 68, ref "AS03", group "rb_quadratic_pisot"]
lemma isAutomatic_const (v : ℕ) : AS.IsAutomatic (fun _ => v) := by
  refine ⟨2, le_refl 2, Set.Finite.subset (Set.finite_singleton (fun _ : ℕ => v)) ?_⟩
  rintro s ⟨i, r, -, rfl⟩
  exact rfl

/-- **The E.2-sharpness payoff**: for every quadratic Pisot `β` and every `x₀ > 0`, the word `w`
is **automatic**.

So E.2's conclusion (`β ∈ Bertin.U`, i.e. Pisot or Salem) cannot be strengthened by discarding the
Pisot case: the Pisot numbers really do produce automatic words, and at degree `2` they are the
*only* members of `U` (`mem_S_iff_mem_U_of_natDegree_two`).  E.2 has content precisely **off**
`U` — where our `β = 3/2` lives (`three_halves_not_mem_Bertin_U`). -/
@[category research solved, AMS 11 68, ref "Dub09" "AS03", group "rb_quadratic_pisot"]
theorem isAutomatic_pisotWord {β : ℝ} {a b : ℤ} (h : IsQuadraticPisot β a b) {x₀ : ℤ}
    (hx₀ : 0 < x₀) : AS.IsAutomatic (fun n => (pisotWord β a b x₀ n).toNat) := by
  obtain ⟨c, hc⟩ := pisotWord_constant h hx₀
  have : (fun n => (pisotWord β a b x₀ n).toNat) = (fun _ => c.toNat) := by
    funext n; rw [hc]
  rw [this]
  exact isAutomatic_const _

/-! ## The golden mean ([Dub09] §6, first example) -/

/-- The golden ratio is a quadratic Pisot number with `X² − X − 1`, i.e. `a = 1`, `b = −1`. -/
@[category research solved, AMS 11, ref "Dub09" "Ber92", group "rb_quadratic_pisot"]
theorem isQuadraticPisot_goldenRatio : IsQuadraticPisot Real.goldenRatio 1 (-1) := by
  refine ⟨by push_cast; linarith [Real.goldenRatio_sq], Real.one_lt_goldenRatio,
    Real.goldenRatio_irrational, ?_⟩
  -- `1 - φ = ψ = goldenConj ∈ (-1, 0)`
  have hconj : ((1 : ℤ) : ℝ) - Real.goldenRatio = Real.goldenConj := by
    push_cast
    linarith [Real.goldenRatio_add_goldenConj]
  rw [hconj, abs_lt]
  exact ⟨Real.neg_one_lt_goldenConj, by linarith [Real.goldenConj_neg]⟩

/-- **[Dub09] §6**: the golden-mean orbit satisfies `x_{n+2} = x_{n+1} + xₙ + 1`.

This is `pisotWord_eq_one` at `a = 1`, `b = −1` (the conjugate `ψ < 0`), read as a recurrence. -/
@[category research solved, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem goldenOrbit_rec {x₀ : ℤ} (hx₀ : 0 < x₀) (n : ℕ) :
    pisotOrbit Real.goldenRatio x₀ (n + 2)
      = pisotOrbit Real.goldenRatio x₀ (n + 1) + pisotOrbit Real.goldenRatio x₀ n + 1 := by
  have hneg : conj Real.goldenRatio 1 < 0 := by
    have hconj : conj Real.goldenRatio 1 = Real.goldenConj := by
      unfold conj
      push_cast
      linarith [Real.goldenRatio_add_goldenConj]
    rw [hconj]
    exact Real.goldenConj_neg
  have h := pisotWord_eq_one isQuadraticPisot_goldenRatio hneg hx₀ n
  rw [pisotWord] at h
  omega

/-- `⌈φ⌉ = 2`. -/
@[category API, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
lemma ceil_goldenRatio : ⌈Real.goldenRatio⌉ = 2 := by
  have h1 := Real.one_lt_goldenRatio
  have h2 : Real.goldenRatio < 2 := by nlinarith [Real.goldenRatio_sq]
  rw [Int.ceil_eq_iff]
  constructor <;> push_cast <;> linarith

/-- **[Dub09] §6, the first example**: the golden-mean ceiling orbit from `x₀ = 1` is
`xₙ = F_{n+2} − 1`, where `F` is Dubickas's Fibonacci indexing `F₀ = F₁ = 1`.

In Mathlib's indexing (`Nat.fib 0 = 0`, `Nat.fib 1 = 1`), Dubickas's `F_n` is `Nat.fib (n+1)`, so
the formula reads **`xₙ = fib(n+3) − 1`**: `1, 2, 4, 7, 12, 20, …` -/
@[category research solved, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem goldenOrbit_eq_fib (n : ℕ) :
    pisotOrbit Real.goldenRatio 1 n = (Nat.fib (n + 3) : ℤ) - 1 := by
  induction n using Nat.twoStepInduction with
  | zero => rw [pisotOrbit_zero]; norm_num
  | one => rw [pisotOrbit_succ, pisotOrbit_zero, Int.cast_one, mul_one, ceil_goldenRatio]; norm_num
  | more n ih0 ih1 =>
    rw [goldenOrbit_rec one_pos n, ih0, ih1]
    have : Nat.fib (n + 5) = Nat.fib (n + 3) + Nat.fib (n + 4) := by
      rw [show n + 5 = (n + 3) + 2 by ring, Nat.fib_add_two]
    rw [show n + 1 + 3 = n + 4 by ring, show n + 2 + 3 = n + 5 by ring, this]
    push_cast
    ring

/-- Sanity: the orbit really is `1, 2, 4, 7, 12` (A000071-shifted, `F_{n+2} − 1`). -/
@[category test, AMS 11, ref "Dub09", group "rb_quadratic_pisot"]
theorem goldenOrbit_sanity :
    pisotOrbit Real.goldenRatio 1 0 = 1 ∧ pisotOrbit Real.goldenRatio 1 1 = 2 ∧
      pisotOrbit Real.goldenRatio 1 2 = 4 ∧ pisotOrbit Real.goldenRatio 1 3 = 7 ∧
      pisotOrbit Real.goldenRatio 1 4 = 12 := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> rw [goldenOrbit_eq_fib] <;> norm_num [Nat.fib]

end RB
