/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import RB.OrbitKernel
import CITED.AlloucheShallitComplexity
import Mathlib.Data.ZMod.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Complexity is residue counting (plan-B1E2, referee round: S1)

**`p_w(m)` is the number of residues mod `2^m` occupied by the orbit** — the one-line
restatement of subword complexity that `RB.isRepetition_iff_dvd` makes available and that the
referee of [B1E2] (report `review-B1E2.md`, C2/S1) identified as the paper's missing
unification.  Length-`m` windows of `w` *are* the residues `x_n mod 2^m`
(`complexity_eq_ncard_residues`), so:

* **Dubickas's linear floor is a pigeonhole triviality** (`complexity_lower_bound`): the first
  `≈ 1.7095·m` orbit values are `< 2^m` and strictly increasing, hence occupy pairwise distinct
  residues.  The certified constant is `41/24 = 1.7083…` (the `3^41 ≤ 2^65` certificate of
  `RB.pow_cert`); the real-log version of the same argument gives exactly
  `log 2/log(3/2) = 1.70951…`, which is [Dub09] Cor 4.
* the deviations are literally the fractional parts `θ_n = {K(3/2)^n}` (`tail_eq_fract`), so
  every combinatorial fact about `w` is a distribution fact about `(K(3/2)^n)` mod one and
  conversely — the Vijayaraghavan/[FLP95] dictionary;
* the first reachable-residue fact beyond the defining modulus: `x_{n+1} mod 3 ∈ {0, 2}`
  (`x_succ_mod_three`).

## Reading the count correctly

`p_w(m) = #{x_n mod 2^m : n ≥ 0}` is a count over the *infinite* orbit; the first `1.7095·m`
positions only witness a lower bound.  Whether the orbit occupies `≫ m` residues — superlinearly
many — is exactly horn 1 of [B1E2] Thm B, and remains open; the restatement moves the question
into the 2-adic dynamics of `U_{3/2}`, it does not answer it.

## References

* [B1E2] `plans/plan-B1E2.html` (rev. 2, 2026-07); `review-B1E2.md` (2026-07), items C2/S1.
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J.
  **51** (2009), 243–252.  (Cor 4: `p_w(n) > 1.70951129·n`.)
* [FLP95] L. Flatto, J. C. Lagarias, A. D. Pollington. *On the range of fractional parts
  `{ξ(p/q)^n}`.* Acta Arith. **70** (1995), 125–147.
-/

namespace RB

open ForMathlib.SubwordComplexity

/-! ## Windows are residues -/

/-- Equality of length-`m` factors is equality of residues mod `2^m`: the window/residue
dictionary, `RB.isRepetition_iff_dvd` in `ZMod` clothing. -/
@[category research solved, AMS 11 68, ref "B1E2", group "rb_rational_base"]
theorem factor_eq_iff_residue_eq (x₀ m a b : ℕ) :
    factor (wmin x₀) m a = factor (wmin x₀) m b ↔
      (x x₀ a : ZMod (2 ^ m)) = (x x₀ b : ZMod (2 ^ m)) := by
  have h1 : factor (wmin x₀) m a = factor (wmin x₀) m b ↔ IsRepetition x₀ a b m := by
    constructor
    · intro hf i hi
      exact congrFun hf ⟨i, hi⟩
    · intro hr
      funext s
      exact hr s s.isLt
  rw [h1, isRepetition_iff_dvd, ZMod.natCast_eq_natCast_iff, Nat.modEq_iff_dvd]
  push_cast
  rfl

/-- Ranges of two functions that identify the same arguments have the same `ncard`. -/
private lemma ncard_range_eq {α β : Type*} (f : ℕ → α) (g : ℕ → β)
    (h : ∀ a b : ℕ, f a = f b ↔ g a = g b) :
    (Set.range f).ncard = (Set.range g).ncard := by
  let F : Set.range f → Set.range g :=
    fun y => ⟨g (Set.rangeSplitting f y), Set.mem_range_self _⟩
  let G : Set.range g → Set.range f :=
    fun z => ⟨f (Set.rangeSplitting g z), Set.mem_range_self _⟩
  have hFG : ∀ y, G (F y) = y := by
    intro y
    apply Subtype.ext
    show f (Set.rangeSplitting g (F y)) = (y : α)
    have h2 : g (Set.rangeSplitting g (F y)) = g (Set.rangeSplitting f y) :=
      Set.apply_rangeSplitting g (F y)
    have h3 : f (Set.rangeSplitting g (F y)) = f (Set.rangeSplitting f y) := (h _ _).mpr h2
    rw [h3, Set.apply_rangeSplitting f y]
  have hGF : ∀ z, F (G z) = z := by
    intro z
    apply Subtype.ext
    show g (Set.rangeSplitting f (G z)) = (z : β)
    have h2 : f (Set.rangeSplitting f (G z)) = f (Set.rangeSplitting g z) :=
      Set.apply_rangeSplitting f (G z)
    have h3 : g (Set.rangeSplitting f (G z)) = g (Set.rangeSplitting g z) := (h _ _).mp h2
    rw [h3, Set.apply_rangeSplitting g z]
  rw [← Nat.card_coe_set_eq, ← Nat.card_coe_set_eq]
  exact Nat.card_congr ⟨F, G, hFG, hGF⟩

/-- **Complexity is residue counting** ([B1E2] referee, S1): the subword complexity of `w` at
length `m` is the number of distinct residues mod `2^m` occupied by the orbit,

  `p_w(m) = #{x_n mod 2^m : n ≥ 0}`.

Immediate from the rigidity theorem `RB.isRepetition_iff_dvd`: length-`m` windows *are*
residues mod `2^m`. -/
@[category research solved, AMS 11 68, ref "B1E2" "Dub09", group "rb_rational_base"]
theorem complexity_eq_ncard_residues (x₀ m : ℕ) :
    AS.complexity (wmin x₀) m = (Set.range fun n => (x x₀ n : ZMod (2 ^ m))).ncard :=
  ncard_range_eq _ _ (fun a b => factor_eq_iff_residue_eq x₀ m a b)

/-! ## Dubickas's linear floor as a pigeonhole -/

/-- The range of the factor map is finite: factors take values in `{0, 1}`. -/
private lemma range_factor_finite (x₀ m : ℕ) :
    (Set.range fun n => factor (wmin x₀) m n).Finite := by
  refine Set.Finite.subset (Set.Finite.pi fun _ : Fin m => Set.finite_Iic 1) ?_
  rintro y ⟨n, rfl⟩
  simp only [Set.mem_pi, Set.mem_univ, Set.mem_Iic, forall_const]
  intro s
  exact wmin_le_one x₀ (n + s)

/-- Early orbit values are small: for `j ≤ ⌊41(m−1)/24⌋` one has `x_j < 2^m` (at `x₀ = 1`).
The certificate is `3^41 ≤ 2^65`, i.e. `log₂3 ≤ 65/41`, as in `RB.pow_cert`. -/
private lemma x_lt_two_pow {m j : ℕ} (hm : 1 ≤ m) (hj : j ≤ 41 * (m - 1) / 24) :
    x 1 j < 2 ^ m := by
  have h24 : 24 * j ≤ 41 * (m - 1) :=
    le_trans (Nat.mul_le_mul_left 24 hj) (by rw [mul_comm]; exact Nat.div_mul_le_self _ 24)
  -- `3^j ≤ 2^(m-1+j)`, by raising to the 41st power and using `3^41 ≤ 2^65`
  have hpow : (3 : ℕ) ^ j ≤ 2 ^ (m - 1 + j) := by
    have h41 : ((3 : ℕ) ^ j) ^ 41 ≤ ((2 : ℕ) ^ (m - 1 + j)) ^ 41 := by
      rw [← pow_mul, ← pow_mul]
      calc (3 : ℕ) ^ (j * 41) = ((3 : ℕ) ^ 41) ^ j := by rw [← pow_mul, mul_comm]
        _ ≤ ((2 : ℕ) ^ 65) ^ j := Nat.pow_le_pow_left (by norm_num) j
        _ = (2 : ℕ) ^ (65 * j) := by rw [← pow_mul]
        _ ≤ (2 : ℕ) ^ ((m - 1 + j) * 41) := Nat.pow_le_pow_right (by omega) (by omega)
    exact (Nat.pow_le_pow_iff_left (by omega)).mp h41
  have hg := two_pow_mul_x_add_one_le 1 j
  have hchain : 2 ^ j * (x 1 j + 1) ≤ 2 ^ j * 2 ^ m := by
    calc 2 ^ j * (x 1 j + 1) ≤ 3 ^ j * (1 + 1) := hg
      _ = 2 * 3 ^ j := by ring
      _ ≤ 2 * 2 ^ (m - 1 + j) := Nat.mul_le_mul_left 2 hpow
      _ = 2 ^ (m - 1 + j + 1) := by rw [pow_succ, mul_comm]
      _ = 2 ^ j * 2 ^ m := by rw [← pow_add]; congr 1; omega
  have := Nat.le_of_mul_le_mul_left hchain (pow_pos (by norm_num : (0 : ℕ) < 2) j)
  omega

/-- **Dubickas's linear floor, by pigeonhole** ([Dub09] Cor 4, certified form; [B1E2] referee,
S1(i)): `p_w(m) ≥ ⌊41(m−1)/24⌋ + 1` at `x₀ = 1`, slope `41/24 = 1.7083…`.

One line from `complexity_eq_ncard_residues`: the orbit values `x_0 < x_1 < ⋯` with `x_j < 2^m`
are pairwise distinct residues mod `2^m`, and there are `> 41(m−1)/24` of them because the orbit
grows like `(3/2)^j` (`x_lt_two_pow`).  The real-log version of the same count gives the exact
slope `log 2/log(3/2) = 1.70951…` of [Dub09]. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2", group "rb_rational_base"]
theorem complexity_lower_bound {m : ℕ} (hm : 1 ≤ m) :
    41 * (m - 1) / 24 + 1 ≤ AS.complexity (wmin 1) m := by
  classical
  have hcoll : ∀ i j : ℕ, i < j → j ≤ 41 * (m - 1) / 24 →
      factor (wmin 1) m i = factor (wmin 1) m j → False := by
    intro i j hlt hj hf
    -- a factor equality between distinct early positions forces `2^m ∣ x_j − x_i` with
    -- `0 < x_j − x_i < 2^m`
    have hdvd := (factor_eq_iff_residue_eq 1 m i j).mp hf
    rw [ZMod.natCast_eq_natCast_iff, Nat.modEq_iff_dvd] at hdvd
    have hmono : x 1 i < x 1 j := x_strictMono (by norm_num) hlt
    have hsize : x 1 j < 2 ^ m := x_lt_two_pow hm hj
    have hmonoZ : (x 1 i : ℤ) < (x 1 j : ℤ) := by exact_mod_cast hmono
    have hpos : (0 : ℤ) < (x 1 j : ℤ) - (x 1 i : ℤ) := by omega
    have hle : (((2 : ℕ) ^ m : ℕ) : ℤ) ≤ (x 1 j : ℤ) - (x 1 i : ℤ) := Int.le_of_dvd hpos hdvd
    have hxi : (0 : ℤ) < (x 1 i : ℤ) := by exact_mod_cast x_pos (by norm_num : 0 < 1) i
    have hsizeZ : (x 1 j : ℤ) < (((2 : ℕ) ^ m : ℕ) : ℤ) := by exact_mod_cast hsize
    omega
  set N := 41 * (m - 1) / 24 with hN
  have hinj : Set.InjOn (fun n => factor (wmin 1) m n) (Finset.range (N + 1)) := by
    intro i hi j hj hf
    by_contra hne
    rcases Nat.lt_or_ge i j with hlt | hge
    · exact hcoll i j hlt (Nat.lt_succ_iff.mp (by simpa using hj)) hf
    · exact hcoll j i (lt_of_le_of_ne hge fun h => hne h.symm)
        (Nat.lt_succ_iff.mp (by simpa using hi)) hf.symm
  have hcard : ((Finset.range (N + 1)).image (fun n => factor (wmin 1) m n)).card = N + 1 := by
    rw [Finset.card_image_of_injOn hinj, Finset.card_range]
  have hsub : (((Finset.range (N + 1)).image (fun n => factor (wmin 1) m n) :
      Finset (Fin m → ℕ)) : Set (Fin m → ℕ)) ⊆ Set.range (fun n => factor (wmin 1) m n) := by
    intro y hy
    simp only [Finset.coe_image, Set.mem_image] at hy
    obtain ⟨n, -, rfl⟩ := hy
    exact Set.mem_range_self n
  calc N + 1
      = (((Finset.range (N + 1)).image (fun n => factor (wmin 1) m n) :
          Finset (Fin m → ℕ)) : Set (Fin m → ℕ)).ncard := by rw [Set.ncard_coe_finset, hcard]
    _ ≤ (Set.range fun n => factor (wmin 1) m n).ncard :=
        Set.ncard_le_ncard hsub (range_factor_finite 1 m)
    _ = AS.complexity (wmin 1) m := rfl

/-! ## The deviations are the fractional parts -/

/-- **`θ_n = {K(3/2)^n}`**: the deviation of the orbit is literally the fractional part of
`K(3/2)^n` — the Vijayaraghavan sequence of `K` for the ratio `3/2`.  Immediate from the closed
form `x_n = ⌊K(3/2)^n⌋` (`RB.closed_form`). -/
@[category research solved, AMS 11 68, ref "B1E2" "FLP95", group "rb_rational_base"]
theorem tail_eq_fract {x₀ : ℕ} (hx₀ : 0 < x₀) (n : ℕ) :
    tail x₀ n = Int.fract (K x₀ * (3 / 2) ^ n) := by
  rw [Int.fract, closed_form hx₀ n, tail]
  push_cast
  ring

/-! ## Reachable residues beyond the defining modulus -/

/-- **`x_{n+1} mod 3 ∈ {0, 2}`**: from `2x_{n+1} = 3x_n + w_n` the orbit avoids the residue `1`
mod `3` from the second term on — the first reachable-residue fact at a modulus other than a
power of `2`. -/
@[category research solved, AMS 11 68, ref "B1E2", group "rb_rational_base"]
theorem x_succ_mod_three (x₀ n : ℕ) : x x₀ (n + 1) % 3 = 0 ∨ x x₀ (n + 1) % 3 = 2 := by
  have h := two_mul_x_succ x₀ n
  have hw := wmin_le_one x₀ n
  omega

end RB
