/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import RB.GeneralBase
import Mathlib.FieldTheory.Minpoly.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Rigidity at every degree: E.2 stated for all `d ≥ 1` ([B1E2b] WP11)

`RB.E2Quadratic` states the automatic upgrade of [Dub09] Thm 2 at degree `2`.  That is the degree
where the *converse* is available (`RB.e2Quadratic_converse`), but it is not the degree the corpus
cares about: the base `3/2` has degree `1`.  This file states the conjecture at **every** degree
and proves the two instance bridges, which is what makes the statement touch the hero object.

Let `β > 1` be algebraic with minimal integer polynomial `P = b_d X^d + ⋯ + b_0`
(`Dubickas.IsMinimalIntPoly`), let `x₀ ≥ 1`, let `xₙ = ⌈βxₙ₋₁⌉` and `wₙ = ∑ᵢ bᵢ x_{n+i}`
(`RB.Alg.word`).

> **`RB.EAll`** — if `w` is automatic then `β ∈ Bertin.U` (Pisot or Salem).

[Dub09] Thm 2 is the same implication with "ultimately periodic" in place of "automatic"
(`Dubickas.periodic_imp_mem_U`, a cited axiom); `EAll` is strictly stronger, and **open**, so it is
a `def : Prop` and never an axiom (layered-QA policy, as for `RB.E2Quadratic` and
`RB.RepresentationQuestion`).

## The two instances that matter

* **`d = 2`** — `eAll_imp_e2Quadratic : EAll → E2Quadratic`.  Two things have to be checked, and
  both are theorems here rather than remarks: that `X² − aX + b` really *is* a minimal integer
  polynomial of an irrational root (`isMinimalIntPoly_quadratic`), and that the conclusion sharpens
  from `U` to `S` because there are no quadratic Salem numbers
  (`natDegree_minpoly_eq_two` + `RB.mem_S_iff_mem_U_of_natDegree_two`).
* **`d = 1`** — `eAll_imp_eRational : EAll → ERational`, where **`RB.ERational`** says: for coprime
  `p > q ≥ 2` and `x₀ ≥ 1`, the minimal word of the base `p/q` is **not automatic**.  Here the
  conjecture's conclusion is *unreachable* — `p/q ∉ U` because it is not an algebraic integer
  (`RB.Gen.not_mem_Bertin_U`) — so at `d = 1` the conjecture is exactly a non-automaticity
  statement, and at `(p, q) = (3, 2)` it **is** the hero problem B.1:
  `eRational_eq_B1 : ¬ AS.IsAutomatic (Gen.word 3 2 x₀) ↔ ¬ AS.IsAutomatic (wmin x₀)`.

That answers review item F7e ("the conjecture is not formulated for rational bases", W4 "§4 does
not touch the hero object"): the `d = 1` case is not an afterthought of the conjecture, it is the
open problem the whole corpus is about.

## Odd degree ([B1E2b] WP11b, review item D16)

`eAll_imp_mem_S_of_odd_natDegree` records the collapse: at odd degree "Pisot or Salem" is just
"Pisot", because Salem numbers have even degree.  That last fact is `Bertin.natDegree_even_of_mem_T`,
**proved** from the corpus's reciprocity axiom `Bertin.salem_aroots_inv_closed` rather than
axiomatized separately — the plan's option (b), in its strongest form.  It is the only declaration
here with a non-`std3` footprint, and the appendix must say so.

## Footprints

`isMinimalIntPoly_quadratic`, `natDegree_minpoly_eq_two`, `eAll_imp_e2Quadratic`,
`eAll_imp_eRational`, `eRational_eq_B1`, `eAll_imp_not_isAutomatic_wmin` are `std3`.
`eAll_imp_mem_S_of_odd_natDegree` is `std3 + Bertin.salem_aroots_inv_closed`.  No declaration here
consumes `Dubickas.periodic_imp_mem_U`: the conjecture is stated, not derived from Thm 2.

## Contents

* **`RB.EAll`** — E.2 at every degree. **Open; a `def`, not an axiom.**
* `RB.isMinimalIntPoly_quadratic`, `RB.natDegree_minpoly_eq_two` — the `d = 2` bookkeeping.
* **`RB.eAll_imp_e2Quadratic`** — `EAll` implies `RB.E2Quadratic`.
* **`RB.ERational`** — the `d = 1` instance, as a non-automaticity statement.
* **`RB.eAll_imp_eRational`**, **`RB.eRational_eq_B1`**, `RB.eAll_imp_not_isAutomatic_wmin`.
* **`RB.eAll_imp_mem_S_of_odd_natDegree`** — the odd-degree collapse.

## References

* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J. **51**
  (2009), 243–252.  Thm 2.
* [Ber92] M.-J. Bertin et al. *Pisot and Salem numbers.* Birkhäuser 1992.  §5.2 (`U`, `S`, `T`).
* [AS03] J.-P. Allouche and J. Shallit. *Automatic Sequences.* CUP 2003.
* [B1E2b] `plans/plan-B1E2b.html` (2026-07-28): WP11, WP11a, WP11b; review items W4, F7d, F7e, D16.
-/

namespace RB

open Polynomial

/-! ## The conjecture, at every degree -/

/-- **E.2 in every degree** ([B1E2b] WP11): for every algebraic `β > 1`, every minimal integer
polynomial `P` of `β`, and every `x₀ ≥ 1`, if the Dubickas word of the ceiling orbit
`xₙ = ⌈βxₙ₋₁⌉` is **automatic**, then `β` is a Pisot or a Salem number.

The hypothesis is `AS.IsAutomatic'`, automaticity of the `ℤ`-valued word itself; no `ℕ`-encoding
appears, and by `RB.e2Quadratic_iff_e2Quadratic'` that costs nothing relative to the encoded form.

Replacing "automatic" by "ultimately periodic" gives [Dub09] Thm 2, which is true
(`Dubickas.periodic_imp_mem_U`); every ultimately periodic sequence over a finite alphabet is
automatic, so `EAll` is a strictly stronger statement, and it is **open**.  Per the layered-QA
policy it is a `def : Prop`, never an axiom. -/
@[category API, AMS 11 68, ref "Dub09" "B1E2b", group "rb_rigidity_degrees"]
def EAll : Prop :=
  ∀ (β : ℝ) (P : Polynomial ℤ) (x₀ : ℤ), 1 < β → Dubickas.IsMinimalIntPoly P β → 0 < x₀ →
    AS.IsAutomatic' (Alg.word P β x₀) → β ∈ Bertin.U

/-! ## Degree 2: `EAll` implies `E2Quadratic` -/

/-- `X² − aX + b` is a **minimal** integer polynomial of an irrational root `β` of it: an integer
annihilator of degree `≤ 1` would make `β` rational (degree `1`) or be zero (degree `0`). -/
@[category research solved, AMS 11 12, ref "Dub09" "B1E2b", group "rb_rigidity_degrees"]
theorem isMinimalIntPoly_quadratic {β : ℝ} {a b : ℤ} (hirr : Irrational β)
    (hroot : β ^ 2 - a * β + b = 0) :
    Dubickas.IsMinimalIntPoly (X ^ 2 - C a * X + C b) β := by
  have hdeg : (X ^ 2 - C a * X + C b : Polynomial ℤ).natDegree = 2 := by
    have hpoly : (X ^ 2 - C a * X + C b : Polynomial ℤ) = C 1 * X ^ 2 + C (-a) * X + C b := by
      simp only [C_neg, map_one, one_mul, neg_mul]; ring
    rw [hpoly]; exact natDegree_quadratic one_ne_zero
  refine ⟨fun h => by rw [h] at hdeg; simp at hdeg, ?_, fun Q hQ hQ0 => ?_⟩
  · simp only [map_add, map_sub, map_mul, map_pow, aeval_X, eq_intCast, map_intCast]
    linarith [hroot]
  · rw [hdeg]
    by_contra hlt
    push Not at hlt
    have hQ1 : Q.natDegree ≤ 1 := by omega
    have hQeq : Q = C (Q.coeff 1) * X + C (Q.coeff 0) :=
      Polynomial.eq_X_add_C_of_natDegree_le_one hQ1
    rw [hQeq] at hQ0
    simp only [map_add, map_mul, aeval_X, eq_intCast, map_intCast] at hQ0
    rcases eq_or_ne (Q.coeff 1) 0 with h1 | h1
    · rw [h1] at hQ0
      simp only [Int.cast_zero, zero_mul, zero_add, Int.cast_eq_zero] at hQ0
      exact hQ (by rw [hQeq, h1, hQ0]; simp)
    · refine hirr ⟨-(Q.coeff 0 : ℚ) / (Q.coeff 1 : ℚ), ?_⟩
      have h1R : ((Q.coeff 1 : ℤ) : ℝ) ≠ 0 := Int.cast_ne_zero.mpr h1
      push_cast
      field_simp
      linarith [hQ0]

/-- An irrational root of `X² − aX + b` has minimal polynomial of degree exactly `2` over `ℚ`:
at most `2` because it divides that quadratic, at least `2` because degree `1` would put `β` in
the image of `ℚ`. -/
@[category research solved, AMS 11 12, ref "Ber92" "B1E2b", group "rb_rigidity_degrees"]
theorem natDegree_minpoly_eq_two {β : ℝ} {a b : ℤ} (hirr : Irrational β)
    (hroot : β ^ 2 - a * β + b = 0) : (minpoly ℚ β).natDegree = 2 := by
  set Q : Polynomial ℚ := X ^ 2 - C (a : ℚ) * X + C (b : ℚ) with hQ
  have hmonic : Q.Monic := by
    have hrw : Q = X ^ 2 + (C (-(a : ℚ)) * X + C (b : ℚ)) := by rw [hQ]; simp only [C_neg]; ring
    rw [hrw]
    exact monic_X_pow_add (lt_of_le_of_lt degree_linear_le (by norm_num))
  have haeval : aeval β Q = 0 := by
    rw [hQ]
    simp only [map_add, map_sub, map_mul, map_pow, aeval_C, aeval_X, eq_ratCast, Rat.cast_intCast]
    linarith [hroot]
  have hint : IsIntegral ℚ β := ⟨Q, hmonic, haeval⟩
  have hle : (minpoly ℚ β).natDegree ≤ Q.natDegree :=
    natDegree_le_of_dvd (minpoly.dvd ℚ β haeval) hmonic.ne_zero
  have hQdeg : Q.natDegree = 2 := by
    have hrw : Q = C 1 * X ^ 2 + C (-(a : ℚ)) * X + C (b : ℚ) := by
      rw [hQ]; simp only [C_neg, map_one, one_mul, neg_mul]; ring
    rw [hrw]; exact natDegree_quadratic one_ne_zero
  have hge : 2 ≤ (minpoly ℚ β).natDegree := by
    refine (minpoly.two_le_natDegree_iff hint).mpr ?_
    rintro ⟨y, hy⟩
    exact hirr ⟨y, by rw [← hy]; simp⟩
  omega

/-- **`EAll` implies `E2Quadratic`**: the degree-`2` instance of the conjecture is the conjecture
already stated in `RB.E2`.

Three steps, each a theorem rather than a remark: `X² − aX + b` is a minimal integer polynomial of
`β` (`isMinimalIntPoly_quadratic`); the general word at that polynomial *is* `RB.pisotWord`
(`RB.Alg.word_quadratic`); and the conclusion sharpens from `Bertin.U` to `Bertin.S` because
degree `2` admits no Salem numbers (`natDegree_minpoly_eq_two`,
`RB.mem_S_iff_mem_U_of_natDegree_two`).  The hypothesis is transported across the faithful
encoding by `AS.isAutomatic'_iff_faithful_encoding` ([B1E2b] WP11a). -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_rigidity_degrees"]
theorem eAll_imp_e2Quadratic : EAll → E2Quadratic := by
  intro h β a b x₀ f hβ hirr hroot hx₀ hfaithful hf
  have hauto : AS.IsAutomatic' (pisotWord β a b x₀) :=
    (AS.isAutomatic'_iff_faithful_encoding hfaithful).mp hf
  have hword : Alg.word (X ^ 2 - C a * X + C b) β x₀ = pisotWord β a b x₀ :=
    funext fun n => Alg.word_quadratic β a b x₀ n
  have hU : β ∈ Bertin.U :=
    h β (X ^ 2 - C a * X + C b) x₀ hβ (isMinimalIntPoly_quadratic hirr hroot) hx₀
      (by rw [hword]; exact hauto)
  exact (mem_S_iff_mem_U_of_natDegree_two (natDegree_minpoly_eq_two hirr hroot)).mp hU

/-! ## Degree 1: `EAll` implies the non-automaticity of every rational-base word -/

/-- **The degree-`1` instance of `EAll`** ([B1E2b] WP11, review item F7e): for coprime `p > q ≥ 2`
and every `x₀ ≥ 1`, the minimal word of the base `p/q` (`RB.Gen.word`) is **not automatic**.

At `d = 1` the minimal integer polynomial of `β = p/q` is `qX − p`
(`RB.Gen.isMinimalIntPoly_rational`) and the word is `wₙ = q·x_{n+1} − p·xₙ`, which is `RB.Gen.word`
on the nose (`RB.Gen.word_eq_alg`, after the `ℕ → ℤ` coercion).  The
conjecture's conclusion `β ∈ U` is *unavailable* here, since `p/q` is not an algebraic integer, so
the `d = 1` case of `EAll` is a pure non-automaticity assertion.

**Open**, like `EAll` itself: a `def : Prop`, not an axiom.  The corresponding *periodicity*
statement is a corpus theorem (`RB.Gen.not_eventually_periodic`, `std3`) — this is its automatic
upgrade, and the gap between the two is the whole difficulty. -/
@[category API, AMS 11 68, ref "Dub09" "B1E2b", group "rb_rigidity_degrees"]
def ERational : Prop :=
  ∀ (p q x₀ : ℕ), 2 ≤ q → q < p → Nat.Coprime p q → 0 < x₀ →
    ¬ AS.IsAutomatic (Gen.word p q x₀)

/-- **`EAll` implies `ERational`**: the conjecture at `d = 1` says the rational-base word is not
automatic, because its conclusion `p/q ∈ Bertin.U` is refuted outright
(`RB.Gen.not_mem_Bertin_U`: `p/q` is not an algebraic integer).

The `ℕ`-valued word is transported to the `ℤ`-valued one of `RB.Alg` by
`AS.isAutomatic'_congr_of_injective` along `Int.ofNat` — this is where the encoding-free API of
[B1E2b] WP11a pays for itself. -/
@[category research solved, AMS 11 68, ref "Dub09" "B1E2b", group "rb_rigidity_degrees"]
theorem eAll_imp_eRational : EAll → ERational := by
  intro h p q x₀ hq hqp hcop hx₀ hauto
  have hq0 : 0 < q := by omega
  have hdvd : ¬ q ∣ p := by
    intro hd
    have : q = 1 := Nat.Coprime.eq_one_of_dvd hcop.symm hd
    omega
  have hβ : (1 : ℝ) < (p : ℝ) / q := by
    rw [lt_div_iff₀ (by exact_mod_cast hq0)]
    exact_mod_cast by omega
  -- the ℤ-valued word of `RB.Alg` at `P = qX − p` is the ℕ-valued word of `RB.Gen`, coerced
  have hword : Alg.word (C (q : ℤ) * X - C (p : ℤ)) ((p : ℝ) / q) (x₀ : ℤ)
      = (fun n : ℕ => ((Gen.word p q x₀ n : ℕ) : ℤ)) :=
    funext fun n => Gen.word_eq_alg hq0 x₀ n
  have hauto' : AS.IsAutomatic' (((↑) : ℕ → ℤ) ∘ Gen.word p q x₀) :=
    (AS.isAutomatic'_congr_of_injective (g := ((↑) : ℕ → ℤ)) Nat.cast_injective).mpr
      ((AS.isAutomatic_iff_isAutomatic' _).mp hauto)
  exact Gen.not_mem_Bertin_U hq0 hdvd
    (h ((p : ℝ) / q) (C (q : ℤ) * X - C (p : ℤ)) (x₀ : ℤ) hβ (Gen.isMinimalIntPoly_rational hq0)
      (by exact_mod_cast hx₀) (by rw [hword]; exact hauto'))

/-- **The `(3, 2)` instance of `ERational` *is* the hero problem B.1** — not an analogue of it, the
same statement: `RB.Gen.wmin_eq` identifies the two sequences on the nose.

So the conjecture stated at every degree does touch the object the corpus is about (review item
W4), and B.1 is not a special problem but the `d = 1`, `(p, q) = (3, 2)` case of the rigidity
conjecture. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2b", group "rb_rigidity_degrees"]
theorem eRational_eq_B1 (x₀ : ℕ) :
    ¬ AS.IsAutomatic (Gen.word 3 2 x₀) ↔ ¬ AS.IsAutomatic (wmin x₀) := by
  rw [show Gen.word 3 2 x₀ = wmin x₀ from funext (Gen.wmin_eq x₀)]

/-- **`EAll` implies B.1**: the minimal word of `3/2` is not automatic.

Composition of `eAll_imp_eRational` at `(p, q) = (3, 2)` with `eRational_eq_B1`.  This is the
formal content of "the conjecture applies to `3/2`": the corpus's open problem is an instance of
it, so nothing about the hero object is outside the conjecture's scope. -/
@[category research solved, AMS 11 68, ref "AFS08" "Dub09" "B1E2b", group "rb_rigidity_degrees"]
theorem eAll_imp_not_isAutomatic_wmin (h : EAll) {x₀ : ℕ} (hx₀ : 0 < x₀) :
    ¬ AS.IsAutomatic (wmin x₀) :=
  (eRational_eq_B1 x₀).mp (eAll_imp_eRational h 3 2 x₀ le_rfl (by norm_num) (by decide) hx₀)

/-! ## Odd degree: the Salem clause is vacuous ([B1E2b] WP11b, review item D16) -/

/-- **At odd degree the conjecture concludes "Pisot"**, not merely "Pisot or Salem": Salem numbers
have even degree (`Bertin.natDegree_even_of_mem_T`).

Footprint: `std3 + Bertin.salem_aroots_inv_closed`.  That axiom is the corpus's cited statement of
Salem reciprocity; the even-degree consequence is *proved* from it (a fixed-point-free involution
on the conjugates), which is [B1E2b] WP11b option (b) in its strongest available form.  Every other
declaration in this file is `std3`. -/
@[category research solved, AMS 11 68, ref "Ber92" "Dub09" "B1E2b", group "rb_rigidity_degrees"]
theorem eAll_imp_mem_S_of_odd_natDegree (h : EAll) {β : ℝ} {P : Polynomial ℤ} {x₀ : ℤ}
    (hβ : 1 < β) (hP : Dubickas.IsMinimalIntPoly P β) (hx₀ : 0 < x₀)
    (hodd : Odd (minpoly ℚ β).natDegree) (hauto : AS.IsAutomatic' (Alg.word P β x₀)) :
    β ∈ Bertin.S :=
  Bertin.mem_S_of_mem_U_of_odd_natDegree (h β P x₀ hβ hP hx₀ hauto) hodd

end RB
