/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import RB.Basic
import Mathlib.Data.Int.GCD
import Mathlib.RingTheory.Coprime.Lemmas
import Mathlib.Tactic.LinearCombination
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# `2`-adic rigidity of the minimal word (plan-B1E2, WP1)

The combinatorial layer of the `3/2` rational base system: length-`m` windows of the minimal
word `RB.wmin` are *exactly* the residues `xₙ mod 2^m`, and that equivalence caps how often
the word may repeat itself.

## Window rigidity (the `↔`)

  `2^m ∣ x_a − x_b`  ⟺  `w` agrees on the length-`m` windows at `a` and `b`
  (`window_eq_of_dvd` / `two_pow_dvd_of_repetition`).

*Forwards* is a `2`-adic **descent** (`dvd_sub_descend`): the selection rule `2xₙ₊₁ = 3xₙ + wₙ`
divides by `2` once per step, so agreement mod `2^m` at `a` decays to mod `2^{m−i}` at `a+i` —
and stays alive exactly `m` steps, the window length.  *Backwards* is `circuit_sum`: equal
windows accumulate equal circuit sums (`W_eq_of_repetition`), so `3^k(x_c − x_a) = 2^k(x_{c+k}
− x_{a+k})` (**Lemma R**, `lemmaR_int`) and `2 ∤ 3` gives `2^k ∣ x_c − x_a`.

## The repetition ceiling

Rigidity is a *cost*: a repeated length-`k` window at `a < c` forces `2^k ∣ x_c − x_a`, hence
`2^k ≤ x_c − x_a`, while the orbit only grows like `(3/2)^c`.  Squeezing:

  `2^{k+c} < 3^c(x₀+1)`   (`repetition_pow_lt`),

log-free, and for `x₀ = 1` certified as the rational slope `41k ≤ 24c + 40`
(`repetition_linear_bound`), i.e. **`k ≲ 0.585·c`** — the same `24/41 > log₂(3/2)` certificate
as `TH.repetition_linear_bound`, and the model twin of the `B3` Liouville floor: repetitions
are *quality*-capped at `0.585`, far under the `τ > 1.71` a subspace attack would demand
(see [B1E2] §2.3 and `B3.not_indexCondition_of_bounds`).

Taking `k → ∞` at fixed gap kills eventual periodicity (`not_eventually_periodic`).  This is
**formalize-known** and has two independent literature proofs: [AFS08] Prop 26 (*no element of
`W_{p/q}` is eventually periodic but `0^ω`*) and [Dub09] Thm 2 (*ultimately periodic ⇒ `β`
Pisot or Salem*; `3/2` is neither, and Dubickas draws exactly this inference on p. 245).
[DN05] Lemma 1 is the sibling.  The proof here is the ceiling argument, mirroring
`TH.not_eventually_periodic`.

## Contents

* `RB.IsRepetition` — two occurrences of one length-`k` factor of `wmin`.
* `W_eq_of_repetition`, **`lemmaR_int`** — Lemma R.
* **`two_pow_dvd_of_repetition`** (`2^k ∣ x_c − x_a`), `dvd_sub_descend`,
  **`window_eq_of_dvd`**, `isRepetition_iff_dvd` — the rigidity `↔`.
* **`repetition_pow_lt`** (`2^{k+c} < 3^c(x₀+1)`), `repetition_linear_bound`
  (`41k ≤ 24c + 40` at `x₀ = 1`) — the ceiling.
* **`not_eventually_periodic`** — WP1(iii).

## References

* [AFS08] Akiyama, Frougny, Sakarovitch. *Powers of rationals modulo 1 and rational base
  number systems.* Israel J. Math. **168** (2008), 53–91.  (**Prop 26** = aperiodicity;
  Lemmas 6/8 = the congruence machinery.)
* [Dub09] A. Dubickas. *On integer sequences generated by linear maps.* Glasgow Math. J.
  **51** (2009), 243–252.  (**Thm 2**, p. 244 = the second proof of aperiodicity; Thm 3 /
  Cor 4, p. 245 = the complexity floor this ceiling is *not* — see [B1E2] §4.)
* [DN05] Dubickas, Novikas. *Integer parts of powers of rational numbers.* Math. Z. **251**
  (2005), 635–648.  (Lemma 1.)
* [B1E2] `plans/plan-B1E2.html` (rev. 2, 2026-07): WP1, §2.3.
* [M4A3] `plans/plan-M4A3.html`: `TH.RepetitionIdentity`, the twin this mirrors.
-/

namespace RB

/-- A length-`k` factor of the minimal word occurring at positions `a` and `c`:
`w (a+i) = w (c+i)` for all `i < k`.  Occurrences may overlap.  Mirror of
`TH.IsRepetition`. -/
@[category API, AMS 11 68, ref "B1E2", group "rb_rational_base"]
def IsRepetition (x₀ a c k : ℕ) : Prop := ∀ i < k, wmin x₀ (a + i) = wmin x₀ (c + i)

/-- Equal factors accumulate equal circuit sums. -/
@[category API, AMS 11 68, ref "M4A3", group "rb_rational_base"]
lemma W_eq_of_repetition {x₀ a c k : ℕ} (h : IsRepetition x₀ a c k) : W x₀ a k = W x₀ c k :=
  Finset.sum_congr rfl fun i hi => by rw [h i (Finset.mem_range.mp hi)]

/-- **Lemma R, integer form**: a repetition at `a`, `c` of length `k` forces
`3^k(x_c − x_a) = 2^k(x_{c+k} − x_{a+k})`.  Mirror of `TH.lemmaR_int`. -/
@[category research solved, AMS 11 68, ref "AFS08" "M4A3", group "rb_rational_base"]
theorem lemmaR_int {x₀ a c k : ℕ} (h : IsRepetition x₀ a c k) :
    (3 : ℤ) ^ k * ((x x₀ c : ℤ) - x x₀ a) = 2 ^ k * ((x x₀ (c + k) : ℤ) - x x₀ (a + k)) := by
  have ha : ((2 : ℤ)) ^ k * (x x₀ (a + k) : ℤ) = 3 ^ k * (x x₀ a : ℤ) + (W x₀ a k : ℤ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℤ)) (circuit_sum x₀ a k)
  have hc : ((2 : ℤ)) ^ k * (x x₀ (c + k) : ℤ) = 3 ^ k * (x x₀ c : ℤ) + (W x₀ c k : ℤ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℤ)) (circuit_sum x₀ c k)
  have hw : (W x₀ a k : ℤ) = (W x₀ c k : ℤ) := by
    exact_mod_cast congrArg (Nat.cast (R := ℤ)) (W_eq_of_repetition h)
  linarith [ha, hc, hw]

/-- `2^k` and `3^k` are coprime in `ℤ`. -/
private lemma coprime_pow (k : ℕ) : IsCoprime ((2 : ℤ) ^ k) ((3 : ℤ) ^ k) := by
  refine IsCoprime.pow ?_
  rw [Int.isCoprime_iff_gcd_eq_one]
  decide

/-- **Rigidity, `⟹`**: equal length-`k` windows force `2^k ∣ x_c − x_a`.  The plan's
"repetition ⇒ `2^t ∣ x_{r+s} − x_r`".  Mirror of `TH.two_pow_dvd_of_repetition`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2", group "rb_rational_base"]
theorem two_pow_dvd_of_repetition {x₀ a c k : ℕ} (h : IsRepetition x₀ a c k) :
    (2 : ℤ) ^ k ∣ (x x₀ c : ℤ) - x x₀ a := by
  have hdvd : (2 : ℤ) ^ k ∣ 3 ^ k * ((x x₀ c : ℤ) - x x₀ a) := by
    rw [lemmaR_int h]; exact Dvd.intro _ rfl
  exact (coprime_pow k).dvd_of_dvd_mul_left hdvd

/-! ## The descent: `2^m ∣ x_a − x_b` propagates for exactly `m` steps -/

/-- One step of agreement mod `2` fixes one letter: `w` is `x mod 2`. -/
@[category API, AMS 11 68, ref "B1E2", group "rb_rational_base"]
lemma wmin_eq_of_dvd {x₀ a b : ℕ} (h : (2 : ℤ) ∣ (x x₀ a : ℤ) - x x₀ b) :
    wmin x₀ a = wmin x₀ b := by
  have h2 : x x₀ b ≡ x x₀ a [MOD 2] := (Nat.modEq_iff_dvd (n := 2)).mpr (by simpa using h)
  exact h2.symm

/-- **The `2`-adic descent**: `2^m ∣ x_a − x_b` decays to `2^{m−i} ∣ x_{a+i} − x_{b+i}`.
Each step of `2xₙ₊₁ = 3xₙ + wₙ` divides the agreement by exactly one power of `2` — the
`3` is invertible and the letters agree as long as one power survives. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2", group "rb_rational_base"]
theorem dvd_sub_descend {x₀ a b m : ℕ} (h : (2 : ℤ) ^ m ∣ (x x₀ a : ℤ) - x x₀ b) :
    ∀ i ≤ m, (2 : ℤ) ^ (m - i) ∣ (x x₀ (a + i) : ℤ) - x x₀ (b + i) := by
  intro i
  induction i with
  | zero => intro _; simpa using h
  | succ i ih =>
    intro hi
    have hi' : i ≤ m := by omega
    have hstep := ih hi'
    -- one power of `2` survives at step `i`, so the letters agree there
    have hone : (2 : ℤ) ∣ (x x₀ (a + i) : ℤ) - x x₀ (b + i) := by
      refine dvd_trans ?_ hstep
      exact dvd_pow_self 2 (by omega)
    have hw : wmin x₀ (a + i) = wmin x₀ (b + i) := wmin_eq_of_dvd hone
    have ha : 2 * (x x₀ (a + i + 1) : ℤ) = 3 * x x₀ (a + i) + wmin x₀ (a + i) := by
      exact_mod_cast congrArg (Nat.cast (R := ℤ)) (two_mul_x_succ x₀ (a + i))
    have hb : 2 * (x x₀ (b + i + 1) : ℤ) = 3 * x x₀ (b + i) + wmin x₀ (b + i) := by
      exact_mod_cast congrArg (Nat.cast (R := ℤ)) (two_mul_x_succ x₀ (b + i))
    have key : 2 * ((x x₀ (a + i + 1) : ℤ) - x x₀ (b + i + 1))
        = 3 * ((x x₀ (a + i) : ℤ) - x x₀ (b + i)) := by rw [hw] at ha; linarith
    -- `2^{m-i} ∣ 3·(…) = 2·(…)`, and `m − i ≥ 1`, so `2^{m-i-1} ∣ (…)`
    have hdvd2 : (2 : ℤ) ^ (m - i) ∣ 2 * ((x x₀ (a + i + 1) : ℤ) - x x₀ (b + i + 1)) := by
      rw [key]; exact Dvd.dvd.mul_left hstep 3
    have hsplit : (2 : ℤ) ^ (m - i) = 2 * 2 ^ (m - i - 1) := by
      rw [← pow_succ']; congr 1; omega
    rw [hsplit] at hdvd2
    have := (mul_dvd_mul_iff_left (by norm_num : (2 : ℤ) ≠ 0)).mp hdvd2
    have he : m - i - 1 = m - (i + 1) := by omega
    rw [he] at this
    have hab : a + (i + 1) = a + i + 1 := by omega
    have hbb : b + (i + 1) = b + i + 1 := by omega
    rw [hab, hbb]
    exact this

/-- **Rigidity, `⟸`**: `2^m ∣ x_a − x_b` forces the length-`m` windows at `a` and `b` to
agree.  With `two_pow_dvd_of_repetition`, windows of length `m` *are* residues mod `2^m`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2", group "rb_rational_base"]
theorem window_eq_of_dvd {x₀ a b m : ℕ} (h : (2 : ℤ) ^ m ∣ (x x₀ a : ℤ) - x x₀ b) :
    IsRepetition x₀ a b m := by
  intro i hi
  have hstep := dvd_sub_descend h i (le_of_lt hi)
  refine wmin_eq_of_dvd (dvd_trans ?_ hstep)
  exact dvd_pow_self 2 (by omega)

/-- **Window rigidity** ([B1E2] WP1(i)): length-`m` windows of `w` ↔ residues `x mod 2^m`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2", group "rb_rational_base"]
theorem isRepetition_iff_dvd {x₀ a b m : ℕ} :
    IsRepetition x₀ a b m ↔ (2 : ℤ) ^ m ∣ (x x₀ b : ℤ) - x x₀ a := by
  refine ⟨two_pow_dvd_of_repetition, fun h => window_eq_of_dvd ?_⟩
  have hneg := (dvd_neg (α := ℤ)).mpr h
  rwa [neg_sub] at hneg

/-! ## The repetition ceiling -/

/-- **The ceiling** ([B1E2] §2.3): a repeated length-`k` window at `a < c` obeys
`2^{k+c} < 3^c(x₀+1)`.  Rigidity forces `2^k ≤ x_c − x_a`; growth caps `x_c` by `(3/2)^c`. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2", group "rb_rational_base"]
theorem repetition_pow_lt {x₀ a c k : ℕ} (hx₀ : 0 < x₀) (hac : a < c)
    (h : IsRepetition x₀ a c k) : 2 ^ (k + c) < 3 ^ c * (x₀ + 1) := by
  have hlt : x x₀ a < x x₀ c := x_strictMono hx₀ hac
  have hdvd := two_pow_dvd_of_repetition h
  have hpos : (0 : ℤ) < (x x₀ c : ℤ) - x x₀ a := by
    have : (x x₀ a : ℤ) < (x x₀ c : ℤ) := by exact_mod_cast hlt
    linarith
  have hle : (2 : ℤ) ^ k ≤ (x x₀ c : ℤ) - x x₀ a := Int.le_of_dvd hpos hdvd
  have hxa : 1 ≤ (x x₀ a : ℤ) := by exact_mod_cast x_pos hx₀ a
  have hknat : 2 ^ k < x x₀ c + 1 := by
    have : (2 : ℤ) ^ k < (x x₀ c : ℤ) + 1 := by linarith
    exact_mod_cast this
  have hgrow := two_pow_mul_x_add_one_le x₀ c
  calc 2 ^ (k + c) = 2 ^ k * 2 ^ c := by rw [pow_add]
    _ < (x x₀ c + 1) * 2 ^ c := (Nat.mul_lt_mul_right (Nat.two_pow_pos c)).mpr hknat
    _ = 2 ^ c * (x x₀ c + 1) := by ring
    _ ≤ 3 ^ c * (x₀ + 1) := hgrow

/-- Integer certificate for `log₂ 3 ≤ 65/41` (house recipe: no reals, no logs).  Same
certificate as `TH.pow_cert`. -/
@[category API, AMS 11 68, ref "M4A3", group "rb_rational_base"]
lemma pow_cert : (3 : ℕ) ^ 41 ≤ 2 ^ 65 := by norm_num

/-- **The ceiling, certified rational form** at `x₀ = 1`: a repeated length-`k` window at
`a < c` obeys `41k ≤ 24c + 40`, i.e. `k ≤ (24/41)c + 1 ≈ 0.585·c`.  `24/41 > log₂(3/2)` is
the same certified slope as `TH.repetition_linear_bound`.

This is [B1E2] §2.3's **repetition ceiling**: the word's repetitions are quality-capped
strictly below the exponent any stammering/subspace attack needs. -/
@[category research solved, AMS 11 68, ref "AFS08" "B1E2", group "rb_rational_base"]
theorem repetition_linear_bound {a c k : ℕ} (hac : a < c) (h : IsRepetition 1 a c k) :
    41 * k ≤ 24 * c + 40 := by
  have hb : 2 ^ (k + c) < 3 ^ c * 2 := by simpa using repetition_pow_lt (by norm_num) hac h
  have h41 : (2 ^ (k + c)) ^ 41 < (3 ^ c * 2) ^ 41 := Nat.pow_lt_pow_left hb (by norm_num)
  have e1 : ((2 : ℕ) ^ (k + c)) ^ 41 = 2 ^ (41 * (k + c)) := by rw [← pow_mul]; ring_nf
  have e2 : ((3 : ℕ) ^ c * 2) ^ 41 = 3 ^ (41 * c) * 2 ^ 41 := by
    rw [mul_pow, ← pow_mul]; ring_nf
  have e3 : (3 : ℕ) ^ (41 * c) ≤ 2 ^ (65 * c) := by
    rw [pow_mul, pow_mul]
    exact Nat.pow_le_pow_left pow_cert c
  have h2 : (2 : ℕ) ^ (41 * (k + c)) < 2 ^ (65 * c + 41) := by
    calc (2 : ℕ) ^ (41 * (k + c)) = ((2 : ℕ) ^ (k + c)) ^ 41 := e1.symm
      _ < ((3 : ℕ) ^ c * 2) ^ 41 := h41
      _ = 3 ^ (41 * c) * 2 ^ 41 := e2
      _ ≤ 2 ^ (65 * c) * 2 ^ 41 := Nat.mul_le_mul_right _ e3
      _ = 2 ^ (65 * c + 41) := by rw [← pow_add]
  have := (Nat.pow_lt_pow_iff_right (by norm_num : 1 < 2)).mp h2
  omega

/-- **WP1(iii)**: the minimal word is not eventually periodic.  A fixed-gap repetition of
every length would beat the ceiling `2^{k+c} < 3^c(x₀+1)` at fixed `c`.

**Formalize-known** — [AFS08] Prop 26 and, independently, [Dub09] Thm 2.  Mirrors
`TH.not_eventually_periodic`. -/
@[category research solved, AMS 11 68, ref "AFS08" "Dub09", group "rb_rational_base"]
theorem not_eventually_periodic {x₀ : ℕ} (hx₀ : 0 < x₀) :
    ¬ ∃ N p, 0 < p ∧ ∀ n, N ≤ n → wmin x₀ (n + p) = wmin x₀ n := by
  rintro ⟨N, p, hp, hper⟩
  set c := N + p with hc
  have hac : N < c := by omega
  have hrep : ∀ k, IsRepetition x₀ N c k := by
    intro k i _
    have hci : c + i = (N + i) + p := by omega
    rw [hci, hper (N + i) (by omega)]
  -- at fixed gap the ceiling caps *every* length by one fixed number
  set k := 3 ^ c * (x₀ + 1) with hk
  have hbound := repetition_pow_lt hx₀ hac (hrep k)
  have hlt : k < 2 ^ k := Nat.lt_two_pow_self
  have hmono : (2 : ℕ) ^ k ≤ 2 ^ (k + c) := Nat.pow_le_pow_right (by norm_num) (by omega)
  omega

end RB
