/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.Data.Set.Finite.Basic
import Corpus.Util.Attributes.Basic
import Corpus.Util.Attributes.Database

/-!
# Automatic sequences — basic notions (Allouche–Shallit)

Jean-Paul Allouche and Jeffrey Outlaw Shallit, *Automatic Sequences: Theory, Applications,
Generalizations*, Cambridge University Press, 2003.

This file records the foundational notions of the theory of automatic sequences, used throughout
the corpus (e.g. by the Adamczewski–Bugeaud transcendence results in `AB/` and the automatic
parity-vector development in `B3/`).

## Notions

* **`k`-kernel** (`kKernel`). The set of subsequences `n ↦ a (kⁱ·n + r)` for `i ≥ 0` and
  `0 ≤ r < kⁱ`.
* **Automatic sequence** (`IsAutomatic`). A sequence `a : ℕ → ℕ` is *`k`-automatic* iff its
  `k`-kernel is finite (Eilenberg's characterization); a sequence is *automatic* iff it is
  `k`-automatic for some `k ≥ 2` — equivalently, generated by a deterministic finite automaton with
  output. The kernel formulation is used so the statement is self-contained (no DFAO machinery).

## Contents
* `kKernel`, `IsAutomatic` — the `k`-kernel and the automatic-sequence predicate.

## References
* [AS03] Allouche, Jean-Paul, and Jeffrey Outlaw Shallit. *Automatic Sequences: Theory,
  Applications, Generalizations.* Cambridge University Press, 2003.
-/

namespace AS

/-- The **`k`-kernel** of a sequence `a : ℕ → ℕ`: the set of all subsequences `n ↦ a (kⁱ·n + r)`
for `i ≥ 0` and `0 ≤ r < kⁱ`. By Eilenberg's theorem, `a` is `k`-automatic iff this set is finite. -/
@[category API, AMS 11 68, ref "AS03"]
def kKernel (k : ℕ) (a : ℕ → ℕ) : Set (ℕ → ℕ) :=
  {s | ∃ i r, r < k ^ i ∧ s = fun n => a (k ^ i * n + r)}

/-- A sequence is **automatic** iff it is `k`-automatic for some base `k ≥ 2`, i.e. its `k`-kernel
is finite — equivalently, it is generated by a deterministic finite automaton with output. -/
@[category API, AMS 11 68, ref "AS03"]
def IsAutomatic (a : ℕ → ℕ) : Prop :=
  ∃ k, 2 ≤ k ∧ (kKernel k a).Finite

end AS
