/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.Analysis.SpecificLimits.Basic

/-!
# Eventually linear growth of a filtration generated by an injective endomorphism

Let `T : V →ₗ[K] V` be an injective endomorphism of a vector space over a field, let `W ≤ V` be a
finite-dimensional subspace, and let `S : ℕ → Submodule K V` be an increasing family with

* `S (N+1) = S N ⊔ (Tᴺ⁺¹ '' W)` — each step adjoins one more `T`-translate of `W`;
* `T '' (S N) ≤ S (N+1)` — `T` moves the filtration up by at most one step.

Then `finrank K (S N)` is **eventually an arithmetic progression**: there are `c` and `N₀` with
`finrank K (S N) = finrank K (S N₀) + c * (N - N₀)` for all `N ≥ N₀`, and `c ≥ 1` as soon as the
dimensions are unbounded.  Equivalently `finrank K (S N) ∼ c * N`.

The mechanism is a two-line monotonicity: the intersections
`t N := finrank K (S N ⊓ Tᴺ⁺¹ '' W)` are *non-decreasing*, because `T` maps
`S N ⊓ Tᴺ⁺¹ '' W` injectively into `S (N+1) ⊓ Tᴺ⁺² '' W`; and they are bounded by `finrank K W`.
Since the increment of `finrank K (S N)` is exactly `finrank K W - t N`, the increment is
non-increasing, hence eventually constant.

## Main results

* `Submodule.IsIteratedFiltration` — the hypotheses, bundled.
* `Submodule.IsIteratedFiltration.exists_finrank_eq` — eventual arithmetic progression.
* `Submodule.IsIteratedFiltration.exists_tendsto_finrank_div` — the asymptotic form
  `finrank K (S N) / N → c`.

## References

The statement is the abstract content of the dimension estimate
[AF22, Lemma 2.2] (B. Adamczewski, C. Faverjon, *A new proof of Nishioka's theorem in Mahler's
method*, arXiv:2210.14528), where `V` is a space of polynomials in a matrix of indeterminates over
a rational function field, `T` is multiplication by `z`, and `S N` is the piece of degree at most
`N` in `z`.  The proof given there (their Appendix A.1) argues in the dual space; the argument
below works with the subspaces themselves and needs neither a basis nor a normalisation.
-/

open Filter Module
open scoped Topology

namespace Submodule

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- The data of a filtration `S` of `V` generated by iterating an injective endomorphism `T` on a
finite-dimensional subspace `W`. -/
structure IsIteratedFiltration (T : V →ₗ[K] V) (W : Submodule K V) (S : ℕ → Submodule K V) :
    Prop where
  /-- `T` is injective. -/
  injective : Function.Injective T
  /-- The bottom piece is finite-dimensional. -/
  finiteDimensional_zero : FiniteDimensional K (S 0)
  /-- The generating subspace is finite-dimensional. -/
  finiteDimensional_gen : FiniteDimensional K W
  /-- Each step adjoins one more `T`-translate of `W`. -/
  step : ∀ N, S (N + 1) = S N ⊔ W.map ((T : Module.End K V) ^ (N + 1))
  /-- `T` moves the filtration up by at most one step. -/
  map_le : ∀ N, (S N).map T ≤ S (N + 1)

namespace IsIteratedFiltration

variable {T : V →ₗ[K] V} {W : Submodule K V} {S : ℕ → Submodule K V}
  (h : IsIteratedFiltration T W S)

include h

/-- `T ^ n` is injective. -/
theorem injective_pow (n : ℕ) : Function.Injective ((T : Module.End K V) ^ n) := by
  rw [Module.End.coe_pow]
  exact h.injective.iterate n

theorem finiteDimensional_map (n : ℕ) :
    FiniteDimensional K (W.map ((T : Module.End K V) ^ n)) := by
  have := h.finiteDimensional_gen
  exact (Submodule.equivMapOfInjective _ (h.injective_pow n) W).finiteDimensional

theorem finiteDimensional (N : ℕ) : FiniteDimensional K (S N) := by
  induction N with
  | zero => exact h.finiteDimensional_zero
  | succ n ih =>
      have := ih
      have := h.finiteDimensional_map (n + 1)
      rw [h.step n]
      infer_instance

theorem monotone : Monotone S :=
  monotone_nat_of_le_succ fun N => by rw [h.step N]; exact le_sup_left

/-- `T ^ n` does not change dimensions. -/
theorem finrank_map (n : ℕ) :
    finrank K (W.map ((T : Module.End K V) ^ n)) = finrank K W :=
  ((Submodule.equivMapOfInjective _ (h.injective_pow n) W).finrank_eq).symm

/-- **Eventually an arithmetic progression.**  If the dimensions `finrank K (S N)` are unbounded,
then they are eventually given by `finrank K (S N₀) + c * (N - N₀)` with `c ≥ 1`.

The proof runs through the *overlaps* `t N = finrank K (S N ⊓ Tᴺ⁺¹ '' W)`, which are
non-decreasing (apply `T`) and bounded by `finrank K W`, hence eventually constant; the increment
of `finrank K (S N)` is `finrank K W - t N`. -/
theorem exists_finrank_eq (hub : ∀ B : ℕ, ∃ N, B ≤ finrank K (S N)) :
    ∃ c N₀ : ℕ, 1 ≤ c ∧
      ∀ N, N₀ ≤ N → finrank K (S N) = finrank K (S N₀) + c * (N - N₀) := by
  set t : ℕ → ℕ := fun N => finrank K ↥(S N ⊓ W.map ((T : Module.End K V) ^ (N + 1))) with ht
  have hkey : ∀ N, finrank K ↥(S (N + 1)) + t N = finrank K ↥(S N) + finrank K ↥W := by
    intro N
    have := h.finiteDimensional N
    have := h.finiteDimensional_map (N + 1)
    simp only [ht]
    rw [h.step N, finrank_sup_add_finrank_inf_eq, h.finrank_map]
  have htle : ∀ N, t N ≤ finrank K ↥W := by
    intro N
    have := h.finiteDimensional_map (N + 1)
    simp only [ht]
    exact (Submodule.finrank_mono inf_le_right).trans_eq (h.finrank_map _)
  have htmono : ∀ N, t N ≤ t (N + 1) := by
    intro N
    have := h.finiteDimensional (N + 1)
    have := h.finiteDimensional_map (N + 2)
    have hsub : (S N ⊓ W.map ((T : Module.End K V) ^ (N + 1))).map T ≤
        S (N + 1) ⊓ W.map ((T : Module.End K V) ^ (N + 2)) := by
      refine le_trans (Submodule.map_inf_le _) (le_inf (le_trans inf_le_left (h.map_le N)) ?_)
      refine le_trans inf_le_right (le_of_eq ?_)
      rw [← Submodule.map_comp]
      congr 1
      exact (Module.End.iterate_succ' _).symm
    simp only [ht]
    calc finrank K ↥(S N ⊓ W.map ((T : Module.End K V) ^ (N + 1)))
        = finrank K ↥((S N ⊓ W.map ((T : Module.End K V) ^ (N + 1))).map T) :=
          (Submodule.equivMapOfInjective _ h.injective _).finrank_eq
      _ ≤ finrank K ↥(S (N + 1) ⊓ W.map ((T : Module.End K V) ^ (N + 1 + 1))) :=
          Submodule.finrank_mono hsub
  obtain ⟨N₀, hN₀⟩ : ∃ N₀, ∀ N, t N ≤ t N₀ := by
    by_contra hcon
    push Not at hcon
    have hgrow : ∀ n : ℕ, ∃ N, n ≤ t N := by
      intro n
      induction n with
      | zero => exact ⟨0, Nat.zero_le _⟩
      | succ k ih =>
          obtain ⟨N, hN⟩ := ih
          obtain ⟨M, hM⟩ := hcon N
          exact ⟨M, by omega⟩
    obtain ⟨N, hN⟩ := hgrow (finrank K W + 1)
    exact absurd (htle N) (by omega)
  have hconst : ∀ N, N₀ ≤ N → t N = t N₀ :=
    fun N hN => le_antisymm (hN₀ N) (monotone_nat_of_le_succ htmono hN)
  refine ⟨finrank K W - t N₀, N₀, ?_, ?_⟩
  · -- the increment is nonzero, else the dimensions would be bounded
    by_contra hc
    have hzero : finrank K W = t N₀ := by
      have := htle N₀
      omega
    have hstab : ∀ N, N₀ ≤ N → finrank K (S N) = finrank K (S N₀) := by
      intro N hN
      induction N, hN using Nat.le_induction with
      | base => rfl
      | succ n hn ih =>
          have := hkey n
          rw [hconst n hn, ← hzero] at this
          omega
    obtain ⟨N, hN⟩ := hub (finrank K (S N₀) + 1)
    rcases le_or_gt N₀ N with hle | hlt
    · rw [hstab N hle] at hN; omega
    · have := h.finiteDimensional N₀
      have := Submodule.finrank_mono (h.monotone hlt.le)
      omega
  · intro N hN
    induction N, hN using Nat.le_induction with
    | base => simp
    | succ n hn ih =>
        have hk := hkey n
        have hle := htle N₀
        rw [hconst n hn] at hk
        have hsub : n + 1 - N₀ = (n - N₀) + 1 := by omega
        rw [hsub, Nat.mul_succ]
        omega

/-- **The asymptotic form.**  The dimension of `S N` is asymptotically `c * N` for a positive
integer `c`.  This is the shape in which [AF22, Lemma 2.2] is stated and used. -/
theorem exists_tendsto_finrank_div (hub : ∀ B : ℕ, ∃ N, B ≤ finrank K (S N)) :
    ∃ c : ℕ, 1 ≤ c ∧
      Tendsto (fun N : ℕ => (finrank K (S N) : ℝ) / N) atTop (𝓝 (c : ℝ)) := by
  obtain ⟨c, N₀, hc, hlin⟩ := h.exists_finrank_eq hub
  refine ⟨c, hc, ?_⟩
  have hlim : Tendsto
      (fun N : ℕ => (c : ℝ) + ((finrank K (S N₀) : ℝ) - c * N₀) / N) atTop (𝓝 ((c : ℝ) + 0)) :=
    tendsto_const_nhds.add (tendsto_const_div_atTop_nhds_zero_nat _)
  rw [add_zero] at hlim
  refine hlim.congr' ?_
  filter_upwards [eventually_ge_atTop (max N₀ 1)] with N hNmax
  have hN₀ : N₀ ≤ N := le_trans (le_max_left _ _) hNmax
  have hN1 : (1 : ℕ) ≤ N := le_trans (le_max_right _ _) hNmax
  have hNpos : (0 : ℝ) < N := by exact_mod_cast hN1
  rw [hlin N hN₀]
  push_cast [Nat.cast_sub hN₀]
  field_simp
  ring

end IsIteratedFiltration

end Submodule
